### ISSUE TITLE
best setting for gameplay recording?

### ISSUE THREAD

**Issue by ivanquirino** [Xaymar/OBS-AMD-Advanced-Media-Framework#101]
What setting should I use to get a good gameplay recording? "Recording" or "High Quality"?

**Comment by Xaymar** [comment]
Recording for little impact, High Quality for higher quality, Indistinguishable for near lossless footage, Lossless for lossless.

**Comment by ivanquirino** [comment]
for little impact you mean keep gameplay smooth at the cost of quality?,

**Comment by Xaymar** [comment]
Yes
