### ISSUE TITLE
Bad quality with changed B-Picture Pattern

### ISSUE THREAD

**Issue by razorlikes** [Xaymar/OBS-AMD-Advanced-Media-Framework#103]
Here are two videos, one with B-Picture Pattern [set to 0](https://drive.google.com/open?id=0B1y2xDp8JscnTFctOXFhRXJITnc) and one with B-Picture Pattern [set to 3](https://drive.google.com/open?id=0B1y2xDp8JscnNTJVZ0t4bWxEelE) (please download the videos so you can see the difference better). As you can see the quality of the video with it set to 3 is way worse than the quality of the video with it set to 0.

Here are my [settings](https://gyazo.com/b63e891b36e469a4ad6c791cbf7b3ea6).

I am using a R9 390, driver 16.9.2 and version 1.3.2.0 of the plugin.

Another thing I noticed is when you change a value in the settings it instantly removes focus of the object you were interacting with. For example a text box in which you entered a number.

Also, log: 
[2016-10-03 18-51-25.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/506751/2016-10-03.18-51-25.txt)

**Comment by Xaymar** [comment]
Please read the [Troubleshooting Guide](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/wiki/Troubleshooting#finally-report-an-issue) and update your issue accordingly. Edit: Your current log does not have Debug Tracing enabled and only includes data for the B-Pictures 3 video.

**Comment by razorlikes** [comment]
Hardware:
AMD FX8350
AMD Radeon R9 390 Nitro
ASUS Crosshair IV Formula
Corsair XMS3 DDR3 12GB
SSD for OS, HDDs for recording and games.

OBS version 0.16.2
Plugin version 1.3.2.0

[Log for B-Picture Pattern = 0](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/506804/2016-10-03.19-34-47.txt)
[Log for B-Picture Pattern = 3](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/506806/2016-10-03.19-36-15.txt)

I hope that's all. Sorry for the inconvenience.

**Comment by Xaymar** [comment]
Try lowering the Delta QP towards 0, your bitrate is quite low so it might move the qp too high with a delta of 4/2.

**Comment by razorlikes** [comment]
No difference. I tried 2/1 and 0/0 but it had no effect on the video quality.

**Comment by Xaymar** [comment]
I'm unsure what's causing this. Can you try and reproduce this exact issue in the [Advanced] one?

**Comment by razorlikes** [comment]
Same issue with the advanced encoder.

Settings: 
https://gyazo.com/006bdf90e1a30eeee667e40eb68d05d4
https://gyazo.com/cb0641e960909bf64a77af0536316a00

[New log.](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/506855/2016-10-03.20-02-54.txt)

**Comment by Xaymar** [comment]
Does this also happen with 1.3.1.0?

**Comment by razorlikes** [comment]
Yes, also happening on 1.3.1.0. I remeber this happening on way earlier versions too. This was also the problem on #25 I think. Just wanted to point this out since you updated the Twitch preset.

**Comment by Xaymar** [comment]
1.3.2.4 will no longer override this on a preset basis.
