### ISSUE TITLE
Output set to 60FPS, but output file have different framerate

### ISSUE THREAD

**Issue by PNunesDev** [Xaymar/OBS-AMD-Advanced-Media-Framework#104]
Hi Xaymar, I was trying to record at 60FPS Bioshock remastered which is very lightweight and easily runs above 60FPS.
I had set the recording to 60FPS, and the game runs perfectly fine at 60FPS or above, altough, the video file ends up being 35FPS, or 39FPS or 48FPS, it's variable.
How can I solve this?

I left my obs log attached after a recording, I couldn't stop notice that obs failed to load some services too
https://gist.github.com/c4775e1b02e05cb044f31c138d2a1286

Cheers

**Comment by Xaymar** [comment]
You have a first generation GCN/VCE card, which can only support **up to** 60 fps. You can try enforcing 60 fps by disabling the "Frame Skipping" option.

**Comment by PNunesDev** [comment]
@Xaymar Nop, didn't worked, recorded a little bit with frame skipping disable and well, the file ended up with 45FPS.
I believe the that software is trying to keep the game runnign at a target framerate, but I would preffer the game to drop frames than the end file, this way I could had a 60FPS video with maybe some drops here and there, and not an entire video capped to a framerate that I didn't choose ^^.

Here's the log of this last recording :)
Cheers
https://gist.github.com/63d553fd52c2c17f8210085176efa703

**Comment by Xaymar** [comment]
Sorry, there's nothing I can do then. The encoder and OBS will not limit the game framerate just because it can't encode fast enough. If your card can't do more, then it can't do more. You can try lowering the bandwidth requirement by using CBR, VBR or CQP instead.

**Comment by PNunesDev** [comment]
I understand...
It's different than most recorders I know, most preffer to drop frames instead of dropping the file target framerate.
Since you know what you are doing, and I just don't really know what to adjust. any suggestion based on this "bandwidth requirements", what do you recommend for minimum/maximum QP?

**Comment by Xaymar** [comment]
I can't recommend anything, but you should try increasing the minimum QP towards 22 until it no longer uses variable framerate.

**Comment by PNunesDev** [comment]
Didn't solved, but thanks Xaymar, I might start use OBS with the plugin, when I have a new card, but until now, I just say you have made a fabolous job.
Cheers and keep it up.

**Comment by Kobata** [comment]
For a bit of help, older cards _can_ do 1080p60, but _only_ on speed preset (balanced might get close, but is likely to be more like 50-55fps). Quality preset is too slow to maintain 60fps at that resolution on those cards.
