### ISSUE TITLE
Black screen Problems came back?!

### ISSUE THREAD

**Issue by locodicegr** [Xaymar/OBS-AMD-Advanced-Media-Framework#107]
[2016-10-06 14-15-14.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/513563/2016-10-06.14-15-14.txt)
[2016-10-06 08-33-58.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/513564/2016-10-06.08-33-58.txt)
[2016-10-06 13-47-30.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/513565/2016-10-06.13-47-30.txt)

3 Different games , result in black screen recording, with the new plugin 1.3.3.0

Yesterday the default obs plugin worked great in doom, (we spoke on steam if you remember)
but today i update to 1.3.3.0 and boom...

R9 380 / Simple Encoder / Recording Preset / 5000 Bitrate / everything else default.

**Comment by Xaymar** [comment]
Your encoder is massively overloaded, the input queue was full for most of
the recording. Make sure you upgrade your drivers.

**Comment by locodicegr** [comment]
I Use DDU this morning to install 16.10.1 :/

**Comment by Xaymar** [comment]
Don't use DDU to install hotfix drivers. Install 16.7.3 and then upgrade, or you will end up with an incomplete driver. (Happened to me with 16.9.2 before)

Edit: It's also not recommended to use DDU for anything but having a clean slate to work off of.

**Comment by locodicegr** [comment]
99% my problem is fixed with 1.3.3.1.

**Comment by Xaymar** [comment]
1.3.3.1 changed nothing that could have caused this - it optimized away some loops, but your issue is probably not the plugin here.

**Comment by Xaymar** [comment]
No response from user, closing this.
