### ISSUE TITLE
Artifacts on Livestreams and Recordings.

### ISSUE THREAD

**Issue by DoctorSoup143** [Xaymar/OBS-AMD-Advanced-Media-Framework#109]
I've gone through all the settings, tried multiple resolutions and everything in between. I went far enough to use DDU and install the latest BETA AMD drivers for my card (R9 380). It's most likely related to my GPU due to the fact that my cousin (who has an R9 390) has no issues with the framework. Any ideas/fixes/support will help. These issues were present in the previous build as well.

**Comment by max20091** [comment]
Can I ask for your configuration when recording with R9 380?
Also reduce B-Frames to 0 and set QP at lower value may help

**Comment by Benman2785** [comment]
when using DDU you should install 16.7.3 AND THEN install 16.10.1 hotfix -> or you will stuck with an incomplete driver

do you stream on twitch? - if yes take my settings from https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/issues/90

have in mind you need to be Partner on twitch.tv or you are forced to 3500kbps bitrate (max 4900kbps peak) -> so max you can stream is 720p60 (but 720p30 looks better)

**Comment by DoctorSoup143** [comment]
@Benman2785 I did do that I just wanted to state the driver version I was on.

**Comment by DoctorSoup143** [comment]
@max20091 It's not recording I want to do, it's streaming. if I list out the settings I have they would be

**Preset:** Twitch
**Keyframe Interval:** 2
**Quality Preset:** Quality
**Profile:** Main
**Profile Level:** 4.1
**Rate Control Method:** CBR
**Target Bitrate:** 3500
**Filler Data:** Enabled
**Frame Skipping:** Disabled
**Memory Type:** Host
**Compute Type:** Disabled
**Surface Format:** Automatic
**CABAC:** Default

As for my resolution its set to downscale from 1080p to 720p at 60FPS (Bi-Cubic). It always seems that the R9 380 is the problem card.

**Comment by locodicegr** [comment]
''when using DDU you should install 16.7.3 AND THEN install 16.10.1 hotfix -> or you will stuck with an incomplete driver'' That doesnt make any sense though...is there someone from amd can confirm this?

Edit: So i asked on twitter AMD_Robert about this, he said tha he never heard of this ''issue''

**Comment by wazerstar** [comment]
Benman2785 you are wrong even if xaymar said it, you do not have to upgrade.

It's not true, you can FINE use ddu to clean and use the latest hotfix which will have all files installed.

I do so, I'm on a 290 and a 480 test bench.

**Comment by Xaymar** [comment]
@DoctorSoup143 How do these artifacts look like? You hardly gave me anything to go off of, please read the [Troubleshooting Guide](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/wiki/Troubleshooting-Guide) and see if your issue isn't fixed by any of the included steps.

@Benman2785 @locodicegr @wazerstar There are beta drivers that **do not** have all content. OpenCL for example was missing in 16.9.2 and 16.8.3. As for 16.10.1, it seems to contain everything. Please do not misquote me, the original message is here: https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/issues/107#issuecomment-251938538
16.10.1 does not have this issue and seems to have everything the stable package does.

**Comment by wazerstar** [comment]
@Xaymar nope.

http://image.prntscr.com/image/550df475504e44658e23ede520ef1cab.png

**Comment by Xaymar** [comment]
@wazerstar That's strange, it didn't install those for me which caused issues while testing (otherwise OpenCL backend would have been in much earlier).

**Comment by max20091** [comment]
I think because the encoder use "Fast - Fastest" preset so it don't have enough bitrate for the video => produce a lot of artifacts especially with dark frames
3500kbps for 60FPS is too low if using AMF to stream, you will need ~6000kbps if you want to stream using AMF

**Comment by Xaymar** [comment]
Well, given that we have no example of how it looks vs how it should look, i think that the bitrate is too low indeed. At Quality Preset: Quality, 3500kbps is decent for 720p60, but it won't look too good in motion.

**Comment by DoctorSoup143** [comment]
I have tried all of these fixes and more. Here is a video of the issue. Its impossible to miss.https://youtu.be/HzDXa1L6L-A

**Comment by Xaymar** [comment]
What am I supposed to be looking at? Low FPS? Too Low Bitrate/Bandwidth for high motion scenes? I'm really confused as to what you are referring to. There were slight I-Frame QP issues (too low bitrate/qp value) but otherwise it looked fine.

**Comment by Zerowalker** [comment]
I looked at the video and i also can't see any artifacts.
I see FPS drop and bad quality, but that's it.
