### ISSUE TITLE
Is it normal that AMF gets 20-30 fps while VCE can get 120 fps?

### ISSUE THREAD

**Issue by MarioPL98** [Xaymar/OBS-AMD-Advanced-Media-Framework#110]
Hi. I just upgraded to obs 0.16.2 from 0.15.something. Before I was using AMD Video Coding Engine H.264. Now I tried this new AMD Advanced Media Framework. I could easily get 60/120 fps at full hd with VCE but I can barely get 25-30 FPS with AMF codec. I tried every preset. Whats wrong?
It lags few secs even after I click stop recording.

PC specs:
960t@3.6GHz
rx 470 4GB, Crismon 16.9.1
16GB ddr3 1600MHz
Windows 7 on SSD and recording to another SSD

If You need more info, just tell me what should I post. Thanks.

EDIT
Now I noticed that VCE is slower too. It lags sometimes even at 60 fps. Going to reinstall older version and test again.

EDIT
It really runs slower even on 0.15.4. Idk what happends there. I will try to upgrade or downgrade drivers.

**Comment by Xaymar** [comment]
[Read it and be wiser](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/wiki/Troubleshooting-Guide)

**Comment by MarioPL98** [comment]
I reinstalled OBS, gpu drivers (now 16.9.2) and it seems to work fine.

One weird thing is that in some videos MediaInfo shows CFR and in other VFR. Maybe it has somehing to do with performance. If it starts recording CFR it keeps 120 fps for whole clip, if it starts in VFR it keeps about 65-75 fps. I checked many frames with mpc-hc and skipping 1 frame forward. In VFR there are bigger "jumps" between frames because of lower FPS. It seems like "Quality" or "Speed" doesn't affect that. It's just randomly. Is there any way to force CFR mode? In old OBS there was just simple box to check.

**Comment by Zerowalker** [comment]
Pretty sure it's CFR even if it says VFR.

**Comment by kytos22** [comment]
Can you try the latest driver hotfix 16.10.1? Also try uninstalling first with DDU and then install the driver. Install the latest release of the plugin from this github. 

Please update your issue with this info:

-Currently Installed OBS Version
-Currently Installed Plugin Version
-Log Files for each Video included in the Issue with Debug Tracing active

**Comment by locodicegr** [comment]
A 3rd version of 16.10.1 came out, maybe try it!

**Comment by MarioPL98** [comment]
[2016-10-17 16-07-29.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/533713/2016-10-17.16-07-29.txt)
Here is log that I got from recording almost the same thing with quality (got 79 fps), speed (stable 120 fps, much bigger size) and balanced(114 fps) presets.
I also updated gpu drivers to 16.10.1.
OBS version: 0.16.2 64 bit
Plugin Version: 1.3.3.1 
OBS settings: high quality preset, 1080p@120fps

Now didn't happen this weird thing that I wrote about one post before. Idk why.

EDIT If it matters, game that i'm recording has 600-1200 fps.

**Comment by kytos22** [comment]
RX400 series had trouble with CBR on previous driver releases, also you need filler data to ensure you get a constant bitrate. I'll take a look to the log on home but I'm not an expert, maybe @Xaymar can help. 
2 questions:

1- What do you mean with VCE? Microsoft foundation one? VCE is just the block inside the chip which interact with AMF interface to encode video.

2- Why do you need hundred of FPS? You can try opencl method inside expert options to see if it helps in your system as your processor isn't very powerful. Also you will get different speeds from different presets and capture methods.

**Comment by MarioPL98** [comment]
1. ![image](https://cloud.githubusercontent.com/assets/16231640/19442503/cd645298-9489-11e6-9b93-b106474e4485.png)
   
   I mean this one.
2. Slow mo.
   Cpu usage for recording doesn't even exceed one core.

What best speed I can get with "Quality" profile? "Speed" doubles file size and reduces quality pretty much.

**Comment by locodicegr** [comment]
You are using windows 7?

**Comment by kytos22** [comment]
6.1 Build 7601 --> Yes

**Comment by MarioPL98** [comment]
I said that in first post.

**Comment by kytos22** [comment]
> What best speed I can get with "Quality" profile? "Speed" doubles file size and reduces quality pretty much.

It depends on your hardware and how obs interacts with AMF, I suppose that RX470 and RX480 can handle that. I can try with my 480 but my processor is much more powerful (i7 4970k @ 4.6GHz).

**Comment by MarioPL98** [comment]
What about multicore optimizations in this plugin? My cpu usage is very low while using AMF. 

Can I ask You for underclocking your cpu to about 1.8-2,2GHz, disable HT and test? It should be similar performance then.

If you want, I can post cpu usage graphs from for example task manager.

**Comment by Xaymar** [comment]
I don't think that will help at all. Your bottleneck is definitely bandwidth, but what bandwidth it is exactly is hard to tell. It's likely that your bottleneck is either CPU <-> RAM or CPU <-> GPU, which means that both your CPU and mainboard are the primary causes for low framerate.

As for multicore optimizations, the plugin tries to do things that can be made parallel as parallel as possible (copying frames on CPU, submission, retrieving) and uses the maximum optimization options that are widely available.

**Comment by kytos22** [comment]
> What about multicore optimizations in this plugin? My cpu usage is very low while using AMF. 

This is the one of the main purposes of hardware encoding, alleviate the CPU, but the problem can be the bandwidth as @Xaymar said. I'll test it and see anyway to make comparisons ;-)

**Comment by MarioPL98** [comment]
I did some tests. First I measured cpu usage without recording.
![1](https://cloud.githubusercontent.com/assets/16231640/19446584/c136dd78-9499-11e6-95fd-2f4abb1e0426.PNG)
Then I tested with recording with preset same as before.
![2](https://cloud.githubusercontent.com/assets/16231640/19446598/cac3cc16-9499-11e6-809d-14d1387eb415.PNG)
Then I turned on opencl. 
![3](https://cloud.githubusercontent.com/assets/16231640/19446605/d025af12-9499-11e6-9bc5-94fb0f895101.PNG)
With opencl I couldn't even stop recording. I had to force it, as you can see in second part of the third graph. The video has been recorded but the framerate is like 1-2 fps, sometimes even 1/3 fps.

**Comment by M4RK22** [comment]
Ended droping frames 

19:34:18.748: [AMF Encoder] <Plugin::AMD::VCEEncoder::SendInput> Input Queue is full, dropping frame...

It output half the framerate/bitrate. I will test more later or tomorrow.

**Comment by max20091** [comment]
@MarioPL98 did you installed Intel CPU OpenCL package? if you installed it, uninstall it.

**Comment by kytos22** [comment]
> I'll test it and see anyway to make comparisons ;-)

Well, I tested with my RX480 8GB on my system (i7 4.6GHz + 16GB DDR3 1600MHz, SSD).
- Quality, high 5.2, CBR 20000, 120FPS 1080P --> Drops a frame every second (60FPS).
- Balanced, high 5.2, CBR 20000, 120FPS 1080P --> Performance between 109 and 120 FPS.

**Comment by MarioPL98** [comment]
Can You also test quality based, not bitrate based? And this performance is almost like mine. Can You also test if your pc can handle 4k@30fps recording at quality or balanced? 
Are You using Windows 7?
BTW How about Your cpu usage difference between OBS turned off completely (not even preview) and recording?

It seems like it's not a problem of my weak CPU.

Can anyone explain why QP of I-frame is lower by default than QP of P-frame?

**Comment by kytos22** [comment]
Here at 4K:
- Quality, high 5.2, CBR 20000, 30 FPS 4K --> 19 FPS.
- Balanced, high 5.2, CBR 20000, 30 FPS 4K--> Mostly 30FPS.

**Comment by MarioPL98** [comment]
Thanks. Similar to mine, however I preffer to use CQP.

**Comment by max20091** [comment]
@MarioPL98 I-Frame is the real frame that need a lot of bitrate, P-Frame just predict movement from I-Frame so it use less bitrate than I-Frame and most people want to increase predict quality so you may see P-Frame have higher QP than I-Frame

**Comment by max20091** [comment]
@MarioPL98 I-Frame is the real frame that need a lot of bitrate, P-Frame just predict movement from I-Frame so it use less bitrate than I-Frame, lower I-Frame QP will improve predict quality but also increase a lot of bits per I-Frame

**Comment by Xaymar** [comment]
CQP is massively bandwidth driven. It is incredibly hard to get anything good looking from it that doesn't take at least ~50-80% of the total available CPU bandwidth. Especially at 120 fps you're looking at a very high bandwidth usage, probably much more than the GPU would like to handle.

**Comment by MarioPL98** [comment]
So theoretically CBR or VBR should make less cpu bandwidth than CQP, is that what You mean? What about buffer size?

**Comment by Xaymar** [comment]
Example for 120 FPS at 1920x1080, QP I/P/B set to 22, expected average bandwidth per second:

```
BANDWIDTH = ((1 - (QP / 51)) ^ 2) * ((Width * Height) * 1.5 * (FPSNumerator / FPSDenumerator))
BANDWIDTH = ((1 - (22 / 51)) ^ 2) * ((1920 * 1080) * 1.5 * (120 / 1))
BANDWIDTH = ((1 - (22 / 51)) ^ 2) * ((1920 * 1080) * 1.5 * 120)
BANDWIDTH = ((1 - (22 / 51)) ^ 2) * (2073600 * 1.5 * 120)
BANDWIDTH = ((1 - (22 / 51)) ^ 2) * 373248000
BANDWIDTH = ((1 - 0.431373) ^ 2) * 373248000
BANDWIDTH = (0.568627 ^ 2) * 373248000
BANDWIDTH = 0.323337 * 373248000
BANDWIDTH = 1206837289 Bit/s, 1206837 KBit/s, 1206 MBit/s
```

That's more than a gigabit of data that needs to come back from the GPU in the worst case (entire frame changed, movement prediction failed). That's why you're getting low FPS - Media Foundation doesn't give you this much control, it sees bad requests and does some software magic to correct them.

**Comment by Xaymar** [comment]
Buffer Size is used to control the overall bitrate of the frame in cbr/vbr rate control methods - it controls how much filler data and how strictly it is applied.

**Comment by MarioPL98** [comment]
Damn. I like to use lossless one.

**Comment by Xaymar** [comment]
Jesus dude, are you insane? Lossless is pure murder for a cpu like yours. You need upwards of 8 gigabit or much more bandwidth to even get 30 fps. (Edit: Worst Case, as always)

**Comment by Xaymar** [comment]
Use High Quality or Indistinguishable - or even Recording. There's absolutely no need to use Lossless.

**Comment by MarioPL98** [comment]
Just tested lossless 4k@30fps with "speed" and no frame drops.

Yes, i'm quite insane.

**Comment by MarioPL98** [comment]
I wonder if I can get anything above 30 fps.

**Comment by MarioPL98** [comment]
It can get a bit above 30 fps at "high quality" but drops many frames at 60 fps.

**Comment by Xaymar** [comment]
Before saying that you can get 30+ fps, you should test it with stressful scenes. Moving image at 150+ velocity, flashy action-rich gameplay, many changes from bright to dark. You've probably tested with a scene that used much lower bandwidth that it would take on average in those scenarios.
