### ISSUE TITLE
CBR + PeakBitrate "Problem"

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#112]
hi

for most "streams" i tested CBR + PeakBitrate are added most times -> so i have CBR of 3400kbps + 1132kbps Peak added + AudioBitrate + "strange additional Bitrate" for a total of 4800-5000kbps when streaming on my own rtmp server (will also check for twitch)

when i set PeakBitrate "0" it will result in ~3700-3900kbps -> mostly 3400+128+"strange additional bitrate" with very few peaks (had just one (from 3690 peaked to 4400) in a minute long video)

main problem of this is that CBR needs minQP 1 to work -> if we could set it to 20 or 18 it wouldnt need that much peaks all time for consistent quality -> but as far as i know this is caused by new AMD AMF (because its also now requiered to set minQP 1 with Jackuns VCE fork) -> so we have to talk to AMD to fix this

**Comment by Xaymar** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/18#issuecomment-253003502

Try that, maybe it helps.

**Comment by Benman2785** [comment]
helped - but buffer is now "to strict" ;)
