### ISSUE TITLE
CBR includes audio-Bitrate

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#113]
Hi

CBR - includes audio-bitrate and not only video-bitrate

its more a feature then a bug - but good to know -> so we can set it higher for streaming

**Comment by Xaymar** [comment]
Not a bug.

**Comment by Benman2785** [comment]
and im wrong with it -> so AudioBitrate IS ADDITIONAL to VideoBitrate
