### ISSUE TITLE
add support for keyint_sec

### ISSUE THREAD

**Issue by jumoog** [Xaymar/OBS-AMD-Advanced-Media-Framework#114]
current version ignores Keyframe Interval completely

i guess you can add Keyframe Interval for real if you do the same like nvenc does:

https://github.com/jp9000/obs-studio/blob/a7ef10f7ea318cfafe2ae3b05a5c86faf4a89578/plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c#L207

**Comment by Xaymar** [comment]
[Read and be wiser](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/wiki/Troubleshooting-Guide).

Edit: https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/blob/master/enc-amf/Source/enc-h264-simple.cpp#L679
