### ISSUE TITLE
AMD drivers has changed default installation path, be aware might cause issues with this and other tools.

### ISSUE THREAD

**Issue by wazerstar** [Xaymar/OBS-AMD-Advanced-Media-Framework#115]
all drivers since version 16.9.1 are getting installed to
\SystemRoot\System32\DriverStore\FileRepository

before 16.9.1 it was
\SystemRoot\system32\DRIVERS

**Comment by Xaymar** [comment]
It wasn't changed. It just occasionally doesn't copy the runtime files to system32. Which is an installer bug, but oh well.
