### ISSUE TITLE
Just found this cool thing called VCEEnc

### ISSUE THREAD

**Issue by max20091** [Xaymar/OBS-AMD-Advanced-Media-Framework#119]
Just found this cool site while data mining my favorite game: http://rigaya34589.blog135.fc2.com/blog-entry-799.html
I dunno if this thing can help OBS AMF project but add a issue to here anyway :D

**Comment by Xaymar** [comment]
Looks like a tool to hardware encode to me. Not really useful to me, since it doesn't seem to have been updated in ages and still uses Media SDK if the auto-translation is to be trusted.
