### ISSUE TITLE
Option for Preconfigured Graphics Cards

### ISSUE THREAD

**Issue by DerekCL** [Xaymar/OBS-AMD-Advanced-Media-Framework#12]
Have a box that changes the recommended values for specific graphics cards so that the user does not have to fiddle with all the settings. For example if I entered rx 480 it would change the settings for an optimized experience on the 480. If I changed back to a r9 290 you would then get the recommended settings for that card.

**Comment by Xaymar** [comment]
This would be #8 then.  Marking as duplicate
