### ISSUE TITLE
Stuttering issues

### ISSUE THREAD

**Issue by Compizfox** [Xaymar/OBS-AMD-Advanced-Media-Framework#120]
Hi,

I'm issues with recording my gameplay at a stable smooth 60 fps. The games run fine, but the recording always comes out stuttery.

**Specs:**

Intel 2500k @ 4.6 GHz
Asus P8P67-M PRO
8 GB RAM @ 2133 MHz
HD7970

**Versions:**

OBS 0.16.2
AMF Encoder 1.3.1.0-1.3.0.5
AMD driver 16.9.2

You can see an example at https://www.youtube.com/watch?v=FoHkYhc_YrE. The stuttering is especially noticeable in the panning shots. It doesn't happen in-game, but only in the recorded video.

I should note that I'm not sure if this is an OBS/AMF specific issue. I've also tried Plays.TV (which also uses VCE) and I have stuttering issues with that as well.

I particularly notice the stuttering in DiRT Rally, but I think it's present with other games as well, and that it's just really noticable with DiRT Rally because of the nature of the footage (fast, smooth, panning shots).

I've tried playing around with the encoder settings but nothing really improves the situation.

So is there anything I can try to improve this or is this just because I have an old (VCE 1.0) card?

Thanks in advance.

**Comment by Xaymar** [comment]
Upgrade to plugin version 1.3.3.2, that's pretty much all i can suggest.

**Comment by max20091** [comment]
You can't record 1080p with 60fps although VCE 1.0 GPU say able to do it. I suggest using 720p or downscale to 720p for the best result
I only test this on my HD 7730 so the things I say above might be wrong

**Comment by Xaymar** [comment]
Quality Preset Speed could help, since it's the fastest one.

**Comment by nwgat** [comment]
1080p30 or 720p60, not 1080p60 in the realworld, i know i have a HD 7970

**Comment by kytos22** [comment]
With a 280x (99% same chip VCE1.0) you need to use balanced or speed preset to do 1080p60, you can do 1080p30 with quality preset. That was my previous card.

**Comment by locodicegr** [comment]
@Compizfox Install 16.10.3 maybe and try again,
Use latest version of the plugin & 64 bit OBS.
Also avoid to use mp4.

**Comment by Compizfox** [comment]
Thanks for all the responses.

I have the same issue when recording in 720p60.

I forgot to mention that I'm already using the `speed` quality preset. With the quality preset set to `quality`, I also get heavy stuttering _in-game_ (not only in the recording).

I'll try if 16.10.3 makes any difference.

@Xaymar Where can I find the 1.3.3.2 plugin? That latest version I can find on Github is 1.3.3.1.

**Comment by Xaymar** [comment]
@Compizfox I meant 1.3.3.1, but I was on a phone and Github on phones doesn't allow editing.

**Comment by Xaymar** [comment]
Bumping this issue since I changed the repository name.

**Comment by Compizfox** [comment]
@Xaymar Ah, no problem.

I downloaded and tried 1.3.3.1 but unfortunately this doesn't seem to improve it.

I'm afraid I'm just hitting the boundaries of what my card can do (in terms of VCE support).

**Comment by Xaymar** [comment]
Looks like it to me. You'll probably have to invest in a cheap VCE2/3 or 3.4 card. R7 360s go for <100€ here, so maybe you can find something similar in your area too.

**Comment by Compizfox** [comment]
A R7 360 would be a (substantial) downgrade compared to my current card ;) But I've been eyeballing the RX480 for a while now...

**Comment by Xaymar** [comment]
It's only for encoding unless you don't have the option to have two cards installed. In that case, a RX makes more sense here. Good luck finding a good card for your needs. :)

**Comment by Compizfox** [comment]
@Xaymar Ah, I see. I hadn't considered that. Anyway, thanks for your help.
