### ISSUE TITLE
Wild bitrates fluctuations on different recordings

### ISSUE THREAD

**Issue by Shivansps** [Xaymar/OBS-AMD-Advanced-Media-Framework#121]
OK this issue makes me want to smash my head on the wall since i got the RX480, and its the reason of why i cant record any gameplay, because sometimes its OK, in others the bitrate goes to the ground.

For example, using this config
http://i.imgur.com/PO9RY2n.png

My first sample video resulted on 1M=457MB, with a overall bitrate of 61.4mbps, the video was exactly 1M, quality was very very good.

Then went ahead and recorded a full game scene of 10M... the file size was 850MB and overall bitrate was 10.4mbps!

I had similar issues with VBR and VBR_LAT, where sometimes the videos goes way, way below the target bitrate resulting in very bad quality, like if i set a target bitrate of 35-40mbps, sometimes the videos are overall 10mbps... with very bad quality, i think that should not happen, and im starting to think something may be broken in VCE 4.0 because Plays.TV has the exact same issue.
This is to me becoming difficult to test as it seems to happen completely random.
So i cant really trust any variable bitrate to record gameplay at this point.

using CBR does not really works, first the video seems to have random issues with quality, and bitrate is far off, and also seems to be variable or something, i set 45mbps in CBR, the overall bitrate of video is 32mbps....

Another, not really related to this issue, using "computation:OpenCL" results in higher CPU usage, about twice, and very very very laggy videos.

And im gona take the oportunity to ask, is H265 recording possible at some point in the future?

OBS 0.16.2 x64/W10
Plugin 1.3.3.1
16.10.3
VCE 4.0/RX480

**Comment by M4RK22** [comment]
Eres español verdad? Hay varios bugs que van a ser supuestamente solucionados con la proxima version estable de los drivers (no hotfix). No es posible codificar de momento h265 HEVC, aunque está confirmado que van a sacar una actualizacion que permita hacerlo, no se sabe cuando.

https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/18
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/3

**Comment by Xaymar** [comment]
@Shivansps Please follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide) closely. You'll notice what is wrong with your report when you actually have read it.

To clear up the Rate Control Methods (which I have already outlined in the Wiki for this repository) to you, here is what each of them does:

**Constant Bitrate (CBR)**
The most performance hungry of all RCMs, it will attempt to stay at the Target Bitrate or fall below it and uses the VBV Buffer to keep track of how much bitrate it currently has used. If Filler Data is enabled, it will fill up the remaining bitrate that was not used with empty data. 
_Used Constraints:_ VBV Buffer, Target Bitrate, Min/Max QP

**Variable Bitrate (Peak Constrained) (VBR)**
VBR will stay below the given Peak Bitrate, not going over it but also doing no extra work to stay at it. It uses the VBV Buffer to keep track of how much was used already. 
_Used Constraints:_ VBV Buffer, Peak Bitrate, Min/Max QP

**Variable Bitrate (Latency Constrained) (VBR_LAT)**
VBR_LAT seems to use the encoding latency for a frame and is by far the best for recording as it has the least performance impact of them all. It will dynamically adjust to a given situation, going either above or below the Target Bitrate but overall tries to stay at the Target Bitrate as much as possible. 
_Used Constraints:_ Min/Max QP 
_Partial Constraints:_ Target Bitrate, VBV Buffer

**Constant QP (CQP)**
Easiest to explain, AMF will use a fixed QP value for each of the individual frame types. Ideal setup here is to pick an I-Frame QP (your minimum quality) and then choose P-/B-QP below that I-Frame QP, with optional B-Picture Deltas set up if supported.
_Used Constraints:_ I-/P-/B-Frame QP  

What is "computation:OpenCL"? There is Compute Type, but that will only work with the correct Memory Type and CPU/GPU setup. Systems with a IGP, Multi-GPU or mobile-switchable GPUs (Optimus and AMD Hybrid) will perform worse as it will prefer to use the CPU for this action. I am working on a possible fix for this in the future.

HEVC will be possible when AMD (@MikhailAMD can answer this question) publicly releases the SDK for it. I could get HEVC support using my reverse engineered work, but I'm sure the Driver team has it's reasons to keep it not public so far (encoding issues, driver crashes, etc).

@M4RK22 Please only speak English in the Issue Tracker. If you wish to speak another language, message the user directly. Thank you.

**Comment by Xaymar** [comment]
Bumping this issue since I changed the repository name.

**Comment by Shivansps** [comment]
I dont think you did understand it right, on VBR or VBR_LAT for example, why, if i set the target bitrate to 40mbps it will drop to 10mbps most of the time? sometimes its so bad i can easily notice the bitrate going up and down.
ONE thing whould be dropping to 10mbps if not needed, another it is dropping to 10mbps and ending in bad quality. Those wild alterations is what makes me unable to record at all, maybe its fine, for 1 video, for no reason on the next video quality is terrible because the avg bitrate went down and its WAY below the target.

This is the same issue im expericing with Plays.TV for example, this is what leads me to belive its maybe a VCE side bug.

Its kinda hard to reproduce because its random, but if i can, i will upload samples to show you.

Also 40mbps should be enoght for a good quality video, i used to record at 35mbps with a 750TI(shadowplay uses constant bitrate), VCE cant be THAT bad.

**Comment by Xaymar** [comment]
You still have not updated your initial issue with what I linked you to. I will be forced to close this as invalid unless you do.

**Comment by Shivansps** [comment]
The " Troubleshooting Guide " links are broken, they all lead to the old repository.

**Comment by Xaymar** [comment]
https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide

**Comment by kytos22** [comment]
https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide I think is not that bad but one thing that makes the 480 not so good is that it does not support B-frames. There is maybe a bug, we are waiting for AMD to release a mandatory driver to fix some bugs.

**Comment by Shivansps** [comment]
OK, im gona wait for new plugin version and maybe new driver version because this seems to be driver problem, if i can reproduce them im gona open a new issue, im leaving this here for the record, but VBR IS  BROKEN on VCE 3.4 (RX480), no 2 ways about it, just tested with the recomended configuracion, VBR_LAT works, seems to keep close to target bitrate and quality across the board is good, but using VBR the results are far, far below the target bitrate and visual quality drops can be noticed a lot, this should not be happening, specially on "quality", this same issue seem to be shared with other programs ive tested.
