### ISSUE TITLE
Variable Bitrate (Peak Constrained) (VBR) ignores user settings

### ISSUE THREAD

**Issue by chummy02** [Xaymar/OBS-AMD-Advanced-Media-Framework#125]
So VBR(peak constrained) used to work before latest update 16.11.1+1.4.0 with my VCE 2. It always produced average and max bitrate exactly what i specified in AMF encoder. Now it always record average of 31Mbit/s. VCEencc and OBS Media Foundation VBR still work like before with new driver so i guess new plugin version messed things up. 

Second issue with update on b-frames for VCE2 in 16.11.1. B-frames were causing this flickering image glitch since some recently AMD driver like you already reported and 16.11.1 fixed the image issue. But now recording with b-frames >0 in AMF encoder video output become very laggy at 16fps only(should be 59.940). In OBS Media foundation using b-frames video output is fine too besides MF cause MPC-HC to read fps wrong but real fps is right. VCEencc even using old SDK is producing fine output with 3 b-frames without image glitch or framerate. VCEencc was causing same image glitch too with b-frames added in previous AMD drivers so 16.11.1 fixed it there too.

Full System Specifications: 
i7 4770k + ASUS Z87
2x8Gb 2400
R9 390
SSD=OS, HDD1=Game, HDD2=Recording
OBS Version= 0.16.3 x64
Plugin Version= 1.4.0.0
AMD Driver= 16.11.1
Windows 10 Pro x64

Log: https://gist.github.com/ed8a6951d6a78e8b6cd4502f0a5e4b77

**Comment by Xaymar** [comment]
VBR (Peak) was also broken with 1.3.3.1. I'm working on a fix.

As for B-Frames, those are resource intensive. If your card can't do them any more then it can't do them any more.

**Comment by chummy02** [comment]
Media Foundation in OBS 16.2+16.11.1 can do b-frames at 1080p@60fps at same game tested than AMF encoder. There should be something wrong in AMF encoder. VCEencc too can encode with 3 b-frames at balanced 1080p@78fps.

 Using B-frames at slower presets VCE2 encoder is faster than not using it. Samething happens to Quicksync and NVENC when using b-frames, slower presets encoding speed increase.

VCEencc Slow preset 0 B-frames= 1080p@45fps
VCEencc Slow preset 3 B-frames= 1080p@65fps

Balanced 0 Bframes = 74fps
Balanced 3 Bframes = 78fps

Fast 0 Bframes = 89fps
Fast 3 Bframes = 84fps

**Comment by chummy02** [comment]
Good job. 1.4.1.0+0.16.4 fixed B-frames problem for CBR, VBR_Latency and Peak constrained all of them working properly here.

Only downside than CQP is totally broken now, encoder refuse to start with CQP enabled:

14:47:57.662: [game-capture: 'Game Capture'] ----------------- d3d11 capture freed ----------------
14:47:58.247: [game-capture: 'Game Capture'] d3d11 shared texture capture successful
14:48:02.315: [AMF Encoder] Starting up...
14:48:02.315: [AMF Encoder] Plugin::AMD::VCEEncoder::VCEEncoder Initializing...
14:48:02.324: [AMF Encoder] Plugin::AMD::VCEEncoder::VCEEncoder Initialization complete!
14:48:02.336: [AMF Encoder] Plugin::AMD::VCEEncoder::SetTargetBitrate Setting to 0 bits failed with error AMF_OUT_OF_RANGE (code 5).
14:48:02.393: [VCEEncoderTrace]  Warning: SetProperty TargetBitrate failed in AMFPropertyStorageExImpl with return code:0x5
14:48:02.545: [AMF Encoder] Exception: Plugin::AMD::VCEEncoder::SetTargetBitrate Setting to 0 bits failed with error AMF_OUT_OF_RANGE (code 5).
14:48:02.545: [AMF Encoder] Unable to create Encoder, see log for more information.

**Comment by Xaymar** [comment]
1.4.1.0 changed nothing related to CBR, VBR_LAT or VBR. The only thing it did fix was that framerate/size wasn't applied properly - which it is now.

EDIT: CQP bug will be fixed soon-ish

**Comment by chummy02** [comment]
I think expressed bad myself, i just wanted to say than b-frames is working properly now and just to be sure i tested b-frames in all of them.

Only VBR Peak constrained caused some strange average bitrates yesterday which i dont know exactly why but worked fine today, maybe something i messed up but that is unimportant now.

**Comment by Xaymar** [comment]
Only CQP seems to be working correctly, the rest ends up as VBR_LAT. Investigating why this happens, but I don't have an ETA for a fix yet.

**Comment by chummy02** [comment]
VBR is already working properly in VCE2, the problem you guys are finding with VCE3+ is not a concern in VCE2. Just tested and was working fine, bitrate target was 50Mbit with 70Mbit peak and average bitrate becomes 40Mbit. The day 1.4.0 + 16.11.1 come out i tested and it caused a targeted 15Mbit/s VBR to become 31Mbit/s output, so because that i get some concerns at that time, but this dont happens anymore.

I want to share some findings about performance, i will post here if you think is not appropriate can move/delete.

I seeing the rx480 guys complaining about frameskipping/duplicate frames than the recording/encoding is causing so i decided to make some tests here to share something about VCE2 at least, probably is not samething to VCE3+. Just making some tests with Witcher 3 and Ashes of the singularity which are heavy CPU/GPU games, i pick that games because they are very hard to record with OBS/VCE without performance problem. 

So for start in AotS if i use game capture with VCE or Quicksync it duplicate same frame for like 3-4x consecutive causing video playback to look like 10fps. If i change from game capture to display capture then the duplicates decrease, yet dont look good enough but it decrease to something like 1x duplicated per frame what make playback feel smoother than game capture. In Witcher 3 game capture cause some duplicated frames but not too much like AotS, once every 5 frames sometimes after 10 frames, recording with fps unleashed.

Now what i find than improve things. Using Win10DVR in AotS it duplicated only 3 of 60 frames at first  second and duplicated 8 frames of 60 in the next second. I suspect it's the case about Win10DVR having better frame capture(lower latency/delay) than OBS has. With Witcher 3 samething, with Win10DVR duplicated frames pratically disappear while with OBS has some randomly. There was already in past NVENC users complaining about OBS with too much duplicated/skipping frames against what Shadowplay was capable to do without loosing too much frames, since there always has some loses like 2-4 frames for second in a 60fps recording but OBS in heavy games cause too much loss.

In the less demanding games OBS cause no hassle. Just to be clear i'm the guy than make the VCE 2.0 video at Reddit. But what i posted here has nothing to do with that test since BF4 is a "less demanding game" and caused no problems to OBS.

**Comment by Xaymar** [comment]
VBR is still broken. Whether this is due to driver or plugin stuff has yet to be determined. I'll hear back from AMD on Monday about this.

**Comment by chummy02** [comment]
Just want to be sure if i understand what you expect from VBR Peak Constrained. Jackun fork and Media Foundation VBR Peak always worked like how it working in AMF, if the scene is low demand it drop average bitrate below target and it keep average bitrate of the Target bitrate at more demanding scenes and not the Peak.  From what i read you expecting it to keep Peak bitrate for average? But none of other VCE implementations worked like that.

VBR Peak Constrained is only doing too low bitrate if i leave buffer automatic then it selecting too low buffer size, but using manual the average bitrate at normal/high scenes stay at the Target.

**Comment by Xaymar** [comment]
Turns out VBR isn't broken, it was just something weird with my driver install.
