### ISSUE TITLE
Constant Bitrate (CBR) ignores user settings

### ISSUE THREAD

**Issue by Xbye** [Xaymar/OBS-AMD-Advanced-Media-Framework#126]
https://gist.github.com/anonymous/1f5ee8392c38521e2923241d1d2844d0

Tried automatic, tried manual. It refuses to listen to the bitrate. I am currently streaming at around 5000 ~ 9000 bitrate uncontrollably.

**Comment by kytos22** [comment]
Same here, for me it goes up to 17000 KBPS with the latest driver and after disable and enable filler data it does not work anymore and the values aren't applied.

**Comment by Xaymar** [comment]
This should also happen with 1.3.3.1 then. There are (next to) no code order differences when applying the rate control settings between 1.3.3.1 and 1.4.0.0:

### 1.3.3.1 Code

```
// Rate Control Method
    m_VideoEncoder->SetRateControlMethod((VCERateControlMethod)obs_data_get_int(settings, AMF_H264_RATECONTROLMETHOD));

    /// Parameters
    m_VideoEncoder->SetTargetBitrate((uint32_t)obs_data_get_int(settings, AMF_H264_BITRATE_TARGET) * 1000);
    m_VideoEncoder->SetPeakBitrate((uint32_t)obs_data_get_int(settings, AMF_H264_BITRATE_PEAK) * 1000);
    m_VideoEncoder->SetMinimumQP((uint8_t)obs_data_get_int(settings, AMF_H264_QP_MINIMUM));
    m_VideoEncoder->SetMaximumQP((uint8_t)obs_data_get_int(settings, AMF_H264_QP_MAXIMUM));
    m_VideoEncoder->SetIFrameQP((uint8_t)obs_data_get_int(settings, AMF_H264_QP_IFRAME));
    m_VideoEncoder->SetPFrameQP((uint8_t)obs_data_get_int(settings, AMF_H264_QP_PFRAME));
    try { m_VideoEncoder->SetBFrameQP((uint8_t)obs_data_get_int(settings, AMF_H264_QP_BFRAME)); } catch (...) {}
    try { m_VideoEncoder->SetBPictureDeltaQP((int8_t)obs_data_get_int(settings, AMF_H264_QP_BPICTURE_DELTA)); } catch (...) {}
    try { m_VideoEncoder->SetReferenceBPictureDeltaQP((int8_t)obs_data_get_int(settings, AMF_H264_QP_REFERENCE_BPICTURE_DELTA)); } catch (...) {}

    /// Buffer Size, Initial Fullness
    if (obs_data_get_bool(settings, AMF_H264SIMPLE_USE_CUSTOM_BUFFER_SIZE)) {
        m_VideoEncoder->SetVBVBufferSize((uint32_t)obs_data_get_int(settings, AMF_H264SIMPLE_CUSTOM_BUFFER_SIZE) * 1000);
        m_VideoEncoder->SetInitialVBVBufferFullness(obs_data_get_double(settings, AMF_H264SIMPLE_CUSTOM_BUFFER_FULLNESS) / 100.0);
    } else {
        m_VideoEncoder->SetVBVBufferSize(0);
        m_VideoEncoder->SetInitialVBVBufferFullness(1.0);
    }

    /// Filler Data and Frame Skipping
    m_VideoEncoder->SetFillerDataEnabled(!!obs_data_get_int(settings, AMF_H264_FILLERDATA));
    m_VideoEncoder->SetRateControlSkipFrameEnabled(!!obs_data_get_int(settings, AMF_H264_FRAMESKIPPING));
```

### 1.4.0.0 Code

```
// Rate Control Properties
    m_VideoEncoder->SetRateControlMethod((VCERateControlMethod)obs_data_get_int(data, AMF_H264_RATECONTROLMETHOD));
    m_VideoEncoder->SetMinimumQP((uint8_t)obs_data_get_int(data, AMF_H264_QP_MINIMUM));
    m_VideoEncoder->SetMaximumQP((uint8_t)obs_data_get_int(data, AMF_H264_QP_MAXIMUM));
    switch ((VCERateControlMethod)obs_data_get_int(data, AMF_H264_RATECONTROLMETHOD)) {
        case VCERateControlMethod_ConstantBitrate:
            m_VideoEncoder->SetTargetBitrate((uint32_t)obs_data_get_int(data, AMF_H264_BITRATE_TARGET) * bitrateMultiplier);
            m_VideoEncoder->SetPeakBitrate(m_VideoEncoder->GetTargetBitrate());
            m_VideoEncoder->SetFillerDataEnabled(obs_data_get_int(data, AMF_H264_FILLERDATA) == 1);
            break;
        case VCERateControlMethod_VariableBitrate_PeakConstrained:
            m_VideoEncoder->SetTargetBitrate((uint32_t)obs_data_get_int(data, AMF_H264_BITRATE_TARGET) * bitrateMultiplier);
            m_VideoEncoder->SetPeakBitrate((uint32_t)obs_data_get_int(data, AMF_H264_BITRATE_PEAK) * bitrateMultiplier);
            m_VideoEncoder->SetFillerDataEnabled(false);
            break;
        case VCERateControlMethod_VariableBitrate_LatencyConstrained:
            m_VideoEncoder->SetTargetBitrate((uint32_t)obs_data_get_int(data, AMF_H264_BITRATE_TARGET) * bitrateMultiplier);
            m_VideoEncoder->SetPeakBitrate((uint32_t)obs_data_get_int(data, AMF_H264_BITRATE_PEAK) * bitrateMultiplier);
            m_VideoEncoder->SetFillerDataEnabled(false);
            break;
        case VCERateControlMethod_ConstantQP:
            m_VideoEncoder->SetIFrameQP((uint8_t)obs_data_get_int(data, AMF_H264_QP_IFRAME));
            m_VideoEncoder->SetPFrameQP((uint8_t)obs_data_get_int(data, AMF_H264_QP_PFRAME));
            try {
                m_VideoEncoder->SetBFrameQP((uint8_t)obs_data_get_int(data, AMF_H264_QP_BFRAME));
            } catch (...) {}
            m_VideoEncoder->SetFillerDataEnabled(false);
            break;
    }
    if (obs_data_get_int(data, AMF_H264_VBVBUFFER) == 0) {
        m_VideoEncoder->SetVBVBufferAutomatic(obs_data_get_double(data, AMF_H264_VBVBUFFER_STRICTNESS) / 100.0);
    } else {
        m_VideoEncoder->SetVBVBufferSize((uint32_t)obs_data_get_int(data, AMF_H264_VBVBUFFER_SIZE) * bitrateMultiplier);
    }
    m_VideoEncoder->SetInitialVBVBufferFullness(obs_data_get_double(data, AMF_H264_VBVBUFFER_FULLNESS) / 100.0);
    m_VideoEncoder->SetFrameSkippingEnabled(obs_data_get_int(data, AMF_H264_FRAMESKIPPING) == 1);
    m_VideoEncoder->SetEnforceHRDRestrictionsEnabled(obs_data_get_int(data, AMF_H264_ENFORCEHRDCOMPATIBILITY) == 1);
    if (obs_data_get_int(data, AMF_H264_MAXIMUMACCESSUNITSIZE) != 0)
        m_VideoEncoder->SetMaximumAccessUnitSize((uint32_t)obs_data_get_int(data, AMF_H264_MAXIMUMACCESSUNITSIZE));
```

**Comment by Xbye** [comment]
@Xaymar 
I am currently streaming with **1.3.3.1** - I reverted back from 1.4.0.0.

With 1.3.3.1 I am maintaining consistent CBR with no issue. 1.4.0.0 just goes crazy.

**Comment by Xaymar** [comment]
Like I said before, there are no differences between parameters in 1.3.3.1 and 1.4.0.0. Merely saying that it works does not help me a bit, I need to know where it fails instead.

**Comment by Xaymar** [comment]
Try and see if 1.4.1.0 helps.

**Comment by Xbye** [comment]
Currently using 1.4.1.0 and I can state that the issue _**seems**_ to be resolved, as CBR is consistently working.

**Comment by Xaymar** [comment]
Then this shit just stopped making any sense. 1.4.1.0 only fixed Frame Size and Frame Rate so what the fuck is going on.

**Comment by kytos22** [comment]
@Xbye For me worked well but then Filler Data randomly stoped working making CBR useless.

**Comment by Xbye** [comment]
@Xaymar 

> Then this shit just stopped making any sense. 1.4.1.0 only fixed Frame Size and Frame Rate so what the fuck is going on.

How I feel when i am trying to overclock, Haha. I will keep debug enabled in case I run into any issues. Is there any other 3rd-party apps you would like me to be running in case to help diagnose future issues?

**Comment by Xaymar** [comment]
So it seems that there is only VBR_LAT and CQP working now. No idea why, anything I set that isn't CQP is ignored.

**Comment by Xbye** [comment]
@Xaymar 
LOG:
https://gist.github.com/anonymous/e976dc30d1196f7b05283608fa30cf69

I had to revert to 1.3 mid-game (had to AFK a round). Essentially... CBR is initially working but then after a few seconds/minutes it goes crazy.

**Comment by Xbye** [comment]
Any news on this, Xaymar?

**Comment by Xaymar** [comment]
Monday

**Comment by Xbye** [comment]
Issue doesn't seem to be resolved in the current newest version (1411). It works well until there is absolutely nothing big moving around in the scene, then skyrockets and after a few seconds tries to correct itself and goes back down to 2500 CBR. Easily replicated by staring at some motionless wall then once the bitrate drops start swinging your mouse around.

**Comment by Xaymar** [comment]
I'm still working on figuring out what causes it and which cards/vendors are affected.

**Comment by Xbye** [comment]
@Xaymar 
This is my card:
http://www.bestbuy.com/site/xfx-amd-radeon-rx-480-8gb-gddr5-pci-express-3-0-graphics-card-black/5507268.p?id=bb5507268&skuId=5507268&cmp=RMX&ref=17&loc=11&CampaignID=798817&SubscriberID=82242074

**Comment by ghost** [comment]
In the previous version on my R9 390x by Sapphire, it also is variable. Didn't test this one yet.

**Comment by Xaymar** [comment]
Got word back from MikhailAMD, the answer is that some scenes hit hardware limits - QP values can only go so high before things need to be dropped. Frame Skipping can help here as it just tells the decoder to repeat last frame.
