### ISSUE TITLE
Unlock Properties not working

### ISSUE THREAD

**Issue by Xbye** [Xaymar/OBS-AMD-Advanced-Media-Framework#127]
https://gist.github.com/anonymous/1f5ee8392c38521e2923241d1d2844d0

Same log as the other. Attempting to use unlock properties to try and force profile level to 4.1 for Twitch doesn't work at all. Both reset after applying an closing the window.

**Comment by Xaymar** [comment]
That is not what unlock properties does. You shouldn't be using "Unlock Properties" either.

**Comment by Xbye** [comment]
@Xaymar Should I make a new issue/thread regarding not being able to change settings when a preset is selected?

**Comment by Xaymar** [comment]
That's intended behaviour. If you want to change settings, change the preset back to nothing.
