### ISSUE TITLE
Missing files when they actually in place/crash when recording starts

### ISSUE THREAD

**Issue by aquamacho** [Xaymar/OBS-AMD-Advanced-Media-Framework#130]
Win 7 x64 with sp1 installed
Drivers: AMD Radeon Software Crimson 16.11.1
Obs Studio: 0.16.3
Visual C++ 2015 installed (14.0.24406) x32\x64
[2016-11-04 02-56-20.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/570407/2016-11-04.02-56-20.txt)
x64 crash log
[Crash 2016-11-04 02-40-04.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/570409/Crash.2016-11-04.02-40-04.txt)
x32 crash log
[Crash 2016-11-04 02-56-26.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/570410/Crash.2016-11-04.02-56-26.txt)
Screenshot showing that files are in place.
![screenshot_2](https://cloud.githubusercontent.com/assets/23249682/19991052/08f77b0a-a23b-11e6-97f0-104511c90320.png)
and one more, when selecting presets like youtube, after changing bitrate to something else its resetting to default 6000 after obs restart (this worked in 1.3.3.1), not sure if this intended or not.

Sorry, i didnt see that issue is already been reported multiple times, im so dumb sometimes.

**Comment by Xaymar** [comment]
There are no missing files related to AMD encoding in your log, what are you trying to report exactly?

**Comment by Xaymar** [comment]
Your crash also happened inside the driver itself, outside of my control.

**Comment by aquamacho** [comment]
Not sure what i`m trying to report either, just installed obs studio version 0.16.2 and all works just fine.
They fixed something for windows 10 and broke amf for win7 :(
With vanilla obs 0.16.3 AMF encoder not even listed for me in advanced settings......
![screenshot_1](https://cloud.githubusercontent.com/assets/23249682/19999632/37ceed3c-a27c-11e6-8c72-a7341e7d16e6.png)
Thats what log saying
10:47:47.017: LoadLibrary failed for '../../obs-plugins/32bit/enc-amf.dll': The specified module could not be found.
But enc-amf.dll file is there.....
[2016-11-04 10-47-44.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/570977/2016-11-04.10-47-44.txt)

**Comment by Xaymar** [comment]
See #132.
