### ISSUE TITLE
Unable to record at 60 fps

### ISSUE THREAD

**Issue by Shivansps** [Xaymar/OBS-AMD-Advanced-Media-Framework#131]
Specs:
Core i5-2500k
18GB DDR3-1333
1TB HDD (Game) + 500GB HDD(Recording)
MSI RX480 8GB

OBS Version:
OBS 0.16.3 (64bit, W10)

Plugin Version:
1.4.0.0

AMD Driver:
16.111 Hotfix

LOG
https://gist.github.com/anonymous/8dfd95600d1967380d1051b4ed4a9b0c

Using this settings:
http://i.imgur.com/shKtVeq.png

OBS is set to record at 60 fps, but the AMF encoder overrides it.

Thinking of it, it whould ne nice to have an override on the plugin so we can set diferent fps for recording/streaming.

**Comment by Xaymar** [comment]
Seems to be caused by using the inproper order of encoding parameters. Slight oversight on my part here.
