### ISSUE TITLE
OBS crashes on stream start

### ISSUE THREAD

**Issue by ghost** [Xaymar/OBS-AMD-Advanced-Media-Framework#133]
Current state of the problem:
After a few updates today, my OBS crashes 90% of the time if I try to stream with any preset used. Sometimes getting a preset and than changing bitrate in it hepls, but most of the time I have to dance with tambourine to reset settings to their normal state...

Answers to https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide
1: Sapphire R9 390x
2: 
VC: Another version of this product already installed
AMD Driver: 16.11,1
OBS Studio: 0.16.4
Plugin: Both patreon only 1.4.1.0 and current OBS are beeing tried out
3:
Did read. Nothing about crashes after trying to stream. Green blocks happened tho, but CABAC was disabled. First ssue now is crashes while using default presets of twitch/youtube with modded bitrate.
4: It happens with both preset on basic mode than switched to empty preset for overriding bitrate, and to preset in master mode with overriding bitrate again. 
5: Yes,it's there: https://github.com/Xaymar/obs-studio_
[Specs.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/572320/Specs.txt)
amf-encoder-plugin/issues/124 but it's closed. And I tried to stream without overriding profile level. If I start recording, it kinda keeps going, but than, it doesn't start if I try to enable stream. And it crashes if I start stream right away.
6: Shouldn't that be in presets already? I really didn'tchange anything but bitrate.

Last log with crash: https://gist.github.com/6b0aeaa3f73b0ef46cdd74c191844531
PC config: http://pastebin.com/WhkX0jF0

**Comment by Xaymar** [comment]
Log file is missing Debug information. Please check the 'Debug' property and upload another one. If it crashes, also include the crash log as it allows me to see where things crashed.

**Comment by Xaymar** [comment]
From the limited information I see, you somehow managed to use OpenCL without DirectX or OpenGL backend. That isn't supported and usually should not even allow the stream to start. Future versions will auto-correct this.

**Comment by ghost** [comment]
Looks like in the current version it is all fine.
