### ISSUE TITLE
CQP broken from 1.4 update

### ISSUE THREAD

**Issue by max20091** [Xaymar/OBS-AMD-Advanced-Media-Framework#134]
I'm trying to record with CQP but OBS doesn't want to start record and switched to default AMF settings
I don't see anything strange in the log file but I will attach 1 log below for analyzing
AMF Plugin ver: 1.4.0.0 - 1.4.1.0
AMD driver ver: 16.10.2
GPU: HD 7730, VCE 1.0
[2016-11-05 08-44-52.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/572956/2016-11-05.08-44-52.txt)

**Comment by Xaymar** [comment]
Already fixed, will be in an update
