### ISSUE TITLE
Some AMF_ACCESS_DENIED error while recording with default presets

### ISSUE THREAD

**Issue by fyrak1s** [Xaymar/OBS-AMD-Advanced-Media-Framework#137]
I have recorded using default presets and it is generally looking well.
However in the logs I see the following error:
`<Plugin::AMD::VCEEncoder::GetQualityEnhancementMode> Failed with error AMF_ACCESS_DENIED (code 3)`
I dunno if it's critical, but I guess it's better I post it here :)
Full log attached.
[obs-log.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/573596/obs-log.txt)

**Comment by Xaymar** [comment]
Left over debug warning messages, only the Input Queue is actually important if it recorded fine.

**Comment by fyrak1s** [comment]
Ah so having this error in there is perfectly fine?

```
[AMF Encoder] <Plugin::AMD::VCEEncoder::GetQualityEnhancementMode> Failed with error AMF_ACCESS_DENIED (code 3).
[AMF Encoder] Quality Enhancement Mode: N/A
```

What is the Quality enhancement mode?

**Comment by Xaymar** [comment]
An internal hidden parameter.

**Comment by fyrak1s** [comment]
Hm I understand. Maybe this error message should be hidden unless the user selects the "Debug" setting in preferences.

**Comment by Xaymar** [comment]
That's what I said in [this comment](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/137#issuecomment-258679113)

**Comment by fyrak1s** [comment]
Yes, but I did _not_ tick the "Debug" setting. So it is obviously a bug in your program.

**Comment by Xaymar** [comment]
Well no shit, that's what I said [in this freaking comment](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/137#issuecomment-258679113)

**Comment by fyrak1s** [comment]
I dont understand... so it will get fixed?

**Comment by Xaymar** [comment]
To clear things up:
- It may end up being "fixed", if I think it is worth "fixing" - it's not a bug.
- The Debug option doesn't have anything to do with things that are written before actually encoding, like this one.

**Comment by fyrak1s** [comment]
Thank you, this is the explanation I was hoping for.
