### ISSUE TITLE
"YouTube" preset is not being set reliably

### ISSUE THREAD

**Issue by fyrak1s** [Xaymar/OBS-AMD-Advanced-Media-Framework#138]
When selecting the "YouTube" preset the target bitrate doesn't get set reliably (and maybe some other options as well, who knows).
To reproduce:

1. Reset presets to default
2. Select "YouTube",  target bitrate will be 3500
3. Now select "Recording"
4. Select "YouTube" agian, target bitrate will be 10000

Other combination work similar of course. I don't think this is intentional right?
Thanks in advance!

**Comment by Xaymar** [comment]
Read the Patch Notes \o/

> - Changed: Adjusted the behaviour of some presets.<br/>'Enforce HRD Compatibility', 'CABAC' and 'Quality Preset' are no longer overridden by Presets. 'Target Bitrate' and 'Peak Bitrate' are now allowed within a certain range in 'Twitch', 'YouTube' and 'Recording' Presets. Twitch limits between 1.0 and 4.0 mbit/s, YouTube between 1.0 and 25.0 mbit/s, Recording accepts anything larger than 10.0 mbit/s.
