### ISSUE TITLE
post-transcoding with ffmpeg gives huge artefacts&blocking

### ISSUE THREAD

**Issue by ghost** [Xaymar/OBS-AMD-Advanced-Media-Framework#141]
So I'm using a youtube preset at 16 mbit/s fullhd 60fps. OBS 0.16.5, 1.4.1.2 encoder

Nginx transcoding application is set like this:

>             application streamto
>             {
>                 live on;
>                 meta copy;
>                 exec avconv
>                     -i          rtmp://localhost/streamto/1234
>                         -vcodec libx264 -preset faster -x264opts nal-hrd=cbr:force-cfr=1:keyint=90
>                         -b:v 3500k -maxrate 4200k -bufsize 4500k -s 1280x720 -sws_flags spline -r 45 -acodec copy
>                     -f flv      rtmp://localhost/streamout/1234;
>             }

As a result of this encoding I see huge blocking with my stream

![Image of blocks](https://i.imgur.com/EypzlK2.jpg)

Same things happened when I was streaming directly to twitch with previous versions. Green screen, many artifacts, especially with action scenes. A brief google search said that it's h264 broken video results in artifacts like that. The recording itself looks all fine, same is youtube clone of the stream. Any tips on how to fix this?

**Comment by Xaymar** [comment]
First, follow the final step in the Troubleshooting Guide. Then I can tell you what to change and where the issue might be.

**Comment by ghost** [comment]
![same frame](https://i.imgur.com/c7HZ55l.jpg)

Same frame from a recording. 
To set things clear - this happened to my twitch stream, that's why I tried to use didecated server to encode, since recs and youtube were fine. Happens with dedicated encoder to x264 as well. Need some help.

**Comment by sneaky4oe** [comment]
Ok, wait for it

**Comment by ghost** [comment]
https://gist.github.com/49e25c0a6911be08c7e6a6b6e897e08d - last log file
http://pastebin.com/WhkX0jF0 - system specs

Radeon driver: 16.11.1
youtube preset at 16 mbit/s fullhd 60fps. 
OBS 0.16.5, 
1.4.1.2 encoder

**Comment by ghost** [comment]
https://gist.github.com/sneaky4oe/f12279983fffe772695d4616cf567f64 A fatter log. I was toying around with presets. I'm afraid that the one I uploaded in the previous message is not the one is needed.

**Comment by ghost** [comment]
And a current log file with blocks in the record - these match for sure:
https://gist.github.com/a0976360e4cd1e769cde4a89432a848f
https://www.twitch.tv/sneaky4oe1080/v/100048608 - blocking at 15-th second

**Comment by Xaymar** [comment]
Try the following:
- Set Profile to High
- Set Level to 5.0 or 5.1
- Enable CABAC
- Set VBV Buffer Strictness to 0
- Set Target Bitrate closer to the non-partner recommended value of 3500kbit - it's at 16mbit right now.

Aside from that, you're also using the "Master" view mode. That usually means no support.

**Comment by ghost** [comment]
Ok. Same results with basic view mode: https://gist.github.com/0207b0b94027438ee33790154160d918
https://www.twitch.tv/sneaky4oe1080/v/100049548 - 14 second
Shouldn't that rule be excluded for custom presets? Like if you can't change most of the settings (and I change mostly bitrate)

With changes recommended: https://www.twitch.tv/sneaky4oe1080/v/100049548
https://www.twitch.tv/sneaky4oe1080/v/100051466 - 0:28
And about bitrate - I know it's too high for twitch, but as I mentioned, it's ffmpeg/avconv encoders can't read and transcode it without artefacts. I use avconv to transcode. And it fails. So does twitch transcoder when I stream at 4000kbit/s twitch preset to my main channel - it leaves tonns of artifacts in there.

Crystal clear recording and youtube streams. Messed up transcoded via twitch or my own avconv.

**Comment by ghost** [comment]
The reason I don't stream to my main channel is not to distract viewers while I'm investigating. But it did have same symptoms with blocks and artifacts on normal bitrates without my avconv server.

**Comment by Xaymar** [comment]
I think it's best to get in contact with the avconv mailing list instead. If the recording looks fine and the artifacts happen after transcoding, then it's not the initial encoders fault.

Edit: You can try ffmpeg with x264 instead, ffmpeg has had no issues with the files I've had here.

**Comment by ghost** [comment]
For me ffmpeg had the same issues, that's why I decided to try avconv. Thought that maybe it's better supported.
But ok, I'll try mailing list if so...
