### ISSUE TITLE
Another crash on stream start

### ISSUE THREAD

**Issue by ghost** [Xaymar/OBS-AMD-Advanced-Media-Framework#142]
Log: https://gist.github.com/254cc06d02283668fac6ca5cd8176032
http://pastebin.com/WhkX0jF0 - system specs
Radeon driver: 16.11.1
youtube preset at 16 mbit/s fullhd 60fps. 
OBS 0.16.5, 
1.4.1.2 encoder

Youtube preset. 1080/60/16mbit/s. Recording+stream started at the same time.

SVP 3 was active at the same time, while using a videocard as encoder ( this thing: https://www.svp-team.com/wiki/Main_Page )

**Comment by Xaymar** [comment]
Crash log?

**Comment by ghost** [comment]
Apologies. Here it is:
https://gist.github.com/sneaky4oe/74451512c8c70e3ef084d0d2f1e4c3e5

**Comment by Xaymar** [comment]
Crash isn't happening in AMD/ATI driver files or the plugin. It's happening somewhere in sdl2.dll, which I don't use. Post this on the OBS forums instead, something else crashed for you that wasn't the encoder.

**Comment by Xaymar** [comment]
srbeep.dll: https://obsproject.com/forum/threads/stream-recording-start-stop-beep-srbeep.48058/
