### ISSUE TITLE
OBS crashing when streaming & recording

### ISSUE THREAD

**Issue by BobbyFuzzy** [Xaymar/OBS-AMD-Advanced-Media-Framework#144]
Hi Xaymar,

Coming over from the OBS forums.

I've reproduced the issue and gotten a memory dump. I've zipped that up along with the relevant logs and my system spec from Speccy. See - https://www.dropbox.com/s/1sm9uv7sz4a7vr8/r4b.7z?dl=0

Using:
OBS 0.16.5
AMF plugin 1.4.1.5
AMD driver 'non-whql-win10-64bit-radeon-software-crimson-16.11.3-nov8'

To reiterate - the issue I'm having is when I am streaming and recording at the same time, OBS crashes after a seemingly random amount of time. It has been anything from ~5mins to ~40mins so far.

I'll also add that I am using only the presets for recording and for streaming, I used the YouTube preset as a base and then bumped the bit rate up to 5000.

Thanks for your help on this.
- r4b

**Comment by ghost** [comment]
Only stream.
twitch preset with 48 fps.
OBS 0.16.5
Plugin: 1.4.1.5
Driver: 16.11.1

There's no crashlog recorded because OBS did hang and didn't crash. I was unable to close it via task manager, but eventually it stopped itself.
https://drive.google.com/open?id=0Bz6nA_MiY6AWSUozaVdBQWlJZk0

**Comment by Xaymar** [comment]
@sneaky4oe Please create your own issue, I will merge them if necessary.

**Comment by Xaymar** [comment]
Try 16.11.4 and report back.

**Comment by ghost** [comment]
Ok, will do.

**Comment by BobbyFuzzy** [comment]
Hi Xaymar,

Updated to latest plugin & driver and getting the same crash by the looks!

Crash log, OBS log, dump and spec here - https://www.dropbox.com/s/cxvplso3jye137l/2016-11-18-crash.7z?dl=0

**Comment by Xaymar** [comment]
Merging this to #143.
