### ISSUE TITLE
1080p60fps recoding constant framedrops 

### ISSUE THREAD

**Issue by xEHLE** [Xaymar/OBS-AMD-Advanced-Media-Framework#147]
Operating System: Windows 10 Home 64-bit (10.0, Build 14393)
System Manufacturer: Gigabyte Technology Co., Ltd.
System Model: H97-D3H
BIOS: BIOS Date: 04/25/14 10:34:00 Ver: 04.06.05
Processor: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz (8 CPUs), ~3.4GHz
Memory: 8192MB RAM
Available OS Memory: 8112MB RAM
GPU: r9 290 3xOC Windforce
SSD: 250gb Samsung evo
HDD: Some 2TB Seagate

OBS: Obs Studio 0.16.5
Plugin version 1.4.1.5

Driver: Radeon software 16.11.3 / Driver Packaging Version
16.40.3111.1101-161108a-308653E (hope this is the right driver number you look for)

Tried lots of different settings and it seems no matter what i set it to, i get frame drops in the recording.
I fiddled around with x264 and it simply uses too much performance to the point where the games i'm trying to record become borderline playable.
Now with h264 the games run with next to no performance impact, but the recordings are not watchable due to the constant dropped frames.
Is my system just not good enough to play the games AND record them at 1080p60fps or is my obs fucking up?

Here is a log file with different settings i tried all giving me basically the same result:
https://gist.github.com/anonymous/b77347d97cab734350312da4348c99d6

If you need more info/specific log files i can do some more test recordings and upload the logs as well.

**Comment by Xaymar** [comment]
Update to 1.4.2.2

**Comment by xEHLE** [comment]
Didn't notice there was already a new version out, very sorry for the inconvenience. Downloaded the last version before going to bed yesterday and still had the support page open.
Works perfectly now, 13 frames dropped out of 20216 in my test recording no hiccups whatsoever.
Thank you for your work! :)

**Comment by Xaymar** [comment]
Could you provide a new log file for comparison?

**Comment by xEHLE** [comment]
Sure, first 2 recordings are in FarCry4 which have slightly higher drops, third recording is in Bf1. 

https://gist.github.com/anonymous/c08c13ce5bf544d33a231fd65ebff27f

**Comment by Xaymar** [comment]
Just as I thought. Your GPU is struggling to encode with B-Pictures, which 1.4.2.x now disable by default. Should have no impact on encoding quality, since it's using CQP anyway.

**Comment by xEHLE** [comment]
Just a question the 2 FarCry recordings are done in display capture, Bf1 was done in game capture. Is that the reason for the higher framedrops?

**Comment by Xaymar** [comment]
No, the default for B-Pictures changed between 1.4.1.5. Your GPU was trying to add B-Frames (a performance heavy task) but couldn't manage 60 fps doing that in the older version, in the newer version those are disabled.
