### ISSUE TITLE
Unable to record 1080P 60 FPS

### ISSUE THREAD

**Issue by ghost** [Xaymar/OBS-AMD-Advanced-Media-Framework#149]
Hi There!

First of all, great work on the plugin. I was previously using version 1.4.1.5 and I can record videos at 1080P with 60 FPS. I updated to the latest version and somehow my recorded videos can't hit 60 FPS anymore.

I noticed there as a similar thread on the issue tracker and I have updated my GPU to the latest drivers, updated visual C++, updated the plugin and OBS as well. However, I still have this issue. I have attached the log file and hope you can advise me. Thanks.

[2016-11-19 02-25-29.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/600654/2016-11-19.02-25-29.txt)

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by max20091** [comment]
> 02:26:28.856: [AMF Encoder] c. (175/5/180)
> 02:26:29.006: [AMF Encoder] Submission queue is full, dropping frame instead...
> 02:26:29.039: [AMF Encoder] Submission queue is full, dropping frame instead...

It seems your setting is too heavy and make Submission queue is full
And if you look at your I-Frame and P-Frame

> 02:26:22.053: [AMF Encoder]     I-Frame: 18
> 02:26:22.053: [AMF Encoder]     P-Frame: 18

You are pushing your GPU to it's limit, try to increase both of them to 22 and see if the Submission queue size is growing slower.
#140

**Comment by Xaymar** [comment]
No response from Issue creator for 4 days, I'll close this unless the issue persists. max20091 gave solutions that you should try.

**Comment by Xaymar** [comment]
Closing as there has been no reply.
