### ISSUE TITLE
VCESpeedTest R9 380 4G

### ISSUE THREAD

**Issue by locodicegr** [Xaymar/OBS-AMD-Advanced-Media-Framework#154]
[test.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/619038/test.zip)

**Comment by Xaymar** [comment]
Anomalies in this test:
- 854x480: Speed is slower than Quality
- 1366x768: Speed, Balanced and Quality all have 68 FPS

**Comment by locodicegr** [comment]
Used Latest ddu in safe mode - install 16.11.5 - restart - re-test !

[Test R9 380 V2.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/622639/Test.R9.380.V2.zip)

**Comment by Xaymar** [comment]
I'll keep the wiki entry as it is as this one has the same anomalies. Maybe you'll figure out what causes them and can do the test again once it's fixed.
