### ISSUE TITLE
VCESpeedTest R9 Nano

### ISSUE THREAD

**Issue by jfoster** [Xaymar/OBS-AMD-Advanced-Media-Framework#155]
[VCESpeedTest_2016-11-16.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/621006/VCESpeedTest_2016-11-16.zip)

It appears that the results for the Nano, for the most part, are identical to the results of the Fury X. Not really surprising considering it's the exact same Fiji GPU as the Fury X, but interesting nonetheless.

**Comment by Xaymar** [comment]
Added to the wiki, thanks for submitting these!
