### ISSUE TITLE
FEEDBACK: "pre Analysis Pass - Enabled" -> looks FANTASTIC 

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#157]
hey

tested your "PreAnalysisPass" on "Enabled" -> looks FANTASTIC with/for 720p60 @3500kbps
now RivaTunerOverlay is better readable and everything looks better

http://benmanshafen.de/pics/OBS/Xaymar/pre_analysis_pass_enabled.mp4

**Comment by Benman2785** [comment]
ps have in mind its 720p60 @3500kbps (so you can stream it to twitch)

**Comment by CKannas** [comment]
@Benman2785 could you share your settings?

I would like to find some nice manual settings for 720p30 for Twitch.

Q: Will enabling OpenCL off-load calculations to GPU? And thus have better performance?

**Comment by Xaymar** [comment]
Keep in mind that these settings are experimental and require you to use view mode Master which disqualifies you from any support.

> Q: Will enabling OpenCL off-load calculations to GPU? And thus have better performance?

It will offload the frame transfer to the GPU, which will only make a difference when there is a GPU usage spike due to games streaming content in and similar.

**Comment by Benman2785** [comment]
![amf_pugin_1 4 3 0_settings_2](https://cloud.githubusercontent.com/assets/21282980/20802549/aa951b36-b7ec-11e6-978f-55ebfcedcb79.jpg)
![amf_pugin_1 4 3 0_settings_1](https://cloud.githubusercontent.com/assets/21282980/20802550/aa9f0c2c-b7ec-11e6-98c6-f416a2cc743a.jpg)

AS SAID - NO SUPPORT FROM DEV // if you want we can go on my TS3 and i help you tweak your settings // but can change with every new Driver and Plugin-Version (because there is work-in-progress)

MAYBE use ProfileLvl 4.2 -> because 5+ is for VCE 3.0 cards (Fury/R7 380/RX 4XX)

**Comment by Benman2785** [comment]
ps when i enable OpenCL i get "Encoder-overload" -> will find out if that has to do with my settings or with AMF

**Comment by Benman2785** [comment]
https://www.youtube.com/watch?v=ex9VpwXoO0k // same video on YT

**Comment by Xaymar** [comment]
Lets hope that Pre-Analysis Pass (Two Pass) and HEVC are stable in the next AMF SDK.

**Comment by Xaymar** [comment]
Closing this. Once Pre-Analysis Pass and HEVC are officially available I will work on getting those to be properly represented.
