### ISSUE TITLE
VCESpeedTest R7 370 2GB

### ISSUE THREAD

**Issue by CKannas** [Xaymar/OBS-AMD-Advanced-Media-Framework#158]
Benchmark results for MSI R7 370 2GB Gaming (Core 1030MHz, GDDR5 1400MHz). 
It's a VCE 1.0 GPU with maximum encoding resolution of 1920 x 1920.

[VCESpeedTest R7 370 2GB.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/623023/VCESpeedTest.R7.370.2GB.zip)

**Comment by Xaymar** [comment]
Added to wiki, thanks!
