### ISSUE TITLE
bitrate is all wonky on gcn1/7970

### ISSUE THREAD

**Issue by nwgat** [Xaymar/OBS-AMD-Advanced-Media-Framework#16]
when i use default settings and set constrained bitrate to 2000, it goes to like 3800 and 22k :/

its like its using CRF or something
stupid question is QP the same as CRF?
- HD 7970 3GB
- OBS 0.15.2 64-bit
- OBS AMD Media Framework 1.1.2 64-bit
- Crimson 16.7.3
- Media SDK installed (runtime or something from link on plugin page)
- Windows 10 Redstone 1

![http://image.prntscr.com/image/2e3b456ec4c54c5c8c6b91409ab4644b.png](http://image.prntscr.com/image/2e3b456ec4c54c5c8c6b91409ab4644b.png)

this is not where i parked my ~~car~~ bitrate

**Comment by Xaymar** [comment]
You parked your bitrate at 2000 bit, that's 2 kbit. I'm not sure what magic you're expecting to happen here. Add three 0s to the end and it should start working.

**Comment by nwgat** [comment]
how about using kbit instead of bits? putting in 17mbps makes way to many zeroes :)

**Comment by Xaymar** [comment]
That's what #8 is for. The advanced encoder is meant to give you full control, if you want it or not.

**Comment by Xaymar** [comment]
Simple Encoder has now been implemented in 1.2.0rc1. Enjoy
