### ISSUE TITLE
VCESpeedTest RX 480

### ISSUE THREAD

**Issue by Saymite** [Xaymar/OBS-AMD-Advanced-Media-Framework#160]
Results:
[Test.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/625925/Test.zip)

On:
[RX 480](http://gpuz.techpowerup.com/16/12/01/agw.png)

**Comment by Xaymar** [comment]
Anomalies:
- Speed slower than Balanced and Quality in some resolutions.

Aside from that, the results are pretty close to what's already on the wiki. Thanks for submitting these!
