### ISSUE TITLE
VCESpeedTest HD 7750

### ISSUE THREAD

**Issue by mirh** [Xaymar/OBS-AMD-Advanced-Media-Framework#161]
[Here](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/625966/7750.ZIP.PDF). 

Of course as always github refuses to accept zips, so I had to change extension.

**Comment by Xaymar** [comment]
Added to the wiki, thanks!

**Comment by mirh** [comment]
Then, just for the records, I believe the first couple of tests were cpu limited.

**Comment by Xaymar** [comment]
Most likely, as the renderer used for the tests is DX11.
