### ISSUE TITLE
VCESpeedTest HD7770 and RX470

### ISSUE THREAD

**Issue by Roph** [Xaymar/OBS-AMD-Advanced-Media-Framework#162]
Latest drivers on both.

[7770.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/625977/7770.zip)
[RX470.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/625973/RX470.zip)

**Comment by Xaymar** [comment]
Your HD 7770 test shows so many anomalies with quality being faster than speed for a lot of resolutions, higher resolutions randomly being faster, etc. Would be great if you could redo that one, as the way it is right now I can't add that to the wiki.

I've added the RX 470 results as they are to the wiki, looks like it's heavily CPU capped at lower resolutions. Thanks for those.

**Comment by Xaymar** [comment]
No response for 6 days, closing.
