### ISSUE TITLE
VCESpeedTest HD7970 Ghz Edition

### ISSUE THREAD

**Issue by MangoNYCr** [Xaymar/OBS-AMD-Advanced-Media-Framework#163]
VCESpeedTest HD7970 Ghz Edition Sapphire Vapor-X 3GB @1150MHz Memory/ 1550MHz Core
Drivers: 16.11.4
[VCESpeedTest_2016-11-16.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/626408/VCESpeedTest_2016-11-16.zip)

**Comment by Xaymar** [comment]
Added to wiki, thanks!
