### ISSUE TITLE
1.4.3.0 doesn't see R9 390x @ 16.11.5

### ISSUE THREAD

**Issue by ghost** [Xaymar/OBS-AMD-Advanced-Media-Framework#165]
Installed a new version of framework. Doesn't see my videocard as encoder. 1.4.1.5 works fine.

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by ghost** [comment]
*sigh*
OBS 0.16.6
Plugin: 1.4.3.0
Driver: 16.11.5
R9 390x
Win8.1

What else to say?.. No option to select...

**Comment by Xaymar** [comment]
Log file?

**Comment by ghost** [comment]
https://gist.github.com/88e42ff02e4c4c9b1d9a4b26a9f35bb7

**Comment by Xaymar** [comment]
`23:47:45.965: [AMF Encoder] <Plugin::API::Direct3D11::CreateInstanceOnAdapter> Failed to enumerate adapters, error code %X.`

For an unknown reason, the plugin failed to create a D3D11 instance on the GPU. This is considered an unsafe environment at the moment and will cause the plugin to not list itself.

**Comment by ghost** [comment]
1,4,1,5 version works just fine...

**Comment by Xaymar** [comment]
1.4.1.5 has a hacked multi-GPU solution in it, that doesn't mean that it works fine, only that the hack works for an unknown reason without taking the entire system with it.

**Comment by ghost** [comment]
https://www.twitch.tv/sneaky4oe1080/v/104810687 - just made it for my channel as a comparison. 1.4.1.5 with 16.11.5 driver

Also, I have only one gpu.

**Comment by Xaymar** [comment]
I'll make a compatibility patch for whatever causes your Direct3D installation to not be supported, though I will not promise that it will help.

**Comment by Xaymar** [comment]
I've modified the code now to still list the encoder even in the case of such a critical failure of a core part. I do not expect it to help in your case, as Direct3D 11.1 should be supported by any Windows 8 system out of the box.

**Comment by Xaymar** [comment]
1.4.3.2 should fix this for you.

**Comment by Xaymar** [comment]
Didn't mean to actually close this.

**Comment by wazerstar** [comment]
Mine is also missing in 1.4.3.2 with 290/x card, I think its AMD driver issue?, Have the latest hotfix which Crimson Edition 16.11.5 Hotfix

Have to go pickup GF now, so no time to test anything, just wanted to let you know.

http://prntscr.com/deo9l1


NVM after reinstalling the latest hotfix once again it shows up on my PC.
