### ISSUE TITLE
Empty settings at 1.4.3.1

### ISSUE THREAD

**Issue by ghost** [Xaymar/OBS-AMD-Advanced-Media-Framework#166]
OBS 0.16.6
Plugin: 1.4.3.1
Driver: 16.11.5
R9 390x
Win8.1

**Comment by ghost** [comment]
https://gist.github.com/b58a5ada87c800e9309673a0bfb9b512

**Comment by Xaymar** [comment]
Screenshot?

Edit: Wait hold on, you said 1.4.3.0 didn't even have the encoder show up for you, how are you using 1.4.3.1?

**Comment by ghost** [comment]
Pressed enter. Got it messed up... 
![untitled](https://cloud.githubusercontent.com/assets/3416242/20851491/deb70b44-b8f1-11e6-9c5b-7713358f6246.png)

**Comment by Xaymar** [comment]
Try 1.4.3.2, as you yourself said that your GPU wasn't being recognized.

**Comment by ghost** [comment]
Same.
https://gist.github.com/d660e537d506b34932da5b50108a3456

**Comment by ghost** [comment]
00:48:08.444: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
00:48:08.445: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
00:48:08.446: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed

This?

**Comment by ghost** [comment]
Was using the installer...

**Comment by Xaymar** [comment]
What happens if you create a completely fresh profile, does the H264 Encoder entry even exist then?

**Comment by ghost** [comment]
Yes. It does with a fresh one.

**Comment by Xaymar** [comment]
Then it should show all options there, right? If not, the bug is not in the plugin but with OBS not calling get_properties.

**Comment by ghost** [comment]
Maybe you add something like checking for existing profiles for installer, if possible, and nullifying them?

It shows those options now, yes.

**Comment by Benman2785** [comment]
you have to uninstall plugin before installing new version

**Comment by Xaymar** [comment]
> Maybe you add something like checking for existing profiles for installer, if possible, and nullifying them?

That is outside of what the plugin is supposed to do. Normally you wouldn't even have had this issue as it's caused by your system being weird.
