### ISSUE TITLE
VCESpeedTest R9 290X refrence card

### ISSUE THREAD

**Issue by wazerstar** [Xaymar/OBS-AMD-Advanced-Media-Framework#169]
Results:
[amd_290x_reference_card_vce_speed_test.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/628982/amd_290x_reference_card_vce_speed_test.zip)

Hardware
GFX: AMD 290x ref
CPU: Intel 4790K
Motherboard: ASUS Z87 MAXIMUS VI FORMULA
Ram: 16GB ddr3 2400mhz

Driver
Crimson Edition 16.11.5 Hotfix

**Comment by wazerstar** [comment]
Re did another test with everything closed on pc like browser etc..

[amd_290x_reference_card_vce_speed_test2.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/628991/amd_290x_reference_card_vce_speed_test2.zip)

**Comment by Xaymar** [comment]
Added to the wiki, thanks!
