### ISSUE TITLE
reset to default button please!

### ISSUE THREAD

**Issue by nwgat** [Xaymar/OBS-AMD-Advanced-Media-Framework#17]
would be useful to go back to defaults?

**Comment by hymccord** [comment]
It's already in the works! 

https://github.com/Xaymar/OBS-AMD-Media-Framework/blob/master/win-amf/Source/enc-h264.cpp#L203

**Comment by Xaymar** [comment]
Waiting for Jim to help me on this. I have no idea why there is no obs_property_set_value function or a way to get the obs_data_t\* instance assigned to the plugin. If worse comes to worst, the only thing that'll be in the encoder properties is a button to open the proper settings window.

**Comment by Xaymar** [comment]
Done in 1.2.0
