### ISSUE TITLE
Doesn't show up in OBS

### ISSUE THREAD

**Issue by SapiensAnatis** [Xaymar/OBS-AMD-Advanced-Media-Framework#170]
Not sure what else to say. I installed the framework and tried again multiple times; I even re-installed OBS and the plugin. It's not in the list under Recording > Encoder.

I have the latest drivers (16.11.5) dated 11/28/2016.

My card is an R9 390 and I have an Intel i5-4430 processor.

**Comment by Benman2785** [comment]
uninstall both
install both in C:\OBS-Studio\
run OBS as admin

or maybe your antivirus makes mistake

**Comment by SapiensAnatis** [comment]
Disabling windows defender didn't do anything, nor did running as admin. I have checked that the dll is in both plugin folders manually, so I doubt the file-path is an issue.

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by SapiensAnatis** [comment]
Ok, sorry about that. I already had the VS 2015 redist (both 64 and 32 bit); it wouldn't let me reinstall. As said in the OP, I have the latest drivers I can find.

As for hardware, my GPU is listed under 2.0 support but I don't see why 3.0 isn't available as the R9 380 has that.

And by reinstalling OBS I've upgraded to the latest version of that. And the plugin too, obviously, as I didn't download it until today.

The only thing I can see in the FAQ is about OBS already having it. I don't think mine does, unless there's been some confusion. I have an AMD media framework plugin, but it doesn't say anything about VCE

**Comment by Xaymar** [comment]
I see no log file attached.

**Comment by SapiensAnatis** [comment]
- [specs.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/629564/specs.txt)
- OBS 0.16.6
- AMD Drivers 16.40.3211.1101-16112 (http://i.imgur.com/iRkeMig.png) (the file I downloaded was called -non-whql-win10-64bit-radeon-software-crimson-16.11.5-nov25.exe)
- Plugin Ver 14.3.2

Latest Log File: https://gist.github.com/384a5484d0565c5a6bf8e3280222df3e

No crash or video recording happened due to the nature of the issue, so these logs aren't included.

**Comment by Xaymar** [comment]
`00:44:53.735: [AMF Encoder] Version 1.4.3.2 loaded (Compiled: 1.3.0.5, Runtime: 1.3.0.5, Library: 1;3;0;5;1.2;201611231859).`

Plugin loaded and there were no error messages about "no supported devices either". You should have an entry for "H264 Encoder (AMD Advanced Media Framework)".

> As for hardware, my GPU is listed under 2.0 support but I don't see why 3.0 isn't available as the R9 380 has that.

Just because it's a 390 doesn't mean it has the same hardware/generation as a 380.

**Comment by SapiensAnatis** [comment]
Oh yes, that was what I was saying in the other comment....my apologies, I thought it would say VCE encoder specifically...

Sorry for wasting your time on this.

**Comment by Xaymar** [comment]
If only there was a [FAQ entry](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Frequently-Asked-Questions#q-i-have-the-plugin-how-do-i-use-it-now) for this...  :P

**Comment by SapiensAnatis** [comment]
If only it was in bold and in size 400, then I *might* have seen it. But
for me even that's not definite :P
