### ISSUE TITLE
VCESpeedTest R9 290

### ISSUE THREAD

**Issue by Glitchvid** [Xaymar/OBS-AMD-Advanced-Media-Framework#171]
Result: 
https://s.gvid.me/s/2016/12/06/VCESpeedTest_R9-290.7z

Hardware:
GPU: Asus R9 290 DirectCU II
CPU: i7 6850k @ 4.1
RAM: 16GiB DDR4 @ 3000

Software:
Radeon Software Version - 16.11.5
Radeon Software Edition - Crimson
Windows Version - Windows 10 (64 bit)

**Comment by Xaymar** [comment]
Thank you, the data has been added to the wiki.
