### ISSUE TITLE
Force HRD Compatibility is enabled by default

### ISSUE THREAD

**Issue by fyrak1s** [Xaymar/OBS-AMD-Advanced-Media-Framework#172]
I have noticed that by default, the "Force HRD Compatibility" option is being enabled.
However the help message says it is recommended to leave it disabled in most cases.

So I guess it should be disabled by default?

**Comment by Xaymar** [comment]
The default for it is Enabled because it helps stabilise bitrate with Constant Bitrate, which most people use for streaming. I've removed the part of the string from the tooltip in the repository now.

**Comment by fyrak1s** [comment]
Ah I see. So it would be wise to set it to disabled for all presets that do not use CBR, since it actually slows down encoding, right?
Just out of curiosity, previously you have recommended to disable it for recording and streaming. Why did you change your mind?

**Comment by Xaymar** [comment]
> So it would be wise to set it to disabled for all presets that do not use CBR, since it actually slows down encoding, right?

No, i didn't say that.

> Just out of curiosity, previously you have recommended to disable it for recording and streaming. Why did you change your mind?

It helps stabilise the bitrate near the beginning of the stream and also seems to have brought a slight overall quality improvement to the footage i tested with.

**Comment by fyrak1s** [comment]
Ok thanks. And no you didn't say that. As you have only mentioned CBR, I thought that maybe it is useless for variable bitrate encoding. But that "forcing HRD" slows down encoding is just a fact.

**Comment by Xaymar** [comment]
> But that "forcing HRD" slows down encoding is just a fact.

And what do you base this fact on? Links, Citations, etc? The more the better.

**Comment by fyrak1s** [comment]
As an example the devs of Magix Video Pro X think so :) http://i.imgur.com/R8uG38v.jpg / http://pro.magix.com/uploads/MAGIX_PRO/video_pro_x/pdfs/video-pro-x6-manual.pdf#434 (bottom)

**Comment by Xaymar** [comment]
\[citation needed\]  

Here's my proof for my statement:

- Enforce HRD OFF: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Hardware-VCE3.4#rx-480
- Enforce HRD ON: 

> | Resolution |    Speed | Balanced |  Quality |
> |:----------:|---------:|---------:|---------:|
> |   160x120  | 3200 FPS | 2300 FPS | 2608 FPS |
> |   240x160  | 2661 FPS | 2406 FPS | 1813 FPS |
> |   256x160  | 2655 FPS | 2276 FPS | 1680 FPS |
> |   320x240  | 1930 FPS | 1527 FPS | 1190 FPS |
> |   480x320  | 1287 FPS | 1047 FPS |  682 FPS |
> |   640x460  |  804 FPS |  611 FPS |  361 FPS |
> |   640x480  |  779 FPS |  596 FPS |  349 FPS |
> |   800x600  |  521 FPS |  399 FPS |  229 FPS |
> |   854x480  |  582 FPS |  454 FPS |  272 FPS |
> |   960x540  |  488 FPS |  379 FPS |  219 FPS |
> |  1024x768  |  337 FPS |  257 FPS |  146 FPS |
> |  1152x864  |  273 FPS |  206 FPS |  116 FPS |
> |  1280x720  |  294 FPS |  222 FPS |  125 FPS |
> |  1280x800  |  267 FPS |  201 FPS |  113 FPS |
> |  1280x1024 |  212 FPS |  159 FPS |   89 FPS |
> |  1366x768  |  262 FPS |  198 FPS |  111 FPS |
> |  1440x900  |  212 FPS |  159 FPS |   89 FPS |
> |  1600x1200 |  148 FPS |  110 FPS |   61 FPS |
> |  1920x1080 |  137 FPS |  102 FPS |   56 FPS |
> |  1920x1200 |  125 FPS |   93 FPS |   51 FPS |
> |  1920x1440 |  105 FPS |   78 FPS |   42 FPS |
> |  1920x1920 |   79 FPS |   59 FPS |   32 FPS |
> |  2048x1080 |  128 FPS |   96 FPS |   53 FPS |
> |  2560x1440 |   79 FPS |   59 FPS |   32 FPS |
> |  3440x1440 |   59 FPS |   44 FPS |   24 FPS |
> |  3840x2160 |   35 FPS |   26 FPS |   18 FPS |
> |  4096x2160 |   33 FPS |   24 FPS |   17 FPS |

As you can clearly see, the speed is nearly identical (difference at streaming resolutions is <0.1%).

**Comment by fyrak1s** [comment]
I will do my own tests but I am convinced, thanks for clearing that up! :)
