### ISSUE TITLE
Plugin doesnt work anymore with Crimson ReLive

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#175]
GPU: Sapphire Nitro+ RX 480 8G OC
CPU: FX-8150 @4.2GHz
MoBo: GigaByte 990FX-Gaming
OBS 0.16.6 64bit
Plugin: 1.4.3.2
Driver: 16.12.1 ReLive

[2016-12-08 20-57-35.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/640447/2016-12-08.20-57-35.txt)

cant stream or record -> OBS does nothing after hotkey or click

**Comment by Xaymar** [comment]
16.12.1 is now available here, so I can track down what causes this.

**Comment by Roph** [comment]
Same problem, 

22:15:02.171: [AMF Encoder] <Plugin::AMD::VCEEncoder::SetFullColorRangeEnabled> Setting to Disabled failed with error AMF_INVALID_ARG (code 4).
22:15:02.205: [AMF Encoder] [22:15:02.151][AMFEncoderVCE]  Warning: AVEQueryEncodeCapabilitiesEx bad status : 0x 80000002

Did you mean to make "here" a link? :o

**Comment by Benman2785** [comment]
no he meant that in his area there was a problem from AMD to provide the driver

**Comment by Xaymar** [comment]
What Benman said, the 16.12.1 page was a white blank for way too long until it finally was available.

**Comment by Xaymar** [comment]
Fixed by commit 1e374973911751ba133443e2f6534091bbd2d37f, will be in 1.4.3.3 soon.

**Comment by Xaymar** [comment]
1.4.3.3 is out fixing this.
