### ISSUE TITLE
Under 30FPS while recording with 60FPS setting

### ISSUE THREAD

**Issue by max20091** [Xaymar/OBS-AMD-Advanced-Media-Framework#176]
Very annoying when recording with 60FPS setting and got under 30FPS video.
AMD ReLive seems better than OBS Studio AMF but sometimes it produce shuttering.

This issue is same as #167 but with High Quality Preset. Recording Preset doesn't solve this issue :(

Log file and video is in a zip file.
https://drive.google.com/open?id=0B3fo2a5_bBE6cmJYQW85YnMwTm8

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide). Please make sure to read it thoroughly before reporting issues. Thank you.

----

If you had relive active, that's what causes it. ReLive is a constant encoding impact.

**Comment by max20091** [comment]
#  System Specifications
Operating System Windows 10 Pro 64-bit
CPU Intel Pentium G630 @ 2.70GHz
RAM 6.00GB Dual-Channel DDR3 (8-8-8-20)
Motherboard ASUSTeK COMPUTER INC. H61M-K (LGA1155)
Graphics
Intel HD Graphics (ASUStek Computer Inc)
1024MB ATI AMD Radeon HD 7700 Series (MSI)
Storage931GB Seagate ST1000DM003-1CH162 (SATA)
Audio Sound Blaster X-Fi Surround 5.1 Pro

Current OBS version 0.16.6
Current AMD Driver 16.12.1, OBS Studio AMF version 1.4.3.3
I didn't active ReLive while recording with OBS

**Comment by Xaymar** [comment]
I took a look at the file and it's constant 60 fps and the log file confirms this. I'm unsure what the problem actually is?

**Comment by max20091** [comment]
I dunno why it make some duplicated frames although YouTube still running in 60FPS and I didn't enable frame skipping and my computer isn't overloaded or getting too hot.

This is my second log file + video recorded: https://drive.google.com/open?id=0B3fo2a5_bBE6LW9QQWdBaDRwTnc

Before second 49, it running 60 FPS with duplicated frames and after that it doesn't make any duplicated frames anymore.

**Comment by Xaymar** [comment]
Same as before, output is solid 60 fps - only 5 frame lagges due to encoding, 19 due to rendering. None of the internal commands ever went about 16.66ms per frame. Queue delay is also acceptable (14 frames, ~1/4th of a second).

If you get duplicate frames with Game Capture or Display Capture, that is entirely normal. OBS will always output the required Framerate, even if that means that a frame is duplicated due to whatever reasons.

**Comment by Xaymar** [comment]
No response for 8 days, I'll consider this solved.
