### ISSUE TITLE
AMD Hardware Encoder not working....

### ISSUE THREAD

**Issue by CyDoneTV** [Xaymar/OBS-AMD-Advanced-Media-Framework#178]
I have an AMD FX8350, a Sapphire Dual-X R9 280 3GB, 16 GB of DDR3 1333Mhz RAM.  The AMD encoder profile WAS working for me about 4 days ago, but now when I have that profile selected it no longer will allow me to record or stream.  This is kind of a big issue when trying to stream the types of games I play (Battlefield 1, Dragon Age Inquisition, Tomb Raider...etc.) cause of the extra load it is putting on my cpu.  It causes some noticeable frame dips.  I have the latest Crimson ReLive drivers, which were installed when this was working about 4 days ago.  There are no new driver updates for AMD.....so IDK what is going on.  Nothing has changed with my computer, save for doing a fresh install of Windows 10 Pro 64bit.

**Comment by Xaymar** [comment]
1. Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide). Please make sure to read it thoroughly before reporting issues. Thank you.
2. Install 1.4.3.3

**Comment by snakedeshazer** [comment]
I am having the same issue, was working just fine until about 4 days ago or so. I did install 1.4.3.3 and still no use. I click the start record button and does nothing, only if I change to another more CPU intensive codec. Please look into this please.

**Comment by Xaymar** [comment]
@snakedeshazer Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Xaymar** [comment]
Eight days have passed with no sign of this being updated, so I'll close this.
