### ISSUE TITLE
HDR support?

### ISSUE THREAD

**Issue by Selur** [Xaymar/OBS-AMD-Advanced-Media-Framework#179]
Just wondering does the encoder (and/or the SDK) support HDR encoding/signaling?
(Seeing that HEVC 10bit encoding seems to be around the corner, hdr would be really nice.)

**Comment by Xaymar** [comment]
OBS would need to have support for this first. If your question is related to AMF directly, I can't answer these questions.

**Comment by Selur** [comment]
question is aimed at AMF directly.

**Comment by Xaymar** [comment]
Go here then: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/

**Comment by Selur** [comment]
Sorry, will do. :)
