### ISSUE TITLE
Quality Flickering or "Refreshing" Effect happens with certain Cards and Settings

### ISSUE THREAD

**Issue by acp2** [Xaymar/OBS-AMD-Advanced-Media-Framework#180]
I didn't know how to describe the issue better.
This is happening on 2 configurations : 
FX 8300 + R7 270 and i5 3330 + R7 260x ( http://i.imgur.com/WYQ01JJ.png ) , both on 16.12.2 , 0.16.6 & 1.4.3.4 running as administrator.
Both systems had clean installs of the drivers.
It's the same issue on both systems , here's vods : 
1st system - 720p30 @ 2800 bitrate https://www.twitch.tv/scenotaf/v/109597610 - around 2h31m30s
2nd system - 720p60 @ 3500 bitrate https://www.twitch.tv/acpbot/v/109676126 - around 2 minutes , look at the game client on both.
http://s.go.ro/upzkfemr - Raw recording on 2nd system.
http://pastebin.com/Kqb2UzC8 - (w/o debug) Log of the session in which I made the stream & recording attempts.
https://gist.github.com/e51c6094f3e40f4d67841bb33c727cac - with debug on.
Only provided logs & raw footage on my system since it's the same issue but I can get them on the other one too.

**Comment by Xaymar** [comment]
If you mean the I-Frame refreshes, that is entirely normal. Until Two Pass encoding is stable/non-experimental there is not much you can do here.

**Comment by acp2** [comment]
Ok , thanks and Merry Christmas.

**Comment by Roph** [comment]
You can somewhat alleviate this by increasing the GOP size. It's not required but a rule of thumb is to use multiples of your framerate. With many encoders a GOP size of 0 simply means the encoder will automatically match it to the framerate, I assume the same is true for AMF.

I use a 150 GOP (5x framerate); the "refreshing" you speak of would only happen at most every 5 seconds in that scenario, displaying mostly static content. You can try even larger values (300), but you'll get negative effects if you're recording higher motion video and I-frames are too rare. I find 150 is a good balance. It's also most effective using VBR, not CBR.

**Comment by Xaymar** [comment]
You actually can't as it has nothing to do with the GOP size. This is an artifact of the total bitrate not being enough to actually encode at that quality the entire time, which pushes the P-Frame QP values lower than they should be. Only Pre-Analysis Pass and VBAQ help here.
Increasing the GOP Size past the Keyframe Interval doesn't work anyway - it is either set at half the Framerate or clamped to the Keyframe Interval.

**Comment by acp2** [comment]
But how can this be " an artifact of the total bitrate not being enough to actually encode at that quality the entire time" while I'm encoding a static screen?

**Comment by Xaymar** [comment]
It's rather simple, the single pass encoding on hardware encoding does rather little analysis of the actual frame, so most of the bitrate ends up being Filler Data. You can see this happening if you disable filler data - you'll actually end up streaming at a much lower bitrate. This is what Pre-Analysis Pass helps with and VBAQ pushes it even further.

**Comment by acp2** [comment]
Any word on the solutions on AMD's side?

**Comment by Xaymar** [comment]
Pre-Analysis Pass/Two Pass, HEVC.

**Comment by acp2** [comment]
I know , but you said they're not stable.
What I meant to ask was if there was anything about when it'll become stable or stable enough to use.

**Comment by Xaymar** [comment]
When we have the new SDK update. Edit: Also I said they are experimental, not unstable.

**Comment by kytos22** [comment]
Hopefully soon in 2017, when AMD release the new version of AMF SDK (they are waiting a bugfix to release) and Xaymar can develop it.

**Comment by acp2** [comment]
That's nice.
Hopefully sooner rather than later.

**Comment by acp2** [comment]
"Until Two Pass encoding is stable/non-experimental".
I have another question.
Wondering if Pre-Analysis Pass/Two Pass or HEVC would work with my 260x or if I need to get a Polaris card.

**Comment by Roph** [comment]
You'd need a polaris card.

> You actually can't as it has nothing to do with the GOP size. This is an artifact of the total bitrate not being enough to actually encode at that quality the entire time, which pushes the P-Frame QP values lower than they should be. Only Pre-Analysis Pass and VBAQ help here.
>Increasing the GOP Size past the Keyframe Interval doesn't work anyway - it is either set at half the Framerate or clamped to the Keyframe Interval.

Is this behavior of your plugin or VCE itself? When using a transcoder with VCE for exmaple, bumping up the GOP from 30 to 150-300 has a very noticeable positive effect. Much less obvious refreshing and overall better quality because of it, less wasted on needless I-frames.

**Comment by rdeleonp** [comment]
Care to elaborate?

**Comment by Roph** [comment]
> Care to elaborate?

Pascal's NVENC and Polaris' VCE appear to be roughly equal when it comes to quality, assuming you are trying to max both out for the best quality possible. Speed I'm not sure of, VCE is clearly benchmarked, I haven't seen recent NVENC ones. 

But the issue is software support. Polaris cards have been available for well over half a year now and HEVC, 2-pass etc are still not properly supported in the SDK from AMD. On the flipside, NVENC's HEVC etc for Pascal was supported before the first card even launched. Likewise, NVENC support in 3rd party software is much more commonplace. I bought a polaris card in part due to the advertised video / streaming features, but I still can't make use of them. As a consumer I feel somewhat burned / regretful. This is off topic though ;)

**Comment by acp2** [comment]
Probably going to get a 1050 I guess if there won't be any solution to what's happening to me.

**Comment by Roph** [comment]
You may have misunderstood; the same thing is almost certainly going to happen at these bitrates with a 1050.

**Comment by Roph** [comment]
Done some more testing and sample generation on this;

[HQ Example of the content, 1080p60 at 75mbit/s](http://dump.roph.eu/vce/tests/1080p60%2075mbit%20source.mp4)

[3.5mbit/s with my VBR settings](http://dump.roph.eu/vce/tests/720p30%20AVC%20OBS%203.5mbit%20(Roph%20VBR%20settings).mp4), CABAC / large GOP etc (though the plugin apparently ignores large GOP settings) ([full settings](http://imgur.com/a/CimxK))

[3.5mbit/s with the plugin's default twitch CBR preset](http://dump.roph.eu/vce/tests/720p30%20AVC%20OBS%203.5mbit%20(Stock%20CBR%20Twitch%20preset).mp4)

[3.5mbit/s H264 through A's convertor](http://dump.roph.eu/vce/tests/720p30%20AVC%20A's%20Convertor%203.5mbit.mkv), enlarged GOP ([full settings](http://i.imgur.com/UVh43Tm.png))

And just out of interest:

HEVC at 3.5mbit/s through A's convertor, [30fps](http://dump.roph.eu/vce/tests/720p30%20HEVC%20A's%20Convertor%203.5mbit.mkv) and [60fps](http://dump.roph.eu/vce/tests/720p60%20HEVC%20A's%20Convertor%203.5mbit.mkv).

I've spent a silly amount of time tonight staring at these samples and the 3.5mbit/s H264 from A's is clearly better than OBS' output, even trying to emulate A's VBR settings in the plugin. I'm not sure why. 

I'm assuming though that when I force a large GOP in A's convertor it really is using one though. I used a GOP of 150. 

Using MediaInfo, it seems that indeed, regardless of the GOP/IDR period set in OBS, the output merely matches the framerate - M=1, N=30.

**Comment by Xaymar** [comment]
I removed the Off-Topic stuff, if you want to discuss GPUs please use private messages for that.

-----

> Is this behavior of your plugin or VCE itself? 

Yes, it is the behaviour of AMF. You can easily see this if you try to modify any of the GOP properties in the Master view mode.

1. [Default GOP Size](http://cdn.xaymar.com/private/2016/12/28/06/2016-12-28_06-35-03.video.mkv)
2. [GOP Size at 5xFramerate](http://cdn.xaymar.com/private/2016/12/28/06/2016-12-28_06-43-14.video.mkv)
3. [GOP Size 5xFPS, No GOP Alignment, Full Range, VBAQ, Pre-Analysis Pass](http://cdn.xaymar.com/private/2016/12/28/07/2016-12-28_07-01-25.video.mkv)

All of these have the same output GOP Size of M=1, N=30, but only Full Range VBAQ Pre-Analysis helped the quality by distributing the bitrate better. If we however modify the Keyframe Interval to 5 seconds, we get a different result.

* [No Custom GOP, Pre-Analysis Pass, VBAQ, 16 ReFrames, IDR Period 5 Seconds](http://cdn.xaymar.com/private/2016/12/28/07/2016-12-28_07-17-55.video.mkv)

Here we can see that the GOP Size metadata entry is missing in both ffprobe and mediainfo, which means that it actually was changed. If we take a look at the stream itself now, the GOP Size is now M=1, N=60 (exactly 1 second, or equal to FPS).

-----

> I'm assuming though that when I force a large GOP in A's convertor it really is using one though.

A's converter uses Media Foundation Transform, which is known to do more than just one thing when changing a property. Changing GOP Size there could have actually changed the IDR Period too overriding what you set for it - you can't have a GOP Size bigger than the IDR Period anyway, only smaller. Changing the GOP Size to be larger than the IDR Period worked pre-16.9.2, but it caused unnecessary issues with decoding and streaming.

-----

I still don't know why you even want to change the GOP Size, the problem isn't I-Frames, it's that the bitrate is not distributed evenly. You get better results with VBAQ and Pre-Analysis Pass or by figuring out the correct settings for Intra-Refresh coding. See [this example](https://www.youtube.com/watch?v=PyebHuR7Z80), you'll see that with just Intra-Refresh coding the overall quality has already drastically increased.

**Comment by acp2** [comment]
So , if I don't get a Polaris card I'm basically stuck with this happening?

**Comment by Xaymar** [comment]
Probably, the alternative is figuring out Intra-Refresh encoding.

Edit: Or get a VCE 3 card, that's at least close to Polaris.

**Comment by Roph** [comment]
I see your point, I just know bumping it up with A's / MFT helps greatly towards fixing OP's issue and also increasing quality slightly. I just want the best possible quality for a given bitrate. The point of using CBR over VBR still eludes me, twitch accepts my VBR just fine.

Your 3rd and 4th samples are much darker than 1 & 2. I noticed you mention full range, though detail for example in the bottom right corner is completely lost.

Though indeed the "refreshing", while still there, is less pronounced - the garry's mod background gradient for example.

Thanks for the insight :)

**Comment by acp2** [comment]
How do I go by testing Insta-Refresh myself?

**Comment by Xaymar** [comment]
> Your 3rd and 4th samples are much darker than 1 & 2. I noticed you mention full range, though detail for example in the bottom right corner is completely lost.

You need a player that uses the metadata embedded in the file, VLC ignores it at the moment, the only players I know that actually use the metadata are MPC-HC and ffmpeg.

> How do I go by testing Insta-Refresh myself?

The properties are called Intra-Refresh and are visible in Master view mode, do keep in mind that using Master view mode will disqualify you from any support.

**Comment by acp2** [comment]
Could you give me a screenshot of the settings you used in your example video?

**Comment by Xaymar** [comment]
Those settings have been replaced already, but take a look at the description of the video.

**Comment by acp2** [comment]
What are you using now?

**Comment by Xaymar** [comment]
Pre-Analysis Pass, Full Range and VBAQ. What else would I be using if not those?

**Comment by Xaymar** [comment]
I managed to reproduce the issue with a much higher effect than planned. I do believe this is unintended behavior.

**Comment by acp2** [comment]
Understood , thanks for reporting it.
Will keep an eye on the AMF issues thread.

**Comment by Xaymar** [comment]
According to Mr 'Rate Control Developer', the solution is to use a VBV Buffer Size close or exactly on the Target Bitrate. If it still happens then, even with Min QP at above 11, then I'd say AMF is not meant for streaming without Pre-Analysis Pass.

It is up to everyone to decide if this solution is okay or not.
