### ISSUE TITLE
Encoder not showing in settings.

### ISSUE THREAD

**Issue by r1fty** [Xaymar/OBS-AMD-Advanced-Media-Framework#181]
Specs: http://pastebin.com/yxhHQ8by
OBS Ver: 17.0
Plugin Ver: 1.4.3.4
AMD Driver Ver: 16.12.2
Log: http://pastebin.com/0mfBX7AB

Issue: http://i.imgur.com/TOtUupz.png

**Comment by Xaymar** [comment]
Log file shows that it failed to create an Encoder on the GPU you have for every single known API. There's not much I can do here, remove any overclocking you may have and start with a completely clean stable (non-hotfix) driver install.

**Comment by Xaymar** [comment]
No response for 9 days, closing.
