### ISSUE TITLE
Unable to record if using VSR feature

### ISSUE THREAD

**Issue by DatCaptainHorse** [Xaymar/OBS-AMD-Advanced-Media-Framework#184]
Tested game: 'Elite: Dangerous'

Issue:
The game is running fullscreen, using AMD's Virtual Super Resolution to get 1440p quality. When I hit the record button on the OBS, it does nothing. Normal x264 works fine with this.

Settings:
Using AMF recording preset.
Color format is NV12, 709, Full Range.
Drawing resolution set to 2560x1440, same for scaled.
MP4 Format, with single audio track at 320kpbs and 48KHz.

Using game capture (fullscreen), preview is working.

Software:
OBS-Studio version: 17.0.0
AMF Plugin version: 1.4.3.4

Specs:
MOBO: Asus M5A99X Evo R2.0
OS: Windows 10 64-bit
GPU: R9 280x 3GB, latest ReLive drivers.
CPU: FX-8320 OC'd at 4GHz
RAM: 1866MHz 16GB
HDD: Recording drive is a seagate 7200rpm 1TB HDD.
Additional: Sound Blaster Z sound card. ASUS Wi-Fi card. NVIDIA Quadro FX 1700. 

Log:
[2017-01-06 23-20-44.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/690938/2017-01-06.23-20-44.txt)

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by DatCaptainHorse** [comment]
Will this do? ^

**Comment by Xaymar** [comment]
Yes, that one will do. For future reference, I need the entire log file since OBS also gives me information to check (base resolution, Operating System, etc).

Anyway, your GPU doesn't support anything larger than 1920x1920. I'd recommend downscaling to 1920x1080 with Lanczos or getting a VCE3 (Tonga, Tonga Pro, Fury, Nano) or VCE3.4 GPU (Polaris, Vega).

**Comment by DatCaptainHorse** [comment]
Sorry for this issue, it seems it was just my hardware. Thank you for this.
