### ISSUE TITLE
Updated Plugin for OBS, not working anymore?

### ISSUE THREAD

**Issue by myrtlejeremy** [Xaymar/OBS-AMD-Advanced-Media-Framework#185]
I updated the plugin for OBS to work with my new graphics card. Unfortunately, it seems as if OBS stopped working altogether. The Start Streaming and Start Recording buttons have stopped working, and there is no hardware encoder found within the software. What can I do to fix this issue?

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Xaymar** [comment]
No response or update for 7 days. Closing this as invalid.
