### ISSUE TITLE
VCESpeedTest (Re-Test / ReLive 17.1.1 / R9 380)

### ISSUE THREAD

**Issue by locodicegr** [Xaymar/OBS-AMD-Advanced-Media-Framework#188]
Re-tested Vcespeedtest with 17.1.1 again for science reasons on my 380 & ssd,
hope it helps somehow.
[17.1.1.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/713491/17.1.1.zip)

**Comment by Xaymar** [comment]
Only a minimal increase, which could itself be due to differences in system usage at the time.
