### ISSUE TITLE
Update H264 Encoder to new shared H264&HEVC AMF interface code

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/OBS-AMD-Advanced-Media-Framework#190]
[Part of the HEVC Encoder Project.](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/projects/2)  
Prerequisite: #189 

With the new AMF interfacing code done, time should now be spent on making the H264 encoder use this code instead to reduce complexity of tracking down bug reports.

**Comment by Xaymar** [comment]
Modifications that need to be made:

- Pre-Encode/Analysis is actually an enum with 4 possible values: Off, On, Downscale 2x, Downscale 4x
- Aspect Ratio was added, however we don't exactly need it unless the user does some weird things (like squashing 2560x1440 into a 1920x1440 surface so that they can use the aspect ratio stuff)

**Comment by Roph** [comment]
Any clue as to what the pre-analysis parameters mean? I'm assuming a less accurate pass when using downscale but at the benefit of higher speed?

**Comment by Xaymar** [comment]
Well, on means that it does a full frame pre-pass to see where it actually needs to push bitrate towards to keep quality consistent. Downscale (2x, 4x) means that it does it at a half or quarter pass. I don't think it makes encoding faster. Edit: Mikhail confirmed that encoding should be slower by up to 25%.

**Comment by Xaymar** [comment]
Implemented since version 1.9.9.0
