### ISSUE TITLE
Implement H265 Encoder using shared H264&HEVC AMF interface code

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/OBS-AMD-Advanced-Media-Framework#191]
[Part of the HEVC Encoder Project.](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/projects/2)  
Prerequisite: #189 

In order to use HEVC there also needs to be code interfacing with it and something that actually is shown to the user and handles the glue parts between obs and the shared interface. There will most likely be small changes to the UI as HEVC adds and removes some parameters:

- HEVC Tier: Main or High
- Min/Max QP for I-/P-Frame: Separated for better quality control.
- QP CB/CR Offset: Seems to allow for compressing gray scenes better, as you can just put the CB/CR offset at 51? (Range 0-51)
- GOP Type: Allows specifying a Fixed or Automatic GOP
- GOP Size/GOPS Per IDR: Used for Fixed mode, allows control over the actual GOP
- GOP Size Min/Max: Used for Automatic mode, allows specifying limits for the GOP.
- Aspect Ratio: In case you want your 1:1 content to be different, no use outside of video editing software.
- Full Range reverted to Nominal Range: Unsure if this parameter is even necessary with HEVC, since it by default should internally work with 10-bit data or better.
- Header Insertion Mode: None, GOP Aligned or IDR Aligned - Don't know the use for this yet
- De-Blocking Filter flag is now inverted, true disables?
- CABACEnable only supports CABAC, since HEVC has no CALVC iirc
- Temporal Layer support? Will most likely require Webcam usage which I block by default (too difficult to implement with the extremely limited UI options that OBS offers)
- HEVCInputQueueSize: Internal queue for incoming frames?

**Comment by JLNNN** [comment]
I don't want you to rush it and I know it's not the feine englische Art (:D) but do you think there will be a new release soon? :) Keep up the great work!

**Comment by Xaymar** [comment]
HEVC will initially only be available to Patrons until i can verify that it
works properly, without any driver crashes or obs crashes. Depending on how
fast the driver bugs are fixed, that could take until summer.

On Feb 1, 2017 15:33, "Julian Stock" <notifications@github.com> wrote:

I don't want you to rush it and I know it's not the feine englische Art
(:D) but do you think there will be a new release soon? :) Keep up the
great work!

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/191#issuecomment-276671973>,
or mute the thread

**Comment by Xaymar** [comment]
Implemented since version 1.9.9.0
