### ISSUE TITLE
2160p60 with VCE 3.4?

### ISSUE THREAD

**Issue by theonlypwner** [Xaymar/OBS-AMD-Advanced-Media-Framework#192]
Will VCE 3.4 support 3840x2160 at 60 fps with HEVC?

**Comment by Roph** [comment]
According to AMD's slides, yes.

**Comment by theonlypwner** [comment]
Also, why doesn't VCE 3.4 support 3840x2160 at 60 fps with H.264? Is it due to optimizing hardware for H.265?

**Comment by Roph** [comment]
Presumably yes, I imagine the VCE team are only allowed so much space on the die and adding in H265 means a regression for H264.

**Comment by Xaymar** [comment]
Highest i have managed to get it to is 33fps at 3840x2160. Though the value
was the same for all quality levels, so i think there is something stopping
it from going higher (cpu, vram, etc).

Edit: That's for HEVC, H264 is already on the wiki.

**Comment by theonlypwner** [comment]
I remember somewhere said that there is a reprogrammable portion on VCE, which makes it slower than other hardware encoders that are hard-coded and cannot be modified. How much can that reprogrammable portion be modified?

**Comment by Xaymar** [comment]
@theonlypwner That was what I said. From my understanding the encoder can be modified by AMD to whatever they want it to be. However it can't get faster without dropping quality/features or using hybrid encoding (GPU-assisted CPU encoding).

**Comment by theonlypwner** [comment]
Is it possible for users to modify it?
If we modify it to remove H264 or H265, could we get over 60 fps at 3840x2160 with the other?

**Comment by Xaymar** [comment]
No to both. This is outside the realm of this plugin anyway.

**Comment by theonlypwner** [comment]
Does "dropping quality/features" mean using the Speed preset then?

Is it possible to tweak the AMD AMF API values to get extremely inefficient but fast encoding?

**Comment by Xaymar** [comment]
> Does "dropping quality/features" mean using the Speed preset then?

No, it literally means dropping encoding features that would bring better quality. You can not do this. Wait for a card that can do HEVC 4k60 fps (possibly special Vega cards) or get an R9 285/380/380X if you really need 4k60 (AVC).

I will close this now as this has gone so far off-topic to the plugin that it isn't even in the same galaxy.
