### ISSUE TITLE
No hardware acceleration on A10-5800K APU (VCE 1.0)

### ISSUE THREAD

**Issue by NoxiousPluK** [Xaymar/OBS-AMD-Advanced-Media-Framework#193]
Speccy output: http://pastebin.com/raw/bJPDQ75q (kept the relevant parts)
Current OBS version: 17.0.2 (x64)
Current plugin version: 1.4.3.8
Current AMD driver: Crimson 16.2.1 (15.301.1901-160226a-299900E) (non-whql-64bit-nieg-radeon-crimson-16.2.1-win10-win8.1-win7-feb27.exe)
Log file: https://gist.github.com/anonymous/82df0a30ec2595005de70a69596c53cc

I used OBS earlier without issues (with hardware acceleration!), but after a reinstall of my machine, I no longer have the ability to use hardware encoding.

My APU supports VCE 1.0 (A10-5800K with Radeon HD 7660D, Piledriver/Trinity): https://en.wikipedia.org/wiki/Video_Coding_Engine#VCE_1.0

I did follow the FAQ, especially this question (I have an APU, how do I use the latest Runtime?):
https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Frequently-Asked-Questions#q-i-have-an-apu-how-do-i-use-the-latest-runtime

Now, my current GPU driver (Crimson 16.2.1) does not have the amfrt32.dll and amfrt64.dll in the package.
So I downloaded non-whql-win10-64bit-radeon-software-crimson-relive-17.1.1-jan16.exe (won't work for my GPU) and took them from that package.
I suspect this is where the problem is at, but "Download the latest Driver Package" isn't exactly clear on what download I need.

See the enclosed logfile.

**Comment by max20091** [comment]
oh well, your APU use Terascale 3 instead of GCN so your APU does not support VCE

"Radeon HD 7660D	1 June 2012	Devastator	TeraScale 3"
https://en.wikipedia.org/wiki/Radeon_HD_7000_Series

**Comment by Xaymar** [comment]
16.2.1 was never supported, use the LATEST driver from amd (that is either
16.12.2 or 17.1.1 depending on hw). How do you not know what the word latest means?

**Comment by NoxiousPluK** [comment]
Ah,

This is confusing as fuck (excuse my language).
If I use the hardware selector, I get taken to this page (hence my driver version):
http://support.amd.com/en-us/download/desktop/legacy?product=legacy3&os=Windows%2010%20-%2064

But you're saying that this should work aswell?
http://support.amd.com/en-us/download/apu?os=Windows+10+-+64

**Comment by Xaymar** [comment]
It's the only download that has the AMF runtime in it. It's also what the
"latest driver" text links to.

**Comment by NoxiousPluK** [comment]
Got it. I'll try it.

The confusing part for me is that it doesnt show up on the driver page for _my_ hardware.

**Comment by Xaymar** [comment]
> The confusing part for me is that it doesnt show up on the driver page for my hardware.

On the first page of the wiki, it shows exactly what you need to run this plugin. A similar text is also present on the OBS resource page.

> * [Visual Studio 2015 Redistributables](https://www.microsoft.com/en-us/download/details.aspx?id=48145)
> * [Latest AMD Driver](http://support.amd.com/en-us/download)
> * [OBS Studio Download](https://obsproject.com/download#mp)

I will however modify the FAQ entry to say that you need a driver that actually has VCE. Edit: I lied and removed it completely instead.

**Comment by NoxiousPluK** [comment]
Well yes, the Latest AMD Driver link takes you to the download page.

Now use the manual driver selector:
- APU
- Desktop
- A-series with Radeon HD 7000D Series
- Windows 10 x64

And you get taken to this page:
http://support.amd.com/en-us/download/desktop/legacy?product=legacy3&os=Windows%2010%20-%2064

That's the driver I've installed :)

Edit:
The 'Latest AMD Drivers and Software' link for 'Radeon™ R5 235X, R5 230, R5 220, HD 8470, HD 8350, HD 8000 (D/G variants), HD 7000 – HD 7600, HD 6000, and HD 5000 Series' also links to that same version.

**Comment by Xaymar** [comment]
Well yeah, but do you see any page here saying you should use the manual driver selector? I don't.

**Comment by NoxiousPluK** [comment]
Well no, but I also don't see it directing to what driver I need.

The download page does not have a 'Latest APU driver' link. Surprisingly, the menu above has.

I'm not saying this is an issue with the FAQ, but at least it's an issue with AMD's webpage. :)

Also see my edit :)

**Comment by Xaymar** [comment]
I can see how it is confusing, considering the manual driver selection most likely goes by the GPU inside it, instead of the CPU inside it. HD 7000D doesn't support GCN technology, so it picks the legacy driver instead of the proper driver for the CPU. (Also HD 7000D does not have VCE 1.0 support, so that one is probably just added on to the CPU.)

**Comment by NoxiousPluK** [comment]
Yea of what I understand, the 7660D doesn't have VCE, but the API does have it as an added feature.
It's one of the exceptions in the list I suppose.

Anyway, I'll try to install the actual latest driver and report back!

**Comment by Xaymar** [comment]
If the new driver does not work, the only current option is to revert to an older build and face the issues and bugs it has. 1.4.2.3 is the last version that didn't check if the encoder is actually available and 1.2.0rc1 is the last version that worked with Media SDK and didn't require 16.7.1 or newer. Future versions will test actually creating an encoder instead of just querying for encoding support, so it should be more accurate.

* 1.4.2.3: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/releases/tag/1.4.2.3
* 1.2.0rc1: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/releases/tag/1.2.0rc1

The Media SDK version is drastically different and you will most likely have to spend a few hours understanding the old UI interface before you can actually do something.

**Comment by NoxiousPluK** [comment]
This is a test with 1.4.2.3: https://gist.github.com/073ab0ce1531d80c389c37b5756aedec

Which makes the option selectable, but fails: AMF_ENCODER_NOT_PRESENT (code 36).

I'll try again with 1.2.0rc1, but I'm pretty sure I had it working with the GUI as how it looks like in 1.4.2.3.

On the driver front: The latest driver that is willing to install is 16.50.2611. The AMD installer claims that 15.7.1 is the suggested driver for my hardware, but I have 16.50.2611 installed right now according to the Radeon GUI.

**Comment by NoxiousPluK** [comment]
I got it working with 1.2.0rc1!

Here's the logfile: https://gist.github.com/11484669bf7103448fab36911f24aa91

Now I'm fairly certain that I used the 'newer' interface that I saw with 1.4.2.3 working, but hey - this works, and it seems to work just fine for my needs.

Thanks a lot! 👍

**Comment by NoxiousPluK** [comment]
I've pledged on Patreon (my nickname there is NoxiousPluK).

Thanks a lot for all the help 👍

**Comment by Xaymar** [comment]
If you do manage to figure out how you ran newer versions that require 16.7.1 or newer, do tell. There are probably a lot of people out there with APUs that would like to know how.

**Comment by NoxiousPluK** [comment]
I might drop some time into it sooner or later yes :)
