### ISSUE TITLE
R7 M370 - VCE Speedtest

### ISSUE THREAD

**Issue by PureLoneWolf** [Xaymar/OBS-AMD-Advanced-Media-Framework#195]
[VCESpeedTest_2016-11-16.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/752501/VCESpeedTest_2016-11-16.zip)
Hi there

My card doesn't seem to be listed and I can't manage to get OBS to give me the AMD Codec option, so here are the results of running the speedtest.

Software Info from the Crimson Drivers:

Radeon Settings Version - 2017.0125.1845.33722
Driver Packaging Version - 16.50.2711-170125a-310791E
Provider - Advanced Micro Devices, Inc.
2D Driver Version - 8.1.1.1583
Direct3D® Version - 9.14.10.01235
OpenGL® Version - 6.14.10.13467
OpenCL™ Version - 21.19.413.0
AMD Mantle Version - 9.1.10.0165
AMD Mantle API Version - 102400
AMD Audio Driver Version - Not Available
Vulkan™ Driver Version - 1.4.1
Vulkan™ API Version - 1.0.37

Would be great if this card could be supported.

Thanks

**Comment by Xaymar** [comment]
`g_AMFFactory.GetFactory()->CreateComponent(AMFVideoEncoderVCE_AVC) failed Error:AMF_NOT_SUPPORTED`

Your card has no physical encoding capabilities, sorry. This is why it ends up not listing the AMD encoder.

**Comment by max20091** [comment]
According to TechPowerUp, this card have GCN 1.0 Architecture but in Wikipedia, this Litho XT GPU does not have VCE

**Comment by CKannas** [comment]
I have the same GPU on a Lenovo Laptop, it seems that some, in not all, mobile GPUs do not have the VCE, I'm guessing due to space and maybe power consumption.

**Comment by max20091** [comment]
Yea, but laptop shipped with AMD APU usually have VCE inside just like desktop APU

**Comment by Xaymar** [comment]
Yeah but usually you need an older driver for that to work and version 1.2.0rc1, see #193
