### ISSUE TITLE
FEEDBACK v1.9.9.3pre

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#200]
hi - will say that your recent v1.9.9.3pre works pretty nice
i like the new Pre-Pass Mode -> amazing quality improvements on low bitrate

i record @3500kbps for streaming on twitch

videos (will add more soon):
720p30
https://youtu.be/4QehIqTD4I4
https://youtu.be/ZVI060Mbx1w
https://youtu.be/HMuUMw6EHY8
720p48
https://youtu.be/-bpA9u7HvUw
https://youtu.be/z5L9qCWnDAY
https://youtu.be/Zd5CCNGS9C8
720p60
https://youtu.be/8UH8RrLRgnc
https://youtu.be/8z6LRS9dwvE

**Comment by Xaymar** [comment]
Great to hear. I have so far not been able to see any improvements (PSNR and SSIM are identical with it on and off for AVC) so I'm hoping for a driver update that fixes it.

**Comment by Benman2785** [comment]
i use 17.2.1

and are you sure SSIM is identical? personally i see improvements - but will check the data for it

**Comment by Xaymar** [comment]
Yes, at least in the files my RX 480 produces.
