### ISSUE TITLE
Encoder not showing

### ISSUE THREAD

**Issue by Eric423** [Xaymar/OBS-AMD-Advanced-Media-Framework#201]
OBS 17.0.2
Plugin ver: 1.4.3.8
Driver ver: 16.2.1 crimson
AMD A10-6800k
AMD Radeon HD 8670D

screenshot: http://prntscr.com/e9rpgk

 Log : [2017-02-16 21-33-05.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/782320/2017-02-16.21-33-05.txt)

**Comment by Xaymar** [comment]
You need driver 16.7.1 or ideally newer. Contact AMD support if you are
having issues getting that driver to run.

**Comment by Eric423** [comment]
Yeah I don't think I'll be able to run drivers newer than 16.2.1, because the newer drivers don't read my card :/

**Comment by Xaymar** [comment]
There is a version based on the old Media SDK (1.2.0rc1 i think). It's not supported anymore, but it should work with cards that don't work on 16.7.1.

**Comment by Eric423** [comment]
you're so fast :o

**Comment by Eric423** [comment]
This version works! Thank you so much!

**Comment by Xaymar** [comment]
I've updated the Troubleshooting guide with a link to something that might help.
