### ISSUE TITLE
x265, HEVC not showing up

### ISSUE THREAD

**Issue by MarioPL98** [Xaymar/OBS-AMD-Advanced-Media-Framework#203]
Hi. I just updated gpu drivers to lastest, OBS and this plugin. I was so excited to use x265 but it doesn't show in OBS. Is it a "feature" or some nasty glitch? If glitch, is there any possible fix? My GPU is rx 470. x264 AMF encoder works well. Thanks.

Phenom II 960t
16GB ddr3 1600MHz cl9
MSI 870a-G46
2 SSDs and HDD
Lastest drivers and OBS
Windows 7

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Troubleshooting-Guide). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Xaymar** [comment]
There is no x264 AMF or x265 AMF encoder. The ones you are looking for are H264 and H265.

**Comment by MarioPL98** [comment]
Sorry, yes and there is no H265

**Comment by MarioPL98** [comment]
LOG: [2017-03-03 17-29-21.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/817335/2017-03-03.17-29-21.txt)

**Comment by Xaymar** [comment]
Are you looking at the Streaming or Recording tab? There is currently no supported streaming format that support H265 content, so it only shows up under Recording.

**Comment by MarioPL98** [comment]
Oh, I was always using stream encoder for recording, it's there, thanks.

**Comment by MarioPL98** [comment]
I have one more small question. Is the "main" profile the only supported by now?

**Comment by Xaymar** [comment]
If it's the only one in the list, then the GPU does not support any other profiles. Not that it matters, many of the profiles are useless to you (static image, 3D, etc).

**Comment by MarioPL98** [comment]
I have weird error. Everytime I try to start recording, I get error after half sec. Here's the log:
[2017-03-03 18-00-50.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/817371/2017-03-03.18-00-50.txt)

**Comment by Xaymar** [comment]
You are recording to flv, flv doesn't support anything else but Quick Time Video and H264.

**Comment by MarioPL98** [comment]
Thanks. What's the best container for x265?

**Comment by Xaymar** [comment]
MKV

**Comment by Xaymar** [comment]
Thanks to GitHubs new Terms of Service, this issue is now tracked here: https://gitlab.digitaldawnstudios.com/Xaymar/obs-studio_amf-encoder-plugin/issues/203
