### ISSUE TITLE
No AMF Encoder showing (AMD A10-7300 APU)

### ISSUE THREAD

**Issue by YamiDarknesSTH** [Xaymar/OBS-AMD-Advanced-Media-Framework#205]
OBS Studio 18.0.0
Plugin version: 1.4.3.11
CPU:  AMD A10-7300 Radeon R6, 10 Compute Cores 4C+6G
VCE 2.0 (Steamroller-Kaveri)
RAM: 8 GB
HDD: 500 GB + 1TB
AMD Radeon R6 M255DX (Dual Graphics)
Radeon Software Edition: Crimson ReLive
Radeon Software Version: 16.12.2
Windows Version: Windows 8.1 (64 bit)
OBS logs:
https://gist.github.com/anonymous/ad284410456251fc6cf6c42c729a735d
APU spec refer:
http://products.amd.com/en-gb/search/APU/AMD-A-Series-Processors/AMD-A10-Series-APU-for-Laptops/A10-7300-with-Radeon%E2%84%A2-R6-Graphics/16

AMD Radeon Software 
  Overview:
  https://nicekung.ml/wp-content/uploads/2017/03/radeonmaintab.png

  Software:
  https://nicekung.ml/wp-content/uploads/2017/03/radeonsoftwaretab.png

OBS : 
https://nicekung.ml/wp-content/uploads/2017/03/noamfencode.png

https://nicekung.ml/wp-content/uploads/2017/03/noamfencode2.png

Sorry for my English

**Comment by Xaymar** [comment]
APUs are not supported by AMF it seems, you will need to use the Media SDK
version 1.2.0

**Comment by Xaymar** [comment]
Thanks to GitHubs new Terms of Service, this Issue is now tracked here: https://gitlab.digitaldawnstudios.com/Xaymar/obs-studio_amf-encoder-plugin/issues/205

**Comment by Xaymar** [comment]
GitHub seems to have removed most offending statements from the ToS now, reopening.

**Comment by YamiDarknesSTH** [comment]
Sorry but I don't know what it is
How to install  or use "Media SDK" ?

**Comment by Xaymar** [comment]
That means that you need to use the Media SDK based Plugin, which the last version of is: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/releases/tag/1.2.0rc1

I worded that badly.

**Comment by YamiDarknesSTH** [comment]
After I install, OBS have VCE Encoder options 
But I can't start Streaming or Recording
Log: https://gist.github.com/anonymous/59f9c8eb1ec43ded631ad804e4b28e3d
Pic: https://nicekung.ml/wp-content/uploads/2017/03/popupobs.png

**Comment by Xaymar** [comment]
Looks like your APU is missing the VCE compoment then. Contact AMD support as I can't help you there.

**Comment by YamiDarknesSTH** [comment]
Thank You, 
but I contact it, after 48 Hours no response

**Comment by YamiDarknesSTH** [comment]
After searches for a long time
Found this thread
https://community.amd.com/thread/209423
`You need to force application to use APU graphics. 
Use Power saving mode for application that need VCE support`

It's work! 
Logs: https://gist.github.com/anonymous/f70c9484bc08b4a3dafe4b86a2d75e6f

**Comment by Xaymar** [comment]
Added to the Troubleshooting guide.
