### ISSUE TITLE
Pixelisation of stream every 2-3 seconds

### ISSUE THREAD

**Issue by ghost** [Xaymar/OBS-AMD-Advanced-Media-Framework#207]
youtube preset with quality preset, Bitrate 2500, basic view.
Video of stream pixelates every few seconds. Same thing happens with twitch preset and slight changiong of settings.

CPU: AMD FX8350
Videocard: XFX RX460 2gb
OS: 8.1 64x

OBS: 18.0.1
radeon driver: 17.2.1

Log: https://gist.github.com/sneaky4oe/087efa2481477f88d5bfb3ba3a1af934
Demo: https://www.twitch.tv/videos/127948271 (the same video has no such issues with other codecs)

**Comment by MSxDOS** [comment]
See https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/180
I've been also having this issue with my RX480 on Win7x64 since 16.10.3 when first tried this plugin. It was mostly noticeable when encoding 1080p using VBR_LAT on low'ish bitrates. I'm curious to see if Pre-Pass fixes it if/when it's fixed: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/66

**Comment by ghost** [comment]
ATM prepass doesn't fix this issue. With or without it the image is still
the same.

2017-03-11 21:11 GMT+03:00 MSxDOS <notifications@github.com>:

**Comment by Xaymar** [comment]
1. You are not running Radeon Driver 17.2.1, you are running Radeon Driver 16.8.3 or 16.8.2. This is clearly visible when looking at the log file during startup sequence. (Exhibit A)
2. The driver you are using doesn't have Pre-Pass/Pre-Analysis or VBAQ features.
3. The plugin version you are running doesn't support Pre-Pass/Pre-Analysis properly as AMD has done some changes to it. Thus changing it does nothing. (Exhibit B)
4. Increase Minimum QP to 18.

#### Exhibit A
`19:08:02.096: [AMF Encoder] Version 1.4.3.11 loaded (Compiled: 1.3.0.5, Runtime: 1.3.0.4, Library: 1;3;0;4;16.30.2511;201608050052).`

#### Exhibit B
```
19:08:37.814: [AMF Encoder] <Plugin::AMD::H264Encoder::IsPreAnalysisPassEnabled> Failed with error AMF_INVALID_ARG (code 4).
19:08:37.814: [AMF Encoder] <Plugin::AMD::H264Encoder::IsVBAQEnabled> Failed with error AMF_INVALID_ARG (code 4).
```

**Comment by ghost** [comment]
1. Now it says Radeon Software Version: 16.8.1, but I swear it was
17.2.1... :-/
2. Okay...
3. Than I'll just keep waiting, I guess.
4. Didn't help. The quality just went much worse, but that pixelation
remained. https://gist.github.com/7844dd4cf52fb8abebab67f2a8aef13d

2017-03-11 22:14 GMT+03:00 Michael Fabian Dirks <notifications@github.com>:

**Comment by Xaymar** [comment]
You are still not using the latest Driver, make sure that your obs directory does not have amfrt*.dll in it.

Edit: You can seriously tell the difference between QP 11 and QP 18? I find that rather hard to believe but okay.

**Comment by Xaymar** [comment]
Here are two sample files, both using the same identical near-lossless source footage on driver 17.3.1:

* http://cdn.xaymar.com/private/2017/03/12/12/2017-03-12%2012-41-52.mkv
* http://cdn.xaymar.com/private/2017/03/12/12/2017-03-12%2012-40-36.mkv

Neither of them shows your issue at all and both of them look the same even though the Min QP is different for each.

**Comment by ghost** [comment]
Ok, I made sure the drivers are up to date by downloading it from their
website and updating manually:
https://gist.github.com/5b2887b0874427152856546f6fd05bf7

OBS doesn't have any "amfrt" files inside it. Made sure by explorer search.

Using default twitch preset with bitrate at 2500. Same issue:
https://www.twitch.tv/videos/128179626
Looks less obvious after first pulse, but is still noticeable.

2017-03-12 14:46 GMT+03:00 Michael Fabian Dirks <notifications@github.com>:

**Comment by Xaymar** [comment]
```
16:41:22.804: [AMF Encoder]   Quantization Parameter: 
16:41:22.804: [AMF Encoder]     Minimum: 11
```

Please set minimum QP to 18, it's under View Mode Advanced.

**Comment by ghost** [comment]
Ok, this seems to fix the issue.

2017-03-12 17:30 GMT+03:00 Michael Fabian Dirks <notifications@github.com>:
