### ISSUE TITLE
5.2 main profile level gives black screen to twitch 

### ISSUE THREAD

**Issue by ghost** [Xaymar/OBS-AMD-Advanced-Media-Framework#208]
The local record of this stream is viewable. On stream it is just black screen. On twitch record has some previews but doesn't play.

CPU: AMD FX8350
Videocard: XFX RX460 2gb
OS: 8.1 64x

OBS: 18.0.1
radeon driver: 17.2.1

Log: https://gist.github.com/0f570b8465f791bb22efd5ee2368156e
Video: https://www.twitch.tv/videos/127949849

**Comment by Xaymar** [comment]
Twitch does not officially support anything about 4.2. Contact Twitch support about this.

**Comment by ghost** [comment]
I did tweet at them and sent email at support#twitch.tv, but they tend to ignore all my attempts to contact them by any means in the past, so they're unlikely to fix this just after my message...  Could you please join asking them somehow?

**Comment by Xaymar** [comment]
Looking at your log, you don't even have a reason for using anything above 4.0. 1280x720@30 fits easily into the guidelines of Profile Level 3.2, so why are you even using 5.2 here? **Always** keep Profile Level on Automatic or the Services recommended setting.

I'll be closing this as user error.
