### ISSUE TITLE
cbr and vbr always uses 20mbit for hevc

### ISSUE THREAD

**Issue by CheeryMom** [Xaymar/OBS-AMD-Advanced-Media-Framework#215]
When using vbr or cbr the output bit rate seems to be always 20000, tested with OBS Studio 18.0.1 and AMD-Encoder-for-OBS-Studio 1.9.9.6.
It seems that this is the same issue like here: https://github.com/rigaya/VCEEnc/issues/1

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Xaymar** [comment]
Also this has already been reported as #196.
