### ISSUE TITLE
More feedback on 1.9.9.6 (Video API: Host, OpenGL) mode

### ISSUE THREAD

**Issue by aquamacho** [Xaymar/OBS-AMD-Advanced-Media-Framework#216]
System specs:
Windows 8.1 x64
AMD Phenom II X6 1045T @3.3
MSI R7770 Power Edition 1GD5/OC (gcn 1.0) hooked up to main monitor
9600 GT Asus Magic HDMI second monitor.
8G ddr3 ram
asrock 970 extreme3 mobo.
Plugin ver - 1.9.9.6 (pre-release)
Drivers 17.3.3 (ReLive is not installed as always).

Obs stuff:
Resolution - 1920x1080
Preset - YouTube \ view mode advanced.
Quality - Balanced
Bitrate - 3500
Video API: Host, OpenGL
Fps - 60

this is host mode trying to record BL: TPS.
[2017-03-25 18-08-47.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/870164/2017-03-25.18-08-47.txt)
Video:
https://drive.google.com/open?id=0B8uCAZ74gXrRTUJFR0c1S0dRSWM

OpenGL (i dont care about this one, but still) Crash at pressing record button.
[2017-03-25 18-28-33.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/870174/2017-03-25.18-28-33.txt)

- 18:28:43.517: [AMF] <Id: 15> Initialized.
- 18:28:43.524: [AMF] <Id: 15> Unable to initalize converter, error AMF_INVALID_FORMAT (code 14)
- 18:28:43.589: [AMF Runtime] [18:28:43.524][AMFVideoConverterImpl]    Error: ..\..\..\..\..\runtime\src\components\VideoConverter\VideoConverterImpl.cpp(243):Assertion failed:Invalid OpenGL output format. Expected AMF_SURFACE_BGRA or AMF_SURFACE_RGBA

Hope this will help in some way and thanks for your hard work. :3

**Comment by Xaymar** [comment]
I've heard back from Mikhail, seems like Host and OpenGL aren't actual API modes and only Direct3D is supported. I'll change this for the next release.

**Comment by Xaymar** [comment]
This has been fixed in the next version.
