### ISSUE TITLE
Asynchronous Queue mode 0 kb/s on stream

### ISSUE THREAD

**Issue by aliez3331** [Xaymar/OBS-AMD-Advanced-Media-Framework#217]
Whenever I mark this option does not work
always stays at  0 kb / s

system specs:
Windows 10 LTSB x64
AMD FX 6300 4.4ghz
R9 380 2gb 
8G ddr3 ram

Plugin ver - 1.9.9.10 (pre-release)
Drivers 17.4.1 

OBS preset youtube 
3500 bitrate
fps 30

LOG 
[2017-04-11 15-07-56.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/914314/2017-04-11.15-07-56.txt)

**Comment by Benman2785** [comment]
have same prob - log in 10min

EDIT:
system specs:
Windows 10 x64
AMD FX-8150 @4.5ghz
RX 480 8G (Nitro+ OC)
16G DDR3 @1600er (a pitty my Kingston doesnt run at 1866 with 4 modules)
Plugin ver - 1.9.9.10 (pre-release)
Drivers 17.4.1

OBS preset youtube
3500 bitrate
fps 30


[2017-04-12 03-49-46.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/915223/2017-04-12.03-49-46.txt)

ps - will test 14.4.2 now

**Comment by Xaymar** [comment]
Seems to both be the same issue, EncodeLoad is never called resulting in an endless growth of the queue.

**Comment by Xaymar** [comment]
I've fixed this now, will be in the next release.

**Comment by Benman2785** [comment]
not 100% fixed 
[2017-04-14 01-04-17.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/921126/2017-04-14.01-04-17.txt)
 noticed at end of stream 0kbps

edit - i think i simply used a wrong server - because no file was created at streaming server xD -> wrong syntax that doesnt give back an error

**Comment by Xaymar** [comment]
The error in your log is the unexplainable OpenCL conversion crash
