### ISSUE TITLE
OBS GameCapture not working with Win10 Creators Update

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#219]
OBS 17.0.1 Game Capture wont work with Win10 Creators Update -> "get-graphics-offset64.exe stopped working"

**Comment by Xaymar** [comment]
wrong repo, report this to obs-studio.

**Comment by Benman2785** [comment]
i reported it to OBS

we can use screencapture

just wanted the people to be informed ;)

![obs-win10-bug](https://cloud.githubusercontent.com/assets/21282980/25001349/6a4c28a0-2045-11e7-9dd3-822190512c86.jpg)
