### ISSUE TITLE
Ability to specify custom I, P and B Interval

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/OBS-AMD-Advanced-Media-Framework#220]
This feature adds 3 interval fields that allow specifying which allow specifying a custom rate at which these frame types appear. This should allow for better visual compression while keeping the same overall bitrate simply by reducing the effective GOP.

Availability: View Mode Expert or Master (will likely start off in Master, then eventually put into Expert).

**Comment by Xaymar** [comment]
Tagging users that have requested this: @Benman2785

**Comment by Benman2785** [comment]
A BIG FAT THANK YOU!!!

**Comment by Benman2785** [comment]
i put i to the extreme: minQP 30 & idr 10 (will change when this is implimented) & custom buffer (1165kbps)

http://benmanshafen.de/OBS/VCE/AMF_1.9.9.11_CBR-3500kbps_minQP-30.flv <- "save as"

results in medium quality - but pretty consistent (not many changes between QPs)

![amf_1 9 9 11_cbr-3500kbps_minqp-30](https://cloud.githubusercontent.com/assets/21282980/25075643/005660ec-2319-11e7-9709-b03e74feb8b2.jpg)
http://benmanshafen.de/OBS/VCE/AMF_1.9.9.11_CBR-3500kbps_minQP-30.jpg
as u can see - just a few peaks - bitrate stays quiet stable

with a better i p b mix it will improve
ps have in mind that was minQP 30 

EDIT:
http://benmanshafen.de/vids/AMF_1.9.9.11_CQP_minQP-24_remux.mp4 here u see a what minQP 24 needs as bitrate // so 3500kbps for a STREAM cant look constantly that good
