### ISSUE TITLE
OBS crash with AMF and Win10 Creators

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#222]
Windows 10 Pro x64 Creators Update (clean install)
AMD FX-8150 @4.5GHz
Sapphire RX 480 8G Nitro+ OC
16G DDR3
Plugin ver - 1.9.9.11 (pre-release)
Drivers 17.4.2

AMF Plugin let OBS Studio x64 crash with these errors:

http://benmanshafen.de/pics/OBS/Xaymar/Crash%202017-04-16%2004-41-06.txt
http://benmanshafen.de/pics/OBS/Xaymar/Crash%202017-04-16%2004-41-24.txt
http://benmanshafen.de/pics/OBS/Xaymar/Crash%202017-04-16%2019-58-13.txt

OBS Studio 32bit works flawlessly ;)

**Comment by Xaymar** [comment]
Can't reproduce this here on either 32-bit or 64-bit.

**Comment by Benman2785** [comment]
yesterday it worked - now it didnt - dont know why...

other also have this problem (u were tagged in OBS Forum)

**Comment by Xaymar** [comment]
From the crash logs I've seen so far this looks like a broken driver installation or a broken Windows update. As I said, I can't reproduce this on either bit-ness, I need to be able to reproduce something to fix it :)

**Comment by Benman2785** [comment]
mh - its a clean Windows install - will reinstall driver now (but also was clean installed yesterday)

**Comment by Benman2785** [comment]
FIXED!

disable Win10 SMART-SCREEN (different in Creators Update)
&
if using RivaTuner - install v7.0.0.0b19

**Comment by Xaymar** [comment]
17.4.3 WHQL is out, so this is probably not going to happen anymore.
