### ISSUE TITLE
Asynchronous Queue does not wake up fast enough

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#223]
hi

Windows 10 Creators x64 
AMD FX-8150 @4.5
RX 480 8G (Nitro+ OC)
GigaByte 990FX-Gaming
16G DDR3 

OBS 18.0.1
Plugin ver - 1.9.9.11 (pre-release)
Drivers 17.4.2 (ReLive is not installed)

when using "Quality" Preset i get "Encoder Overload" when using more then 30 Frames

**Comment by Benman2785** [comment]
![amfenc_1 9 9 11_qp-quality_bug](https://cloud.githubusercontent.com/assets/21282980/25190230/df7aa832-252b-11e7-81d4-45d91eaebce6.jpg)

have to use this for 48 and 60 FPS // with 30 FPS i can use "Quality" QP

log in 30min

edit: will update to 17.4.3 now

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Benman2785** [comment]
[2017-04-19 18-32-16.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/936080/2017-04-19.18-32-16.txt)

http://benmanshafen.de/OBS/VCE/AMFenc_1.9.9.11_QP-Quality_bug.flv <- save as (in 5min)

**Comment by Benman2785** [comment]
vid looks like it only uses the i-Frames

**Comment by Xaymar** [comment]
- Change the Profile Level to Automatic.
- Coding Type should not be manually set, leave this at Automatic.
- Revert your "fixes" to Min and Max QP, these should never be moved away from 18 - 51.
- Pre-Pass has a huge impact on encoding if it actually works, it's about ~20-35% lower expected fps.

Aside from that, the only issues I can see are that the retrieve thread isn't waking up as it should, taking a few ms longer. And that the main timer is messed up for some reason. Actual Submit -> Query latency is about 15msec, much higher than it should be.

**Comment by Benman2785** [comment]
[2017-04-19 19-25-25.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/936649/2017-04-19.19-25-25.txt)
hasnt fixed it

**Comment by Xaymar** [comment]
Submit to Query time is now down to 12-13ms, but the Retrieve Async Queue thread is still not waking up as soon as it should. For now don't use Async Queue, as your CPU should be fast enough to do everything on the same thread.

**Comment by Benman2785** [comment]
[2017-04-19 19-51-44.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/936871/2017-04-19.19-51-44.txt)
disabled AsyncQueue -> fixed now

**Comment by Xaymar** [comment]
This is fixed by 2.1.2 and later. The threads now wake up and sleep the proper amount of time.
