### ISSUE TITLE
Question: Which version should we use?

### ISSUE THREAD

**Issue by CKannas** [Xaymar/OBS-AMD-Advanced-Media-Framework#224]
Which version should we use 1.4.3.11 or the pre-release 1.9.9.6?

Thanks :)

**Comment by Xaymar** [comment]
Neither, as 2.0.0 is coming out.

**Comment by Benman2785** [comment]
and there is also a patreon version (current 1.9.9.11) ;)

**Comment by MSxDOS** [comment]
I hope Intra Refresh is coming back some day :)

**Comment by Xbye** [comment]
@Xaymar Will 2.0.0 work properly with the old 16.11.5 Non-ReLive AMD driver?

**Comment by Benman2785** [comment]
nope - u need at least 17.2.1 i think - better use 17.4.3

xbye do u need color-settings in additional settings from AMD Driver? i have a fix for any new driver
https://community.amd.com/thread/208986 - last post (posted the wrong msi // redownload it and it will work)

**Comment by Xbye** [comment]
@Benman2785 @Xaymar 
Damn, then I won't be able to use it.

No, I need a stable AMD driver for my card. Every single ReLive driver released is causing my display driver to crash during intense scenes. Only drivers before ReLive are 100% stable for me, no matter how intense scenes get.

https://community.amd.com/thread/214750 - My thread on it.

EDIT: Just tried to test 2.0.0.0. Crashes when I try to open settings. So yeah, guess that's the end of the line for me then since none of the ReLive drivers are even remotely stable for me.

**Comment by max20091** [comment]
You should reinstall Windows, update motherboard and GPU BIOS and install WHQL driver.
I'm not sure if that solved your issue but it solved my computer and my GPU run much faster now.
Edit: WHQL is most stable driver and it's certified by Microsoft.

**Comment by Xbye** [comment]
@max20091 I am not formatting my PC... especially when I don't have the Win10 install disc nor the ID a friend bought for me a while back.

**Comment by Xaymar** [comment]
You don't have to reformat a PC to reset Windows 10 back to the original state. Windows 10 keeps an unmodifyable version that you can return to that is pretty much an identical copy of the first Windows 10 that was started.

Anyway, there will be no support for non-ReLive drivers as the driver updates actually fix things that the plugin actively used. If you want to use a non-ReLive driver you will have to stick to 1.4.3.11 or compile the plugin without HEVC support which will drop the minimum driver version to 16.7.3. Visual Studio 2015 Express or Visual Studio 2017 Express should work fine for that.

**Comment by max20091** [comment]
Start > Settings > Update & Security > Recovery > Reset this PC to totally reset your Windows 10

**Comment by Benman2785** [comment]
u can download an iso of current Win10 with media-creation-tool from microsoft // before using that u should add your win10 key to your live-account (outlook or hotmail or live) and when installing you only use your live accoutn to login and your win10 is already activated
