### ISSUE TITLE
FEEDBACK to v2.0.0 ;)

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#226]
Windows 10 Creators x64
AMD FX-8150 @4.5GHz
RX 480 8G (Nitro+ OC)
GigaByte 990FX-Gaming
16G DDR3 @1670MHz CL9-9-9-27 (4x4G - and my MemoryController sucks)

OBS 18.0.1
Plugin ver - 2.0.0 
Drivers 17.4.3 (with Display-Color-Fix for additional Radeon Settings)

i tested a little and have to say - good work Xaymar (as usual)

here some vids to check the quality ("save as")

720p48 (good for streaming most Shooters/fast-scene-switching games in higher fps)
http://benmanshafen.de/OBS/VCE/AMFenc_2.0.0._720p48_CBR-3500kbps_minQP-18_IDR-96_KFI-2,00.flv
-> that is "standard-settings" quality and the only videofile you can "search" with media-players
http://benmanshafen.de/OBS/VCE/AMFenc_2.0.0._720p48_CBR-3500kbps_minQP-18_IDR-12_KFI-2,00.flv
-> here i changed the IDR-Period to 1/4fps -> results in more i-Frames // file cant be "searched"

now the best quality of 720p48

http://benmanshafen.de/OBS/VCE/AMFenc_2.0.0._720p48_CBR-3500kbps_minQP-18_maxQP-42_IDR-8_KFI-2,00.flv
-> i turned IDR-Period to 1/5fps -> more i-Frames -> better quality -> video cant be "searched" -> we can call it a preview of v2.1.0 (when we can force i-frames - without messing the IDR Period - so videos will be search-able again ;) // also i use a very-strict custom buffer

**Comment by Benman2785** [comment]
https://youtu.be/xI98gaUJnck

**Comment by Benman2785** [comment]
https://www.youtube.com/playlist?list=PLZ9nWzw_bSDFUaoX-zXZ8pU2NQjE3dH8v

did some vids -> check them out if you want ;)

**Comment by Xaymar** [comment]
Thanks for the feedback, it's really appreciated. Hopefully you'll find newer versions even more to your liking.
