### ISSUE TITLE
HEVC not working

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#227]
Windows 10 Creators x64
AMD FX-8150 @4.5GHz
RX 480 8G (Nitro+ OC)
GigaByte 990FX-Gaming
16G DDR3 @1670MHz CL9-9-9-27 (4x4G - and my MemoryController sucks)

OBS 18.0.1
Plugin ver - 2.0.0
Drivers 17.4.3 (with Display-Color-Fix for additional Radeon Settings)

i cant record with h265/hevc - it ends in unspecific error
![hevc_error](https://cloud.githubusercontent.com/assets/21282980/25206157/8bf68218-2566-11e7-85be-337aafffe3d8.jpg)

[2017-04-20 01-08-40.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/938881/2017-04-20.01-08-40.txt)

**Comment by Xaymar** [comment]
> Recording HEVC to FLV
> Expecting that to work

FLV only supports Quick Time Video and H264/AVC.

**Comment by Benman2785** [comment]
QP Quality & Pre-Pass Mode "enabled" läuft nicht
