### ISSUE TITLE
x64 Crash on startup (caused by AMF plugin)

### ISSUE THREAD

**Issue by ghost** [Xaymar/OBS-AMD-Advanced-Media-Framework#229]
Crash with x64 using AMF:
https://gist.github.com/droidxbounty/cd3352cae906cc0456046d9ff879ea24

Running log using the x32 with AMF:
https://gist.github.com/droidxbounty/dbeb6bac8b5d123a2fdfa2eaf94224fb

Live Chat log of testing:
https://gist.github.com/droidxbounty/1cf7a5282b7d13e49f2744fa1146f411

However, I can run the x32 using AMF (I am using a 64 bit system).
Drivers are latest. (AMD 17.4.3, Win 10 creators update)
OBS ver. 18.0.1
AMF Plugin ver. 2.0.0

Syst Info:
OS - Win 10 creators
CPU - fx 8350 black
GPU - r9 390x
RAM - 16GB
1 HDD - 1T
1 SDD (OS) - 128GB
AMDrivers: 17.4.3 (recommended)
OBSversion: 18.0.1

**Comment by Xaymar** [comment]
Direct3D 9 crash, not caused by plugin but other things you have installed. Run Display Driver Uninstaller and install 17.4.3 cleanly and update anything you have installed (RivaTuner Statistics Server for example).

**Comment by Benman2785** [comment]
update your RivaTuner to 7.0.0b19 -> that should fix it
http://www.guru3d.com/files-get/rtss-rivatuner-statistics-server-download,14.html

**Comment by Benman2785** [comment]
@droidxbounty is it fixed?

**Comment by ghost** [comment]
(Sorry it took so long for a response) Yes, clean installing Riva with the new 7.0.0 beta version (most recent) solved the x64 crash. Everything works now, including recording/streaming.

Its weird that Riva didnt notify me of an available update, and I did not think of it after the win10 creators update at all. Thank you!
