### ISSUE TITLE
VCESpeedTest_2016-11-16.7z (HD 7870)

### ISSUE THREAD

**Issue by Kostas-Ioannidis** [Xaymar/OBS-AMD-Advanced-Media-Framework#231]
[VCESpeedTest_2016-11-16.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/949043/VCESpeedTest_2016-11-16.zip)

**Comment by Benman2785** [comment]
can u give some additional infos?

**Comment by Xaymar** [comment]
The archive is missing a critical file, please make sure that you upload all .txt files it creates. Also from the looks of it, you are using an outdated Test, you can always find the latest one here: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Hardware-Support

**Comment by Kostas-Ioannidis** [comment]
I got the test I run from this link: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Hardware-VCE1.0 

Perhaps it needs updating. I downloaded the updated test, run it and compressed the files as the instructions described. The file size seems to be around 39mb so I can't upload it here. I'm uploading it on Google Drive right now and will link it soon. Hopefully this information will be of use to some.

**Comment by Kostas-Ioannidis** [comment]
Here it is: https://drive.google.com/open?id=0B1EkTlerYnz6dkJGRlBOVkhwZ00

**Comment by Xaymar** [comment]
| Resolution | Speed  | Balanced | Quality | Speed  | Balanced | Quality |
|:----------:|-------:|---------:|--------:|-------:|---------:|--------:|
|            | AVC    |          |         | HEVC   |          |         |
| 1:1        | -      | -        | -       | -      | -        | -       |
|    256x256 | 1127,0 | 1385,1   | 1033,5  |        |          |         |
|    512x512 | 578,9  | 511,5    | 332,9   |        |          |         |
|  1024x1024 | 171,7  | 149,3    | 91,1    |        |          |         |
|  2048x2048 | N/A    | N/A      | N/A     |        |          |         |
| 4:3        | -      | -        | -       | -      | -        | -       |
|    320x240 | 1356,0 | 1270,6   | 920,9   |        |          |         |
|    480x360 | 815,8  | 739,6    | 492,7   |        |          |         |
|    640x480 | 505,3  | 445,9    | 288,5   |        |          |         |
|    800x600 | 347,2  | 306,3    | 192,6   |        |          |         |
|   1024x768 | 226,3  | 197,4    | 118,7   |        |          |         |
|  1600x1200 | 95,6   | 83,1     | 50,2    |        |          |         |
| 5:4        | -      | -        | -       | -      | -        | -       |
|   1152x864 | 180,5  | 157,5    | 96,0    |        |          |         |
|  1280x1024 | 138,7  | 120,6    | 73,1    |        |          |         |
| 16:9       | -      | -        | -       | -      | -        | -       |
|    426x240 | 1207,8 | 1102,6   | 774,9   |        |          |         |
|    640x360 | 662,8  | 586,5    | 380,5   |        |          |         |
|    854x480 | 382,4  | 351,0    | 223,6   |        |          |         |
|    960x540 | 329,4  | 288,8    | 180,0   |        |          |         |
|   1280x720 | 194,4  | 169,4    | 103,6   |        |          |         |
|   1366x768 | 166,0  | 146,6    | 90,2    |        |          |         |
|  1920x1080 | 87,5   | 76,3     | 46,1    |        |          |         |
|  2560x1440 | N/A    | N/A      | N/A     |        |          |         |
|  3840x2160 | N/A    | N/A      | N/A     |        |          |         |
| 16:10      | -      | -        | -       | -      | -        | -       |
|   1280x800 | 175,3  | 153,2    | 93,4    |        |          |         |
|   1440x900 | 136,1  | 119,3    | 73,0    |        |          |         |
|  1920x1200 | 80,0   | 69,5     | 41,8    |        |          |         |

**Comment by Xaymar** [comment]
Added to the wiki.
