### ISSUE TITLE
[32 Bit - OBS] Starting the output failed...

### ISSUE THREAD

**Issue by Xbye** [Xaymar/OBS-AMD-Advanced-Media-Framework#232]
**Erro**r: [Discord Image](https://cdn.discordapp.com/attachments/304812467781894145/305441797499518986/unknown.png)
**OBS Log**: [Github](https://gist.github.com/anonymous/238faf7eb48a79f6d82d403b4138a9e9)
**Notable Lines (38 - 53)**:
>13:01:47.547: ---------------------------------
13:01:47.548: Required module function 'obs_module_load' in module '../../obs-plugins/32bit/chrome_elf.dll' not found, loading of module failed
13:01:47.548: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
13:01:47.549: LoadLibrary failed for '../../obs-plugins/32bit/enc-amf.dll': The specified module could not be found.
13:01:47.549:  (126)
13:01:47.549: Module '../../obs-plugins/32bit/enc-amf.dll' not found
13:01:47.553: Required module function 'obs_module_load' in module '../../obs-plugins/32bit/libcef.dll' not found, loading of module failed
13:01:47.553: Required module function 'obs_module_load' in module '../../obs-plugins/32bit/libEGL.dll' not found, loading of module failed
13:01:47.553: Required module function 'obs_module_load' in module '../../obs-plugins/32bit/libGLESv2.dll' not found, loading of module failed
13:01:47.553: Failed to load 'en-US' text for module: 'obs-browser.dll'
13:01:47.553: [browser_source: 'Version: 1.29.0']
13:01:47.554: LoadLibrary failed for 'nvEncodeAPI.dll': The specified module could not be found.
13:01:47.554:  (126)
13:01:47.561: VLC found, VLC video source enabled
13:01:47.563: No blackmagic support
13:01:47.670: ---------------------------------

**Driver Version**: [Crimson ReLive Edition 17.4.3](http://support.amd.com/en-us/download/desktop?os=Windows+10+-+64)

I understand it says 64bit, but is there really no way to get this to work with 32bit? The 64bit OBS makes my mouse feel funky. Also, I used the precompiled installer.

**Comment by Xbye** [comment]
I recently just formatted my computer. Seems I solved it by installing - [Visual Studio 2015 Redistributables](https://www.microsoft.com/en-us/download/details.aspx?id=48145) **x86**, after reading through the <>Code section. Not sure how they made it past me.

The OBS log still shows the above errors however, but it seems to be recording fine?

**Comment by Xaymar** [comment]
If you no longer get an error loading enc-amf you should be fine. Also this is solved by reading Step 2 of the Troubleshooting Guide.
