### ISSUE TITLE
For Benman2785

### ISSUE THREAD

**Issue by zecableguy** [Xaymar/OBS-AMD-Advanced-Media-Framework#233]
[ResultsH265.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/949373/ResultsH265.zip)

**Comment by Benman2785** [comment]
can u pls run the h264 @zecableguy

**Comment by Benman2785** [comment]
thank you

http://benmanshafen.de/OBS/ResultsH264.zip

**Comment by Jamesc359** [comment]
[ResultsH264_ResultsH265.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/949385/ResultsH264_ResultsH265.zip)

**Comment by Benman2785** [comment]
thank you ;)

**Comment by Xaymar** [comment]
Thanks all of you, I don't see anything out of the ordinary in the results. Which means that the issue is elsewhere :/
