### ISSUE TITLE
Enabling B frames results in frame rate being halved.

### ISSUE THREAD

**Issue by trillerr** [Xaymar/OBS-AMD-Advanced-Media-Framework#234]
[Specs.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/952002/Specs.txt)

Obs version: 18.0.1
Plugin version 2.0.0.0
AMD Drivers: 17.4.3

[2017-04-24 09-12-18.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/952021/2017-04-24.09-12-18.txt)

When I enable a single b-frame the resulting output is always half of the framerate specified in the video tab.  The log file attached includes three recordings.  The first is 1920x1080 with no b-frames at 60 fps.  The next has a single b-frame enabled at 60 fps.  The final I reduced the framerate to 30 fps.  

This provided me with a 60 fps output file, 30 fps output file, and 15 fps output file.  At first I suspected the encoder might be overloaded and would only be able to output half the frames when using a b-frame.  But reducing the desired framerate always reduced the output proportionally.  

I wasn't sure the easiest way to provide details on the framerates.  Here are some snipped images of the video details in explorer:
[OutputVideoDetails.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/952080/OutputVideoDetails.zip)

Additionally whenever I increase B-Frames above 1 the encoder seems to hang.  I am unable to stop the recording via obs.  Here is a log file where I attempt to record 1920x1080 at 10 fps with 2 b-frames.  Would It be best if I moved this to a separate issue?
[2017-04-24 09-32-47.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/952091/2017-04-24.09-32-47.txt)

**Comment by Xaymar** [comment]
B-Frame support in 2.0.0 is not complete yet as it adds slight changes to the timestamps. Marking as bug and in progress.
