### ISSUE TITLE
'Hardware (AMD)' Missing

### ISSUE THREAD

**Issue by NuclearC** [Xaymar/OBS-AMD-Advanced-Media-Framework#235]
Hi,

So today I spent a lot of time on trying installing AMD Relive, but fcking AMD software was shit (relive tab was missing lol) and I decided to take a look at OBS. Everyone gave me advice to use OBS.  I installed it, but it was lagging like hell. Now I finally found this super plugin for AMD, and it doesnt work. Why? In wikipedia it says that my Radeon 8750M (GCN1) supports VCE1. Now whats the problem?

Some Info:
OBS: 18.0.1
Windows 10 build 14393
AMD's shit: AMD Crimson 17.4.3
Driver: 22.19.157.3
CPU: Intel Core i7 4702mq

So any hope on using OBS on my laptop?

**Comment by Xaymar** [comment]
There is no entry for an 8750M on the wiki.

Sincerely,

Michael Fabian Dirks
https://xaymar.com/

**Comment by NuclearC** [comment]
It's written as 'Mobile Radeon HD 8000-Series':

![image](https://cloud.githubusercontent.com/assets/8341270/25564386/4b6429c0-2dc3-11e7-8225-c543705f6edc.png)

EDIT: It says "Since 2012 it is integrated into all of their GPUs and APUs." and my GPU  was announced on 16.11.2012 according to notebookcheck.net

**Comment by Xaymar** [comment]
You have an 8750M. This is not on the wiki. Case closed.

**Comment by Xaymar** [comment]
Unless you find your GPU on this list, it is not supported: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Hardware-Support
