### ISSUE TITLE
v2.1.0 i-Frame Period (in Frames) sets Key-Frames not i-Frames

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#236]
Windows 10 Creators x64
AMD FX-8150 @4.5GHz
RX 480 8G (Nitro+ OC)
GigaByte 990FX-Gaming
16G DDR3 @1670MHz CL9-9-9-27 (4x4G - and my MemoryController sucks)

OBS 18.0.1
Plugin ver - 2.1.0
Drivers 17.4.4 (with Display-Color-Fix for additional Radeon Settings)

Hi - it looks like that the function for forced i-Frames forces it to be Key-Frames - so it the following p-frame isnt able to refer on that frame - so it gets blocky

here output from ffprobe of a video with i-Frame every 12 frames
[frametest.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/970207/frametest.txt)

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

-----

Additionally, your own linked file proves you wrong: the only actual Key frames are every 2 seconds.

```
[FRAME]
media_type=video
stream_index=1
key_frame=1
pkt_pts=0
pkt_pts_time=0.000000
pkt_dts=0
pkt_dts_time=0.000000
...
pict_type=I
coded_picture_number=0
display_picture_number=0
...
[/FRAME]
...
[FRAME]
media_type=video
stream_index=1
key_frame=0
pkt_pts=250
pkt_pts_time=0.250000
pkt_dts=250
pkt_dts_time=0.250000
...
pict_type=I
coded_picture_number=12
display_picture_number=0
...
[/FRAME]
...
[FRAME]
media_type=video
stream_index=1
key_frame=0
pkt_pts=750
pkt_pts_time=0.750000
pkt_dts=750
pkt_dts_time=0.750000
...
pict_type=I
coded_picture_number=36
display_picture_number=0
...
[/FRAME]
```

**Comment by Benman2785** [comment]
yeah i see now - but i still dont get why the p-frame following the forced i-frame is so blocky

**Comment by Xaymar** [comment]
Because you can't improve quality by throwing something at it that requires even more bitrate. I frames are really expensive compared to P frames.

**Comment by max20091** [comment]
I Frames require more bitrate to reach P Frames quality and P Frames also require more bitrate than B Frames so don't force I Frames only unless you have issue with cutting videos or fast forwarding
Currently there is no way to improve video quality without using less bitrate by hardware encoding unless Xaymar can make a hybird CPU & AMD GPU encoder.

**Comment by Benman2785** [comment]
you did a great job - now we can change IDR-Period and still maintain a "searchable" videofile // they process faster on youtube
