### ISSUE TITLE
VCE 3.1 missing on wiki

### ISSUE THREAD

**Issue by max20091** [Xaymar/OBS-AMD-Advanced-Media-Framework#237]
It seems on Wiki there isn't VCE 3.1 which available in Carrizo, Bristol Ridge APU as well as Carrizo-L and Stoney Ridge mobile APU

**Comment by Xaymar** [comment]
I have not seen any difference between VCE 3.1 and VCE 3.0, can you elaborate why that would need its own page?

**Comment by max20091** [comment]
I think it have much slower speed compared to VCE 3.0
Anyway, we don't need to make a new page, just mark the Fiji GPU as VCE 3.1 and slower than Tonga

**Comment by Xaymar** [comment]
Done.
