### ISSUE TITLE
Under 60fps recording despite being able to play and record 1080p60

### ISSUE THREAD

**Issue by Ryzym** [Xaymar/OBS-AMD-Advanced-Media-Framework#24]
Can't reopen an issue since I don't own this project, so I looked up how and it said I have to reference the issue, so the issue is #22. Reopen old one and get rid of this one if you feel the need to.

Edit: After updating to the newest release of OBS, the old encoder and this plugin both seem to be able to handle 1080p60 recordings with no issue? Don't know what happened there.

**Comment by Ryzym** [comment]
And now I'm getting random color issues? I can record a video if needed. It even shows after rendering.

Edit: I need to do more recordings to see if this is game specific or something because I got color issues recording Dark Souls 3 but not Overwatch, although I didn't record Overwatch for very long.

**Comment by Xaymar** [comment]
There already is an issue for this, as this issue has been known for a while now: #18
