### ISSUE TITLE
[2.1.2] Immediately Crashes On Encoder Start

### ISSUE THREAD

**Issue by Xbye** [Xaymar/OBS-AMD-Advanced-Media-Framework#240]
Old 2.0.0.0 currently works. I reset my configuration upon upgrading to 2.1.2 . Switching between Full and Partial didn't change anything.

**RX 480** - _17.5.1_

**OBS Log**: https://gist.github.com/anonymous/b3ad82d2b13f650c59703b34a0d8680f
**Crash Log**: https://pastebin.com/Ngk5qUBz

**Comment by Xaymar** [comment]
32-Bit, already known and reported. This is a driver bug.

**Comment by Xaymar** [comment]
A temporary solution is to not use 32-bit and instead use 64-bit until AMD releases a driver with this fixed.

**Comment by Xbye** [comment]
>A temporary solution is to not use 32-bit and instead use 64-bit until AMD releases a driver with this fixed.

This isn't a solution for me since I still haven't been able to fix the floaty mouse issue that comes with 64-bit. I should be fine for now since 2.0.0.0 still works.

**Comment by Nuc1eoN** [comment]
So the 64bit version of OBS is still buggy? Thought it does well on 64bit systems.

**Comment by Xaymar** [comment]
> This isn't a solution for me since I still haven't been able to fix the floaty mouse issue that comes with 64-bit. I should be fine for now since 2.0.0.0 still works.

Sucks for you. Since so far I've seen nobody else reproduce that problem, I don't think it's something anyone can ever solve.

**Comment by Nuc1eoN** [comment]
So the bug is in the 64bit Radeon driver?

**Comment by Xaymar** [comment]
@Nuc1eoN I keep seeing emails pop up from you with no related comment. To answer the question, the bug **is in the 32-bit driver** not in the 64-bit one.

**Comment by Xaymar** [comment]
2.1.5 contains a workaround for the time being.

**Comment by Xaymar** [comment]
Driver 17.7.2 supposedly fixes this, have not confirmed yet.

**Comment by Xaymar** [comment]
Fixed by 17.7.2
