### ISSUE TITLE
Encoder Overload problems presist

### ISSUE THREAD

**Issue by Saymite** [Xaymar/OBS-AMD-Advanced-Media-Framework#241]
Hello there, Xaymar first of all I want to thank you for developing this plugin.

The issue im reporting is still the same as #225 , but since you updated the plugin I wanted to test the new version out,you can go ahead and close #225 , so here goes nothing;

Specs:

https://hastebin.com/pujafezeco.sql

Short Version : R9 280X
		i5 4670

The issue: The Issue I am having is that I get "Encoder Overloaded" while trying to record something that worked before and is well within my cards capabilities, to add to that my videos become extremelly laggy, eg. 1 frame per 10 seconds, and pressing "Stop Recording" takes 1-2 mins and sometimes makes OBS just quit.
This issue started to happen since 2.0.0.0+
Before when I would get "Encoder Overloaded" my frames would go down but never this extremely.
This is all on a fresh install of codecs + OBS + drivers, might try re-installing OS if problems cant be found.

Testing methadology:
Run a benchmark in GTA V windowed mode.
OBS settings : Using Indistinguishable Preset

2.1.2 log:
https://gist.githubusercontent.com/anonymous/8f9d9a7dcd6a998cc7233c75fa321081/raw/061d9b3a4594c595335e42bb3bb96e0b210cf4fb/2017-05-14%252013-40-36.txt

2.1.2 video:
https://www.youtube.com/watch?v=iAp0RK-Ql_Q&feature=youtu.be

1.9.9.6 log:
https://gist.githubusercontent.com/anonymous/3e1a946fff9eae89ea567e0b2bec91e7/raw/09a1bf273908b9cbb8fdf3592c68d31c845542eb/2017-05-14%252013-59-35.txt

1.9.9.6 video:
https://www.youtube.com/watch?v=LGBeaMUsaXA&feature=youtu.be

**Comment by Xaymar** [comment]
First off, for fox sake, stop comparing to an early preview that had significant issues keeping track of anything. In the future I'll just immediately close things that refer to version 1.9.9.6 or 1.4.3.11. The only version you are allowed to compare against is 1.2.0rc1 (which used the older AMD video runtime)

Also if your issue is still the same, don't open a new one keep it in the old one.
