### ISSUE TITLE
[BUG / 2.1.3] AMF Encoder not selectable in Drop Down Menu anymore

### ISSUE THREAD

**Issue by Redundanz** [Xaymar/OBS-AMD-Advanced-Media-Framework#242]
Since updating to 2.1.3 the encoder entry in the menu just vanished. I can only select x264 there.
Using OBS Studio 18.0.1 (64bit) on Windows 10 1703 (Creators Update)
I double checked the installation by copying all files over to the "obs-plugin" folder a second time. 
After copying the old versions dlls and pdbs (32&64) everything works again.

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Xaymar** [comment]
I can tell you right now that "just vanished" is not an error the plugin actually produces. It always has a reason for not being there and usually it is because you don't have a supported GPU or don't have the VS 2015 runtime installed.

**Comment by Redundanz** [comment]
I have VS2015 installed.
And your plugin (v2.0.0 from 25 days ago) worked fine with my 270X so far. And older versions did as well.

I'm only trying to help here. For me it's not a big problem using an older version.

**Comment by Xaymar** [comment]
Then please actually follow the Troubleshooting Guide as I said above.

Edit: This is with 2.1.3, please provide the log file:

![http://cdn.xaymar.com/private/2017/05/15/14/2017-05-15_14-03-09.png](http://cdn.xaymar.com/private/2017/05/15/14/2017-05-15_14-03-09.png)

**Comment by Redundanz** [comment]
There is nothing in the Guide which I didn't try / didn't take into consideration.
- My GPU is supported.
- My OBS is on 18.0.1 (latest)
- I have the most recent GPU driver by Windows Update. (latest WHQL / non-beta)
- Framework is the latest freshly downloaded from your github

So unless there is a secret paragraph hidden in the guide which I can't see... i can safely say I followed that guide.

In all honesty. Do you think it is a problem with anything else than the new binaries when switching out 2.1.3 binaries with 2.0.0 binaries makes it work again?

**Comment by Redundanz** [comment]
https://pastebin.com/FEGe8XLW

**Comment by Xaymar** [comment]
See, I knew you didn't follow the Troubleshooting Guide properly. The second step in the guide says that your driver has to be on the latest, most recent version, which is 17.5.1. You are currently running a driver that is either the Windows Update one or a variant of the 16.11.5 one.
