### ISSUE TITLE
2.1.3 Feedback

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#243]
new behaviour of AsyncQueue works great!

from #Fixed 'Encoding overloaded!' by making Asynchronous Queue the default behaviour and removing that option.

i can capture TheDivision in "Profile: high" now - before i was limited to "constrained baseline" or "baseline"

**Comment by ivanquirino** [comment]
Well, I can't evaluate because soon after I start recording I get this error: 

Failed to recreate D3D11: Failed to duplicate output (80070005

I'm am going to install version 2.0.0.0 of the plugin again and check if the problem persists, because it can be my GPU's fault (R9 380)

**Comment by Xaymar** [comment]
@ivanquirino The error you get is not from the plugin. It is an OBS error.

**Comment by ivanquirino** [comment]
well, it happend after I updated to 2.1.3, I am going to check with the 2.0 version and the x264 encoder to see if the problem persists

**Comment by Xaymar** [comment]
> well, it happend after I updated to 2.1.3, I am going to check with the 2.0 version and the x264 encoder to see if the problem persists

Correlation does not imply causation.

**Comment by ivanquirino** [comment]
Using plugin version 2.0 OBS doesn't crash, and I recorded a full Overwatch match. Switched back do 2.1.3 and it crashed again, some time after I started recording, same error as above. Attached goes the full log. For now, I'm going to keep version 2.0.

[log_before_crash.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1005297/log_before_crash.txt)

**Comment by Xaymar** [comment]
@ivanquirino If you have an overclock, you might want to consider removing it because your GPU is actually crashing - not OBS.

**Comment by ivanquirino** [comment]
@Xaymar no overclock here. The strange thing is, why does it crash with the 2.1.3 plugin and not with the 2.0 plugin?

**Comment by Xaymar** [comment]
The strange thing is why is your GPU crashing with a version that actually uses the GPU? 2.0 is not using the GPU to its full potential which leaves large gaps in encoding performance aka 'Encoding overloaded!' showing up.

**Comment by ivanquirino** [comment]
Well, I don't get "Encoding overloaded' when using 2.0. And I can keep recording for a long time using that version. Maybe my GPU has some problem, I don't know.

**Comment by ivanquirino** [comment]
How can I disable full range encoding? Or any other new setting that may be crashing it.

**Comment by Xaymar** [comment]
> How can I disable full range encoding? Or any other new setting that may be crashing it.

If you haven't set OBS to full range, then it's sending partial range frames. As for "new settings that may be crashing it", there is only custom I/P/B/Skip interval which is only used if you have View Mode set to Expert or above.

**Comment by ivanquirino** [comment]
I tested more times, and all my recordings at 50 and 60 fps crashed, both in 1080p and 720p, but 30 fps records in these resolutions went with no crashes. It looks like when the encoder overloads, it is crashing the GPU. But this didn't happen in version 2.0, I used to have encoder overloads but never had any crash before 2.1.3

**Comment by Xaymar** [comment]
It might be overheating then. Encoding at such high framerates does incur quite a bit of heat and the log you've shown does match the behaviour of a GPU driver reset due to that.

**Comment by ivanquirino** [comment]
it might be overheating the encoding engine? Because I keep checking the temps and it is always at the same 72º C level.

**Comment by ivanquirino** [comment]
Testing with Radeon ReLive, I have no problems at all to record 1080p 60fps at 30000 kbps.

**Comment by Xaymar** [comment]
Is it actually 60 fps?

**Comment by ivanquirino** [comment]
ReLive is configured to record at 60 fps, and also temps don't go above 70º C (recorded for 7 minutes), I checked in VLC and it is 59.89 fps. In OBS I use "Limit Capture Frame Rate" and set my quality to "speed". Later I'm going to try again using VBR instead of VBRLAT, and CALVC coding. There's also that setting "max reference frames" that I need to tweak too...

Maybe the async queue is too fast for my GPU? How can I slow it down?

OBS is great, your plugin is great, we just need to beat ReLive! See ya later.

**Comment by Xaymar** [comment]
The Async Queue can't be too fast. It runs at the same Framerate you set OBS to, so the GPU Driver will actually underclock it if it is underused (which it usually is). I don't know what's causing the issue for you, but I've been able to go back up to 130 fps on an RX 480.

**Comment by Benman2785** [comment]
@ivanquirino Xaymars Plugin beats ReLive already ;)
maybe try to use MSI Afterburner and improve your Fan-curve // if you have a reference-card you may consider buying and after-market cooler like Accelero Mono Plus ( https://www.youtube.com/watch?v=zU7BibxgQSM )

**Comment by ivanquirino** [comment]
@Benman2785 I know it beats, it beated for me until 2.1.3, I could record without any problems. Superb quality, high fps, and encoder overloads didn't crash anything. Now I've got a Ryzen 5 1600X I can record 60fps using x264 too, just crank up the bitrate.

**Comment by Xaymar** [comment]
More than 7 days have passed since the last reply, closing.
