### ISSUE TITLE
2.1.3 Still shows "Encoder Overload"

### ISSUE THREAD

**Issue by Saymite** [Xaymar/OBS-AMD-Advanced-Media-Framework#244]
Since the last ticket #225 is closed and I cant re-open it I'll have to make a new one.

So I've still got the same problem, and I'm really sorry for bothering you. 
I deciced to format my PC to see if the problem was with drivers or something not related to the plugin, unfortunatly it seems that wasnt the case.

The same issue pressists , "Encoder Overload", shows up at any of the presets and video looks to be 1-2fps max.

Speccy : https://hastebin.com/hupisoruge.sql
Latest OBS and plugin version used

log ; https://gist.github.com/05eea637cfe43c1994a0d19e2db56503

From looking at the log seems that AMF Repeat Code 24 is new.

**Comment by Xaymar** [comment]
Your GPU is actually telling us that it can't encode faster and there's quite literally nothing I can do anymore. What you can try now is:

- Reduce to Quality Preset Speed (CQP looks the same for all Quality Presets!)
- Disable VBAQ and Enforce HRD
- Set Queue Size to 1 and then work up from there (it's maximum is 32 for cards with lots of GPU memory).

**Comment by Xaymar** [comment]
Oh and you also have to keep in mind that the results on the wiki are quite literally the best that could happen. They're done with Constant Bitrate at 3500kbit, which has a much lower impact on GPU throughput than Constant QP has.

**Comment by Saymite** [comment]
Yeah, no cigar, even 3500 CBR showed that, but I have seem to found the reason for the issue,

Clock Speeds, apparently the 280x as a bug in which it locks itself to 950/1500 and that makes the encoder overload, on the other hand if I applied any Overclock the Encoder Overload would appear too.

I've successfully recorded with the Indistinguishable preset @60 at stock speeds, 

https://gist.githubusercontent.com/anonymous/1ef0a15d5f97ac81b19971e97b957c5b/raw/5d560800afd47dd8a26b29d7f55e12b546dba086/2017-05-16%252009-07-09.txt

LGTM  frame duration is around 16ms

Thanks for your help again, you should add "Remove any Overclocks" to the troubleshoot guide :P

**Comment by Xaymar** [comment]
> Thanks for your help again, you should add "Remove any Overclocks" to the troubleshoot guide :P

It used to be on there, don't know how it got lost in the redesign. I've added it to the FAQ now: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Frequently-Asked-Questions#q-the-message-encoding-overloaded-shows-up-even-though-it-used-to-work-correctly
