### ISSUE TITLE
Question: can someone explain Target Bitrate vs Peak Bitrate when using VBRLAT control method?

### ISSUE THREAD

**Issue by ivanquirino** [Xaymar/OBS-AMD-Advanced-Media-Framework#245]
I keep target bitrate at 30000 and peak bitrate at 28000. I chose 30000 because that's what AMD's ReLive sets to you at it's "High" preset. Which is 3 times the default 10000 from the plugin, so I multiplied the peak bitrate by the same amount. If someone can explain what is the peak bitrate and how to set it, I would be grateful.

**Comment by Xaymar** [comment]
From what I know, VBR only uses Target Bitrate, I've never seen it care about Peak Bitrate.

**Comment by ivanquirino** [comment]
So, that's just an option provided by the GPU encoder?

**Comment by Xaymar** [comment]
Yes. I don't know if it's a bug or intended that it practically does nothing.

**Comment by ivanquirino** [comment]
Thank you, @Xaymar!

**Comment by Xaymar** [comment]
I have asked Mikhail about how Peak Bitrate works in VBR. Basically it is controlled by the VBV Buffer Size, so a bigger VBV Buffer also means that it can peak more while a smaller one means that it will keep the target bitrate more. Hope this clears it up.
