### ISSUE TITLE
How To Tell Version Used

### ISSUE THREAD

**Issue by SirJaxxy** [Xaymar/OBS-AMD-Advanced-Media-Framework#247]
I'm just wondering if there is a why to identify which version we have in our OBS install?

**Comment by Xaymar** [comment]
You can find the installed version in the OBS log file. Just [open the log file](http://cdn.xaymar.com/private/2017/05/21/16/obs64_2017-05-21_16-08-57.png) and look for something like this:

```
16:07:53.102: [AMF] Version 2.1.4 loaded (Compiled: 1.4.2.0, Runtime: 1.4.2.0, Library: 1;4;2;0;17.10.2711.1021;201705171616;CL#1410780).
```

The first part ("[AMF] Version 2.1.4 loaded") is the installed plugin version, the next part ("Compiled: 1.4.2.0") is the AMF SDK it was compiled against, then comes the driver SDK version ("Runtime: 1.4.2.0") and finally the actual Library (DLL) loaded ("Library: 1;4;2;0;17.10.2711.1021;201705171616;CL#1410780"). The first two are used to identify what exact version is being run while the last two are used to identify the driver its running on.

**Comment by RytoEX** [comment]
@Xaymar Could you elaborate on the Library string a bit more?  I'm unfamiliar with AMD version numbers/strings.  You said:

> finally the actual Library (DLL) loaded ("Library: 1;4;2;0;17.10.2711.1021;201705171616;CL#1410780"). The first two are used to identify what exact version is being run while the last two are used to identify the driver its running on.

Which parts of the Library string correlate to which components (plugin, AMF SDK version, driver SDK version, driver version running, etc.)?  Also, if I split the string by semi-colons, there's more than just four parts.  Which parts are you referring to in your comment above when you say "first two" and "last two"?  Thanks!

**Comment by Xaymar** [comment]
> [AMF] Version 2.1.4 loaded (Compiled: 1.4.2.0, Runtime: 1.4.2.0, Library: 1;4;2;0;17.10.2711.1021;201705171616;CL#1410780).

"Version 2.1.4" is the plugin version, "Compiled: 1.4.2.0" is the AMF SDK compiled against, "Runtime: 1.4.2.0" is the AMF Runtime on the system and "Library: (long string)" is the runtime identity. The runtime identity allows you to pinpoint what exact driver is being run as it is usually different for each release.

**Comment by Xaymar** [comment]
More than 7 days have passed since the last answer here, closing.
