### ISSUE TITLE
Encoding speed affected by overclocking?

### ISSUE THREAD

**Issue by max20091** [Xaymar/OBS-AMD-Advanced-Media-Framework#249]
I just noticed when I overclocking my GPU, AMD AMF is always overloaded. Is there anything I can do to overclocking my GPU without affecting encoding speed?

**Comment by Xaymar** [comment]
No.

**Comment by max20091** [comment]
I don't know if this is overclock isssue or not because I overclocked again and it doesn't happen anymore.
Anyway, this is the log file: 
[2017-05-25 07-17-57.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1027963/2017-05-25.07-17-57.zip)

**Comment by Xaymar** [comment]
You have the issue that you're being affected by #228, which is fixed in an upcoming build. Don't set Keyframe Interval lower than 1 until then.

**Comment by max20091** [comment]
oh, so it's fine then. I will close this one. Problem solved.
