### ISSUE TITLE
Very poor quality at 1900kbit/s. "Flickering"

### ISSUE THREAD

**Issue by razorlikes** [Xaymar/OBS-AMD-Advanced-Media-Framework#25]
The quality is very bad altough I have my bitrate set to 1900kbit/s. It's wierd, somehow one frame looks very bad and the next one is okay. I don't know how to explain this, so i uploaded a video of it.

You need to download the files to really see the effect, because of googles video transcoding.
https://drive.google.com/open?id=0B1y2xDp8JscndHByMjZKTUZVaGM  (VBR)
https://drive.google.com/open?id=0B1y2xDp8JscnLWVHU1JZQjF6VTA  (CBR)

Here are my settings. I set the recording encoder to use the stream encoder.
http://imgur.com/a/1I2uU

I am currently using the 16.7.3 driver on a 64bit Windows 10 Pro. This happened with all versions of the plugin I tested till now. I have a R9 390, a FX 8350 and 12GB of DDR3 1600 RAM.

**Comment by wazerstar** [comment]
set number of b-pictures to 0 not -1

also try idr frames 120 and gop size to the number of your recording fps.

**Comment by razorlikes** [comment]
Setting Number of B-Pictures to 0 helped, thanks!
GOP Size is set to my recording FPS and IDR Frames are set to 60 since Twitch wants you to have a 2 second keyframe interval. Or am I wrong here?

**Comment by wazerstar** [comment]
This is mine for twitch. - still testing and helping out xaymar

http://prntscr.com/c3osru

**Comment by CKannas** [comment]
Hi all,

I'm using Xaymar's OBS AMD Media Framework for a couple of days now.
First let me thank Xaymar for his work!

My setup has an AMD Athlon 860K and an MSI R7 370 2GB Gaming OC.
The settings I use for OBS (0.15.4) is a mixture of Xaymar's tested
configuration and the suggested configuration from the OBS VCE fork, mostly
for the values of QP (https://community.amd.com/thread/198392 and
https://obsproject.com/forum/threads/obs-branch-with-amd-vce-support.13996/
).

For streaming my games at Twitch I downscale from 1080p 60FPS (VSync
enabled) to 480p 30FPS using CBR and the configuration is:

http://prntscr.com/c3x5yn
http://prntscr.com/c3x6ff

Note: I have a 2Mbits upload line.

Last night's streaming result (skip to 00:27:00 to have sound :/ I had it
muted by mistake): https://www.twitch.tv/nobodyhells/v/82679089

I have a configuration for 720p 30FPS mostly for streaming programming
related content which I haven't tested much...
The difference is only in target bitrate from 1600 Kbps to 1700 Kbps, which
I know is not enough for 720p streaming, but I just want clearer image.

When I had the default -1 value for QP variables the output was really bad
during movement: https://www.twitch.tv/nobodyhells/v/82424814

​Best Regards,​

Christos

Christos Kannas

**Comment by Xaymar** [comment]
@razorlikes What you're experiencing is known as the broken IDR problem - IDR-Frames just overwrite the I-Frame and you don't get any I-Frames for some reason. Also the Keyframe distance is further down and called IDR-Period, which is set in Frames. GOP Size is meant to further restrict or widen the bitrate range over a specific amount of frames.

@CKannas You have the same issue as many others, set Number of B-Pictures to 0 and Reference to B-Frame to Disabled.

**Comment by hymccord** [comment]
I also had to set my B-Pictures to 0 to get the blocking/flickering to go away.

@Xaymar Does this IDR period refer to how many I-Frames there have been since the last IDR or just how many frames in general?
It shouldn't be an issue to have every I-Frame to be an IDR frame.

**Comment by Xaymar** [comment]
IDR frames are keyframes. If you find it useful to store an entire keyframes for each i frame to ahead, but don't blame the plugin for quality :p

**Comment by hymccord** [comment]
IDR frames shouldn't be any bigger than a regular I-frame, they just prevent P and B frames from referencing before the IDR frame which would make a larger file size.

My first question remains about IDR period. Say I'm recording at 45FPS with 60GOP and a 30 IDR period. Which is correct?
1. IDR frames are every 1800 frames because I-Frames come at the beginning of GOP and every 30 I-Frames is a IDR (60/45*30 sec or every 45 seconds)
2. IDR frames every 30 frames (or every .66 sec)

**Comment by Xaymar** [comment]
@InKahootz 
If you're recording at 45 fps with 60 GOP and a 30 IDR Period, you get a IDR frame every 30 frames. So 2 would be correct here.
If you have any further questions about how AMF works, please direct them at AMD and their developer forum.

**Comment by Xaymar** [comment]
RX 4xx sets the B-Frames to 0 by default and refuses to change this setting, so we're most likely looking at something that AMD is now aware of. Let us hope that Media SDK 1.2 (or whatever it is going to be called) will fix these issues.

Edit: 1.2.0pre4 does a lot for the quality at lower bitrates, see these example files:

R9 285: http://cdn.xaymar.com/private/2016/08/2016-08-12%2016-24-31.mkv  
RX 480: http://cdn.xaymar.com/private/2016/08/2016-08-13%2015-52-05.mkv

Please remember that you can't expect the same quality from a hardware encoder that you get from a software encoder at a certain bitrate.

**Comment by Xaymar** [comment]
1.2.0rc1 should mostly fix this. Please report back if you have any issues.

**Comment by hymccord** [comment]
Everything works awesome on Quality: Speed.
http://imgur.com/uYPUffr.png

When I set to None, Balanced, or Quality then I get what looks like some light random static all over the image. I'm happy with it though.

**Comment by Xaymar** [comment]
Try disabling the Deblocking Filter, that seemed to cause some issues for some tests on my end.

**Comment by Xaymar** [comment]
This issue, similar to many others, will most likely be fixed by the new SDK. I'm closing this as there is no further work being done on the Media SDK version.
