### ISSUE TITLE
Recording works but Streaming does now ... advice?

### ISSUE THREAD

**Issue by mlwiles** [Xaymar/OBS-AMD-Advanced-Media-Framework#251]
We are trying to get OBS 18.0.1-ftl.0.9.4 (64-bit, windows) functioning with v2.1.6.  Please advise, thanks in advance.

We are recording without issue, but when we start to stream we are getting error message:
Failed to start streaming
Starting the output failed,  Please check the cog for details

Log file contains: <maintainer cut>

**Comment by Xaymar** [comment]
Please don't post the log contents, instead attach the log itself. The maximum file size is 4-6 MB and you can easily get below that if you just use Winrar or 7-zip.

Also it looks like your issue with with the FTL opus encoder, nothing i can do about that:

```
16:13:33.472: error: Specified sample rate 44100 is not supported
16:13:33.472: [FFmpeg opus encoder: 'Track1'] Failed to open opus codec: Invalid argument
...
16:14:00.324: error: Specified sample rate 44100 is not supported
16:14:00.324: [FFmpeg opus encoder: 'Track1'] Failed to open opus codec: Invalid argument
...
16:14:34.710: error: Specified sample rate 44100 is not supported
16:14:34.710: [FFmpeg opus encoder: 'Track1'] Failed to open opus codec: Invalid argument
```

**Comment by Benman2785** [comment]
why use the old OBS?

**Comment by Xaymar** [comment]
@Benman2785 FTL is the Beam.pro (pre-microsoft) fork of OBS.

**Comment by max20091** [comment]
Well, Opus is not supporting 44.1khz, maybe you need to move to 48khz or switch to another audio codec to solve the issue 😉

**Comment by Xaymar** [comment]
Author of the issue has not replied for 7 days, I'm considering this issue abandoned and will close it.
