### ISSUE TITLE
(Win10 Bootcamp) Can't find AMD Advanced Media Framework Encoder in OBS

### ISSUE THREAD

**Issue by cancoel** [Xaymar/OBS-AMD-Advanced-Media-Framework#253]

**Comment by Xaymar** [comment]
```
03:03:43.618: [AMF] Encountered Exception during AMF initialization: Unable to load 'amfrt64.dll', error code 126.
```

Your driver does not have the AMF runtime.

**Comment by cancoel** [comment]
how can i add AMF runtime?

**Comment by Xaymar** [comment]
By installing the latest AMD driver with a supported GPU.

**Comment by DetectiveBurning** [comment]
@saker2 Were you able to get it? I have the same problem. My Graphics card is AMD Radeon R7 450

**Comment by DetectiveBurning** [comment]
@Xaymar Where can I download my latest AMD Driver?

**Comment by Benman2785** [comment]
@DetectiveBurning
maybe from AMD website?

but i think your R7 450 cant use VCE - due to the low-profile cooler - at least its a GCN 1.0 card
maybe consider upgrading to a RX 460 or 560 (when their prices come down again)

**Comment by max20091** [comment]
According to AMD website, R7 450 doesn't have VCE so it doesn't work, only R7 455 have it.
Source: http://www.amd.com/en-us/products/graphics/desktop/oem/r7

**Comment by Xaymar** [comment]
More than 7 days have passed since the last user interaction, so this is considered solved.
