### ISSUE TITLE
Encoder setting not appearing in OBS

### ISSUE THREAD

**Issue by MarkusG** [Xaymar/OBS-AMD-Advanced-Media-Framework#255]
# System Specifications/Software Versions #
* Motherboard - MSI H81M-P33
* CPU - Intel i5-4570
* GPU - Radeon R9 280
* RAM - 8GB DDR3
* OS - Windows 10 Pro
* OBS Studio 19.0.2
* Plugin version 2.1.6 hotfix 3
* Radeon Software Version 16.6

### [Log (starting at AMF messages)](https://gist.github.com/MarkusGordathian/00a672f171112d2cc040defce2c3d882#file-log-txt-L38) ###

# Issue #

The encoder list only contains Software (x264) and Software (x264 low CPU usage preset...). From what I can tell from the log, my GPU isn't supported, but according to [the wiki](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Hardware-Support) the R9 280 supports VCE 1.0.

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

-----

Especially read step 2.

**Comment by MarkusG** [comment]
My bad, my drivers stop auto-updating. Thanks for pointing that out. Updating to 17.4.4 resolved everything.
