### ISSUE TITLE
R9 280 speed test result

### ISSUE THREAD

**Issue by FluffyDiscord** [Xaymar/OBS-AMD-Advanced-Media-Framework#257]
results taken on MSI R9 280 GAMING 3G
driver 17.6.1

results:
http://www119.zippyshare.com/v/8CWx79m0/file.html

Also I have noticed you are missing ultrawide resolutions, so I have added two standart ones

**Comment by Xaymar** [comment]
By ultrawide, do you mean 7:3 (21:9)? I have not included these as their scores are usually very similar to 8:5 (16:10) or 16:9 ones. You've only added 2560x1080 as far as i've seen, which isn't supported by your card.
