### ISSUE TITLE
Encoder does not show up in OBS Studio

### ISSUE THREAD

**Issue by hus12345** [Xaymar/OBS-AMD-Advanced-Media-Framework#258]
i downloaded all the programs i put the plugins into 64 and 32 whatever and i open obs and my amd is still not in encoder please help ive been up for 2 days trying to fix this :(

-----

i downloaded all the programs i put the plugins into 64 and 32 whatever and i open obs and my amd is still not in encoder please help ive been up for 2 days trying to fix this :(  i have a radeon 8470 hd graphics card

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Benman2785** [comment]
8470 may have NO VCE -> so maybe it wont work with your GPU

try to get a RX460 or better

works with all fullsize GCN cards since HD7750
avoid Low-Profile-Cards

**Comment by max20091** [comment]
Unluckily, this Terascale 3 OEM GPU doesn't have VCE so you can't using hardware encoding.
You should buy at least a RX 460 or better one.

**Comment by Xaymar** [comment]
The HD 8470D is part of the Richland APU (A6) and the Richland APU support VCE 1.0. However the latest driver (17.5.1 and up) is required.

**Comment by max20091** [comment]
I dunno if he means this 8470 (no VCE, rebrand of 6450):
https://www.techpowerup.com/gpudb/1978/radeon-hd-8470-oem
Or this one (have VCE):
https://www.techpowerup.com/gpudb/2001/radeon-hd-8470d-igp

**Comment by Xaymar** [comment]
~~The user specified the 8470D, which is a Richland APU.~~ Correction, the other issue states 8470 HD. If it is a HD 8470, then it does indeed not have VCE: http://www.amd.com/documents/AMD_Radeon_HD_8400_Series_Feature_Summary.pdf

**Comment by Xaymar** [comment]
More than 7 days have passed since the last user interaction, so I will consider this solved.
