### ISSUE TITLE
Issues with Sapphire Radeon r7 250

### ISSUE THREAD

**Issue by Botmon14** [Xaymar/OBS-AMD-Advanced-Media-Framework#260]
I have a Sapphire Radeon R7 250 and it supports VCE(http://prntscr.com/fpywrw).. only problem is that I cant select the "hardware encoding" option in the OBS , it just isnt there 
I can only select x264. Do you know what's the issue?

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Benman2785** [comment]
install latest driver

**Comment by Benman2785** [comment]
@Botmon14 any answer?

**Comment by Xaymar** [comment]
More than 7 days have passed since the last user interaction, so I will consider this solved.
