### ISSUE TITLE
Something is wrong with my RX 580....

### ISSUE THREAD

**Issue by AMDJona** [Xaymar/OBS-AMD-Advanced-Media-Framework#262]
Hey. I thought it was a OBS settings problem, but then i used your benchmark tool. 
Compared to other GPUs, it's extremly bad.
As far as i can tell the H265 look much better than the h264 ones. But i really want to record in h264. Any Idea why my GPU is performing that bad? Relive is not installed.
What i did so far
-Clean reinstalled driver (uninstalled with DDU in safe mode)
-Closed all programms, tryed again
-Asked in OBS forum

Any idea what's wrong? :/
[Asus RX 580 Strix.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1175336/Asus.RX.580.Strix.zip)

**Comment by AMDJona** [comment]
I just checked out results from R9 280.
At 1920x1080 the R9 280 got 310 FPS while my RX 580 only got 120.

my full PC specs
FX 8350 @4.4
16gb ddr3 1600
RX 580 Strix
Samsung 850 Evo 256gb

Update:
I reinstalled windows on another Harddrive for testing. Same results on fresh Windows.

**Comment by Xaymar** [comment]
> I just checked out results from R9 280.
> At 1920x1080 the R9 280 got 310 FPS

Could you upload the speedtest results for the R9 280? My Hardware Support page only lists GCN1/VCE1.0 devices as capable of 88 fps.

As for the RX 580, your results are only slightly worse than the reference results for an RX 480.

**Comment by AMDJona** [comment]
I saw the speed result on the Internet.
I just found out it was some R7 (which is even worse,I guess)
[ResultsH264-R7Bristol.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1177313/ResultsH264-R7Bristol.zip)

Why does the R7 got average of 219 FPS in 1080P while my RX 580 is at 120 ? :(

Also on your wiki i saw the following lines; 
Due to this the plugin is easily capable of encoding at 3840x2160 (4K) with 90 FPS or more1.

Mine can only do 30FPS with speed and 17FPS with Quality preset.
But why is that?

**Comment by Xaymar** [comment]
The card you have is a VCE3.4 card, while the card you are comparing against is a BIOS modded GCN3 (Tonga, Tonga XT) card. The only known cards that can go that high in FPS are the R9 285 and the R9 380, which are GCN3 VCE3.0. Both of those reach a peak speak of ~305 fps.

Your card is not broken, it is correctly hitting hardware limitations.

**Comment by AMDJona** [comment]
Oh, ok.
So if i understand it right, the RX 580 is just weak in AMF performance? 

Is there anything i can do to improve the AMF Performance? I saw overclocking didn't make any differenz...

**Comment by Xaymar** [comment]
It's the same as all other VCE3.4 cards, about equal with VCE3.1 (fury, fury x) but with added HEVC support.

**Comment by AMDJona** [comment]
Ok, so one last question, if i record in h265, I always have to handbrake the files to use them in my Adobe Software/ Sony Vegas. Is there any Codec I can download, so I don't have to Handbrake it everytime ?

**Comment by Xaymar** [comment]
Ask the makers of Sony Vegas about that. All modern editing software supports decoding H265 just fine and Sony Vegas seems to be very stuck in the past.

**Comment by AMDJona** [comment]
Ok thank you very much for your Support!

**Comment by AMDJona** [comment]
If i put the h265 file in After Effects, it's just green. It detects everything correctly (framerate, resolution, HVEC) but it's just a green screen. Any Idea what i did wrong?`

**Comment by Xaymar** [comment]
Are you running CC versions? CS6 has no support for H265 (it didn't exist publicly back then).

**Comment by AMDJona** [comment]
Yeah im running the latest version of CC 2017. Either Premiere or After Effects are working with it. Both Green Screen. But i know the file is okay, because if i encode it with Handbrake it's working. I'm pretty sure it's just a wrong setting in OBS

**Comment by Xaymar** [comment]
This seems to be an OBS problem. If it's the plugin or not is to be tested.

**Comment by Xaymar** [comment]
Tests so far:
- 1280x720, default settings: works correctly
- 1920x1080, default settings: green footage

The same tests with the AMD provided sample however works fine, so i'm not sure what's wrong.

**Comment by AMDJona** [comment]
Hmm :/ Pls text me if you got a fix.
Meanwhile im just recording x264 in 1080 120 or 720 180 which is working great!(beside some framedrops, because my GPU is at its limits)
Thanks for providing this awesome plugin!

**Comment by AMDJona** [comment]
Any Idea what cause that Green Screen in AE? Even with 360p 30FPS and 1k bitrate i get this Green Screen in AE or Premiere. File is fine when played back with VLC

edit:
Fixed. I don't really know what was wrong, but i guess i had to deactivate the deblocking filter... 
Jup, even working with 1080 180FPS clips.

2. edit:
It's even working with Vegas 14 now . Stock. Without adding any plugins to Vegas.

**Comment by Xaymar** [comment]
> We also need an upgraded ffmpeg. At the moment it reorders HEVC bitstreams wrong, leaving users with HEVC footage that can't be played back by reference decoders and requires either transcoding or a less strict decoder.
> 
> Quoting AMF developer Mikhail for this:
> 
> > first IDR frame has wrong order of NAL units. It has: VPS, SPS, PPS, AUD, VPS, SPS, PPS, IDR while it should have: AUD, VPS, SPS, PPS, IDR.

From the 2.2.0 PR: https://github.com/jp9000/obs-studio/pull/981

**Comment by Xaymar** [comment]
I've reported this issue to AMD, see #265.

**Comment by AMDJona** [comment]
Ok, thank you.

**Comment by Xaymar** [comment]
Issue is supposedly not caused by the encoder according to AMD, so not much I can do.
