### ISSUE TITLE
Feedback v2.2.0 with 17.7.2

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#264]
hey - now we can use 2-Pass (PrePass)
Xaymar - thank you again for your good work ;)

https://www.mediafire.com/?51nq129708r7r0o
https://www.youtube.com/watch?v=HoWR2bese-A

this is with "Twitch-Preset" and custom buffer + enabled OpenCL
https://www.mediafire.com/?fojvznpswak2jy5

**Comment by FluffyDiscord** [comment]
neat
