### ISSUE TITLE
H265/HEVC: Deblocking Filter causes green/grey/corrupt frames in Premiere Pro, After Effects and other strict decoders

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/OBS-AMD-Advanced-Media-Framework#265]
Issue for tracking purposes, this seems to be an AMD Driver bug.

### Related Links:
* AMF Issue: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/103
* Mantis Issue: https://obsproject.com/mantis/view.php?id=972

**Comment by Xaymar** [comment]
Workaround applied in 2.2.0+, waiting on AMD to fix it.

**Comment by Xaymar** [comment]
Apparently not an actual issue with the encoder. Behaviour can't be reproduced in x265 or nvenc.

**Comment by donnayarbrough** [comment]
Another method is to use iDealshare VideoGo to convert HEVC to Adobe Premiere more supported format like MPG, AVI, WMV, etc 
Here is the step by step guide: https://www.idealshare.net/video-converter/import-hevc-to-premiere-pro.html
