### ISSUE TITLE
H265/HEVC: Crash on stopped streaming/recording

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/OBS-AMD-Advanced-Media-Framework#266]
A regression bug caused by AMD Driver 17.7.2.

### Relevant Links:
* AMF Issue: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/102
* Mantis Issue: https://obsproject.com/mantis/view.php?id=973

**Comment by max20091** [comment]
anyway to avoid this bug? My GPU doesn't have any other driver before 17.7.2

**Comment by Xaymar** [comment]
Wait for AMD to fix it.

**Comment by kamild1996** [comment]
17.8.1 didn't fix the issue :(

**Comment by Benman2785** [comment]
@kamild1996 be aware that it often takes quiet some time for DriverDevs to fix such things ;)

**Comment by Benman2785** [comment]
17.8.2 is here - tested! NOT fixed!

**Comment by Xaymar** [comment]
Fixed by AMD Driver 17.8.2
