### ISSUE TITLE
VCE 3.4 AVC vs HEVC

### ISSUE THREAD

**Issue by max20091** [Xaymar/OBS-AMD-Advanced-Media-Framework#267]
Is HEVC faster than AVC? I want to buy a RX 550 and I very curious to know if HEVC is faster than AVC in some case

**Comment by Xaymar** [comment]
https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Hardware-VCE3.4#rx-480

See for yourself

**Comment by max20091** [comment]
I know but sometimes it faster, sometimes it slower
Like at 2560x1440, quality preset AVC got 32 FPS and HEVC got 71 FPS, this make me confuse
Edit: is that result is accurate?

**Comment by Xaymar** [comment]
HEVC is faster than AVC, you can see that on the highest resolution (3840x2160). The differences in lower resolutions come from differences in how things are encoded. At 2160p, 1440p, 1080p, 720p, 540p, 480p, 360p, 240p and any other resolution that does not go into the emulated/cropped resolutions, HEVC is faster and better than the best quality that AVC on AMD offers you.

**Comment by max20091** [comment]
ok, thanks. I will close this one :)
