### ISSUE TITLE
Getting overload with AMD

### ISSUE THREAD

**Issue by wbgsbroadcasting** [Xaymar/OBS-AMD-Advanced-Media-Framework#268]
I am using an AMD RX580 and getting overload any ideas to why?

**Comment by Benman2785** [comment]
we need MUCH more info - pls use https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Benman2785** [comment]
Your issue does not follow Xaymar's [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by wbgsbroadcasting** [comment]
Also sometimes your codec wont broadcast at all yet x264 does explain that one? Here is what I have.

2X Xeon 5570 2.93ghz
12gig ddr3 ecc ram
RX580 8gig
OBS Version: 20.0.1
Driver Version: 17.7.2
AMD plugin version:2.2.3


Also telling me my issue does not follow anything really don't help me at all so yeah. Current log below to help you.

https://gist.github.com/445ed896c80275c717b2d252a28f52b0

The issue is I sometimes get overloading issues and all the time the codec wont broadcast to sites just a grey square and nothing. Yet X264 works like a charm I am baffled over this and need help.

**Comment by Xaymar** [comment]
> Also telling me my issue does not follow anything really don't help me at all so yeah. 

The Troubleshooting Guide tells you exactly what and how to post an Issue report, includes FAQ entries with common solutions and also shows you how to create proper log files. So yes, *it does help you*. If you can't deal with having to read something before making an issue report then you are completely wrong here.

> Current log below to help you.

The log wasn't created with the instructions in the Troubleshooting Guide, so please follow the Troubleshooting Guide. It does however show to actual issues with the encoding, all streams were stopped by you or failed to connect to Mixer.

**Comment by Benman2785** [comment]
@wbgsbroadcasting 
dude to help you we need to know what is happening on your system - thats why we need the correct log

**Comment by wbgsbroadcasting** [comment]
Guys your coded is missing modules if you only read the log you would see this and fix this issue in the next version.

**Comment by razorlikes** [comment]
Well, if you are missing modules, have you tried to reinstall OBS and the plugin?

**Comment by wbgsbroadcasting** [comment]
obs runs fine its the plugin missing modules yup. I was not missing anything before the plugin was installed.

**Comment by razorlikes** [comment]
As I said, have you tried reinstalling OBS and the plugin? If you don't do the things people tell you to fix your problem, good luck fixing it...

**Comment by wbgsbroadcasting** [comment]
I already done that on top of a reinstall i have said this already I am sick of repeating my self.

**Comment by Xaymar** [comment]
The plugin is not "missing modules". Be clear about your actual issue. And if you are "sick of repeating yourself", the door is over there.

**Comment by wbgsbroadcasting** [comment]
So this is how you treat all the people with issues good luck on development.

**Comment by razorlikes** [comment]
Look, I'm sorry to tell you this but you are the one that's not helping here. Xaymar told you what to do, **you** need to deliver what's asked from you so he can help you fix your problem. Looking at your profile on GitHub I can see you have another issue open at the OBS FTL repo where you were asked to deliver a log for your problem 7 days ago. You never even responded there.

I'm sorry but no one can help you if **you** don't cooperate

**Comment by wbgsbroadcasting** [comment]
I do respond as i did here yet your complete dicks about everything and have no respect and resort to hate if you look in this thread above i posted all the specs and the obs log proving obs is missing modules so go figure you just don't wanna read or anything.

**Comment by razorlikes** [comment]
Have you ever thought about the possibility that your missing modules aren't the issue here?
The troubleshooting guide also says to include "The latest/current log file from Open Broadcaster Software Studio showing the Issue (start OBS with --verbose --log_unfiltered --unfiltered_log as parameter and tick the Debug option in the encoder!)"
Which you didn't. Your log simply doesn't contain the needed information and Xaymar told you exactly that!

I think you are the one who doesn't "wanna read or anything" here...

**Comment by AMDJona** [comment]
Wow. ... I suggest adding a banning feature in OBS. This is just like:
Mom: I think I have cancer
Dad: hmm if you think so go to a doctor.
Mom: Are you fucking retarded ? Oh yeah btw did I already tell you , I think I have cancer.


Why don't you just send your advanced log ? Now it's too late anyways

**Comment by wbgsbroadcasting** [comment]
They said they need more info i gave it to them then they still act like complete dicks.

**Comment by razorlikes** [comment]
Have you even tried to read my comment?

**You provided the wrong log!**

**Comment by AMDJona** [comment]
Dude you have to be more patient and respectful! It's their free time! There don't getting payed by you. They don't have to help you, they just do it because there very kind.

**Comment by wbgsbroadcasting** [comment]
Well I was paitent until i was disrespect by this community so yeah.

**Comment by Xaymar** [comment]
To save everyone from this pretentious asshole, I'll close this issue now. If you make another issue and behave the same i will ban you.

**Comment by CKannas** [comment]
@wbgsbroadcasting, the log you provided does not have the debug information Xaymar wants to see.

But from lines 173 and 174 from the log you submitted shows that you try to stream to an empty URL....

Bottom line, enable debug mode, repeat your actions and send the log.

**Comment by max20091** [comment]
@wbgsbroadcasting 
Do you mean this?

```
17:29:37.243: Required module function 'obs_module_load' in module '../../obs-plugins/32bit/libcef.dll' not found, loading of module failed
17:29:37.243: Required module function 'obs_module_load' in module '../../obs-plugins/32bit/libEGL.dll' not found, loading of module failed
17:29:37.244: Required module function 'obs_module_load' in module '../../obs-plugins/32bit/libGLESv2.dll' not found, loading of module failed
```


This part is not related to AMF module or having any impact with both OBS and AMF so you can skip this.
You need to do a record test before doing a stream so it's better to analyze encoder problem.
I also recommend using H265 rather than H264 for better performance and quality (before doing that then downgrade your driver to 17.7.1, AMD forgot to fix this in 17.7.2 and also newer 17.8.1 too)

**Comment by wbgsbroadcasting** [comment]
Yes Max that is what I mean yup.

**Comment by Benman2785** [comment]
@wbgsbroadcasting dont you get it - without the log we ducking cant see why this is happening - so its you who stops us from helping you - and after 4 people asking you to provide correct log you simply say we "disrespected" you...

**Comment by wbgsbroadcasting** [comment]
What log do you want I gave you the only log holy the OBS log is the one you need right thats the one everyone uses to trouble shoot plugins and all that stuff so yeah.

**Comment by Xaymar** [comment]
1. Are you using Simple or Advanced mode to stream? If you don't know how to tell, the easiest way to tell is if you have a lot of options on multiple tabs vs only a few options and the encoder is called "Hardware (AMD)".
2. Your problem is not missing modules, those aren't even part of the plugin or even shipped with them. Those are from Browser Source.
3. You are streaming to an empty URL.

**Comment by wbgsbroadcasting** [comment]
You say i am yet I am not lol, I put my info in the easy fix is Xsplit lol peace out.

**Comment by Xaymar** [comment]
Alright, you won't be missed.

**Comment by Benman2785** [comment]
@wbgsbroadcasting people even told you what log we need here in that thread - so you even hadnt had to read Troubleshooting guide

the fucking log you provided ISNT THE RIGHT LOG - because it misses all the stuff from "PATH-to\OBS Studio\bin\64bit\obs64.exe" --verbose --log_unfiltered --unfiltered_log // with checked debug option in plugin

are you that fucking stupid?
