### ISSUE TITLE
[Overwatch] Encoder Always Overloaded

### ISSUE THREAD

**Issue by Xbye** [Xaymar/OBS-AMD-Advanced-Media-Framework#269]
It's been a while(months) since I've played/streamed Overwatch, but I don't remember constantly getting encoder overloaded.

I've used the default Twitch settings (2500 BR), and modified things like multi-threading or queue size. Constantly keeps saying encoder overloaded. Even if I cap my FPS at 120 in-game (I have 144hz monitor) it still does it. Even lowering the render scale from 100% to 75%. Using 1080p in-game. Streaming 540p.

**LOG**: https://gist.github.com/anonymous/730dcc41430a998d729d6c232a7f984d

If you need something more thorough please let me know. Kind of frustrated right now.

EDIT: Want to add, this is the only game I'm having this issue with. So far.
EDIT(2): Fixed log, obsplz.

**Comment by Xaymar** [comment]
That log has to be one of the least useful ones I've seen, it's just the warning message that obs is already running. :D

**Comment by Xbye** [comment]
Hey @Xaymar !

Yeah, I literally just saw that. I quickly made another log. OBS keeps crashing for some reason and refuses to close, ect. I was in the process of getting ready to update my AMD drivers to see if that'll fix the issue.

**Comment by Xaymar** [comment]
```
10:25:15.024: Output 'adv_stream': Number of lagged frames due to rendering lag/stalls: 77 (3.9%)
10:25:15.187: Output 'adv_file_output': Number of lagged frames due to rendering lag/stalls: 73 (3.7%)
10:25:15.257: Video stopped, number of skipped frames due to encoding lag: 72/1998 (3.6%)
```

First off, you have both rendering and encoding lag. Rendering lag happens if the game takes too much GPU time (uncapped framerate, too high graphics settings) while Encoding lag happens due to GPU congestion or too high encoding settings - or by using Master View Mode without actually needing any of the things Master View Mode offers you.

```
10:24:41.745: [AMF] [H264]<Id: 5>     Multi-Threading: Enabled
```

Disable Multi-Threading, there is absolutely no reason to ever use this unless your CPU is on Pentium speed levels. This is only a compatibility option and not to be used if you do not have any actual issues.

```
10:24:41.745: [AMF] [H264]<Id: 5>     Format: NV12 709 Full
```

If you are streaming, no browser currently supports 709 Full and all browsers assume 601 Partial. Only Edge correctly differentiates between Partial and Full output.

```
10:24:41.746: [AMF] View Mode 'Master' is active, avoid giving anything but basic support. Error is most likely caused by user settings themselves.
```

Well yeah.

**Comment by Xbye** [comment]
> or by using Master View Mode without actually needing any of the things Master View Mode offers you.

So just having "master" enabled in general, even without tinkering with anything, can cause issues?

>Disable Multi-Threading, there is absolutely no reason to ever use this unless your CPU is on Pentium speed levels. This is only a compatibility option and not to be used if you do not have any actual issues.

I toggled this on and off, issue wasn't fixed. I like to have it on because my mouse movement feels noticeably more responsive even though I'm on a 4790k.

>If you are streaming, no browser currently supports 709 Full and all browsers assume 601 Partial. Only Edge correctly differentiates between Partial and Full output.

I am recording locally with Intel's Quicksync as well. I upload my content to YouTube occasionally. Would it just be pointless to have 709 FULL even for YouTube?

>Well yeah.

I don't normally go into Master. I usually just do Advanced but was in a rush to quickly replace the log. Making sure I had everything reset to defaults first.

I just now installed the latest drivers. Will see if the issue persists.

**Comment by Xaymar** [comment]
> So just having "master" enabled in general, even without tinkering with anything, can cause issues?

Yes.

> I toggled this on and off, issue wasn't fixed. I like to have it on because my mouse movement feels noticeably more responsive even though I'm on a 4790k.

This will not have any effect on mouse movement, as the waiting time is identical. The only difference it actually does is where the frames are submitted or retrieved from, which will not change system behavior. Keep it off unless you are actually running an ancient CPU.

> I am recording locally with Intel's Quicksync as well. I upload my content to YouTube occasionally. Would it just be pointless to have 709 FULL even for YouTube?

If you want to have correct stream quality, then yes it is pointless - given that there's no visual difference after YouTube murders your videos with compression.

**Comment by Xbye** [comment]
Here is two more logs:

**Without Multi-threading - Simple View** : [LOG](https://gist.github.com/anonymous/6c716fa762d785bae654855f6f7092a2)
**With Multi-Threading - Advanced View**: [LOG2](https://gist.github.com/anonymous/5e434ff9d5790fde99b35eaf1a0676b0)

I'm still going to keep multi-threading on because I'm still getting a noticeable improvement in mouse movement. Regardless, the issue isn't solved with it off anyways.

I changed back to 601 and Partial as well, no dice.

These are my Overwatch settings: [Discord Image](https://cdn.discordapp.com/attachments/310279364879187968/344908232000798731/20170809111534_1.jpg)

Lowering render scale doesn't seem to fix the issue, only lower the amount of times it occurs. Same with lower frame-rate cap instead of 300 FPS framerate cap.

Do you know if RadeonMod ([Image](https://cdn.discordapp.com/attachments/310279364879187968/344908810390863876/unknown.png)) could be interfering with the encoder? The only settings I have changed are Main3D [0x3300 -> 0x3100] , Main3D_DEF [3 -> 1] and StutterMode [2 -> 0]. Everything else is AMD defaults.

Is this just perhaps, the limit of the RX480 or at least, my RX480? I also don't remember having these issues when I was using the AMD encoder to record instead of stream, and I was recording 1080p@60 Speed.

**Comment by Xbye** [comment]
I _seem_ to have solved the issue!

**LOG - Multithread**: https://gist.github.com/8dd345e7100671c9511a26da25e839f2

I went into the gaming settings and disabled **Game Mode**. I've had it enabled all this time since someone did some slow-motion testing and discovered it reduced input lag. However if I can't stream(Overwatch) with it, then I can't really have it on. Not sure why game mode is causing the encoder to lag all of a sudden.

Will update this thread if I have anymore issues.

**Comment by Xaymar** [comment]
Now it makes sense why Multi-Threading helped, Game Mode significantly slows everything down as even asynchronous operations block.

**Comment by Xbye** [comment]
Alright I did another test, this one twice as long. No encoder overloaded signs.

I think it's _safe_ to say that **Game Mode** was the reason the error was showing up. You can close this thread if you want 👍

**Comment by Benman2785** [comment]
@Xbye when using "Master View Mode" you have to set everything properly by hand - because the "0" in some cases can cripple the performance ;)

so you should know what you are doing - simply use "Basic" or "Advanced"
