### ISSUE TITLE
Can't achieve lower than QP 18 with "Constant QP" rate control

### ISSUE THREAD

**Issue by ItEndsWithTens** [Xaymar/OBS-AMD-Advanced-Media-Framework#271]
When using the "Constant QP" rate control method, I'm unable to get a QP below 18, though I can if I use CBR/VBR/VBRLAT. I wonder if someone can tell me if this is a bug or just my own stupidity.

Hardware:
Pentium G3258, stock 3.2Ghz (dual core, no hyperthreading, yes I know, bear with me)
ECS H81H3-A3 motherboard
8GB DDR3 1333 RAM
Sapphire Nitro RX460 4GB
120GB OCZ Vector 150 (OS)
2TB Seagate ST2000DL004 (storage)
4TB Seagate ST4000DM005 (storage, recording drive; only 5980rpm but sustains 140MB/s+ sequential write)
Steinberg UR22 audio interface, 1.9.10 64-bit drivers

Software:
Windows 10 64-bit, version 1607 (the Creators Update hasn't hit me yet)
OBS Studio 20.0.1
AMF plugin 2.2.2
Radeon ReLive 17.7.2 (clean uninstall of 17.5.2 beforehand)

Logs:
[bad-2017-08-11 18-53-45.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1219289/bad-2017-08-11.18-53-45.txt)
[good-2017-08-11 18-56-36.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1219288/good-2017-08-11.18-56-36.txt)

In short: when recording, if I use Basic view mode and choose the Lossless preset, or I leave the preset blank and use "Constant QP" rate control with I and P QPs set to 0 (or anything below 18), the resulting encode is QP 18 across the board. If I instead leave Preset blank, use CBR (or VBR, or VBRLAT), and switch to Advanced view mode so I can set the Minimum QP and Maximum QP to 0 (or again, anything below 18), it works just fine. Above you'll find two logs, 'bad' being from a recording using Constant QP with I and P QPs at 0, and 'good' being from CBR with Min/Max QP set to 0.

A longer explanation, if it's helpful:

I've been doing the Let's Play thing for a while now, like everybody and his brother, and earlier this year upgraded my graphics card. I took the opportunity to see if I could do better than Fraps+Audacity for recording, since that had worked well but made audio sync a bit of a hassle. OBS Studio seemed to do the trick (thank God for "Use device timestamps"), and the added benefit of a lossless option satisfied my anal-retentive worries about hardware-accelerated H.264 recording quality.

"Why would you think such a low end CPU and graphics card could even approach 1080p60 lossless with a codec like H.264?" I didn't, at first, but my curiosity got the best of me; after some tinkering (set Above Normal OBS priority, enable OpenCL) and tests with Studio it seemed to be working, at least on the old games I record, e.g. Quake and HL2. Despite some trepidation at the MediaInfo-reported bitrates, which seemed way too low for lossless, I rationalized it like a dope and went on my merry way.

Until a few days ago, when I discovered I hadn't been thorough enough in my initial tests. Something caught my eye in a recording of a recently released Quake map that's intensely red, with lots of high frequency detail, and I did some digging. Namely bringing my original footage into Avisynth+ with FFMS2 and using Tweak(sat=10.0) to crank the saturation all the way up. This clearly accentuates compression artifacts, and I saw them everywhere in this footage. Double checking my settings, I indeed still had my Recording set to use the "Lossless" preset, and the grayed-out dropdowns had both I and P QPs at 0.

I also managed to confirm the QP values of each frame in the recordings. As per [this Doom9 post](https://forum.doom9.org/showthread.php?p=1692797#post1692797), I'm getting the QP of each frame using ffplay, from ffmpeg, by way of the following one liner:

`ffplay.exe -hide_banner -an -debug 1 -loop 1 -autoexit -i "video.mkv" 2> "info.txt"`

That will play the footage once, spitting stats out to a text file, and you can simply scroll through it looking at the "qp: X" lines. If I use a constant QP of 51, the text file shows 51 and the video quality suffers as expected. If I use 30, the text shows 30 and quality improves. Same with 18. But I if I use 15, or 0, the resulting text file shows QP 18 for every frame.

Switching over to CBR encoding, though, and dragging the Min/Max QP sliders all the way to 0, produces a text file that shows QP 0 all the way through. No noticeable impact on my system during gameplay, and buttery smooth 1080p60 footage that can go through the most insane color correction without so much as a whisper of compression artifacts.

The number seems to correspond to what I see [here](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/blob/7644d3cf376ae8abd7b9d9d3d29c0de653f32c34/Source/enc-h264.cpp#L168), where P_QP_MINIMUM gets set, but I'm swinging above my weight as far as analyzing your codebase, so take that with a grain of salt.

Ultimately yes, I understand that the relative merits of capturing lossless footage are up for debate, but I would think the option should still work properly if it's there, and it doesn't seem to. The fact that I can achieve my desired result by coming at it from a different angle, so to speak, is what motivated me to open an issue here. Have I run into some sort of bug in this plugin, or maybe one in OBS? Or am I just using the software all wrong, and there's some simple setting that would make Constant QP rate control work as I'd expect it to?

**Comment by Xaymar** [comment]
Please check the "Debug" option in the encoder settings, right now there is not enough information in the log file to tell what broke and why it broke.

**Comment by Xaymar** [comment]
Reproduced locally. CQP seems to be using Min/Max QP for an unknown reason.
