### ISSUE TITLE
Streaming Upload speed get's limited to ~1000kb/s

### ISSUE THREAD

**Issue by TheRealPrinceVinc** [Xaymar/OBS-AMD-Advanced-Media-Framework#272]
So ever since Version 19.0.3 of OBS I can not stream with the AMF Encoder anymore due to it limiting my Upload to ~1000kb/s.

The codec works fine if I use the 19.0.2 Version of AMF.

I tested this with the newest AMD Driver.

Here are some log files and the OBS Thread that provided a temporarily solution.

https://obsproject.com/forum/threads/my-rate-goes-up-and-down-to-0-kb-s.72758/#post-310217

I currently work around the issue by replacing the 20.0.1 AMF version with the 19.0.2 AMF Version.

![image](https://user-images.githubusercontent.com/31005925/29455778-ce152a5e-8412-11e7-88d1-f57db063dea2.png)
![image](https://user-images.githubusercontent.com/31005925/29455815-f04a0608-8412-11e7-85c3-42f7d7f8077c.png)
[2017-08-18 12-54-43.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1234196/2017-08-18.12-54-43.txt)
[2017-08-18 12-57-33.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1234198/2017-08-18.12-57-33.txt)

When I disable !new network encoding! Issue "gone" but why?
[2017-08-18 12-58-43.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1234202/2017-08-18.12-58-43.txt)

What is the "installed plugin version"? I haven't installed any Plugins just what is build into OBS

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Benman2785** [comment]
btw to replace 20.0.1 is stupid - because it brings a ton of new features and some improvements...

**Comment by TheRealPrinceVinc** [comment]
@Benman2785 what are the greatest features/improvements worth when they don't work for what I need them for?

So since the 19.0.2 AMF does work with streaming and the 20.0.1 AMF does not I would not call it stupid...

**Comment by Benman2785** [comment]
Your issue does not follow Xaymar's [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

its very likely that you did the error and not the new AMF - so please provide logs and follow [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting) and we may can help you...

**Comment by Benman2785** [comment]
ps in "Advanced" OBS settings - disable "new network-code" and "low latency"

**Comment by Xaymar** [comment]
Like Benman said, if you do not follow the Troubleshooting Guide, your issue will be considered invalid and closed in four days.

**Comment by TheRealPrinceVinc** [comment]
@Benman2785 why would those settings be an issue? It wasn't before in version 19.0.2

I just tested it out and indeed, the "issue" is gone when you disable new networking code.

But why does it interfere with the newest Version of 20.0.1 AMF but the previous Version 19.0.2 does not?

**Comment by TheRealPrinceVinc** [comment]
I updated the Troubleshoot post, hope I have not forgotten anything.

**Comment by Benman2785** [comment]
because AMF and "new networking code" of OBS Studio wont work together yet - for that Jim has to work with MikhailAMD
btw you dont need "nnc" - i dont have any advantage by it - and my server runs with low-latency-kernel (what most servers dont - and even shouldnt)

**Comment by TheRealPrinceVinc** [comment]
Ahh

**Comment by TheRealPrinceVinc** [comment]
Whoops hit the wrong button! @Benman2785 Ohhhhh I didn't knew that, I just activated it in the past, cause I want as little delay in my streams as possible for the user interaction. So that was the problem all along?

Could we get a warning message or something popup in OBS that indicates that?

Thanks for your time and have a lovely day.

**Comment by Benman2785** [comment]
"12:54:43.819: [AMF] Version 2.2.2 loaded..."
that is your plugin-version

well OBS says itself that its "new networking code" is experimental - so not for common-use

it will need some time for AMD-, Nvidia-, Intel-DriverDevs to adapt the new OBS code - but as i said; as of today there is no use of it

**Comment by TheRealPrinceVinc** [comment]
Ok, it seems like the issue is "resolved" than ^^

**Comment by Xaymar** [comment]
> it will need some time for AMD-, Nvidia-, Intel-DriverDevs to adapt the new OBS code - but as i said; as of today there is no use of it

This is incorrect. Driver and/or encoder developers do not have to adapt to the new OBS code, OBS however has to adapt to the encoder used. If it works without the experimental stuff then the experimental stuff is still not working right.

**Comment by Benman2785** [comment]
that is what i meant ;)
