### ISSUE TITLE
1440p with AMD h264/AVC encoder impossible

### ISSUE THREAD

**Issue by simonkulessa** [Xaymar/OBS-AMD-Advanced-Media-Framework#273]
Hi,
using OBS for some weeks now I´ve some error since changing my display and the resolution is now 1440p.
When using H264/AVC Encoder (AMD Advanced Media Framework) I now get the following error:

CPU: Intel Xeon X5650
MoBo: ASUS P6T
GPU: R9 390X
HDD/SSD: Samsung 840 Pro 256GB, 1TB Seagate HDD, 500GB WD RE4
Latest OBS
Latest AMD Graphics Driver (17.7.2)
Plugin Version: 2.2.2

> 
21:44:56.806: CPU Name: Intel(R) Xeon(R) CPU X5650 @ 2.67GHz
21:44:56.806: CPU Speed: 3600MHz
21:44:56.806: Physical Cores: 6, Logical Cores: 12
21:44:56.806: Physical Memory: 16374MB Total, 11581MB Free
21:44:56.806: Windows Version: 10.0 Build 15063 (revision: 296; 64-bit)
21:44:56.806: Running as administrator: false
21:44:56.806: Aero is Enabled (Aero is always on for windows 8 and above)
21:44:56.806: Portable mode: false
21:44:56.827: OBS 20.0.1 (64bit, windows)
21:44:56.827: ---------------------------------
21:44:56.828: ---------------------------------
21:44:56.828: audio settings reset:
21:44:56.828: samples per sec: 44100
21:44:56.828: speakers: 2
21:44:56.829: ---------------------------------
21:44:56.829: Initializing D3D11...
21:44:56.829: Available Video Adapters: 
21:44:56.830: Adapter 1: AMD Radeon (TM) R9 390 Series
21:44:56.830: Dedicated VRAM: 4270292992
21:44:56.830: Shared VRAM: 4289781760
21:44:56.830: output 1: pos={0, 0}, size={2560, 1440}, attached=true
21:44:56.832: Loading up D3D11 on adapter AMD Radeon (TM) R9 390 Series (0)
21:44:56.841: D3D11 loaded successfully, feature level used: 45056
21:44:57.608: ---------------------------------
21:44:57.608: video settings reset:
21:44:57.608: base resolution: 2560x1440
21:44:57.608: output resolution: 2560x1440
21:44:57.608: downscale filter: Bicubic
21:44:57.608: fps: 30/1
21:44:57.608: format: NV12
21:44:57.609: Audio monitoring device:
21:44:57.609: name: Standard
21:44:57.609: id: default
21:44:57.609: ---------------------------------
21:44:57.610: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/chrome_elf.dll' not found, loading of module failed
21:44:57.611: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
21:44:57.634: [AMF] Version 2.2.2 loaded (Compiled: 1.4.4.0, Runtime: 1.4.4.0, Library: 1;4;4;0;17.30.1041;201707201852;CL#1437322).
21:44:57.665: [AMF] <Id: 2> Unable to create H265/HEVC encoder, error AMF_ENCODER_NOT_PRESENT (code 36)
21:44:57.704: [AMF] <Id: 4> Unable to create H265/HEVC encoder, error AMF_ENCODER_NOT_PRESENT (code 36)
21:44:57.704: [AMF] [H265/HEVC] Not supported by any GPU, disabling...
21:44:57.713: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
21:44:57.713: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
21:44:57.713: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
21:44:57.714: Failed to load 'en-US' text for module: 'obs-browser.dll'
21:44:57.714: [browser_source: 'Version: 1.29.0']
21:44:57.716: LoadLibrary failed for 'nvEncodeAPI64.dll': (null) (126)
21:44:57.815: VLC found, VLC video source enabled
21:44:57.817: No blackmagic support
21:44:57.856: ---------------------------------
21:44:57.856: Loaded Modules:
21:44:57.856: win-wasapi.dll
21:44:57.856: win-mf.dll
21:44:57.856: win-dshow.dll
21:44:57.856: win-decklink.dll
21:44:57.856: win-capture.dll
21:44:57.856: vlc-video.dll
21:44:57.856: text-freetype2.dll
21:44:57.856: rtmp-services.dll
21:44:57.856: obs-x264.dll
21:44:57.856: obs-vst.dll
21:44:57.856: obs-transitions.dll
21:44:57.856: obs-text.dll
21:44:57.856: obs-qsv11.dll
21:44:57.856: obs-outputs.dll
21:44:57.856: obs-filters.dll
21:44:57.856: obs-ffmpeg.dll
21:44:57.856: obs-browser.dll
21:44:57.856: image-source.dll
21:44:57.856: frontend-tools.dll
21:44:57.856: enc-amf.dll
21:44:57.856: coreaudio-encoder.dll
21:44:57.856: ---------------------------------
21:44:57.856: ==== Startup complete ===============================================
21:44:57.857: Service '' not found
21:44:57.859: All scene data cleared
21:44:57.859: ------------------------------------------------
21:44:57.889: WASAPI: Device 'Lautsprecher (Sound Blaster X-Fi Surround 5.1 Pro)' initialized
21:44:57.899: WASAPI: Device 'Eingang/Mikro (Sound Blaster X-Fi Surround 5.1 Pro)' initialized
21:44:57.955: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds
21:44:58.087: Switched to scene 'LetsPlay'
21:44:58.087: ------------------------------------------------
21:44:58.087: Loaded scenes:
21:44:58.087: - scene 'LetsPlay':
21:44:58.087: - source: 'Spielaufnahme' (game_capture)
21:44:58.087: - source: 'Videoaufnahmegerät' (dshow_input)
21:44:58.087: ------------------------------------------------
21:44:58.199: ---------------------------------
21:44:58.199: [DShow Device: 'Videoaufnahmegerät'] settings updated: 
21:44:58.199: video device: Microsoft® LifeCam HD-3000
21:44:58.199: video path: \\?\usb#vid_045e&pid_0810&mi_00#6&2178b29e&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
21:44:58.199: resolution: 640x480
21:44:58.199: fps: 30.00 (interval: 333333)
21:44:58.199: format: YUY2
21:45:03.932: rtmp-common.c: [initialize_output] Could not find service ''
21:45:03.933: rtmp-common.c: [initialize_output] Could not find service ''
21:45:03.934: rtmp-common.c: [initialize_output] Could not find service ''
21:45:03.935: rtmp-common.c: [initialize_output] Could not find service ''
21:45:04.028: rtmp-common.c: [initialize_output] Could not find service ''
21:45:05.573: rtmp-common.c: [initialize_output] Could not find service ''
21:45:21.586: Settings changed (outputs)
21:45:21.586: ------------------------------------------------
21:45:25.531: rtmp-common.c: [initialize_output] Could not find service ''
21:45:25.542: [AMF] [H264]<Id: 8> <Plugin::AMD::EncoderH264::SetResolution> Failed to set to 2560x1440, error AMF_OUT_OF_RANGE (code 5)

When using downscale to 1080p everything works fine but in native resolution the recording doesn´t start. The graphics card used is an AMD R9 390X. It used to work with my 1080p monitor. Graphics drivers are up to date, OBS Version is up to date, too. Is this error related to AMF or the plugin?
Any ideas?

Best regards
Simon

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

-----

To be exact, read the hardware support page.

**Comment by simonkulessa** [comment]
Mhm ok...so the R9 390 simply doesn´t support 2560x1440 as output resolution due to VCE2? Thats a pity :(

Sorry for creating an issue - my fault.
