### ISSUE TITLE
OBS Crashes as soon as I press Start Stream or Start Recording

### ISSUE THREAD

**Issue by lolerinc** [Xaymar/OBS-AMD-Advanced-Media-Framework#274]
Hardware:
8350 (Overclocked to 4.5)
R9 390 MSI
16 GB of RAM

Software:
Windows 10 Pro Build 1703
OBS 20.0.1
Radeon Software 17.7.2

Already Tried:
DDU My Graphics Drivers
Reinstalling OBS Studio
Install the latest version of AMF encoder (2.2.3)

Issue
OBS Studio opens fine but as soon as I click Start Streaming or Start Recording it  prompts me with the message that OBS has crashed. 

LOG: [Crash 2017-08-20 18-29-43.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1237434/Crash.2017-08-20.18-29-43.txt)

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

1. Please attach a normal log file that shows the exact steps and settings, see the Troubleshooting Guide on how to do that.
2. The crash you are experiencing happens in the driver, which likely means that your Overclock is not stable or that your Driver is in an invalid state and needs to be completely cleanly installed (Restart > DDU Safe Mode Cleanup > Restart > Windows Update > Restart > Install current Driver > Restart).

**Comment by Benman2785** [comment]
your LOG says nothing that we need to know to fix your problem
Crashlogs are most likely for OBS Devs and not for that Plugin - only in rare cases needed here

**Comment by Benman2785** [comment]
@lolerinc 
if you dont post here it will be closes soon...

**Comment by Xaymar** [comment]
This issue has been closed for inactivity.
