### ISSUE TITLE
AMFSpeedTest RX Vega 64

### ISSUE THREAD

**Issue by Glitchvid** [Xaymar/OBS-AMD-Advanced-Media-Framework#275]
Results:
https://s.gvid.me/s/2017/08/21/ResultsH264.7z
https://s.gvid.me/s/2017/08/21/ResultsH265.7z
(H.265 spits out a lot of errors, not sure why)

Hardware:
GPU: AMD Radeon RX Vega 64 Liquid Cooled (RX-VEGMXWFXW)
CPU: i7 6850k @ 4.1
RAM: 32GiB DDR4 @ 3200

Software:
Radeon Software Version - 17.8.1
Radeon Software Edition - Crimson ReLive
Windows Version - Windows 10 (64 bit)
Radeon Settings Version - 2017.0815.1452.24946
Driver Packaging Version - 17.30.1051.1011-170815a2-317200C-CrimsonReLive

**Comment by Xaymar** [comment]
AVC Capabilities:
- Hardware Accelerated
- Maximum Profile: High
- Maximum Level: 5.2
- Max Temporal Layers: 1
- B-Frames: No
- Resolution: 64x64 - 4096x4096 (larger than before)
- Native NV12/DX11

SVC Capabilities:
- Max Temporal Layers: 3

HEVC Capabilities:
- Not supported?!

AVC Speed:
- 854x480: 849/737/466
- 960x540: 721/615/382
- 1280x720: 463/388/230
- 1920x1080: 233/191/108
- 2560x1440: 137/114/80
- 3840x2160: 62/51/35
- **Vega is weaker than the Tonga/Tonga XT cards!**

HEVC Speed:
- 854x480: 1066/470
- 960x540: 918/846
- 1280x720: 559/512
- 1920x1080: 279/252
- 2560x1440: 158/143
- 3840x2160: 72/65
- **Vega is twice as strong as VCE3.4 in HEVC!**

**Comment by Xaymar** [comment]
Thanks a lot for these, I'll add them to the wiki soon.

**Comment by Glitchvid** [comment]
Some of the results might be a bit wonky, the drivers are really buggy for me right now.  Installing them actually causes the graphics card to "unplug" itself once the final driver stage is finished, so I can't install ReLive itself, or "finish" the process (Being unable to see the screens, I have to hard reset).

Vega also seems to partition off the hardware encoding from the main CUs themselves with Infinity fabric (according to the whitepaper), so I don't know how core clock would effect outcomes.

I'll try and get the driver situation a bit more stable and see if the results change.

**Comment by Glitchvid** [comment]
Just got ReLive installed and working, results are exactly the same.

**Comment by Glitchvid** [comment]
17.9.1 correctly reports capabilities for HEVC now.
[Caps.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1287649/Caps.txt)
