### ISSUE TITLE
Encoder not showing up

### ISSUE THREAD

**Issue by WorstBehaviour** [Xaymar/OBS-AMD-Advanced-Media-Framework#277]
1. My hardware is supported (I am pretty sure it is at least)
2. I have the latest updates installed
3. I have read through the frequently asked questions (didn't help)
4. I checked the issue tracker for similar issues (didn't help)
5. I have made a new profile.

None if this worked. I need some help.

OS: Windows 10
CPU: AMD A6-6400K Richland 32nm Technology
RAM: 8.00GB Dual-Channel DDR3 @ 800MHz
Motherboard: Gigabyte Technology Co. Ltd. F2A78M-HD2
Graphics: AMD Radeon HD 8470D

OBS Version: 20.0.1
Plugin Version: 2.2.3
AMD Driver Version: I have no idea how to get that

Latest log:
16:55:59.638: CPU Name: AMD A6-6400K APU with Radeon(tm) HD Graphics  
16:55:59.638: CPU Speed: 3893MHz
16:55:59.638: Physical Cores: 1, Logical Cores: 2
16:55:59.638: Physical Memory: 7369MB Total, 2903MB Free
16:55:59.638: Windows Version: 10.0 Build 15063 (revision: 296; 64-bit)
16:55:59.639: Running as administrator: false
16:55:59.639: Aero is Enabled (Aero is always on for windows 8 and above)
16:55:59.639: Portable mode: false
16:55:59.662: OBS 20.0.1 (64bit, windows)
16:55:59.662: ---------------------------------
16:55:59.700: ---------------------------------
16:55:59.701: audio settings reset:
16:55:59.701:     samples per sec: 44100
16:55:59.701:     speakers:        2
16:55:59.701: ---------------------------------
16:55:59.701: Initializing D3D11...
16:55:59.701: Available Video Adapters:
16:55:59.703:     Adapter 1: AMD Radeon HD 8470D
16:55:59.703:       Dedicated VRAM: 771870720
16:55:59.703:       Shared VRAM:    3623878656
16:55:59.703:       output 1: pos={0, 0}, size={1920, 1080}, attached=true
16:55:59.706: Loading up D3D11 on adapter AMD Radeon HD 8470D (0)
16:55:59.718: D3D11 loaded successfully, feature level used: 45056
16:56:00.847: ---------------------------------
16:56:00.847: video settings reset:
16:56:00.847:     base resolution:   1920x1080
16:56:00.847:     output resolution: 1280x720
16:56:00.847:     downscale filter:  Bicubic
16:56:00.847:     fps:               30/1
16:56:00.847:     format:            NV12
16:56:00.849: Audio monitoring device:
16:56:00.849:     name: Default
16:56:00.849:     id: default
16:56:00.849: ---------------------------------
16:56:00.853: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/chrome_elf.dll' not found, loading of module failed
16:56:00.872: [CoreAudio encoder]: Adding CoreAudio AAC encoder
16:56:00.874: [AMF] Encountered Exception during AMF initialization: Unable to load 'amfrt64.dll', error code 126.
16:56:00.874: Failed to initialize module 'enc-amf.dll'
16:56:00.912: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
16:56:00.913: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
16:56:00.914: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
16:56:00.915: Failed to load 'en-US' text for module: 'obs-browser.dll'
16:56:00.915: [browser_source: 'Version: 1.29.0']
16:56:00.928: LoadLibrary failed for 'nvEncodeAPI64.dll': The specified module could not be found.
16:56:00.928:  (126)
16:56:01.267: Couldn't find VLC installation, VLC video source disabled
16:56:01.295: No blackmagic support
16:56:01.572: ---------------------------------
16:56:01.572:   Loaded Modules:
16:56:01.572:     win-wasapi.dll
16:56:01.572:     win-mf.dll
16:56:01.572:     win-dshow.dll
16:56:01.572:     win-decklink.dll
16:56:01.572:     win-capture.dll
16:56:01.572:     vlc-video.dll
16:56:01.572:     text-freetype2.dll
16:56:01.572:     rtmp-services.dll
16:56:01.572:     obs-x264.dll
16:56:01.572:     obs-vst.dll
16:56:01.572:     obs-transitions.dll
16:56:01.572:     obs-text.dll
16:56:01.572:     obs-qsv11.dll
16:56:01.572:     obs-outputs.dll
16:56:01.572:     obs-filters.dll
16:56:01.572:     obs-ffmpeg.dll
16:56:01.572:     obs-browser.dll
16:56:01.572:     image-source.dll
16:56:01.572:     frontend-tools.dll
16:56:01.572:     enc-amf.dll
16:56:01.572:     coreaudio-encoder.dll
16:56:01.572: ---------------------------------
16:56:01.572: ==== Startup complete ===============================================
16:56:01.605: Service '' not found
16:56:01.615: No scene file found, creating default scene
16:56:01.615: All scene data cleared
16:56:01.615: ------------------------------------------------

Any help?

**Comment by Benman2785** [comment]
EDIT: your A6-6400k should be ok

use DDU in "Safe-Mode" to uninstall driver - reboot again - install driver

**Comment by Xaymar** [comment]
You do not have the AMF runtime installed, which is part of the AMD Driver. If the driver won't install it for you, you can alternatively switch to an older version, which the Troubleshooting Guide even tells you to.
