### ISSUE TITLE
OBS.exe Stopped working with H265

### ISSUE THREAD

**Issue by AMDJona** [Xaymar/OBS-AMD-Advanced-Media-Framework#279]
Hey. I wanted to record something, so I opened up OBS (20.0.1) with the AMD RX 580 (17.30.1041)
No matter what settings I used, it crashed using H265. H264 is working fine. 
[2017-10-14 14-28-59.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1384640/2017-10-14.14-28-59.txt)

PC Specs:
6700k
8gb ddr4 3000mhz
3x1080P screens
256GB SSD
2TB HDD
Windows 10 Pro, latest updates installed

**Comment by Xaymar** [comment]
Still the same H265 crash I have reported here: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/102

Solution should be to update your driver to the absolute latest version or do a clean install of those.

**Comment by Xaymar** [comment]
No user response for over a week, considering fixed by driver update.
