### ISSUE TITLE
AMF Surface Conversion failing - RX Vega 56

### ISSUE THREAD

**Issue by Snowknight26** [Xaymar/OBS-AMD-Advanced-Media-Framework#280]
For some reason recording fails due to a surface conversion failure in the AMF library on my RX Vega 56.

Relevant lines:

> 16:59:24.674: [AMF Runtime] [16:59:24.674][AMFDeviceDX9Impl]    Error: ..\..\..\..\..\runtime\src\core\DeviceDX9Impl.cpp(167):AMF_ERROR 10 : AMF_NOT_SUPPORTED: FromAMFtoDX9SurfaceFormat(format, width, height, dxformat, bTexture)
> 16:59:24.674: [AMF Runtime] [16:59:24.674][AMFSurfaceImpl]    Error: ..\..\..\..\..\runtime\src\core\SurfaceImpl.cpp(263):AMF_ERROR 10 : AMF_NOT_SUPPORTED: AllocPlanes()- CreateSurface
> 16:59:24.674: [AMF] <Id: 3> [Store] Conversion of Surface failed, error AMF_NOT_SUPPORTED (code 10)

Relevant Specs:
Windows 7 64-bit, full updated
RX Vega 56
OBS 20.0.1 using the AMF encoder plugin v2.2.2
Catalyst 17.10.1 (latest as of this post)

Verbose log during the issue:
[2017-10-16 16-59-18.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1389182/2017-10-16.16-59-18.txt)

**Comment by Xaymar** [comment]
Revert Color Format to NV12.

**Comment by Snowknight26** [comment]
That did it.
