### ISSUE TITLE
AMF Encoder not respecting replay buffer limitations

### ISSUE THREAD

**Issue by kamild1996** [Xaymar/OBS-AMD-Advanced-Media-Framework#282]
Latest OBS 20.1 update allows you to use the replay buffer while in advanced mode - so I updated immediately after I saw the changelog, and tried out the replay buffer with the HEVC encoder.
I set the buffer limits to 30 seconds and 100 MB, but sadly these don't seem to be respected. My replay videos are 700MB+ big and 12+ minutes long... The video itself seems fine otherwise.
The issue is gone once I switch to an x264 encoder, and NVENC is also apparently working fine with it.

- Full system specs: Intel Core i5-3350P 3.5 GHz, 8GB RAM DDR3-1333, Radeon RX 480 4GB, ASRock P67 Pro3, Seagate Barracuda 7200.11 1TB, GoodRAM Iridium Pro 240 GB
- OBS version: 20.1.0 64-bit for Windows
- Plugin version: 2.2.3
- AMD driver version: 17.8.2
- Verbose logs: https://gist.github.com/ab2b37d9201cf53209eebd7866b91de5

**Comment by Xaymar** [comment]
This is not an encoder issue, replay buffer is not handled by the encoder.
