### ISSUE TITLE
The Division crashes AMF & Game when using prepass - now confirmed ;) // started with 17.7.2 - still persists

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#283]
CPU: AMD FX(tm)-9590@4721MHz
GPU: RX580 4G - Sapphire Nitro+ OC @ GPU: 1411 MHz / GDDR5: 2000MHz
RAM: 16GB Kingston HyperX DDR3 1866 CL9 

Win10x64 Build 16299
OBS 20.1.1 x64bit
Plugin: [AMF] Version 2.2.4 loaded (Compiled: 1.4.4.0, Runtime: 1.4.6.0, Library: 1;4;6;0;17.40.1021;201710201855;CL#1473250).

LOG: 
http://benmanshafen.de/obs/xaymar/2.2.4/2017-10-27_14-55-27.7z - 4MB 
http://benmanshafen.de/obs/xaymar/2.2.4/2017-10-27_14-55-27.txt - 56MB

Videos:
http://benmanshafen.de/streamdl/stream-1509108943.flv - 842MB +20min without prepass
http://benmanshafen.de/streamdl/stream-1509110256.flv - 11MB 15s with prepass - crashed

both files are only for download - non edited - that is what my streaming server recieved from OBS

As I said in: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/263 the game and driver crashes when using prepass. i tested with reseted settings and only twitch preset with custom bitrate of 5333 // works without prepass (over 20min) // crashes with prepass (this time in 15s)

startup AMF:
`14:55:28.363: Loading module: enc-amf.dll
14:55:28.373: [AMF] <obs_module_load> Loading...
14:55:28.373: [AMF] <Plugin::AMD::AMF::AMF> Initializing...
14:55:28.386: [AMF] <Plugin::AMD::AMF::AMF> Loaded 'amfrt64.dll'.
14:55:28.387: [AMF] <Plugin::AMD::AMF::AMF> AMF Library initialized.
14:55:28.388: [AMF Runtime] [14:55:28.387][TraceImpl]    Error: ..\..\..\..\..\runtime\src\core\debug\TraceImpl.cpp(615):Assertion failed:result
14:55:28.388: [AMF] Version 2.2.4 loaded (Compiled: 1.4.4.0, Runtime: 1.4.6.0, Library: 1;4;6;0;17.40.1021;201710201855;CL#1473250).
14:55:28.388: [AMF] <Plugin::AMD::AMF::AMF> Initialized.
14:55:28.461: [AMF Runtime] [14:55:28.461][TraceImpl]    Error: ..\..\..\..\..\runtime\src\core\debug\TraceImpl.cpp(615):Assertion failed:result
14:55:28.495: [AMF] <Id: 1> Initialized.
14:55:28.496: [AMF] <Id: 1> Finalized.
14:55:28.496: [AMF] [Capability Manager] Testing Direct3D 11 Adapter 'Radeon RX 580 Series (VEN_1002/DEV_67df/SUB_e3661da2/REV_00e7)' with codec H264/AVC: Supported.
14:55:28.507: [AMF Runtime] [14:55:28.507][TraceImpl]    Error: ..\..\..\..\..\runtime\src\core\debug\TraceImpl.cpp(615):Assertion failed:result
14:55:28.517: [AMF] <Id: 2> Initialized.
14:55:28.520: [AMF] <Id: 2> Finalized.
14:55:28.520: [AMF] [Capability Manager] Testing Direct3D 11 Adapter 'Radeon RX 580 Series (VEN_1002/DEV_67df/SUB_e3661da2/REV_00e7)' with codec H265/HEVC: Supported.
14:55:28.572: [AMF Runtime] [14:55:28.572][TraceImpl]    Error: ..\..\..\..\..\runtime\src\core\debug\TraceImpl.cpp(615):Assertion failed:result
14:55:28.574: [AMF] <Id: 3> Initialized.
14:55:28.575: [AMF] <Id: 3> Finalized.
14:55:28.575: [AMF] [Capability Manager] Testing Direct3D 9 Adapter 'Radeon RX 580 Series [\\.\DISPLAY1] (VEN_1002/DEV_67df/SUB_e3661da2/REV_00e7)' with codec H264/AVC: Supported.
14:55:28.600: [AMF Runtime] [14:55:28.600][TraceImpl]    Error: ..\..\..\..\..\runtime\src\core\debug\TraceImpl.cpp(615):Assertion failed:result
14:55:28.602: [AMF] <Id: 4> Initialized.
14:55:28.605: [AMF] <Id: 4> Finalized.
14:55:28.605: [AMF] [Capability Manager] Testing Direct3D 9 Adapter 'Radeon RX 580 Series [\\.\DISPLAY1] (VEN_1002/DEV_67df/SUB_e3661da2/REV_00e7)' with codec H265/HEVC: Supported.
14:55:28.606: [AMF] [H264/AVC] Registered.
14:55:28.606: [AMF] [H265/HEVC] Registered.
14:55:28.606: [AMF] <obs_module_load> Loaded.`

additional info: start looking at 15:17:36.834
`15:17:36.837: [AMF Runtime] [15:17:36.837][TraceImpl]    Error: ..\..\..\..\..\runtime\src\core\debug\TraceImpl.cpp(615):Assertion failed:result
15:17:36.853: [AMF Runtime] [15:17:36.853][TraceImpl]    Error: ..\..\..\..\..\runtime\src\core\debug\TraceImpl.cpp(615):Assertion failed:result
15:17:36.880: [AMF] <Id: 8> Initialized.
15:17:36.881: [AMF Runtime] [15:17:36.881][TraceImpl]    Error: ..\..\..\..\..\runtime\src\core\debug\TraceImpl.cpp(615):Assertion failed:result
15:17:36.882: [AMF Runtime] [15:17:36.882][CLWrapper]    Trace: Release:: FreeLibrary C:\WINDOWS\SYSTEM32\amdmcl64.dll successed
15:17:36.888: [AMF Runtime] [15:17:36.888][CLWrapper]    Trace: Init:: LoadLibrary C:\WINDOWS\SYSTEM32\amdmcl64.dll successed
15:17:36.888: [AMF Runtime] [15:17:36.888][CLWrapper]    Trace: Load function clCreateSubDevices failed
15:17:36.888: [AMF Runtime] [15:17:36.888][CLWrapper]    Trace: Load function clCreateCommandQueueWithProperties failed
15:17:36.888: [AMF Runtime] [15:17:36.888][CLWrapper]    Trace: Load function clCreateFromGLTexture failed
15:17:36.888: [AMF Runtime] [15:17:36.888][CLWrapper]    Trace: Load function clEnqueueAcquireGLObjects failed
15:17:36.888: [AMF Runtime] [15:17:36.888][CLWrapper]    Trace: Load function clEnqueueReleaseGLObjects failed
15:17:37.083: [AMF Runtime] [15:17:37.083][CLWrapper]    Trace: Load function clGetGLContextInfoKHR failed`

`15:17:37.183: [AMF Runtime] [15:17:37.183][VCEEncoderTrace]  Warning: GetProperty BPicturesDeltaQP failed in AMFPropertyStorageExImpl with return code:0x3
15:17:37.183: [AMF] [H264]<Id: 8>       Delta QP: N/A
15:17:37.183: [AMF] [H264]<Id: 8>       Reference: Disabled
15:17:37.184: [AMF Runtime] [15:17:37.184][VCEEncoderTrace]  Warning: GetProperty ReferenceBPicturesDeltaQP failed in AMFPropertyStorageExImpl with return code:0x3`

now the final error
`15:18:01.343: [AMF Runtime] [15:18:01.343][AMFEncoderVCE]    Error: ..\..\..\..\..\runtime\src\components\EncoderVCE\EncoderVCEImpl.cpp(2628):Assertion failed:QueryOutput(-1) Failed to execute QueryOutputs(). AVE error = 0x80000009
15:18:01.344: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_FAIL (code 1).
15:18:01.344: [AMF] <Id: 8> [Main] Retrieving Packet failed, error AMF_FAIL (code 1)
15:18:01.344: Video stopped, number of skipped frames due to encoding lag: 31/834 (3.7%)
15:18:01.344: [AMF] <Plugin::Interface::H264Interface::~H264Interface> Finalizing...
15:18:01.344: [AMF Runtime] [15:18:01.344][AMFEncoderVCE]    Error: ..\..\..\..\..\runtime\src\components\EncoderVCE\EncoderVCEImpl.cpp(2513):Assertion failed:Drain() Failed to execute Encode() = 0x80000009
15:18:01.344: [AMF Runtime] [15:18:01.344][PerfMon]     Info: ------------------------------------------------------
15:18:01.344: [AMF Runtime] [15:18:01.344][PerfMon]     Info: ------ Performance results for AMFEncoderVCEImpl:
15:18:01.344: [AMF Runtime] [15:18:01.344][PerfMon]     Info: Metric              CreateEncoder                   SetEncodeConfig                 SubmitInput                     CheckAndUpdateConfig            CheckResoultion                 BufferReadParams                AttachAmfBuffer                 AVEEncode                       BufferQueue_Add                 QueryOutput                     BufferQueue_Pop                 
15:18:01.344: [AMF Runtime] [15:18:01.344][PerfMon]     Info: Average/Call (msec) 66.528                          4.579                           2.082                           0.003                           0.000                           0.032                           0.002                           1.952                           0.042                           1.673                           0.066                           
15:18:01.344: [AMF Runtime] [15:18:01.344][PerfMon]     Info: Min  (msec)         66.528                          3.578                           0.013                           0.000                           0.000                           0.006                           0.000                           0.005                           0.014                           0.028                           0.023                           
15:18:01.345: [AMF Runtime] [15:18:01.344][PerfMon]     Info: Max  (msec)         66.528                          5.579                           2976.646                        3.582                           0.012                           2.436                           0.218                           2976.623                        2.008                           2797.824                        2.483                           
15:18:01.345: [AMF Runtime] [15:18:01.345][PerfMon]     Info: Total (msec)        66.528                          9.157                           3635.370                        5.683                           0.541                           55.993                          3.542                           3408.770                        32.508                          3094.462                        50.250                          
15:18:01.345: [AMF Runtime] [15:18:01.345][PerfMon]     Info: Calls number        1                               2                               1746                            1746                            1746                            1746                            1746                            1746                            776                             1850                            761                             
15:18:01.345: Device Remove/Reset!  Rebuilding all assets...
15:18:01.345: [AMF Runtime] [15:18:01.345][VCEEncoderTrace]     Info: &&&DestroyEncoder(-1):active encoder instance=0, codecID=0x5 ok!
15:18:01.345: [AMF Runtime] [15:18:01.345][AMFEncoderVCE]     Info: Submitted 0, Queried 0
15:18:01.345: [AMF Runtime] [15:18:01.345][EncoderVCEPropertySet]    Debug: ~EncoderVCEPropertySet(): destroyed
15:18:01.345: [AMF Runtime] [15:18:01.345][EncoderVCEPropertySet]    Debug: ~EncoderVCEPropertySet(): destroyed
15:18:01.346: [AMF Runtime] [15:18:01.346][AMFVideoConverterImpl]     Info: Submitted 834, Queried 834
15:18:07.367: [AMF Runtime] [15:18:07.367][CLWrapper]    Trace: Release:: FreeLibrary C:\WINDOWS\SYSTEM32\amdmcl64.dll successed
15:18:07.367: [AMF Runtime] [15:18:07.367][CLWrapper]    Trace: Release:: FreeLibrary C:\WINDOWS\SYSTEM32\amdmcl64.dll successed
15:18:07.368: [AMF] <Id: 8> Finalized.
15:18:07.368: [AMF] <Plugin::Interface::H264Interface::~H264Interface> Complete.
15:18:07.368: Error encoding with encoder 'streaming_h264'`

happens always

ps had to disable DX12 & run in windowed fullscreen - otherwise all drivers from 17.7.2 will crash the game randomly

cant test with my old RX480 8G - because switched to the 580

**Comment by Benman2785** [comment]
`15:17:55.514: [AMF] <Id: 8> Input Queue is full, encoder is overloaded!
15:17:55.514: [AMF] <Id: 8> No output Packet, encoder is overloaded!
15:17:55.515: [AMF] <Id: 8> EncodeStore: PTS(     831) DTS(     831) TS(       173125000) Duration(          208333) Type(Automatic)
15:17:55.516: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.516: [AMF Runtime] [15:17:55.516][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.516: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.517: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.517: [AMF Runtime] [15:17:55.517][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.517: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.518: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.518: [AMF Runtime] [15:17:55.518][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.518: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.520: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.520: [AMF Runtime] [15:17:55.520][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.520: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.522: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.522: [AMF Runtime] [15:17:55.522][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.522: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.523: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.523: [AMF Runtime] [15:17:55.523][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.523: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.524: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.524: [AMF Runtime] [15:17:55.524][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.524: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.525: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.525: [AMF Runtime] [15:17:55.525][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.525: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.527: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.527: [AMF Runtime] [15:17:55.527][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.527: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.528: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.528: [AMF Runtime] [15:17:55.528][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.528: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.529: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.529: [AMF Runtime] [15:17:55.529][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.529: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.531: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.531: [AMF Runtime] [15:17:55.531][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.531: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.532: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.532: [AMF Runtime] [15:17:55.532][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.532: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.533: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.533: [AMF Runtime] [15:17:55.533][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.533: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.535: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.535: [AMF Runtime] [15:17:55.535][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.535: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.536: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.536: [AMF Runtime] [15:17:55.536][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.536: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.538: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.538: [AMF Runtime] [15:17:55.538][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.538: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.540: [AMF] <Id: 8> Input Queue is full, encoder is overloaded!
15:17:55.540: [AMF] <Id: 8> No output Packet, encoder is overloaded!
15:17:55.541: [AMF] <Id: 8> EncodeStore: PTS(     832) DTS(     832) TS(       173333333) Duration(          208333) Type(Automatic)
15:17:55.542: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.542: [AMF Runtime] [15:17:55.542][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.542: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.544: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.544: [AMF Runtime] [15:17:55.544][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.544: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.545: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.545: [AMF Runtime] [15:17:55.545][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.545: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.546: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.546: [AMF Runtime] [15:17:55.546][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.546: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.547: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.547: [AMF Runtime] [15:17:55.547][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.547: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.548: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.548: [AMF Runtime] [15:17:55.548][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.548: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.549: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.549: [AMF Runtime] [15:17:55.549][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.549: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.551: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.551: [AMF Runtime] [15:17:55.551][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.551: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.553: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.553: [AMF Runtime] [15:17:55.553][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.553: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.555: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.555: [AMF Runtime] [15:17:55.555][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.555: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.556: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.556: [AMF Runtime] [15:17:55.556][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.556: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.558: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.558: [AMF Runtime] [15:17:55.558][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.558: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.559: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.559: [AMF Runtime] [15:17:55.559][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.559: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.560: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.560: [AMF Runtime] [15:17:55.560][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.560: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.561: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.561: [AMF Runtime] [15:17:55.561][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.561: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.562: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.562: [AMF Runtime] [15:17:55.562][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.562: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.563: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).
15:17:55.563: [AMF Runtime] [15:17:55.563][AMFEncoderVCE]    Debug: QueryOutput(-1) Repeat: inputFrames=776, outputFrames=761
15:17:55.563: [AMF] <Id: 8> [Main/Query] QueryOutput returned AMF_REPEAT (code 24).
15:17:55.564: [AMF] <Id: 8> Input Queue is full, encoder is overloaded!
15:17:55.564: [AMF] <Id: 8> No output Packet, encoder is overloaded!
15:17:55.569: [AMF] <Id: 8> EncodeStore: PTS(     833) DTS(     833) TS(       173541667) Duration(          208334) Type(Automatic)
15:17:58.546: [AMF] <Id: 8> [Main/Submit] SubmitInput returned AMF_INPUT_FULL (code 25).`

**Comment by Benman2785** [comment]
when i cripple the old 17.6.2 (worked before - ps i know there wasnt prepass available but -> )and insert these dlls
`amdh264enc64.dll
amdh265enc64.dll
amdmcl64.dll
amd_opencl64.dll
amfrt64.dll`
it works with prepass enabled - so i think its not the AMF or the Plugin - but i cant be 100% sure - maybe i missed some dlls // yet again i think AMD has to fix their driver - maybe Mikhail can help ;)

**Comment by Xaymar** [comment]
1. Nobody else, not even at AMD, managed to reproduce this issue at all.
2. You have previously confirmed to me that the issue is with your system.
3. Thus the issue is invalid/user-error.

**Comment by Benman2785** [comment]
to 2. i thought it was GPU error - but after i changed GPU i still have it
to 3. i use your preset - only custom bitrate
