### ISSUE TITLE
h265 crashes with unspecified error

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#284]
CPU: AMD FX(tm)-9590@4721MHz
GPU: RX580 4G - Sapphire Nitro+ OC @ GPU: 1411 MHz / GDDR5: 2000MHz
RAM: 16GB Kingston HyperX DDR3 1866 CL9

Win10x64 Build 16299
OBS 20.1.1 x64bit
Plugin: [AMF] Version 2.2.4 loaded (Compiled: 1.4.4.0, Runtime: 1.4.6.0, Library: 1;4;6;0;17.40.1021;201710201855;CL#1473250).

LOG:
[2017-10-27 16-11-49.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1422306/2017-10-27.16-11-49.txt)

**Comment by Xaymar** [comment]
There is no crash in the log file. What is there however is you forgetting that flv only support H264 and QuickTime Video

**Comment by Benman2785** [comment]
thank you - thats it!
