### ISSUE TITLE
(Win 10) Unable to record\stream. Encoding overload in 3D scenes.

### ISSUE THREAD

**Issue by aquamacho** [Xaymar/OBS-AMD-Advanced-Media-Framework#285]
Hello, Xaymar.
Im having quite interesting issue for about half a year (or more, can't remember), 
As far as i know, this issue happens in every 3D game i tried (Metro 2033, GTA 5, Alien: Isolation and so on) howewer, i can record 2D stuff\desktop just fine, until 3D stuff happen. When rendering 3d scene obs immediately says "encoder overload'. 
Even more interesting thing, when i was playing with metro 2k33 on win 10, Obs did not showed message "EncOvrld", but fps was dropping to 54~ from 60 that was set to record to. Funny enough, when i fist seen this, i was thinking that this is how it supposed to work, like obs recording my current fps in game and puts same fps in video, like relive does. stupid.

Anyways:

Nice new feature was added to win 10, you can monitor GPU loads, even Encodind\decoding.
Normal Desktop browsing,no enc ovrlded msgs:
![screenshot_3](https://user-images.githubusercontent.com/23249682/32150820-8b622360-bcd4-11e7-913d-0513a75f2129.png)

This log is Win 10 GTA 5:
[2017-10-30 01-16-00 Win 10.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1425649/2017-10-30.01-16-00.Win.10.zip)
![screenshot_1](https://user-images.githubusercontent.com/23249682/32150626-8e3db81c-bcd2-11e7-8ab6-28eab0bc6526.png)
Vid:
https://drive.google.com/open?id=0B8uCAZ74gXrRT1RMMUFub05kVUE

This is AI (Alien Isolation) Win 10:
[2017-10-30 02-39-35.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1425656/2017-10-30.02-39-35.zip)
![screenshot_2](https://user-images.githubusercontent.com/23249682/32150770-24813366-bcd4-11e7-95af-a2a8eeac8415.png)
Vid:
https://drive.google.com/open?id=0B8uCAZ74gXrRZERMOHh4SkEzRkU

This is 2d game called Crea:
[2017-10-30 02-00-38.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1425658/2017-10-30.02-00-38.zip)
As you can see, no problems.
Vid:
https://drive.google.com/open?id=0B8uCAZ74gXrRMURpR0tlRHJNZWM

This one is Win 8.1 same GTA 5 for reference:
[2017-10-29 23-03-05 Win 8.1.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1425642/2017-10-29.23-03-05.Win.8.1.zip)
no problems to.
Vid of cource that im not bul***:
https://drive.google.com/open?id=0B8uCAZ74gXrRZHREY3Q3bkZLRWM

My hardware same as before:
Vanilla Windows 10 x64 (1709) (when im bored) \ 8.1 Daily
AMD Phenom II X6 1045T 2.7 stock @ 3.3 OC with boost to 3.9
MSI R7770 Power Edition 1GD5/OC only ram to 1300 mhz (gcn 1.0) hooked up to main monitor
9600 GT Asus Magic HDMI second monitor.
8G ddr3 ram
asrock 970 extreme3 mobo.
Plugin ver latest same as obs
Drivers latest 17.10.3 (ReLive is not installed).
Both GPU's as well as CPU overclocked, and they were overclocked when i was running on win 8.1 with no problems. I was streaming\recording on youtube daily with this overclocks for a year, and all was rock solid.
As summary, win 10 is crap same as before. Nothing changed.

Obs stuff: view mode basic
Resolution - 1920x1080
Preset: YT
Quality - Balanced
Bitrate - 20k
Fps - 60
Prewiew is disabled just in case.
Obs running as admin. Running obs not as admin not helping.

I was thinking somebody will report this, but either nobody is using same gpu as mine for AMF recordings\streaming or either nobody records with GCN 1.0 or both. At time when this started happening, i didn't cared much to report about this, because i was happily using Win 8.1 with no problems and was thinking that this is maybe caused by windows 10 itself, not by the AMF (Maybe it still Win 10 problem).
I was waiting for more and more and more updates to come out (drivers and windows), now its like 2 or 3 big updates later and im still having same issues as before.. Am i the only one?
So why im even posting this? AMD recently decided to not support win 8.1 anymore, so im forced upgrade to win 10.

**Comment by aquamacho** [comment]
"aquamacho opened this issue 9 hours ago"
What? github, please.
Upd: Just tried plugging two monitors in main gpu just in case. Not helped.
Upd2: just tried running VCE bench x32
![screenshot_1](https://user-images.githubusercontent.com/23249682/32153037-2c17c606-bce5-11e7-87de-031018bfacb7.png)
x64 version seems fine.
Results x64:
https://drive.google.com/open?id=0B8uCAZ74gXrRa3h3eDFYRUpPR1U
Okay, i think we getting somewere:
This is ReLive.
https://drive.google.com/open?id=0B8uCAZ74gXrRLVhpQWxHZWFVVDg
no problems.

**Comment by Xaymar** [comment]
1. Turn off VSync in game.
2. Lower game quality until you get at least 1.5 times your monitors refresh rate as FPS **in the most demanding area of the game**.
3. Turn on VSync in game.
4. Enjoy playing while actually leaving space for the GPU to do other tasks than rendering the game.

The reason this happens is actually quite easy: Your GPU has a finite amount of time to do tasks. If the '3D' load (actually contains all GPU tasks) is at more than 90% while your game is running, you leave next to nothing to OBS Studio and the AMF Encoder, which means that one of them can't do their work anymore.

A similar situation happens if your CPU is at over 90% load during the game, which pretty much leaves too little time for other things to work or might even cause frame dropping/skipping. Same thing happens if your RAM bandwidth is all used by the game, but most games are actually pretty good at having low memory impact (except for terrible ports, like GTA V).

The reason ReLive does not run into this issue is because it is tied to the game FPS and does not have to do additional scene rendering or copying to and from RAM, which OBS Studio has to in order to support software encoders - ReLive only has to support AMDs encoder.

**Comment by aquamacho** [comment]
Wait, Did you read the post? if yes then
Why everything is okay while im doing literally same tasks on win8.1??
Nothing in game settings or obs settings were changed

**Comment by Xaymar** [comment]
Yes, I read the post. Win 8.1 works differently from Win 10.

**Comment by aquamacho** [comment]
differently?

**Comment by Xaymar** [comment]
Windows 10 is more efficient when it comes to GPU tasks, allowing much higher performance for the game with less overhead. It also has a Game Mode which negatively impacts _all_ other applications on the system. See google for an answer on how to deactivate Game Mode after Fall Creators Update.

**Comment by aquamacho** [comment]
I was having same issues before game mode even existed.... and im runnning game on minimal settings already.

**Comment by aquamacho** [comment]
Hmmm, i think you're kinda right? i lowered resolution from hd to 1650x1050 and this helped, but why? this literally changes nothing from performance perspective. Is windows 10 has poor gpu memory usage\performance?
I don't get it, whats so different in os'es that i lose performance instead of getting it?
So i was right about win10 after all :D what a crap.
Im remembering now, when i was streaming Crysis 3\2 i was using gpu on full load, with win 8.1, and when Fps in game dropped (almost always) obs never lagged, it will always stay at 60 fps on recording or stream, even if game dips. Im literally speechless......

**Comment by aquamacho** [comment]
You can close this if you want, I see no more sense arguing about it, its just the reality that we living in. We downgrading instead of getting more, i think the "host mode" when it were existed in plugin were the best,
You can literally play the game at 25 fps with host mode and record in 60 fps at the same time without this encoder overload ****.

**Comment by Xaymar** [comment]
Host mode is still in the plugin. It never left.

**Comment by Benman2785** [comment]
aquamacho - lowering your ingame resolution reduced the load on your GPU - so it had enough "left" for VCE/AMF

**Comment by aquamacho** [comment]
You can correct me if im wrong, but doesnt the whole point of AMF\OVE was that it is supposed to be like super "lightweight" solution? Like the whole point of AMF is that you can run intense stuff on GPU and record it at the same time by trading like 20% h.264~ quality to performance\not overloading the encoder\stuttering? If thats not the case, then it holy useless.

**Benman2785** - Back in the day i was able to record valley bench and resulting video fps was 60 without overloading encoder, I just prooved already that i can literally record all those games and valley bench just by downgrading my os version..... why do we arguing about the resolution thingy? My gpu was loaded on 100% and was able to record stuff without overloading the encoder before.
The only thing that i can understand happened, is that M$ or amd changed something in way how stuff is transferring to\from the gpu on win 10 different to 8.

**Xaymar**, can you make options like OpenCl transfer\conversion actually work with dx11 or 9? i know that they are here for the "compatibility" reasons only, but isnt they supposed to be like some kind of a backup plan if suddenly gpu gets overloaded?
And about host mode, its not there in options, how can i use it? I can not see anything related about Host mode on the wiki to.
![image](https://user-images.githubusercontent.com/23249682/32176823-e96a4ea8-bd45-11e7-9d42-6bdecbbf6db3.png)


I don't know anymore, im tired of all this.

**Comment by Xaymar** [comment]
> ... it is supposed to be like super "lightweight" solution? Like the whole point of AMF is that you can run intense stuff on GPU and record it at the same time by trading like 20% h.264~ quality to performance\not overloading the encoder\stuttering? If thats not the case, then it holy useless.

This has never been the case with any GPU encoder. There still need to be time to do on-GPU copies, queuing of frames to the encoder, copying the result back to RAM and so on. It is practically only there to allow you to spend some extra CPU time on games that you would normally spend on encoding, but these days CPUs are more efficient at encoding than all AMD GPUs. AMD GPUs encode at quality between ultra and superfast.

> why do we arguing about the resolution thingy? My gpu was loaded on 100% and was able to record stuff without overloading the encoder before.

The Operating Systems work differently, you have to understand this. Windows 8.1 added a significant overhead to the system with a half-baked DWM and a half-baked Kernel driver stack. So in short, anything that can use your GPU fully in Windows 10 couldn't do so in Windows 8.1 without the use of Direct3D 12 or Vulkan (and even then may have still be limited).

> can you make options like OpenCl transfer\conversion actually work with dx11 or 9? i know that they are here for the "compatibility" reasons only, but isnt they supposed to be like some kind of a backup plan if suddenly gpu gets overloaded?

OpenCL is neither of what you said, it is merely a different way of getting the frames onto the GPU and then converting them. On average it adds about 3-5ms latency to a frame, more if the frame gets bigger. Also OpenCL supports less color format conversions and more easily crashes your Driver.

> And about host mode, its not there in options, how can i use it? I can not see anything related about Host mode on the wiki to.

"Host" is the default when Video API and Video Adapter are not visible. The original behaviour of "Host" is selecting the best available native backend API, and you can verify this yourself by looking at the code in older versions (it's all here, open source, with the entire history attached).

> I don't know anymore, im tired of all this.

I recommend going to a university/school and attending a class on IT, especially Advanced Graphics Programming. It helps a lot to understand what you're actually working with to configure it better.

**Comment by aquamacho** [comment]
> I recommend going to a university/school

Got it.
