### ISSUE TITLE
OBS x64  0.15.4 crashes as soon as i select New Encoder

### ISSUE THREAD

**Issue by galaara98** [Xaymar/OBS-AMD-Advanced-Media-Framework#29]
[Crash 2016-08-12 12-45-56.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/415997/Crash.2016-08-12.12-45-56.txt)
[Crash 2016-08-12 12-46-30.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/416000/Crash.2016-08-12.12-46-30.txt)

32bit does not crash

**Comment by Xaymar** [comment]
[Read this](https://github.com/Xaymar/OBS-AMD-Media-Framework/wiki/Reporting-Issues) and update your issue report. A crash log isn't really helpful to me at all.

**Comment by Xaymar** [comment]
Same issue as #32, CPU doesn't support AVX instructions. Normally windows should handle this, but it looks like not when it's a DLL.
