### ISSUE TITLE
i dont see vce encoding option.

### ISSUE THREAD

**Issue by TheAwesomeC0de** [Xaymar/OBS-AMD-Advanced-Media-Framework#290]
i installed obs and amd encoder plugin but only encoding option in settings is h.264(software).relive recording also doesnt work.do i need to install some drivers for vce specifically?
obs 20.1.3
amd encoder for obs 2.3.1 .
athlon 5350  apu with r3 graphics(i disabled igpu and clean installed drivers to no avail)
gigabyte am1 s2h mobo
4gb ram
r7 240 1gb variant (1st gen vce supported).
radeon drivers 17.4.4
windows 7 64 bit

can someone help me?

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by TheAwesomeC0de** [comment]
I think i gave all information. something else i should do? I have read the troubleshooting guide.

**Comment by TheAwesomeC0de** [comment]
As for log files.i dont know how to create them.i am new to all this.

**Comment by Benman2785** [comment]
OBS - "HELP" - view log files

and i see what your problem is

r7 240 - DOESNT HAVE VCE!
https://en.wikipedia.org/wiki/Video_Coding_Engine

btw Xaymar told you to read stuff - and there it was stated that r7 240 isnt supported

**Comment by TheAwesomeC0de** [comment]
It IS on the supported hardware list of this plugin.But you are right,i ran that vce speedtest just an hour ago and it failed. I dont know whats wrong but it is probably amd's problem not yours.

**Comment by Benman2785** [comment]
no - its NOT AMDs problem

yes the r7 240 is a GCN1 card - BUT MOST doesnt have VCE - because VCE takes lots of power - so the small-chip would have "aua" if it would run it - so OEMs leaves it out

for example the ASUS r7 240 low-profile dont have it or the xfx r7 240 doesnt have it etc

i think the only lp gcn 1 card that have VCE in lowprofile is the XFX R7 250E http://xfxforce.com/en-us/products/amd-radeon-r7-200-series/amd-radeon-r7-250e-core-edition-r7-250e-clf4

**Comment by TheAwesomeC0de** [comment]
I cant agree with your low power card argument. I used relive on my integrated r3 gpu before i bought this card and it worked fine. this gpu is a rocket relatively. If oems disabled it maybe i can flash a different bios to make it work. And when i said that other people are using relive on this same card i meant the exact same model from saphire.

**Comment by Benman2785** [comment]
what is your full name of GPU?

and you can simply look the feature list of your gpu yourself - or read the link i posted you
VCE is usually supported from R7 250E up

**Comment by Benman2785** [comment]
http://www.sapphiretech.com/productdetial.asp?pid=6B79F8E2-5DCD-4223-90A7-82AD60F6C441&lang=deu

Says UVD but not VCE

**Comment by Xaymar** [comment]
R7 240 and R7 250 are incorrectly listed and have no VCE.

**Comment by TheAwesomeC0de** [comment]
Yup you are right. I  just checked that manual. I cant use vce and i have a weak cpu so can you suggest me a program light on cpu? Anyways thanks for helping.

**Comment by TheAwesomeC0de** [comment]
Sorry for closing and reopening issue. I am on mobile so wrong button presses.

**Comment by Benman2785** [comment]
You can consider buying an rx460 or 560 - maybe even a rx550

**Comment by Benman2785** [comment]
R7 240 and r7 250 don't have VCE 
R7 250E + R7 250X and up have VCE

**Comment by TheAwesomeC0de** [comment]
Thanks for your suggestion but i dont think i will upgrade a card i just upgraded to and make another small upgrade which might get outdated pretty quick. I will replace my ageing pc in a 5-6 months and will probably buy a rx 570- gtx 1060 class card instead.i am closing this issue now. Thanks for all your help
