### ISSUE TITLE
Crash with AMD Adrenaline Drivers 17.12.2

### ISSUE THREAD

**Issue by smeep0** [Xaymar/OBS-AMD-Advanced-Media-Framework#291]
### Operating System
	Windows 10 Pro 64-bit
### CPU
	Intel Core i7 6700K @ 4.00GHz	21 °C
	Skylake 14nm Technology
### RAM
	32.0GB Dual-Channel Unknown @ 1200MHz (14-14-14-35)
### Motherboard
	ASRock Z170 Gaming-ITX/ac (CPUSocket)	33 °C
### Graphics
	S19B420 (1366x768@60Hz)
	S19B420 (1366x768@60Hz)
	S19B420 (1366x768@60Hz)
	4096MB ATI AMD Radeon R9 Fury Series (ASUStek Computer Inc)	36 °C
### Storage
	931GB Samsung SSD 850 EVO 1TB (SSD)	27 °C
	3726GB TOSHIBA HDWE140 (SATA)	36 °C
	238GB NVMe Samsung SSD 950 (Unknown)
	465GB Seagate FreeAgent GoFlex USB Device (USB (SATA))	26 °C
	1863GB TOSHIBA External USB 3.0 USB Device (USB (SATA))
### Optical Drives
	hp BD MLT UJ240
### Audio
	Realtek High Definition Audio

**OBS Version:** 20.1.3  
**Radeon Software version:** 17.12.2  
**Radeon Software Edition:** Adrenaline

Attached are the crash log files:
[Crash 2017-12-21 23-50-59.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1581467/Crash.2017-12-21.23-50-59.txt)

Issue: OBS Crashes when trying to stream using H264/AVC Encoder AMD Advanced Media Framework under output settings. Troubleshooting guide and OBS Project chat were consulted before considering posting issue.

**Comment by smeep0** [comment]
Crash log file with debug parameters included (--verbose --log_unfiltered --unfiltered_log):
[Crash 2017-12-22 00-18-25.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1581483/Crash.2017-12-22.00-18-25.txt)

**Comment by Xaymar** [comment]
Crash is in the drivers, can't say much more without the original log file (not the crash log).

**Comment by smeep0** [comment]
Where can I find these log files?

**Comment by Xaymar** [comment]
Same place as always: %appdata%\obs-studio\logs. Make sure that you picked the correct log file that matches your crash log.

**Comment by smeep0** [comment]
Recreated the crash to produce Crash Report with corresponding Log File. Debug Parameters were included.
[2017-12-26 23-31-38.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1588323/2017-12-26.23-31-38.txt)
[Crash 2017-12-26 23-34-14.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1588325/Crash.2017-12-26.23-34-14.txt)

**Comment by smeep0** [comment]
Here is also the log file prior to the crash:
[2017-12-26 23-27-56.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1588330/2017-12-26.23-27-56.txt)

**Comment by Xaymar** [comment]
Did you try any of the following?

- Clean Driver reinstall using Display Driver Uninstaller
- Clean Driver reinstall with the AMD Driver Installer
- A different Driver version (perhaps an earlier one than this one)

As for the issue itself, it looks like there is a mismatch or error in the shipped Direct3D 11 runtime in the driver, as it crashes inside that. It's best to try one of the above and if none help, report the bug using the AMD driver bug report form.

**Comment by smeep0** [comment]
Yup, I did the above except downgrading the driver version. I always do this practice when updating drivers too, much to my chargin.

Must be an issue with the recent Adrenaline Drivers then, as it was also occuring in 17.12.1.

**Comment by MikhailAMD** [comment]
Thanks for dxdiag. We still cannot reproduce the issue. There are three things to try:
1. dxdiag shows that three monitors are connected via DVI. But R9 has no DVI connectors. How many GPUs do you have and how are they connected?
2. Crash log shows ddumd.dll in between drivers dlls. It is not part of Windows and should not be there. Could you please find which product it is from and uninstall it?
3. Could you please send a crush dump file (DMP), not a text version of the dump?

**Comment by smeep0** [comment]
1. I have only one AMD R9 Nano connected to 3 monitors via DisplayPort-to-DVI adaptors. No additional GPUs are present since it is a miniITX build.
2. ddumd.dll is reported to be from Kairos DuetDisplay (which I do use). I'll try uninstalling DuetDisplay and seeing if it affects anything.
3. Which DMP file? OBS does not seem to output .dmp files.

**Comment by smeep0** [comment]
After uninstalling **Duet Display**, I tested OBS using AMF and it works as it should now.

So there seems to be a conflict with Duet Display and AMF.

**Comment by Xaymar** [comment]
Would you consider this solved? Technically it's an issue with Duet Display, not the plugin or AMF.

**Comment by smeep0** [comment]
My bad. Seems like the issue is with Duet Display.
