### ISSUE TITLE
Plugin not working/running?

### ISSUE THREAD

**Issue by LockeCole91** [Xaymar/OBS-AMD-Advanced-Media-Framework#292]
Hi, I installed your plugin today but when I go to settings in Obs it still looks like it can't find my AMD gpu (I still only have x264 and QuickSync H.264, with the second one not working, as it makes Obs crash everytime I try recording/streaming with it on, which is exactly what it was doing before I installed the plugin).
I have an AMD Radeon HD 8750M. I updated the drivers today and I already tried uninstalling and reinstalling both Obs and the plugin.
Any idea what might be causing this issue?
Thanks

**Comment by Xaymar** [comment]
HD 8750M is not in the compatible devices, please read the Troubleshooting Guide.

**Comment by PadTrick** [comment]
used obs and this plugin a while ago and it worked nice.
now i reinstalled obs and the plugin. just getting software rendering.
the rx480 should handle it

**Comment by Xaymar** [comment]
If the plugin no longer appears, you are running a driver that is too old. 18.1.x is the latest driver and currently only drivers from 17.11.x and up are supported.
