### ISSUE TITLE
Bitrate limit

### ISSUE THREAD

**Issue by aliez3331** [Xaymar/OBS-AMD-Advanced-Media-Framework#295]
i use nginx to stream to another pc via RTMP 
but i cant pass 100k bitrate on amf (x264 use up 370k bitrate)
only on basic mode i can write 100k + but dont work

CPU : i5 4670k
GPU : R9 380 2gb
Ram : 10 gb 1333mhz

Driver : Adrenalin Edition 18.1.1
Win 10 LTSB

sorry bad english

**Comment by Xaymar** [comment]
Bitrate limit is set by GPU. If you want bitrate >that limit, use CQP with a fixed QP value.

**Comment by Xaymar** [comment]
Closing as one week has passed without further interaction from the reporter.
