### ISSUE TITLE
Keyframe Interval and IDR Period stuck at 0 with Driver 18.2.1

### ISSUE THREAD

**Issue by LB--** [Xaymar/OBS-AMD-Advanced-Media-Framework#297]
I was previously on [18.1.1](https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Adrenalin-Edition-18.1.1-Release-Notes.aspx) where recording worked, now on [18.2.1](https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Adrenalin-Edition-18.2.1-Release-Notes.aspx) a recording file is never generated and it is impossible to stop recording without killing the OBS process - even exiting OBS does not stop it.

Log file: [2018-02-02 12-49-01.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1690474/2018-02-02.12-49-01.zip)
OBS Studio 21.0.1 and the included amf encoder plugin that is part of the full installer.
Windows 10 64 bit
CPU Name: AMD A8-8650 Radeon R7, 10 Compute Cores 4C+6G
Graphics card: Radeon (TM) RX 480 Graphics

**Comment by Xaymar** [comment]
It looks like you're trying to record with impossible recording settings. You either have Keyframe Interval or GOP Size set to 0, which is a value that will cause only one Keyframe to ever be generated - something OBS can not work with. To fix, increase Keyframe Interval and GOP Size above 0. If you have no GOP Size entry, it will match your current framerate.

**Comment by LB--** [comment]
Strange, these are the settings I used for that log:
![image](https://user-images.githubusercontent.com/1296838/35763787-5c0c45dc-0879-11e8-8cd0-70aff7045c89.png)
They have worked fine previously to record lossless video.

EDIT: When I change the view mode so I can see the GOP size, it seems to already be at 60.

**Comment by Xaymar** [comment]
Fixing.
