### ISSUE TITLE
Radeon HD 5500

### ISSUE THREAD

**Issue by ericleonardo** [Xaymar/OBS-AMD-Advanced-Media-Framework#299]
Please, will this plugin allow me to use Radeon HD 5500 as video encoder on OBS Studio?
If not, is there any alternative way to use HD 5500 for this task?

Best regards
Eric

**Comment by Xaymar** [comment]
Hardware support is restricted to cards listed in the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting) > Hardware Support. If your card is not listed there, nothing can be done.

**Comment by ericleonardo** [comment]
Sad, being recycled to save the planet seems to be the only HD 5500's useful function these days..
Thank you!
