### ISSUE TITLE
Unexpected Memory Leak

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/OBS-AMD-Advanced-Media-Framework#3]
With some rate control types, the plugin lets OBS climb to 8 or more gigabytes of memory.
Would be nice if I had some help tracking this down.

If you aren't a coder, you can help by reporting games and settings that this happened on.

**Comment by KyleStilkey** [comment]
So far I've only noticed this with Shadows of Mordor, but not in Bioshock, or some older titles. I'll do some testing later today if you don't or someone else finds this to see if I can track down some clues on to why this is happening.

**Comment by jackun** [comment]
Encoder is too slow (well, actually game's GPU usage is too high) and then input queue grows wildly.

**Comment by Xaymar** [comment]
Possible solution of course is to catch this at encode time. Count how many frames are already inside the queue and if it goes over return false. But this might hurt settings that rely on this.

Edit: GPU usage hardly matters, VCE is another MIPS chip on the GPU - PCI-E bandwidth usage matters though.

**Comment by ndv400** [comment]
> Encoder is too slow (well, actually game's GPU usage is too high) and then input queue grows wildly.

I've been playing some Kingpin: Life of Crime lately, and that game uses 99% of my GPU no matter what (which also makes my laptop overheat, but I only tested the AMD VCE encoder on my PC), and at one point OBS tried to use 6GB of memory (and crashed). Might be related.

**Comment by Xaymar** [comment]
@Daniil1288 What settings do you use?

**Comment by ndv400** [comment]
@Xaymar 
![image](https://cloud.githubusercontent.com/assets/1404955/17277905/1fb20498-5757-11e6-81c1-115824d5168b.png)

(R9 280x 6G; been using QP with the default AMD encoder, but one day video and audio started going out of sync on 1080p60fps. Can record 1080p60fps without major stutter/lag with this encoder.)

**Comment by ndv400** [comment]
Interesting... After updating to v1.1.2pre1 and applying the settings above to local recordings OBS only uses 200MB of RAM.

**Comment by Xaymar** [comment]
RGB encoding still has this issue (probably not yet supported in Media SDK 1.1). I've not encountered it myself on version 1.1.2, so it's probably fixed now.

**Comment by Xaymar** [comment]
So a lot of people are reporting this, most likely due to too high settings - will probably have to limit the stored frame count to ~60 or so.

**Comment by Xaymar** [comment]
Issue #7 is going to do something for this. Hard to tell ahead of time.

**Comment by Xaymar** [comment]
Fixed by #7
