### ISSUE TITLE
Bitdefender / antivirus Issue

### ISSUE THREAD

**Issue by Eefreeth** [Xaymar/OBS-AMD-Advanced-Media-Framework#301]
The Bit defender and Iobit Malware Fighter detects the installer exe as malware and virus, the files:

C:\Program Files (x86)\obs-studio\Unins0000.exe

C:\Users\user\AppData\Local\Temp\is-PFD.43.tmp

C:\Users\user\AppData\Local\Temp\_iu14D2N.tmp

C:\Users\user\AppData\Local\Temp\AMD-ENCODER-FOR-OBS-STUDIO.2.3.1.TMP

![image](https://user-images.githubusercontent.com/36575632/36345669-1b6aa924-13f5-11e8-818a-31c019b6e791.png)
![image](https://user-images.githubusercontent.com/36575632/36345702-9ca839ca-13f5-11e8-83a9-9ba744696c2c.png)

**Comment by Xaymar** [comment]
The Installer and Uninstaller are InnoSetup files, please update your AntiVirus solution or definitions to the latest version. [Not even VirusTotal can find anything.](https://www.virustotal.com/#/file/887d53c78cc447953d0226a1a624b88f8f45ddffc85a8e406f8678d17e0473fc/detection) In fact, on VirusTotal BitDefender and Malwarebytes do not consider it malware.

Also make sure that your machine and network router is not infected. If you get these random infected results more often you might have an infected system.

**Comment by Xaymar** [comment]
Closing as more than a week has passed.
