### ISSUE TITLE
Version the DLLs

### ISSUE THREAD

**Issue by foxx1337** [Xaymar/OBS-AMD-Advanced-Media-Framework#302]
This is maybe not possible with OBS-Studio's infrastructure, but it would be cool to have a version for the DLLs:

![versioned](https://i.imgur.com/yz0HZ7s.png)

**Comment by Xaymar** [comment]
Possible, but not high priority. First on the list is getting builds via CI working for the encoder.

**Comment by Xaymar** [comment]
CI building is now done.

**Comment by Xaymar** [comment]
![image](https://user-images.githubusercontent.com/437395/45003779-17b6e080-afe6-11e8-9455-c9b8ccfbb157.png)

Change has been implemented.
