### ISSUE TITLE
OBS Output Failed when launching stream/recording

### ISSUE THREAD

**Issue by FearTheRange** [Xaymar/OBS-AMD-Advanced-Media-Framework#305]
OS: Windows 7
CPU: Intel i5 3570k
RAM: 8.00GB
Motherboard: Gigabyte GA-Z77X-UD5H
Graphics: HIS Radeon HD 7970 3GB Video Card

OBS Version: 20.0.1
Plugin Version: 2.2.2
AMD Driver Version: 18.2.3

[2018-02-24 16-57-55.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/1755344/2018-02-24.16-57-55.txt)

Basically, when I switch to using AMD encoding it stops and tells me to install latest drivers. When I switch back to X264 it works again instantly. Am i missing something here? I have tried looking here for a solution but have not been able to find one.

**Comment by Xaymar** [comment]
Update your OBS Studio to the latest version.

**Comment by FearTheRange** [comment]
Thanks Xaymar. That fixed my issue. Can mark as complete.
