### ISSUE TITLE
FEEDBACK: v2.3.3 with custom settings (twitch.tv - 720p48)

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#310]
Windows 10 Creators x64
AMD FX-9590 @stock+UV
RX 580 4G (Nitro+ OC)
GigaByte 990FX-Gaming
16G DDR3 @1670mhz CL9-9-9-27 (4x4G - and my MemoryController sucks)

OBS 21.1.0
Plugin ver - 2.3.3
Drivers 18.3.2

i am pretty pleased with the quality - should be enough to stream decent to twitch.tv as non partner in 720p48
yet it still dont hold up to NVenc or x264

https://youtu.be/Um1kZUhTKmw
org flv: http://benmanshafen.de/obs/xaymar/2.3.3/720p48_AMF_noHRD_CABAC_tra_b2_que3.flv

Bitrate:
![720p48_amf_nohrd_cabac_tra_b2_que3](https://user-images.githubusercontent.com/21282980/37650603-b28ed1b0-2c35-11e8-8c5b-091ef36e6c0b.jpg)

settings:
![720p48_h264 4872kbps_aac 128kbps](https://user-images.githubusercontent.com/21282980/37650738-15b4cdee-2c36-11e8-827f-a81449b70ff4.jpg)

works well so far

**Comment by Benman2785** [comment]
when minqp set to 26 it looks even better and also stays in bandwidth-limit

**Comment by Benman2785** [comment]
The Division - http://youtu.be/HEzI20ZOp2o
![720p48_qp26-44_nohrd_cabac_tra_b2_que3_td_snap](https://user-images.githubusercontent.com/21282980/37687428-e2c61936-2c9b-11e8-83d6-b4db13ec46c1.png)
![720p48_qp26-44_nohrd_cabac_tra_b2_que3_td_br](https://user-images.githubusercontent.com/21282980/37687432-e5c4acec-2c9b-11e8-8e87-2febc8772eb0.jpg)
http://benmanshafen.de/obs/xaymar/2.3.3/720p48_qp26-44_noHRD_CABAC_tra_b2_que3_TD.flv


Dying Light - http://youtu.be/2rf_UjdUR7s
![720p48_qp26-44_nohrd_cabac_tra_b2_que3_dl_snap](https://user-images.githubusercontent.com/21282980/37687468-efe74d4c-2c9b-11e8-8ad1-3cdb75ef5909.png)
![720p48_qp26-44_nohrd_cabac_tra_b2_que3_dl_br](https://user-images.githubusercontent.com/21282980/37687473-f25b8160-2c9b-11e8-851e-514b373f1888.jpg)
http://benmanshafen.de/obs/xaymar/2.3.3/720p48_qp26-44_noHRD_CABAC_tra_b2_que3_DL.flv

**Comment by Roph** [comment]
Polaris can easily do 720p60 with its "quality" setting, it's only 1080p where it just barely comes in under 60fps when set to quality.

Why not use quality preset instead of balanced? I'd wager it would look the same or better than your 48fps, but at 60 instead.

I would use more reference frames too. A bunch more ref frames is a nightmare for software encoding but the extra quality from more reference frames is essentially "free" from the hardware encoder. I leave it at 16.


![image](https://user-images.githubusercontent.com/6389581/37703953-50256484-2cef-11e8-8fd5-607193ba07a7.png)

**Comment by Benman2785** [comment]
dude - check the bitrate of your output - you have peaks to 8mbit and higher

i will try 720p60 with 5872kbits + 512kbits buffer (super-strict) - that should only peak to 6350ish

720p48@4872kbits = 101.5kb per frame
720p60@5872kbits = 97.8kb per frame

so my quality should be 3.65% better :p (and this with lower bitrate)

balanced vs quality -> i will test that now; but i fear choppy output

btw - disable VBAQ -> it makes more worse than it helps (test yourself) - but Mikhail is trying to make it better

**Comment by Benman2785** [comment]
i am pretty sensitive to stutter - and "Quality" has stuttery output and impacts the game more

check yourself:

Quality
![720p48_q_nohrd_cabac_tra_b2_que3-dl](https://user-images.githubusercontent.com/21282980/37701055-e99241a2-2ced-11e8-8d95-f815dd0d56a3.png)
http://benmanshafen.de/obs/xaymar/2.3.3/720p48_Q_noHRD_CABAC_tra_b2_que3_DL.flv

Quality
![720p48_q_nohrd_cabac_tra_b2_que3_td](https://user-images.githubusercontent.com/21282980/37701128-317c7082-2cee-11e8-86f1-682d6cd19da8.png)
http://benmanshafen.de/obs/xaymar/2.3.3/720p48_Q_noHRD_CABAC_tra_b2_que3_TD.flv

Balanced
![720p48_b_nohrd_cabac_tra_b2_que3](https://user-images.githubusercontent.com/21282980/37701148-3cb005f4-2cee-11e8-89ea-bf285bdf1c01.png)
http://benmanshafen.de/obs/xaymar/2.3.3/720p48_B_noHRD_CABAC_tra_b2_que3.flv

Speed
![720p48_s_nohrd_cabac_tra_b2_que3](https://user-images.githubusercontent.com/21282980/37701163-4ab51fcc-2cee-11e8-8406-a2f8593d6d7b.png)
http://benmanshafen.de/obs/xaymar/2.3.3/720p48_S_noHRD_CABAC_tra_b2_que3.flv

i would even choose "Speed" - because most responsive in-game ;)

**Comment by Roph** [comment]
Saw it decided to leave it :+1: 

As for bits/frame, remember that higher fps doesn't need a linear amount more bitrate for the same quality since with there being more frames, less is changing between each frame.

**Comment by Benman2785** [comment]
so you dont notice stutter? i only notice it on my 144hz 1ms Screen - my 75Hz IPS shows that its smooth - but its not (the screen is simply to slow to notice it)

oh and if you peak to high on twitch you will drop frames - because twitch-servers deny high peaks

nah - every p-frame needs the same bitrate doesnt matter if 48 or 60 fps - otherwise it gets blurry in movement // but you are kind of correct when we use b-frames; because those can "share" positions for frames before and after them // yet last card that supported b-frames was R9 380(X)

**Comment by Benman2785** [comment]
decide yourself
5872kbit/s + 512kb Buffer 720p60

Balanced - looks better for scenes with fast movements
http://benmanshafen.de/obs/xaymar/2.3.3/720p60_B_noHRD_CABAC_tra_b2_que3.flv

Quality - looks better for "static-ish" scenes (use for Diablo 3 or LOL etc) - creates noticeable stutter for 144hz screens
http://benmanshafen.de/obs/xaymar/2.3.3/720p60_Q_noHRD_CABAC_tra_b2_que3.flv

**Comment by Xaymar** [comment]
I watched both videos and there is no stuttering in either of them. If you notice any stuttering, it is likely that your video player (or even CPU) is not fast enough to not miss any frames while decoding with a more advanced feature set enabled.

**Comment by Roph** [comment]
I rarely use OBS any more and use relive instead (OBS' increased overhead makes pubg streaming impossible for me, the stream lags to hell and back), though when I do use OBS I use that 720p60 config I showed above. I open my own stream on my tablet nearby to check its quality etc and it never drops. My friend(s) who watch don't report any drops either.

Looking back at the archived file, I don't notice any stutter (that wasn't in the game to begin with). I use a 75hz main monitor and VLC player 99% of the time.

**Comment by Benman2785** [comment]
@Roph did you try programms like ~~link removed by moderator~~
lets say you have an FX-8XXX -> you run game on Cores 2-7 (3 modules) & run OBS (with "above normal priority") and all other Programms on Cores 0-1 (1 module) // you can do it all by yourself (what takes 3min fun in taskmgr or buy this programm)

with that i am able to stream "The Division" with my FX-9590 - not many can do this ;)

// ps about that stuttery output - i will bring a testgroup here and ask them about the videos

**Comment by Roph** [comment]
That program is an utter scam, its developer is notorious for being a novice dev, repackaging basic windows features into for-profit GUIs and advertising them with incredibly misleading statements leading the lesser technically inclined to believe they'll see big changes when 99.9% of the time nothing different will happen. He's also very censorious, deleting and banning anything and anyone who points out how useless his programs are or who tries to warn people against buying his snake oil. I'm disappointed you'd suggest such a tool. Just google "reddit startuptim" and have a read.

Back to topic, it's a known "issue" with OBS that it's simply not as efficient as ReLive, shadowplay etc due to its round trips through RAM etc. Xaymar himself has explained as much in other issues. My CPU isn't 100% when playing pubg and trying to stream it with OBS. The game is just too heavy.

Further back to topic, twitch doesn't seem to care if my settings make a few frames burst to 8mbit/s from an average of 5.7mbit/s, my stream doesn't drop. I'd say it's a good thing to allow such bursts, a cleaner new P frame or scene change etc.

**Comment by Benman2785** [comment]
@Roph i told you that you can do it all by yourself in 3min - but that programm does it with a click - and i am very lazy ;) && i only use it to push my 100 threads on 2 cores and the game on the remaining 6 (not to have a higher ingame framerate (which is does provide when streaming)) - all with that one klick :p 

twitch did drop when the bitrate goes up to 7.5mbit over 3 times in x seconds
depending on the scene you play it is possible that it will happen

when you use a more strict buffer it stays better within target-bitrate - and, maybe have a better quality constancy -> because it doesnt drop down to 3-4mbit when it hits the average-bitrate-limit after a big peak

OBS needs to fix its code - to make it less demanding for the mem-controller

off-topic: do you use any anti-virus? deinstall it - or set up a fresh windows - only Windows Defender and FW -> your pc uses less mem-bandwidth

**Comment by Xaymar** [comment]
No advertisement or endorsement of unknown or unrelated products here please, I have removed the link to the product.

Additionally the product linked does what you can already do in seconds with Command Shell, Powershell or Task Manager (if you know how to actually use Task Manager). Please remember that changing process priority and core assignments has _severe_ side effects that are hard to notice immediately, such as restricting the speed at which frames can be duplicated, limiting the amount of free CPU cores to offload asynchronous tasks to and more.

In short: **Don't do this, there are rarely any benefits from this.**

> when you use a more strict buffer it stays better within target-bitrate - and, maybe have a better quality constancy -> because it doesnt drop down to 3-4mbit when it hits the average-bitrate-limit after a big peak

The first part is correct, the second and last part are wrong. Limiting the VBV Buffer Size that strictly will make AMF use more Filler Data as each frame can't take up a lot of space. Combined with the Maximum QP changes you did in the other Issue, you practically tell the encoder to "never go above this compression ratio but try to keep it as small as possible".

So you get the worst quality possible with those restrictions and will (if a scene demands it) easily blow past your per-frame bitrate budget, causing future frames to have lower quality.

> with that i am able to stream "The Division" with my FX-9590 - not many can do this ;)

I recorded The Division on High preset with an FX-6350 and R9 285, this is not an impressive feat for the program. The Division has very high GPU usage and barely touches the CPU for anything but gameplay, rendering, physics, networking, audio and filesystem interaction - the latter three make up next to nothing, while the first two or three likely all run sequentially in the same thread. This is pretty much identical for every existing game so far.

> off-topic: do you use any anti-virus? deinstall it - or set up a fresh windows - only Windows Defender and FW -> your pc uses less mem-bandwidth

Windows Defender has the same if not worse impact on a Computer. The fastest PCs are those without one, but special care has to be taken for those (such as never ever disabling uBlock for any site, not even for supposedly good ads).

**Comment by Benman2785** [comment]
sry for the link
btw - i have +50 processes running (and i cant select multiple in taskmgr to force them on core 0+1 - that takes 2min // but i think google is my friend

about that drops - i noticed them often after i had high peaks // if you want i can provide videos

and The Division takes all my 8 Cores now - but will test again
