### ISSUE TITLE
VULKAN or DX12?

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#311]
Hey - i want to ask if you could implement VULKAN or DX12 besides DX9 & DX11 ;)

**Comment by Xaymar** [comment]
DirectX 12 and Vulkan have no benefit for this type of video encoding. Additionally implementation depends on AMD, without AMD it is not possible. AMF is still closed source, but the headers are under an open source compatible license.

**Comment by Benman2785** [comment]
thats what i thought too - no benefit so far;

i will try to speak to the AMD Community Managers and post a link here (and also for Mikhail) to push AMD into makeing it OpenSource
