### ISSUE TITLE
Encoder overloaded + crash

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#312]
Windows 10 Creators x64
AMD FX-9590 @5ghz+UV
RX 580 4G (Nitro+ OC)
GigaByte 990FX-Gaming
16G DDR3 @1776mhz CL9-9-9-27-1T (4x4G)

OBS 21.1.0
Plugin ver - 2.3.3
Drivers 18.3.2 (18.3.3 gives me problems in some games -> black screens or white flashes = only 1/10s or so)

http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-24_11-20-09.txt
http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-24_11-20-09.flv

ps logs without OC && will now provide with OC

found that when i use FramerateTargetControl it takes up to 30min for "The Division" to crash (otherwise it crashes in ~1-3min)

also found that i can crash 100% stable games when using "Radeon Settings Game Profiles" - can provide examples if needed

**Comment by Xaymar** [comment]
If you can reproduce this, please provide the following for AMD:

- DxDiag of your system
- GPUView log of the entire recording/streaming session where it happened

These two things should help figuring out what the issue is.

**Comment by Benman2785** [comment]
i already did - so i close here

the encoder overload should be caused by AMF - usually happens after those freezes and crashes you reported
