### ISSUE TITLE
AMD encoding not recognized

### ISSUE THREAD

**Issue by orkprof** [Xaymar/OBS-AMD-Advanced-Media-Framework#313]
OBS won't show AMD among the encoding options. I'm sure it's there, I've been using AMD encoding with StreamLabs OBS till last Friday. The only thing is that SLOBS wouldn't able to see it either until I opened a game. Now I'm switching to OBS Studio but it won't see the AMD encoder even when a game is up and running.

Operating System: Windows 10 Home 64-bit
CPU: AMD A8-9600	50 °C
	Bristol Ridge 28nm Technology
RAM: 12,0GB Dual-Channel Unknown @ 931MHz (13-13-13-31)
Motherboard HP 81FA (Socket FP4)
Graphics: Generic PnP Monitor (1366x768@60Hz)
	         512MB ATI AMD Radeon R5 Graphics (HP)
	         2048MB ATI AMD Radeon R7 M340 (HP)
	         CrossFire Disabled
Storage: 931GB Hitachi HGST HTS541010A9E680 (SATA)
Optical Drives: hp DVDRW GUD1N
Audio: Realtek High Definition Audio

OBS Studio v 21.1
AMD Radeon v18.2
AMD software v18.3
AMD Encoder for OBS v2.3.3

I'm not sure how to post my log file here, I'm reading the instructions but I'm a bit lost (where am I suppsoed to insert "--verbose --log_unfiltered --unfiltered_log"?)

A person had me notice these lines in the log file which may be connected with the issue:  
20:12:08.895: [AMF] Version 2.3.3 loaded (Compiled: 1.4.6.0, Runtime: 1.4.6.0, Library: 1;4;6;0;17.50.33.01;201803162024;CL#1528515).
20:12:09.088: [AMF] <Id: 1> Unable to create H264/AVC encoder, error AMF_ENCODER_NOT_PRESENT (code 36)
20:12:09.202: [AMF] <Id: 2> Unable to create H265/HEVC encoder, error AMF_NOT_SUPPORTED (code 10)
20:12:09.354: [AMF] <Id: 3> Unable to create H264/AVC encoder, error AMF_ENCODER_NOT_PRESENT (code 36)
20:12:09.509: [AMF] <Id: 4> Unable to create H265/HEVC encoder, error AMF_NOT_SUPPORTED (code 10)
20:12:09.509: [AMF] [H264/AVC] Not supported by any GPU, disabling...
20:12:09.509: [AMF] [H265/HEVC] Not supported by any GPU, disabling...

I've been told this may mean the encoder is jsut not there, but as I said I've been using it with SLOBS till last Friday.

Thanks for your time & attention.
Franco

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you. (You can drag & drop log files to upload them or use the included uploader in obs studio.)

**Comment by orkprof** [comment]
Hi Xaymar,
thanks for replying. I was quite sure I followed all the steps, but you may be right. Yesterday evening I opened my AMD Radeon settings app and set OBS to run with one of the options (power saving or high performance, can't remember which).
After that, OBS was finally able to detect the AMD encoder and I was able to stream my games at a good, stable bitrate.

So it's solved :-)

**Comment by mmss123** [comment]
My obs still not detect the encoder what should i do?? plz help.
