### ISSUE TITLE
AMFenc + FrameRateTargetControl impacts game + crashes

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#314]
Windows 10 Creators x64
AMD FX-9590 @5ghz+UV
RX 580 4G (Nitro+ OC) @stock
GigaByte 990FX-Gaming
16G DDR3 @1776mhz CL9-9-9-27-1T (4x4G)

OBS 21.1.0
Plugin ver - 2.3.3
Drivers 18.3.3

game "stutters" when using FRTC in Radeon Settings while using AMF - looks like work for AMD
http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-25_23-40-53_FRTC.flv
http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-25_23-40-53_FRTC.txt
game && plugin crashes randomly (i try to reproduce it)

no stutter when using built-in framerate-cap of game
http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-26_00-16-48_game_crash.flv
http://benmanshafen.de/obs/xaymar/2.3.3/2018-03-26_00-16-48_game_crash.txt
yet game crashes randomly

**Comment by Xaymar** [comment]
Neither of these are encoder related. Is there anything encoder related that you need actual help with?

**Comment by Benman2785** [comment]
game crashes are related to driver changes since 18.2.1
and the stutter when using FRTC is also AMD related

i just wanted to provide logs for you - i already posted this for AMD
so it was more of way of informing you

**Comment by Xaymar** [comment]
If they are only AMD related, this is the wrong place for that. This is the issue and support tracker for the AMD Encoder in OBS Studio, not general AMD help and information. Please use the community forum for that instead.
