### ISSUE TITLE
Obs not see amd amf

### ISSUE THREAD

**Issue by portovayashlyha** [Xaymar/OBS-AMD-Advanced-Media-Framework#318]
After reinstalling windows obs now not see my amd graphics and i can't set amd for coding
Why it can be?
https://hastebin.com/avojupokoh

**Comment by Xaymar** [comment]
`[AMF] A critical error occured during AMF Testing.`

This means that the AMF runtime crashed while testing for support. Use Display Driver Uninstaller to clean your AMD Drivers and reinstall them.

**Comment by portovayashlyha** [comment]
https://hastebin.com/ujaxocuwid
Done.
More infermation:
before win reinstalation it works (pretty sure) on 15.7 drivers, but now - not
My gpu to old, but i'm sure i had amf encoder before reinstalattion :(

**Comment by portovayashlyha** [comment]
If i set in AMD control center OBS to perfomance (i guess it means it will use dicret card), then by obs got crash with this log https://hastebin.com/vinubabate.tex

**Comment by Xaymar** [comment]
> hastebin.com/ujaxocuwid

Same problem as before, it doesn't find the actual GPU

> hastebin.com/vinubabate.tex

This is a driver crash, you might have luck with an older version of the plugin. All recent plugin versions require an up to date driver. IIRC 15.7 was last supported with plugin version [1.4](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/releases/tag/1.4.3.11), some driver+card combinations may even require an [even older version](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/releases/tag/1.2.0rc1).

**Comment by portovayashlyha** [comment]
1.2.0rc1 works for me! Hahaha, it's too old but it's working.
Thx man...

**Comment by Xaymar** [comment]
You're welcome. Just keep in mind that I can not update that version, so what you have there is what you have to work with until you get a new APU (AMD Ryzen 2000 maybe) or GPU (if these ever go down in price again).
