### ISSUE TITLE
OBS 64-bit crashed at start in version 1.2.0rc1

### ISSUE THREAD

**Issue by max20091** [Xaymar/OBS-AMD-Advanced-Media-Framework#32]
Specs:
OBS 0.15.2 and OBS 0.15.4
Windows 10
AMD Radeon HD 7730 with driver 15.7.1

This only happened when I launch 64-bit version, 32-bit still working normal.

I attached the crash file below.
[Crash 2016-08-14 19-01-42.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/417013/Crash.2016-08-14.19-01-42.txt)

**Comment by Xaymar** [comment]
Upload a log file please, the crash file only tells me that it crashed in AMFEncoder::VCE_H264_Encoder::get_defaults, but not why.

Edit: What CPU do you have? Also I'm gonna need you to [read this](https://github.com/Xaymar/OBS-AMD-Media-Framework/wiki/Reporting-Issues) and update your issue accordingly

**Comment by max20091** [comment]
you can see the spec in the crash file, it always say the CPU and OS I use.
CPU: Intel G630

Log file:
[2016-08-15 11-57-57.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/417545/2016-08-15.11-57-57.txt)

**Comment by Xaymar** [comment]
Seems like that CPU doesn't support AVX, which is required for fast memory operations. I'll have to figure out something with the installer then.

**Comment by Xaymar** [comment]
Future versions will not rely on AVX and instead use SSE2.
