### ISSUE TITLE
Every time I try to record or stream it crashes

### ISSUE THREAD

**Issue by ZZags** [Xaymar/OBS-AMD-Advanced-Media-Framework#320]
When ever i try to stream or record with the plugin it crashes, and ive updated everything, you can check out the crash log below

[Crash 2018-06-01 21-46-51.txt](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/2083110/Crash.2018-06-01.21-46-51.txt)

**Comment by Xaymar** [comment]
Uninstall Intel Graphics Drivers using DDU or similar. This is the same issue as seen in #317.

**Comment by Xaymar** [comment]
This also has a FAQ entry: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Frequently-Asked-Questions#q-ffmpeg-shows-an-error-that-avcodec-avutil-and-avformat-are-missing-after-enabling-opencl-features

**Comment by r9-lorenzo** [comment]
@Xaymar Thank you so much dude !
