### ISSUE TITLE
AMD AMF no longer working after OBS upgrade to 21.x

### ISSUE THREAD

**Issue by oakmage** [Xaymar/OBS-AMD-Advanced-Media-Framework#321]
Hello,

I had this problem in the past but didn't report it here. Only fix I had was to roll OBS back to version 20.x. I may have to do that again.

Updated it again today, unable to use AMD AMF. Encoder plugin is up-to-date, video drivers are up-to-date, OBS as well... newest version: 21.1.2.

Here's my OBS log: https://hastebin.com/hivopusizo

Any thoughts?

**Comment by Xaymar** [comment]
Change the value of the Target Bitrate field to something else than "-1". There is a yet unfixed bug in the transition from old property names to new property names that sometimes results in a -1 being stored as the target bitrate, instead of a 0.

**Comment by oakmage** [comment]
It's already set as a "1". I tried 0 as well but it didn't stick. 2 didn't work either.

**Comment by oakmage** [comment]
Got it. It was set as a "1". I switched preset back and then set my custom bitrate again. Now I'm good. Thank you.

**Comment by Xaymar** [comment]
#304 has another case of this happening. The actual reason is unknown, as it technically shouldn't be possible.
