### ISSUE TITLE
Support Of Graphics Chipset Amd Radeon HD 8570

### ISSUE THREAD

**Issue by oldaccountzorrow** [Xaymar/OBS-AMD-Advanced-Media-Framework#327]
[ResultsH264.zip](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/files/2204824/ResultsH264.zip)

**Comment by Xaymar** [comment]
Your card does not have a VCE or HEVC encoding unit, as shown by Caps.txt.

**Comment by Xaymar** [comment]
Closing as very confusing.
