### ISSUE TITLE
pls add VULKAN Support!

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#335]
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/125#issuecomment-423045199

so now we can add vulkan as API

**Comment by Xaymar** [comment]
What would this bring? It's not going to be faster with Vulkan, and the only reason to have it would be for Linux support - in which case I'd need AMD to provide drivers for Debian / stop locking their Drivers to be ubuntu only.

**Comment by Benman2785** [comment]
there are rumors that AMD will bring linux drivers

using vulkan over dx11 can maybe lower latency a litte - what would allow a "heavy" setting for the encoder

but, i know that it would be quiet some work - and wouldnt impact quality that much

**Comment by Xaymar** [comment]
AMD already has linux drivers. However they lock them to specific distributions, so as a Debian user (since the machine also runs my build bots) it isn't possible for me to add linux support. Well, technically it would be ubuntu support.

**Comment by GloriousEggroll** [comment]
unsure if you've tried this but apparently you should be able to install the drivers in debian by changing a line in the install script:

https://community.amd.com/thread/220723

it would be great to have the option to use amd amf in linux. While vaapi exists, the quality is not great unless you really crank the bitrate.

**Comment by fjorgemota** [comment]
Hey.

Just a noob question related to this issue: It's not possible to use the opensource drivers from the kernel, right? Because AMF doesn't  support it yet, correct?

I'm asking this because the opensource drivers are, in fact, better and more recommended for gamers according to AMD itself, and because they are totally distro-agnostic, only needing an updated kernel (because part of the driver is on the kernel) and updated mesa (to implement opengl and vulkan APIs)

btw, sorry for the noob question, I'm just confirming it. I definitely would like to see Linux support on this plugin while using the opensource drivers..But I did not have too much knowledge on AMF as a project.

Thank you for the answer anyway

**Comment by GloriousEggroll** [comment]
@fjorgemota currently OBS has VAAPI support for open source drivers, you'll need to compile from git as there hasnt been a release yet and it was just added a few weeks ago

**Comment by fjorgemota** [comment]
Oh, nice. Thanks for the information, @GloriousEggroll!

**Comment by Xaymar** [comment]
Unfortunately not going to implement this myself. While it seems it may be useful for Linux users, the code base right now is mostly aimed at Windows and I lack the required knowledge for a proper implementation on Linux. If someone with better knowledge of Linux coding wants to implement it, feel free to make a PR and ask any questions about the code base.

**Comment by Xaymar** [comment]
Merging into #361 (same basic issue with Vulkan).

**Comment by peti** [comment]
@GloriousEggroll,

> Currently OBS has VAAPI support for open source drivers, you'll need to compile from git as there hasnt been a release yet and it was just added a few weeks ago

I built the current `master` of the OBS git repository and I could not find anything to that extend (except for the VAAPI via ffmpeg plugin, which is inefficient and slow in my experience). Can you please be more specific as to what exactly you're referring to?

**Comment by GloriousEggroll** [comment]
That is what i was referring to. VAAPI itself is not inefficient and slow, it depends on the hardware you're running it on. RX 500 cards are limited to about 1080p 30, where later cards have better output/do not overload the encoder as easily.

This however does not have anything to do with capturing vulkan, as a new capture method would need to be implemented for that. VAAPI is simply another encoder which as you know, utilizes encoder hardware on the GPU.
