### ISSUE TITLE
An unspecified error occurred while recording

### ISSUE THREAD

**Issue by MrChimichanga** [Xaymar/OBS-AMD-Advanced-Media-Framework#339]
When I press record I receive the "An unspecified error occurred while recording" error. I haven't recorded in a while so I'm not sure what settings might have changed so I uninstalled and reinstalled OBS but the problem persists. I checked online for similar issues but changing encoders and messing with audio settings didn't help, I also have antivirus turned off and ran OBS as admin. Any help is appreciated.

Specs:
Windows 10 Education 64-bit
Intel Core i7 3770 @ 3.40GHz	
8,00GB Dual-Channel DDR3 @ 668MHz
ASUSTeK COMPUTER INC. P8Z77-V LX (LGA1155)
ATI Radeon RX 580 Series
Latest AMD drivers 18.10.2
OBS 22.0.2 64 bit

[2018-10-31 22-38-22.txt](https://github.com/obsproject/obs-amd-encoder/files/2536184/2018-10-31.22-38-22.txt)

**Comment by Xaymar** [comment]
`22:52:07.872: [ffmpeg muxer: 'adv_file_output'] os_process_pipe_write for info structure failed`

This is outside of the scope of this repository. Please use the OBS Forum, OBS Discord or OBS Issue Tracker for this.
