### ISSUE TITLE
Obs not letting me Record. Help!!!

### ISSUE THREAD

**Issue by MajesticRecluse** [Xaymar/OBS-AMD-Advanced-Media-Framework#340]
I just got a new laptop an Lenovo ideapad 330 with a Ryzen 3 amd.  And just need to know what i need to do to get obs recording and acting right. Please let me know if you can figure out what i need to do.

https://obsproject.com/logs/OIqx_v1y840QMJt-

OBS 22.0.2 (64-bit, windows) log file uploaded at 2018-10-30, 19:55:45

19:54:57.438: CPU Name: AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx 
19:54:57.438: CPU Speed: 2495MHz
19:54:57.438: Physical Cores: 2, Logical Cores: 4
19:54:57.438: Physical Memory: 7733MB Total, 5133MB Free
19:54:57.438: Windows Version: 10.0 Build 17134 (revision: 376; 64-bit)
19:54:57.438: Running as administrator: false
19:54:57.438: Aero is Enabled (Aero is always on for windows 8 and above)
19:54:57.439: Windows 10 Gaming Features:
19:54:57.439: Game DVR: On
19:54:57.441: Sec. Software Status:
19:54:57.442: Windows Defender Antivirus: disabled (AV)
19:54:57.442: McAfee VirusScan: enabled (AV)
19:54:57.443: McAfee Firewall: enabled (FW)
19:54:57.443: Windows Firewall: disabled (FW)
19:54:57.443: Windows Defender Antivirus: disabled (ASW)
19:54:57.443: McAfee VirusScan: enabled (ASW)
19:54:57.444: Browser Hardware Acceleration: true
19:54:57.444: Portable mode: false
19:54:57.606: OBS 22.0.2 (64-bit, windows)
19:54:57.606: ---------------------------------
19:54:57.619: ---------------------------------
19:54:57.619: audio settings reset:
19:54:57.619: samples per sec: 44100
19:54:57.619: speakers: 2
19:54:57.620: ---------------------------------
19:54:57.620: Initializing D3D11...
19:54:57.620: Available Video Adapters: 
19:54:57.622: Adapter 1: AMD Radeon(TM) Vega 3 Graphics
19:54:57.622: Dedicated VRAM: 253255680
19:54:57.622: Shared VRAM: 4054622208
19:54:57.622: output 1: pos={0, 0}, size={1366, 768}, attached=true
19:54:57.625: Loading up D3D11 on adapter AMD Radeon(TM) Vega 3 Graphics (0)
19:54:57.639: D3D11 loaded successfully, feature level used: 45056
19:54:58.401: ---------------------------------
19:54:58.401: video settings reset:
19:54:58.401: base resolution: 1366x768
19:54:58.401: output resolution: 1092x614
19:54:58.401: downscale filter: Bicubic
19:54:58.401: fps: 60/1
19:54:58.401: format: NV12
19:54:58.401: YUV mode: 601/Partial
19:54:58.403: Audio monitoring device:
19:54:58.403: name: Default
19:54:58.403: id: default
19:54:58.403: ---------------------------------
19:54:58.406: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/chrome_elf.dll' not found, loading of module failed
19:54:58.409: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
19:54:58.685: [AMF] Version 2.4.2 loaded (Compiled: 1.4.7.0, Runtime: 1.4.6.0, Library: 1;4;6;0;17.40.3601.1014;201806212331;CL#1571515).
19:54:58.757: [AMF] [Capability Manager] Testing Direct3D 11 Adapter 'AMD Radeon(TM) Vega 3 Graphics (VEN_1002/DEV_15dd/SUB_38ef17aa/REV_00c5)':
19:54:58.757: H264/AVC: Supported
19:54:58.757: H265/HEVC: Supported
19:54:58.757: 
19:54:58.813: [AMF] [Capability Manager] Testing Direct3D 9 Adapter 'AMD Radeon(TM) Vega 3 Graphics [\\.\DISPLAY1] (VEN_1002/DEV_15dd/SUB_38ef17aa/REV_00c5)':
19:54:58.813: H264/AVC: Supported
19:54:58.813: H265/HEVC: Supported
19:54:58.813: 
19:54:58.829: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
19:54:58.830: LoadLibrary failed for '../../obs-plugins/64bit/libEGL.dll': The specified procedure could not be found.
19:54:58.830: (127)
19:54:58.830: Module '../../obs-plugins/64bit/libEGL.dll' not loaded
19:54:58.831: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
19:54:58.833: [obs-browser]: Version 2.1.5
19:54:58.836: LoadLibrary failed for 'nvEncodeAPI64.dll': The specified module could not be found.
19:54:58.836: (126)
19:54:58.941: Couldn't find VLC installation, VLC video source disabled
19:54:58.945: No blackmagic support
19:54:58.950: ---------------------------------
19:54:58.950: Loaded Modules:
19:54:58.950: win-wasapi.dll
19:54:58.950: win-mf.dll
19:54:58.950: win-dshow.dll
19:54:58.950: win-decklink.dll
19:54:58.950: win-capture.dll
19:54:58.950: vlc-video.dll
19:54:58.950: text-freetype2.dll
19:54:58.950: rtmp-services.dll
19:54:58.950: obs-x264.dll
19:54:58.951: obs-vst.dll
19:54:58.951: obs-transitions.dll
19:54:58.951: obs-text.dll
19:54:58.951: obs-qsv11.dll
19:54:58.951: obs-outputs.dll
19:54:58.951: obs-filters.dll
19:54:58.951: obs-ffmpeg.dll
19:54:58.951: obs-browser.dll
19:54:58.951: image-source.dll
19:54:58.951: frontend-tools.dll
19:54:58.951: enc-amf.dll
19:54:58.951: coreaudio-encoder.dll
19:54:58.951: ---------------------------------
19:54:58.951: ==== Startup complete ===============================================
19:54:58.951: Service '' not found
19:54:58.958: All scene data cleared
19:54:58.958: ------------------------------------------------
19:54:59.126: WASAPI: Device 'Speakers (Realtek(R) Audio)' initialized
19:54:59.129: [WASAPISource::TryInitialize]:[{0.0.1.00000000}.{d46b5b20-197b-4932-80fa-a2636137770c}] Failed to activate client context: 88890004
19:54:59.129: [WASAPISource::WASAPISource] Device '{0.0.1.00000000}.{d46b5b20-197b-4932-80fa-a2636137770c}' not found. Waiting for device
19:54:59.133: Switched to scene 'Scene'
19:54:59.133: ------------------------------------------------
19:54:59.133: Loaded scenes:
19:54:59.133: - scene 'Scene':
19:54:59.133: - source: 'Screen Record' (monitor_capture)
19:54:59.133: - source: 'Audio Tech' (wasapi_input_capture)
19:54:59.133: ------------------------------------------------
19:54:59.219: CalculateFileHash: Failed to open file 'C:\Users\noble\AppData\Roaming\obs-studio\updates\whatsnew.json': 
19:55:01.164: [AMF] [H264]<Id: 5> <Plugin::AMD::EncoderH264::SetProfileLevel> Failed to set to 32, error AMF_FAIL (code 1)
19:55:01.295: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds
19:55:22.271: [AMF] [H264]<Id: 6> <Plugin::AMD::EncoderH264::SetProfileLevel> Failed to set to 32, error AMF_FAIL (code 1)
19:55:34.901: [AMF] [H264]<Id: 7> <Plugin::AMD::EncoderH264::SetProfileLevel> Failed to set to 32, error AMF_FAIL (code 1)

**Comment by Xaymar** [comment]
Set Profile Level to another value than 3.2 (or if you haven't set it at all, set it to automatic after setting it to another value).

**Comment by MajesticRecluse** [comment]
where is settings for profile located? thank you for actually responding!

**Comment by Xaymar** [comment]
If you are using the advanced output mode, it is in the encoder settings. You might have to set "View Mode" to "Advanced" for it to show up.

**Comment by MajesticRecluse** [comment]
Thank you I was able to fix it with your help in settings> output.

**Comment by MajesticRecluse** [comment]
what would be best overall settings for my laptop resolution, streaming, and recording wise if you could let me know?
