### ISSUE TITLE
SLOBS not show 2nd graphic card

### ISSUE THREAD

**Issue by rysdol** [Xaymar/OBS-AMD-Advanced-Media-Framework#342]
Hi,

When i use obs, without any special configuration, obs detects my 2 graphic cards, and i can change the selected card.

The problem comes when i try to select a graphic card in streamlabs obs, because not show any card (see pic), but if i change directX, it shows both cards, but if i select my secondary card (r9 380), dissapear.

I need to select secondary card but is impossible in SLOBS, but works in OBS. Could you help me, please?

My specs are:

MB: msi x470 gaming pro
CPU: amd ryzen 2700
RAM: gskills 16GB
SSD: mushkin chronos 120GB
HDD: seagate shdd 2TB
OBS version: 22.0.2
SLOBS version: 0.11.1
AMF version: 1.4.7 and 1.4.9
AMD driver version: 18.5.1 and 18.10.2

Best regards.
![captura](https://user-images.githubusercontent.com/12101112/47955770-32cdae80-df9d-11e8-89eb-72978bd9084b.PNG)
![captura2](https://user-images.githubusercontent.com/12101112/47955771-33664500-df9d-11e8-8e3c-e946fab8e765.PNG)
![captura3](https://user-images.githubusercontent.com/12101112/47955772-33664500-df9d-11e8-8c04-a29ea148fa79.PNG)
![captura4](https://user-images.githubusercontent.com/12101112/47955773-33664500-df9d-11e8-81ed-1e496b02c30c.PNG)
[slobs_changing_graphic_card.txt](https://github.com/obsproject/obs-amd-encoder/files/2545243/slobs_changing_graphic_card.txt)
[slobs_new_amf.txt](https://github.com/obsproject/obs-amd-encoder/files/2545244/slobs_new_amf.txt)
[slobs_old_amf.txt](https://github.com/obsproject/obs-amd-encoder/files/2545245/slobs_old_amf.txt)
[obs_old_amf.txt](https://github.com/obsproject/obs-amd-encoder/files/2545247/obs_old_amf.txt)

**Comment by Xaymar** [comment]
Since it works in OBS Studio and not in Streamlabs OBS, your problem is with Streamlabs OBS. Please contact their support instead.
