### ISSUE TITLE
I in confuse with AMD 390X and VCE. Does it support 4K?

### ISSUE THREAD

**Issue by dEROZA** [Xaymar/OBS-AMD-Advanced-Media-Framework#346]
I thought that VCE version guarantees max encoding resolution. So tried to use my AMD R9 390X as 4K encoder on my stream PC. But it not works.. Does 390X really not support H265? Because I thought that I can use R9 390X as encoder in 3840*2160@60 resolution...

**Comment by Xaymar** [comment]
H265 Encoding support was added with VCE 3.4 and newer, which is Polaris and Vega. H264 4K resolution is supported by VCE 3.0. An R9 390X is a VCE 2.0 card.
