### ISSUE TITLE
AMFSpeedTest doesn't seem to work on R9 290

### ISSUE THREAD

**Issue by danilaml** [Xaymar/OBS-AMD-Advanced-Media-Framework#347]
Here is the log:
[H264_256x256.zip](https://github.com/obsproject/obs-amd-encoder/files/2578139/H264_256x256.zip)

Maybe it needs to be updated?

Win 10 x64, 
Catalyst 18.10.1

**Comment by Xaymar** [comment]
AMFSpeedTest is not maintained, it was a test tool all the way back then (v1.something).

**Comment by danilaml** [comment]
I figured. I've just used the "run the test yourself" link [from the wiki](https://github.com/obsproject/obs-amd-encoder/wiki/Hardware-Support). Perhaps it needs to be updated as well.

**Comment by danilaml** [comment]
@Xaymar is there a working tool to collect such info https://github.com/obsproject/obs-amd-encoder/wiki/Hardware-VCE3.0 now?
