### ISSUE TITLE
OBS stream crash with AMD encoder with visual 2017 installed and xaymar plugin installed

### ISSUE THREAD

**Issue by mjlk** [Xaymar/OBS-AMD-Advanced-Media-Framework#349]
hey,

card is rx570

have the correct visual redistributables installed (2017)
radeon software18.11.12
obs 22.0.2

OBS crashes when i attempt to start stream,

the crash log is very long. do i post it here anyways?
(edited) here is the crash log link
https://obsproject.com/logs/CVcfZ_mH_cDQPsiO
log link
https://obsproject.com/logs/hL5UaZCZ0CC1RTb6

please help!

**Comment by Xaymar** [comment]
This crash is described in the Frequently Asked Questions and is due to Intel Drivers. Please follow the FAQ.

**Comment by mjlk** [comment]
solved this issue weeks ago. the faq was dated and not helpful in this
case. had to enable onboard graphics in bios, update the intel drivers
manually from device manager and then disable the device from bios. thanks
for the reply. maybe this was in the faq but did not see it, searched up
and down the faq and support pages but it all was either dated or circled
back to redundant materials. also, uninstalling the intel adapter
completely does not seem to be necessary.

also, most recent version of obs comes with your plug in and the required
visual distributables comes with the most recent version of radeon drivers.

thanks for your work!

**Comment by Xaymar** [comment]
I'm pretty sure this isn't dated or circles back to redundant materials: [Why is OBS Studio crashing when I click Start Stream/Record?](https://github.com/obsproject/obs-amd-encoder/wiki/Frequently-Asked-Questions#q-why-is-obs-studio-crashing-when-i-click-streamrecord). To date this is the known fix if Windows has decided to load the Intel driver for unknown reasons (even with a disabled Onboard Graphics option).

The most recent version is not always in OBS Studio, this is a standalone build capable plugin, which means that there are releases that are newer than the one in OBS Studio. As for VCRedist, not everyone is able to use the latest AMD drivers. :)

**Comment by mjlk** [comment]
interesting.

i didn't have to uninstall the adapter. i updated it and then disabled it
from bios and the crash ceased.

thanks for the reply! and thanks for the plug in!
