### ISSUE TITLE
The Path to AMF SDK

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/OBS-AMD-Advanced-Media-Framework#35]
This Issue is meant to track progress on the upgrade to AMF SDK. Commits that are related to it will show up here.

AMF SDK: https://github.com/GPUOpen-LibrariesAndSDKs/AMF
- [x] Library Binding Class for AMF SDK.
- [x] New Shared Encoder based on Library Binding Class and AMF SDK updates.
- [x] Update Capability Reporter to use new SDK.
- [x] Update Simple Encoder Interface to new Shared Encoder.
- [x] Update Advanced Encoder Interface to new Shared Encoder.
- [x] [Proper Color Profile and Range](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/6#issuecomment-241218439)

**Comment by Xaymar** [comment]
The SDK seems to be missing HEVC/h265 and TwoPass encoding, perhaps this is internally done and will be pushed soon?

**Comment by Xaymar** [comment]
**Library Binding Class for AMF SDK.**

Task completed:

```
11:43:27.929: [AMF Encoder] Version 1.3.0-1.3.0.5
11:43:27.929: [AMF Encoder] <Plugin::AMD::AMF::AMF> Initializing...
11:43:27.929: [AMF Encoder] <Plugin::AMD::AMF::AMF> Loaded 'AMF_DLL_NAME'.
11:43:27.929: [AMF Encoder] <Plugin::AMD::AMF::AMF> Runtime is on Version 1.3.0.4
11:43:27.930: [AMF Encoder] <Plugin::AMD::AMF::AMF> AMF Library initialized.
11:43:27.930: [AMF Encoder] <Plugin::AMD::AMF::AMF> Initialized.
```

**Comment by Xaymar** [comment]
**New Shared Encoder based on Library Binding Class and AMF SDK updates.**

Task completed.

**Comment by Xaymar** [comment]
Just sent off this E-Mail to AMD Tech Support, I hope I hear back from them soon.

> Hello again,
> 
> I'm am almost done with the complete upgrade to the new SDK, however I stumpled upon really strange bugs.
> 1. The SubmitInput/QueryOutput issue is back and it's worse than before. In Media SDK, only SubmitInput would flip out - in AMF SDK, both will flip out randomly. This means that on many computers the loaded library will just get stuck at 100% cpu usage, rendering the encoder useless.
> 2. BFrames are no longer supported, there is no way for me to test if the issue is still here or not.
> 3. No Yuv 4:4:4 support. Have not opened an issue for this yet as I'm still looking for official documents that say VCE supports this. NVENC and QuickSync both support this out of the box so it might be worth it to implement this.
> 4. Color Range and Profile are still locked to Partial and .601, rendering output footage to be in the wrong color.
> 5. Even though you advertised Single Pass and Two Pass encoding variants, there seems to be no way to actually select these in the API.
> 
> I have opened GitHub Issues for this on the Repository for the AMF SDK:
> 1. https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/9
> 2. https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/8
> 3. None yet as I couldn't find anything but Wikipedia listing this support.
> 4. https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/6
> 5. https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/2
> 
> I thank you for your time and hope to hear back from you soon.

**Comment by Xaymar** [comment]
**A new Preview Build is available to all current and future Patrons on my Patreon!**

You can find it here: https://www.patreon.com/posts/amd-advanced-for-6579254

**Comment by Xaymar** [comment]
Patrons can now enjoy the latest fixes (without having to compile it themselves) by [clicking here](https://www.patreon.com/posts/6584660) and downloading the attached files.

1.3.0pre1 has been released to the public too now.

**Comment by Xaymar** [comment]
Apparently, I was downgraded back to customer support, which in turn told me to ~~figuratively go fuck myself and~~ post in the Media SDK Dev Guru forum instead. I don't have access to that, and that forum has been deader than a corpse.

> Thank you for the update.
> 
> Technical support for developers is not available through Customer care, the correct place to post your questions and feedback will be on our AMD developer support forums.
> 
> We have AMD engineers and developers present on the dev guru forum that will be able to work with your on AMF.  We encourage you to sign up to the developer forums and , participate and ask your questions here where you will get the technical help you need. https://community.amd.com/community/devgurus/media-sdk
> 
> Please be advised that this service request will be permanently closed if you do not reply within 10 days. If more time is needed to respond to my e-mail above, please let me know and I will ensure that this service request remains open for you.
> 
> In order to update this service request, please respond, leaving the service request reference intact.
> 
> Best regards,
> 
> AMD Global Customer Care

**Comment by mirh** [comment]
If you don't have access to that, then post in the newcomer section. 
It's not really a senior engineer helpdesk, but hey, took them a working day to get back to me with opengl issues (and 6 months to release a fixed driver, but hey, who am I to complain?). 

Media sdk section if any has low activity exactly because most of people can't post there. 
But imo, you are hell entitled to access it. My bets are you'd be instantly whitelisted.

**Comment by Xaymar** [comment]
@mirh I have two posts in Newcomers section about Media SDK. Still not whitelisted as of today.

Edit: I'll make a third one... when I run out of Github issues on the api.

**Comment by Xaymar** [comment]
**Update Advanced Encoder Interface to new Shared Encoder**

Task completed. Mostly. Still need to do some things with the order, or perhaps even try to make a completely dynamic interface (drop down with add and remove buttons).

**Comment by Xaymar** [comment]
**1.3.0pre3 is now out for the public!**

Patrons had a half day headstart on using this and now you can too! Get the pre-built binaries here: https://github.com/Xaymar/OBS-AMD-Media-Framework/releases/tag/1.3.0pre3

**Comment by mirh** [comment]
Why did you left build files in release? :s

**Comment by Xaymar** [comment]
@mirh What do you mean? dll files are always supposed to be there.

**Comment by mirh** [comment]
And indeed I meant everything but the dll. 
exp, iobj, ipdb, lib and pdb files have no sense to be there.

**Comment by Xaymar** [comment]
Just because you don't use them doesn't mean they have no sense to be there. You're welcome to open a pull request if you think those 5mb (<500kb compressed) need to be removed from the packages.

**Comment by mirh** [comment]
> Just because you don't use them doesn't mean they have no sense to be there. 

I see, so.. What would this sense be then?

And it's not like about size, it's about I learned never to expect any special intelligence from people, so I wouldn't add stuff useless 99.9% of times.

**Comment by Xaymar** [comment]
I use the shipped binaries to test issues that happen after I have already continued work on the encoder - that way i know it actually happens and where it happened.

Again, if you don't like it, you're welcome to make a PR for it.

**Comment by Xaymar** [comment]
Port to AMF SDK is technically done. Investigation into the Video Converter revealed that it doesn't help unless you explicitely use I420 - both NV12 and RGBA look perfectly fine (although the output format is YUV 4:2:0 Partial).
