### ISSUE TITLE
Streamlabs OBS "Go Live" doesnt work with AMD Encoder

### ISSUE THREAD

**Issue by Curvezy** [Xaymar/OBS-AMD-Advanced-Media-Framework#353]
I have a ryzen 5 2500U, tried looking through some other posts but nothing really worked
[2019-01-05 17-01-44.txt](https://github.com/obsproject/obs-amd-encoder/files/2729319/2019-01-05.17-01-44.txt)
Here is my logs hope i can get some help, if you need any other information just ask me.

**Comment by Xaymar** [comment]
`[000:01:42:25.320.824.761][Error] [AMF] [H264]<Id: 11> <Plugin::AMD::EncoderH264::SetProfileLevel> Failed to set to 30, error AMF_FAIL (code 1)`

Issue is already tracked under #345. This is a problem with the AMD Hardware or Driver, and your only option is to attempt to manually set the Profile Level correctly, as the hardware/driver returns invalid information.

**Comment by Curvezy** [comment]
okay i set the profile to 4.1 and worked, thanks.

**Comment by Xaymar** [comment]
I've linked a test update in #345. It might be a little bit more difficult to test in Streamlabs OBS, but I'm sure that the people working on Streamlabs OBS can help out there.
