### ISSUE TITLE
request: ratetol & aq_strength

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#357]
hi, 
is it possible to implement a changeable ratetol?
or to make it dynamic-bound to buffersize?

aq_strength of 1.5 would sharpen the quality quite a bit

**Comment by Xaymar** [comment]
All the settings you see under View Mode Expert are all that AMD is currently exposing. Since neither of those terms mean anything in AMD Settings right now, can you explain what they should do?

**Comment by Xaymar** [comment]
> ratetol
> 
> Only applicable to 1pass bitrate encodes. Sets the percentage that x264 can miss the target average bitrate by. 1.0 = 1%. This means the final average bitrate (and corresponding filesize) will be within about ±1% of what you set.

This is achievable with precise settings in Target Bitrate, VBV Buffer and so on. However it is not something for the plugin to add. However, not a feature in AMF.

> aq-strength
> 
> Adaptive Quantization Strength
> Sets the strength of AQ bias towards low detail ('flat') macroblocks. Negative values are not allowed. Values more than a couple of hundred percent off from 1.0 are probably a bad idea. 

This is not a feature in AMF.

**Comment by Benman2785** [comment]
aq_strength could sharpen the image more - this would help alot

ratetol can maintain better quality over time because it limits the max and minimun size difference of any single frame  to a percentage of average bitrate - in combination with custom buffer it would maintain a "less spiky & overall good quality stream"

maybe you can ask Mikail to implement that

**Comment by Xaymar** [comment]
The [GPUOpen AMF repository](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/) would be the place to request these features.

**Comment by Benman2785** [comment]
;)

ok i will do my best there

**Comment by Benman2785** [comment]
done - https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/148

**Comment by Xaymar** [comment]
Closing as not relevant to the plugin.
