### ISSUE TITLE
Settings for r9 2xx users, try those, look my output and results

### ISSUE THREAD

**Issue by wazerstar** [Xaymar/OBS-AMD-Advanced-Media-Framework#36]
**OBS-AMD-Media-Framework 1.2.rc1 Stress test 1080p@60fps no scaling - 3000-3200kbit**
https://youtu.be/Z2_pOOozY9Y

**OBS-AMD-Media-Framework 1.2.rc1 Stress test 1080p@60fps scaled to 1280@720@60fps - 3000-3200kbit** 
https://youtu.be/m60WFCT2O7s

**OBS-AMD-Media-Framework 1.2.rc1 Stress test 1280,960@60fps scaled to 1280,720@60fps stretched - 3000-3200kbit** 
https://youtu.be/d5Q4Dj4uki4

**Hardware:**
CPU:  Intel 4790K
Graphics: AMD R9 290 4GB GDDR5 modded to 290x - Then remodded to 390x
Motherboard: Asus MAXIMUS VI FORMULA
Ram: 16GB DDR3 2400mhz
Disk: 1TB Samsung EVO 840

**Settings:**

Type:              Advanced Video Coding
Usage Type:            Transcoding
Quality Preset:           Balanced
Profile:            Main
Profile Level:           5.0
Maximum LTR:           0

Scan Type:             Progressive
Rate Control Method:         CBR: Constant Bitrate
Frame skipping:           Disabled
Filler Data:           Disabled
Enforce HRD Compatability:         No
Group Of Picture Size:          60
VBV Buffer Size (In Bits):        3200000
Initial VBV Buffer Fullness:        1
Maximum AU Size (In Bits):        0
B-Picture Delta QP:          4
Reference B-Picture Delta QP:       2
Minimum QP:            1
Maximum QP:            35
I-Frame QP:            22
P-Frame QP:            22
B-Frame QP:            22
Target Bitrate (In Bits):        3000000
Peak Bitrate (In Bits):         3200000
Header Insertion Spacing (In bits):      0
Number of B-Pictures:         0
De-Blocking Filter:          Enabled
B-Picture Reference:         Disabled
IDR (Keyframe Period) (In frames):      120
Intra-Refresh Memory Per Slot In Macroblocks (In MB):  0
Slices Per Frame:          1
Motion Estimation:          Both
Temporal Enchancement Layers:       -1

Remember this is a stress test where the game is speeded up a lot to see how the recording/streaming looks under extreme and unrealistic fast paced circumstances

**Comment by wazerstar** [comment]
I got some issues when using twitch today.

http://prnt.sc/c70h6n
http://prnt.sc/c70jds
http://prnt.sc/c70jl9

If you notice it starts using more and more bandwidth and the IDR goes up to 4 seconds instead of 2.

Cant forget to think of that maybe anything is left behind in the graphics card memory and getting pushed out bit after bit, I tried stopping and starting the stream but same result. After a reboot everything was back to normal again until same thing happened again.

[2016-08-17 22-05-22.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/425183/2016-08-17.22-05-22.txt)

**Comment by nwgat** [comment]
you call that a stress test?, try overwatch its way better to test video encoding quality, it has alot happeing on screen with explosives

**Comment by Xaymar** [comment]
Overwatch hardly stresses the GPU and Encoder chip. They have a defined color set which even while action is happening doesn't really change much. CS:GO, Call of Duty, Battlefield would all be better tests than Overwatch.

Edit: To an encoder, little change means near-zero difficulty to encode since it already knows the values needed.

**Comment by nwgat** [comment]
a game with explosives, alot of flashes, foliage, water
i think far cry primal might be a good candidate 
https://www.youtube.com/watch?v=dJQX0tZsZo4

**Comment by Xaymar** [comment]
Yeah, games like Far Cry Primal (with lots of little details) would work best. Anything where there are just big changes will just show what we already know about the encoder and not the settings.

**Comment by wazerstar** [comment]
nwgat of course its a stress test, its speeded and really fast paced to see how the pixels relate to the fast movement, if i wanted to be casual i could play overwatch, sadly its a silly game and will never be viewer friendly for any none gamers that want to watch it and understand it right away. Now lets just wait for Xaymar's magic with the new sdk rev  ;)

**Comment by Tazimuss** [comment]
Just left a comment on one of those Youtube vids, and this is important to me so I made an account here.  I'll post my Youtube comment to save some time, just in case:

Hey man.  I get no where near this quality when using your exact settings.  I am using an R9 Fury X (which definitely can handle it) and a 9590 @ 5ghz (which by FAR handles it).  I have all the right drivers, everything is good, except when I stream it's all blocky (using 3500kb, which I can handle as I have 4500 upload) and NOTHING seems to stop the blocky look.  What is going on?

As a side note, I cranked up every setting to the max.  It made zero difference.  Still streamed at "720p60fps" but looks blocky as fuck, and no where near as good as this example.

Take a look at Twitch.tv/tazimuss and look at pretty much any of those vods that are over a minute long or something (there's a LOT of tests).  

Again, what the hell is going on?

**Comment by Xaymar** [comment]
Hard to say, but do try to [read this](https://github.com/Xaymar/OBS-AMD-Media-Framework/wiki/Reporting-Issues) and follow it for the new issue you create. Hijacking an unrelated issue is not acceptable, i will merge them myself if they turn out to be similar.

**Comment by Tazimuss** [comment]
Wait, so coming into this exact post where I used this guys exact details is "hijacking"?  I was just looking for help on the issue from the guy who posted it.  It's not unrelated.  It's very much related.  It can't be more related.

**Comment by Tazimuss** [comment]
Look I'm not trying to be a dick, but you are.  I was just asking the guy who posted this for help concerning this posts exact specifications, and you are being a dick about it.

**Comment by Xaymar** [comment]
I merely asked you to either create your own issue, or don't use a Issue Tracker for the **plugin** for issues with settings from another user. You could have chosen to privately message him or follow my request and open an issue, but instead you decided to be a dick about it and insult the plugin creator. Not cool man.

Additionally, your R9 Fury X may be strong enough to handle games, but that does not mean it can handle encoding well. There are many factors affecting it: BIOS, VCE generation, PCI-E speed and slot type, Mainboard, bandwidth, CPU and GPU load, etc. Your CPU hardly matters here, the plugin is lightweight so in theory even an old Athlon X2 could handle it as long as the PCI-E bandwidth is available.

If in the future you need any help with the plugin, please do follow the rules. It makes things easier for both of us.

**Comment by nwgat** [comment]
ooh my, hmm which version? the 1.3 version uses a updated sdk, so try the 1.2 rc1 and Crimson 16.7.3 or later

anyhow

**Comment by Tazimuss** [comment]
Okay, so I'll agree that I was a dick about you being a dick.  I didn't follow your rules and for that I apologize.  However, you're suggesting that, instead of asking about the settings in this post, I should have created a whole different post, linked this post in that post, and ask the guy in this post about this post from my other, non related post.  
I'll agree that I didn't follow your rules and called you a dick, several times, and I shouldn't have done that, but making a whole different, non related independent thread when I just had a simple question about these settings seems a bit redundant and tedious.
He already responded to my Youtube comment, anyway.  
I'm sorry I didn't follow your rules, but come on man.  I'm going to let this go and apologize one more time.  Sorry.

**Comment by Xaymar** [comment]
Apology accepted. In the future, just open up a new issue, as my local issue tracker software will ping me when issues get updated, so a new issue is better here.

**Comment by wazerstar** [comment]
Xaymar, maybe delete your own comments again, he deleted his and removed his profile from here.

**Comment by Xaymar** [comment]
I will close this issue as #61 is now there to gather further tested settings for version 1.3.0pre5 and higher. 1.2.0rc1 is officially no longer supported.
