### ISSUE TITLE
Linux (Ubuntu) support?

### ISSUE THREAD

**Issue by ridaamirini** [Xaymar/OBS-AMD-Advanced-Media-Framework#361]
Is there anyway to get this run on Linux?

**Comment by Xaymar** [comment]
Yes, someone would have to write an Vulkan API layer.

**Comment by Xaymar** [comment]
See #335 for a similar question to this.

**Comment by Aurnytoraink** [comment]
Where is Linux support for this plugin, has now AMF is on Linux

https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/4

**Comment by Xaymar** [comment]
Linux support is not planned, as I have neither the time or money to invest into this. If this is truly something you need (and you can't wait for a VAAPI plugin to work well enough), you'll have to ask the OBSProject team to put out a bounty for the implementation of linux support.

**Comment by Xaymar** [comment]
Closing this as obs-ffmpeg-encoder will eventually replace this plugin, since the ffmpeg integrated AMF supports linux. VAAPI is also already available as a plugin.
