### ISSUE TITLE
error AMF_OPENCL_FAILED (code 19)

### ISSUE THREAD

**Issue by TheBitcoinBaron** [Xaymar/OBS-AMD-Advanced-Media-Framework#366]
I keep getting this obs error in the log it wont record or stream. Whatever video settings I use, what does this mean? Nothing else is using the card (Vega 64).

Please advise what obs settings are supposed to work with this encoder. OBS and AMD drivers are all up to date.

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by TheBitcoinBaron** [comment]
Hi that's not a helpful response, the Troubleshooting guide i had already been through. I have a supported card, have the latest drivers for everything, and theres no other open issue tracker for this particular error code... I'm not sure what more is required. Step 5 I dont understand how i would do. There are a million options in obs, I dont even remember the ones I have changed.

If you are saying one of those steps should fix it, please advise which one and provide full details.


Unless you mean the system specs and logs, if thats what you meant, those details are here:

AMD FX-9370 processor and Asus motherboard.
16GB DDR 3 ram.
AMD VEGA 64 

OBS 32.0.1
AMD ADRENALIN 19.1.1
LOGFILE
[2019-02-28 12-27-36.txt](https://github.com/obsproject/obs-amd-encoder/files/2914935/2019-02-28.12-27-36.txt)

**Comment by Xaymar** [comment]
[How to report an issue correctly, according to the Troubleshooting Guide](https://github.com/obsproject/obs-amd-encoder/wiki/Guide%3A-Troubleshooting#if-nothing-helped-report-an-issue).

**Comment by TheBitcoinBaron** [comment]
AHAH, I think I have figured out the issue (see system specs above), and can give more details on how it manifests.

Basically, if anything else is using the amd graphics card when starting to encode, it will fail. Even if it's only using a few % of the GPUs power. If I start obs and start the recording/streaming, and then start the game, there is no issue. The issue only occurs if the GPU is somewhat already engaged by something else. Hopefully that will give enough info about how the problem manifests to enable you to fix it. 

I am getting a dedicated (NVIDIA) encoder card tomorrow so it wont be of much use to me though.

**Comment by Xaymar** [comment]
> 12:27:51.471: [AMF] <Id: 5> Unable to initalize converter, error AMF_OPENCL_FAILED (code 19)

Did you perhaps enable any of the OpenCL options in the encoder?

**Comment by reedog117** [comment]
Having the same problem with an older system:

OBS 23.2.1, encoder version 2.5.1

Detailed log
https://obsproject.com/logs/9TP0M_dlw9IvOxCx

None of the OpenCL options are enabled. Also tried running DDU and reinstalling the most recent AMD drivers I could find. I don't think it's because the % GPU in use on start is the problem - I tried starting stream with a completely blank scene and have the same issue.

I think here's the relevant portion:

```
09:58:46.094: [AMF] <Id: 8> Initialized.
09:58:46.095: [AMF Runtime] [09:58:46.095][AMFEncoderVCE]  Warning: AVEQueryEncodeCapabilitiesEx bad status : 0x 80000002
09:58:46.095: 
09:58:46.099: [AMF Runtime] [09:58:46.098][CLWrapper]    Trace: Release:: FreeLibrary C:\Windows\SYSTEM32\amdmcl64.dll successed
09:58:46.100: [AMF Runtime] [09:58:46.099][CLWrapper]    Trace: Init:: LoadLibrary C:\Windows\SYSTEM32\amdmcl64.dll successed
09:58:46.100: [AMF Runtime] [09:58:46.099][CLWrapper]    Trace: Load function clCreateSubDevices failed
09:58:46.100: [AMF Runtime] [09:58:46.099][CLWrapper]    Trace: Load function clCreateCommandQueueWithProperties failed
09:58:46.100: [AMF Runtime] [09:58:46.099][CLWrapper]    Trace: Load function clCreateFromGLTexture failed
09:58:46.101: [AMF Runtime] [09:58:46.100][CLWrapper]    Trace: Load function clEnqueueAcquireGLObjects failed
09:58:46.101: [AMF Runtime] [09:58:46.100][CLWrapper]    Trace: Load function clEnqueueReleaseGLObjects failed
09:58:46.231: [AMF Runtime] [09:58:46.230][CLWrapper]    Trace: Load function clGetGLContextInfoKHR failed
09:58:46.325: [AMF Runtime] [09:58:46.324][AMFComputeKernelImpl]    Error: ..\..\..\..\..\runtime\src\core\ProgramsComputeImpl.cpp(418):OpenCL failed, error = -11:clBuildProgram() failed (-11)
09:58:46.325: [AMF Runtime] [09:58:46.324][AMFComputeKernelImpl]    Error: ..\..\..\..\..\runtime\src\core\ProgramsComputeImpl.cpp(176):AMF_ERROR 19 : AMF_OPENCL_FAILED: LoadProgram() - failed
09:58:46.325: [AMF Runtime] [09:58:46.324][AMFComputeKernelImpl]    Error: ..\..\..\..\..\runtime\src\core\ProgramsComputeImpl.cpp(643):AMF_ERROR 19 : AMF_OPENCL_FAILED: GetKernel.CreateProgram failed
09:58:46.325: [AMF Runtime] [09:58:46.324][AMFDeviceComputeImpl]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImpl.cpp(1789):AMF_ERROR 19 : AMF_OPENCL_FAILED: AMFProgramsCompute::Get().GetProgram(kernelID, (void**)&clProgramTmp, &buildID, this)
09:58:46.325: [AMF Runtime] [09:58:46.324][AMFDeviceComputeImpl]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImpl.cpp(1701):AMF_ERROR 19 : AMF_OPENCL_FAILED: GetKernel(zeroBufferKernelID, &m_pKernelZeroBufferUChar)
09:58:46.325: [AMF Runtime] [09:58:46.324][AMFDeviceComputeImpl]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImpl.cpp(1662):AMF_ERROR 19 : AMF_OPENCL_FAILED: PostInit()
09:58:46.326: [AMF Runtime] [09:58:46.325][AMFContextImpl]    Error: ..\..\..\..\..\runtime\src\core\ContextImpl.cpp(468):AMF_ERROR 19 : AMF_OPENCL_FAILED: pDeviceMCL->Init(NULL)
09:58:46.326: [AMF Runtime] [09:58:46.325][CLWrapper]    Trace: Release:: FreeLibrary C:\Windows\SYSTEM32\amdmcl64.dll successed
09:58:46.326: [AMF Runtime] [09:58:46.325][CLWrapper]    Trace: Release:: FreeLibrary C:\Windows\SYSTEM32\amdmcl64.dll successed
09:58:46.326: [AMF Runtime] [09:58:46.325][CLWrapper]    Trace: Release:: FreeLibrary opencl.dll successed
09:58:46.326: [AMF Runtime] [09:58:46.325][CLWrapper]    Trace: Init:: LoadLibrary opencl.dll successed
09:58:46.326: [AMF Runtime] [09:58:46.325][CLWrapper]    Trace: Load function clSetPrintfCallback failed
09:58:46.326: [AMF Runtime] [09:58:46.325][CLWrapper]    Trace: Load function clSetImageFormatAMD failed
09:58:46.326: [AMF Runtime] [09:58:46.325][CLWrapper]    Trace: Load function clCreateImageTiledAMD failed
09:58:46.326: [AMF Runtime] [09:58:46.326][CLWrapper]    Trace: Load function clSetThreadTraceBuffersAMD failed
09:58:46.776: [AMF Runtime] [09:58:46.775][AMFComputeKernelImpl]    Error: ..\..\..\..\..\runtime\src\core\ProgramsComputeImpl.cpp(415):OpenCL failed, error = -42:BinaryProgram::Compile() clCreateProgramWithBinary() failed (-42)
09:58:46.777: [AMF Runtime] [09:58:46.775][AMFComputeKernelImpl]    Error: ..\..\..\..\..\runtime\src\core\ProgramsComputeImpl.cpp(176):AMF_ERROR 19 : AMF_OPENCL_FAILED: LoadProgram() - failed
09:58:46.777: [AMF Runtime] [09:58:46.776][AMFComputeKernelImpl]    Error: ..\..\..\..\..\runtime\src\core\ProgramsComputeImpl.cpp(643):AMF_ERROR 19 : AMF_OPENCL_FAILED: GetKernel.CreateProgram failed
09:58:46.777: [AMF Runtime] [09:58:46.776][AMFDeviceComputeImpl]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImpl.cpp(1789):AMF_ERROR 19 : AMF_OPENCL_FAILED: AMFProgramsCompute::Get().GetProgram(kernelID, (void**)&clProgramTmp, &buildID, this)
09:58:46.777: [AMF Runtime] [09:58:46.776][AMFDeviceComputeImpl]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImpl.cpp(1701):AMF_ERROR 19 : AMF_OPENCL_FAILED: GetKernel(zeroBufferKernelID, &m_pKernelZeroBufferUChar)
09:58:46.777: [AMF Runtime] [09:58:46.776][AMFDeviceComputeImpl]    Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImpl.cpp(1662):AMF_ERROR 19 : AMF_OPENCL_FAILED: PostInit()
09:58:46.777: [AMF Runtime] [09:58:46.776][AMFContextImpl]    Error: ..\..\..\..\..\runtime\src\core\ContextImpl.cpp(318):AMF_ERROR 19 : AMF_OPENCL_FAILED: pDeviceOpenCL->Init(pCommandQueue)
09:58:46.788: [AMF Runtime] [09:58:46.787][CLWrapper]    Trace: Release:: FreeLibrary opencl.dll successed
09:58:46.789: [AMF Runtime] [09:58:46.788][CLWrapper]    Trace: Release:: FreeLibrary opencl.dll successed
09:58:46.789: [AMF Runtime] [09:58:46.788][AMFVideoConverterImpl]    Error: ..\..\..\..\..\runtime\src\components\VideoConverter\VideoConverterImpl.cpp(338):AMF_ERROR 19 : AMF_OPENCL_FAILED: err
09:58:46.789: [AMF Runtime] [09:58:46.788][EncoderVCEPropertySet]    Debug: ~EncoderVCEPropertySet(): destroyed
09:58:46.789: [AMF Runtime] [09:58:46.788][EncoderVCEPropertySet]    Debug: ~EncoderVCEPropertySet(): destroyed
09:58:46.789: [AMF] <Id: 8> Finalized.
09:58:46.790: [AMF] <Id: 8> Unable to initalize converter, error AMF_OPENCL_FAILED (code 19)
09:58:46.790: Stream output type 'rtmp_output' failed to start!
```

**Comment by Xaymar** [comment]
See the log message a few lines above that:

```
09:54:54.047: [AMF] <Plugin::AMD::AMF::AMF> Loaded 'amfrt64.dll'.
09:54:54.047: [AMF] The AMF Runtime is very old and unsupported, consider updating your drivers.
09:54:54.047: [AMF] <Plugin::AMD::AMF::AMF> AMF Library initialized.
09:54:54.049: [AMF] Version 2.5.1 loaded (Compiled: 1.4.9.0, Runtime: 1.4.0.0, Library: 1;4;0;0;16.50.2001.1004;201705021555).
```

**Comment by Xaymar** [comment]
Closing as the issue was "resolved".

**Comment by Shahed0631j** [comment]
am using Intel pentium g4400 with 8gb ddr4 ram amd asus h110mk motherboard, 120 GB transcend ssd
recently I've added asus r7 360 oc 2gb ddr5 v2 graphics card ,
I had installed amd driver adrenalin-2020-21.5.2 , in obs it shows h254/AVF,,, and i have installed obs-amd-encoder-2.6.0.0
but when I select and try to record or stream it says
'starting the output failed. please check the log for more details '
and in the log it says
"Unable to initialize converter, error AMF_OPENCL_FAILED (code 19)"
please help m
[2021-09-29 13-15-36.txt](https://github.com/obsproject/obs-amd-encoder/files/7249664/2021-09-29.13-15-36.txt)

**Comment by Shahed0631j** [comment]
Please help me eeeeee please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please please
