### ISSUE TITLE
AMF benchmark throws AMF_ERROR 18 and 25

### ISSUE THREAD

**Issue by gutko** [Xaymar/OBS-AMD-Advanced-Media-Framework#367]
Seeing benchmark tables empty on wiki I wanted to get results on rx580, but benchmark 1.9.9.6 seems to not work. Attached result file with errors. I have no problems running actual obs plugin

[H264_256x256.zip](https://github.com/obsproject/obs-amd-encoder/files/2947918/H264_256x256.zip)

**Comment by Xaymar** [comment]
Benchmark is no longer maintained.
