### ISSUE TITLE
OBS crashes when using AMD encoder

### ISSUE THREAD

**Issue by SpieleFresser** [Xaymar/OBS-AMD-Advanced-Media-Framework#369]
Hello :)

I know, this issue has already been reported but I think I've got the same problem like CyberiumShadow, it might help you to know that. 

Installed OBS version: 23.0.2
Installed obs-amd-encoder version: 2.5.1.0
Radeon Software Version: 19.1.1 
Radeon Software Edition: Adrenalin 2019

Log file:
[2019-03-24 11-05-06.txt](https://github.com/obsproject/obs-amd-encoder/files/3000273/2019-03-24.11-05-06.txt)

Crash file: 
[Crash 2019-03-24 11-05-21.txt](https://github.com/obsproject/obs-amd-encoder/files/3000271/Crash.2019-03-24.11-05-21.txt)

Operating system
	Windows 10 Home 64-bit
CPU
	Intel Core i5 6500 @ 3.20GHz	
	Skylake 14nm Technologie
RAM
	8,00GB Dual Kanal Unbekannt @ 1066MHz (15-15-15-36)
Motherboard
	ASRock H170M Pro4S (CPUSocket)	
GPU
	VN279 (1920x1080@59Hz)
	SAMSUNG (1920x1080@59Hz)
	8192 MBATI Radeon RX 580 Series (C.P. Technology)	
Storage
	1863GB Western Digital WDC WD20EZRZ-00Z5HB0 (SATA )	
Optical drives
	TSSTcorp CDDVDW SH-224FB
Audio
	Realtek High Definition Audio

Issue: OBS crashes after 1-2 seconds when I use the AMD encoder and hit "start stream".

I alreday made a full clean, installed and deinstalled OBS like 5 times, installed all vc_redists and have the same problem in Streamlabs.

**Comment by Xaymar** [comment]
Please run OBS Studio `--verbose --unfiltered_log` and upload a log file with the same attempt. Without this information I am unable to provide further help.

**Comment by SpieleFresser** [comment]
[2019-03-24 16-36-11.txt](https://github.com/obsproject/obs-amd-encoder/files/3000524/2019-03-24.16-36-11.txt)
 I hope, that's what you're asking for

**Comment by Xaymar** [comment]
That log still seems to be the same as before, did you adjust the shortcut to obs like this?
![image](https://user-images.githubusercontent.com/437395/54883281-9715df80-4e64-11e9-84f1-09bbd0c6e109.png)

If so, make sure you also check "Debug" in the encoder options. Note that this option is only visible in advanced output mode.

**Comment by SpieleFresser** [comment]
I'm sorry, I just changed the name of the link, not the target link. Now it should be the right log.
[2019-03-24 22-02-24.txt](https://github.com/obsproject/obs-amd-encoder/files/3000849/2019-03-24.22-02-24.txt)

**Comment by SpieleFresser** [comment]
I also recognized, that I have only 2 encoders to pick from for streaming (in the options), but 3 encoders for video recording. I don't know if that's normal but it may help.

**Comment by Xaymar** [comment]
Unfortunately this seems to be a driver crash, which are out of my control. If you aren't already on the newest version of everything (Windows, AMD Driver, etc), consider doing a clean reinstall of the AMD Driver using Display Driver Uninstaller.

**Comment by SpieleFresser** [comment]
I've found out another thing. I am able to record and stream but only if my output resolution is 480p or less. If I set it to a value above, it crashes like described. I hope it helps you.

**Comment by x61s** [comment]
[Crash 2019-06-06 15-27-02.txt](https://github.com/obsproject/obs-amd-encoder/files/3262038/Crash.2019-06-06.15-27-02.txt)

apu 9800b

**Comment by Xaymar** [comment]
> 
> 
> [Crash 2019-06-06 15-27-02.txt](https://github.com/obsproject/obs-amd-encoder/files/3262038/Crash.2019-06-06.15-27-02.txt)
> 
> apu 9800b

Could you open up another issue with your crash log, your full system information and if possible a normal obs log file too? The crash that was reported here is different from the one you're experiencing.
