### ISSUE TITLE
benchmark mode

### ISSUE THREAD

**Issue by nwgat** [Xaymar/OBS-AMD-Advanced-Media-Framework#37]
would been useful to have a mode where we can test settings and see if it can keep up, msi afterburner has something similar benchmark mode, we just need a simple one that has text with Good(Green)/Acceptable(Yellow)/Bad(Red) and results from a simple game/demo

![http://image.prntscr.com/image/806c4d41bb3744a2aef3e3316929879b.png](http://image.prntscr.com/image/806c4d41bb3744a2aef3e3316929879b.png)

**Comment by hymccord** [comment]
It probably falls out of the scope of the project. There's already a benchmark in the new AMF SDK. Just compile VCEEncoderD3D project and run the VCEEncoderD3DPerformanceTest.bat.

**Comment by Xaymar** [comment]
Benchmarking is something that would need to be implemented through OBS Studio. I can write tools that test, but they aren't gonna be useful for OBS performance (OBS internally has a lot of weird decisions which may be faster or slower than what I'd write).
