### ISSUE TITLE
Will there be soon Radeon vii (VEGA 20 / VCE 4.1) support?

### ISSUE THREAD

**Issue by chocosobo** [Xaymar/OBS-AMD-Advanced-Media-Framework#371]
I'm not sure why but radeon vii streaming has lot of lag
Maybe cause Hybrid GPU setting (1070ti for gaming/Radeon VII for encoding) and obs looks not support radeon vii well yet
Has lot of crashes

**Comment by Xaymar** [comment]
I have submitted an [expense reimbursement request](https://opencollective.com/obsproject/expenses/7567) to the Open Collective part of the OBS Project. Unfortunately as I do not have the hardware, I can't guarantee any kind of stability or functionality with Radeon VII at the moment.

**Comment by Vectrobe** [comment]
Perchance are you using a 4K display? I've found the relive encoding stutters, and OBS encoding flat-out doesn't work if you use native 4K. Down-scaling the canvas however (ie; not encoding resize) to 1440p or lower allows it to work perfectly.

**Comment by Xaymar** [comment]
I can't confirm this happening on the Radeon VII when using it for gaming and encoding. "Hybrid" encoding will always perform worse, as cross-GPU has to go through the CPU, so unless you have lots of PCI-E bandwidth available hybrid mode will drastically perform worse.
