### ISSUE TITLE
AMD Encoder on OBS

### ISSUE THREAD

**Issue by FunkaSaurus** [Xaymar/OBS-AMD-Advanced-Media-Framework#374]
I tried literally everything.

Updated OBS
Updated Drivers
Installed AMD Encoder plugin thing for OBS

For some reason the AMD Codec just won't appear in the OBS output codec box... there's only H24

I'd honestly be in heavens if someone helped me out with this problem...

My specs are:

Graphics: AMD R7 240
RAM: 4 GB [don't mind it, runs everything perfectly lmao]
Processor: Intel(R) Xeon(R) CPU     W3550  @ 3.07GHz

**Comment by Xaymar** [comment]
Please attach an obs log file too

**Comment by Xaymar** [comment]
Also make sure that you've read through the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting) fully, as it contains a link to a list of supported hardware.

**Comment by FunkaSaurus** [comment]
[2019-06-07 20-09-52.txt](https://github.com/obsproject/obs-amd-encoder/files/3266545/2019-06-07.20-09-52.txt)


ay u talkin' bout this mate? ;-; i hope so... i'm new to github. hope i uploaded the right way....


btw i also tested without the argument "--verbose --unfiltered_log" that you see in there.

[didn't work tho.]

**Comment by Xaymar** [comment]
```
20:09:54.078: Loading module: enc-amf.dll
20:09:54.093: [AMF] <obs_module_load> Loading...
20:09:54.276: [AMF] <Plugin::AMD::AMF::AMF> Initializing...
20:09:54.278: [AMF] <Plugin::AMD::AMF::AMF> Loaded 'amfrt64.dll'.
20:09:54.278: [AMF] <Plugin::AMD::AMF::AMF> AMF Library initialized.
20:09:54.278: [AMF Runtime] [20:09:54.278][TraceImpl]    Error: ..\..\..\..\..\runtime\src\core\debug\TraceImpl.cpp(615):Assertion failed:result
20:09:54.278: [AMF] Version 2.5.1 loaded (Compiled: 1.4.9.0, Runtime: 1.4.12.0, Library: 1;4;12;0;19.10.15.05;201905220903;CL#1786102).
20:09:54.278: [AMF] <Plugin::AMD::AMF::AMF> Initialized.
20:09:54.292: [AMF Runtime] [20:09:54.292][TraceImpl]    Error: ..\..\..\..\..\runtime\src\core\debug\TraceImpl.cpp(615):Assertion failed:result
20:09:54.292: [AMF] [Capability Manager] Testing Direct3D 9 API...
20:09:54.319: [AMF Runtime] [20:09:54.319][TraceImpl]    Error: ..\..\..\..\..\runtime\src\core\debug\TraceImpl.cpp(615):Assertion failed:result
20:09:54.320: [AMF] [Capability Manager] Testing Direct3D 9 Adapter 'AMD Radeon R7 200 Series [\\.\DISPLAY1] (VEN_1002/DEV_6613/SUB_20141787/REV_0000)' with codec H264/AVC failed, reason: <Id: 1> Unable to create H264/AVC encoder, error AMF_NOT_SUPPORTED (code 10)
20:09:54.347: [AMF Runtime] [20:09:54.347][TraceImpl]    Error: ..\..\..\..\..\runtime\src\core\debug\TraceImpl.cpp(615):Assertion failed:result
20:09:54.348: [AMF] [Capability Manager] Testing Direct3D 9 Adapter 'AMD Radeon R7 200 Series [\\.\DISPLAY1] (VEN_1002/DEV_6613/SUB_20141787/REV_0000)' with codec H265/HEVC failed, reason: <Id: 2> Unable to create H265/HEVC encoder, error AMF_NOT_SUPPORTED (code 10)
20:09:54.348: [AMF] [Capability Manager] Testing Direct3D 9 Adapter 'AMD Radeon R7 200 Series [\\.\DISPLAY1] (VEN_1002/DEV_6613/SUB_20141787/REV_0000)':
20:09:54.348:   H264/AVC: Not Supported
20:09:54.348:   H265/HEVC: Not Supported
20:09:54.348: 
20:09:54.348: [AMF] [H264/AVC] Not supported by any GPU, disabling...
20:09:54.348: [AMF] [H265/HEVC] Not supported by any GPU, disabling...
20:09:54.348: [AMF] <obs_module_load> Loaded.
```

Pretty clear answer from the log file here, the GPU has no hardware enconding units. If it is an R7 240, it is not supported as shown in the Troubleshooting Guide, section Hardware Support.

**Comment by FunkaSaurus** [comment]
oooh.... is there anything else i can do? :/ other than using that encoder?

**Comment by Xaymar** [comment]
Software encoding or installing a GPU that does have an encoder. See the Troubleshooting Guide for the list of Hardware that has supported hardware encoding units.
