### ISSUE TITLE
Deblocking and Motion Estimation Question.

### ISSUE THREAD

**Issue by Potatotatoo** [Xaymar/OBS-AMD-Advanced-Media-Framework#376]
I Think "Deblocking Filter& Motion Estimation" should be in the "Advanced Setting" ,Disabled Half-Pixel  looks better.

CPU: Intel(R) E3-1231 v3  3.4GHz
GPU: AMD Radeon RX480 8GB/AMD RX550 2GB
RAM: Micron DDR3 16GB 1600Mhz
OS: Windows 10 Pro (18362.175)

**Comment by Xaymar** [comment]
I'm not sure if this is a question or a request.

**Comment by Potatotatoo** [comment]
> I'm not sure if this is a question or a request.

Eeee .... This is a request......

**Comment by Xaymar** [comment]
After much testing and running PSNR, SSIM, VMAF and various other image comparison, the answer is: No. Disabling Motion Estimation options reduced final quality by a few percent in all cases, further reducing the quality we already get from it. You're free to customize the options to your liking, but I will not change the default for this one.
