### ISSUE TITLE
Encoder not showing up (did everything)

### ISSUE THREAD

**Issue by yahiaelpronc** [Xaymar/OBS-AMD-Advanced-Media-Framework#377]
Specs : [Specs.txt](https://github.com/obsproject/obs-amd-encoder/files/3347413/Specs.txt)
OBS 23.2.1
encoder 2.5.1
amd 19.6.3 drivers

description : i did every solution i can make , i searched every forum i can search for the past few days to know why OBS ain't showin my encoder , i got all settings right , i got a card that has VCE generation one so it is supported , even posted a thread on the forums and tried to solve it on a span of couple of days [here](https://obsproject.com/forum/threads/c0000005-crash-on-startup.107890/) , nothing never works and the last resort ( as adviced by other members ) is to contact the devs

P.S : the encoder isn't showing so idk where the "debug" button at, so i uploaded a log with the problem happening [here](https://obsproject.com/logs/r-ajbuuPqmYXlk2U)

**Comment by Xaymar** [comment]
```
23:41:43.382: [AMF] [Capability Manager] Testing Direct3D 11 Adapter 'AMD Radeon (TM) R5 M335 (VEN_1002/DEV_6660/SUB_6b21028/REV_0081)':
23:41:43.382:   H264/AVC: Not Supported
23:41:43.382:   H265/HEVC: Not Supported
```

According to your own hardware, there is no encoder on that card. Be aware that R# M### cards do not always have encoding units, but I don't know why - so I chose to just test if it's possible to initialize the encoder, if not it won't show up.

**Comment by yahiaelpronc** [comment]
initialize the encoder ?
and that means there is absolutely nothing i can do , thanks a bunch tho

**Comment by Xaymar** [comment]
> initialize the encoder ?

Means to just try and start encoder with the basic settings, to see if the encoder actually works. If it doesn't work, there's no use displaying it either.

**Comment by yahiaelpronc** [comment]
sorry if i'm being stupid here , how can i start it if the option to choose it is not showin up?

**Comment by Xaymar** [comment]
The test (initialize the encoder) runs automatically at obs start. If it's not able to start the encoder, the encoder will not show up as you can see, as there is no point in listing an encoder which doesn't work.

**Comment by yahiaelpronc** [comment]
i see , thanks a lot
