### ISSUE TITLE
Getting encoded overloaded.

### ISSUE THREAD

**Issue by renk4** [Xaymar/OBS-AMD-Advanced-Media-Framework#383]
When I try to record in 240fps of Minecraft, I get encoding overloaded, IDK anymore what settings to use, I had an older GTX 1050 Ti that could do it in a breath, Any ideas? Resolution I record in is 1280x660.

OS: Windows 10 64bit
CPU: i5-4590 3.30GHz
RAM: 16GB DDR3 1600MHz
GPU: MSI Armored Radeon RX 590

**Comment by Xaymar** [comment]
Your issue does not follow the [Troubleshooting Guide](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/wiki/Guide%3A-Troubleshooting). Please make sure to read it thoroughly before reporting issues. Thank you.

**Comment by Xaymar** [comment]
Closing as there has not been a reply in a full month.
