### ISSUE TITLE
Cannot Initialize output for Hardware Encoder

### ISSUE THREAD

**Issue by SpeederFlash** [Xaymar/OBS-AMD-Advanced-Media-Framework#387]
### Description
AMD H264 and H265 encoders will not initialize. Specific error code of "Starting the output failed." This persisted even after a clean install of VC 2017, OBS Studio, the plugin, and DDUing the graphics driver.

### Expected Behavior
It should start streaming or recording, but the output fails.

### Reproduction Steps
Create a new profile, change stream and or recording encoder to H264 or H265. Press start recording or streaming, the same error occurs.

### System Information
- Software Version: OBS 24.0.3, Plugin version 2.6.0
- Operating System: Windows 10
- Kernel Version:1909
- CPU: Ryzen 2600
- GPU: RX 5700 XT
- RAM: 16GB

### Checklist:
- [x] I have read the contribution guidelines.
- [x] I can reproduce the issue with the exact reproduction steps I have provided.
- [x] The issue appears on all of my systems that can run this software.
Log File: [2019-11-18_16-15-53.txt](https://github.com/obsproject/obs-amd-encoder/files/3860694/2019-11-18_16-15-53.txt)

**Comment by Xaymar** [comment]
```
16:15:59.019: [AMF] 2019-11-18 16:15:59.018     3360 [AMFComputeKernelImpl]   Error: ..\..\..\..\..\runtime\src\core\ProgramsComputeImpl.cpp(405):OpenCL failed, error = -42:BinaryProgram::Compile() clCreateProgramWithBinary() failed (-42)
16:15:59.019: 
16:15:59.019: [AMF] 2019-11-18 16:15:59.018     3360 [AMFComputeKernelImpl]   Error: ..\..\..\..\..\runtime\src\core\ProgramsComputeImpl.cpp(164):AMF_ERROR 19 : AMF_OPENCL_FAILED: LoadProgram() - failed
16:15:59.019: 
16:15:59.019: [AMF] 2019-11-18 16:15:59.018     3360 [AMFComputeKernelImpl]   Error: ..\..\..\..\..\runtime\src\core\ProgramsComputeImpl.cpp(704):AMF_ERROR 19 : AMF_OPENCL_FAILED: GetKernel.CreateProgram failed
16:15:59.019: 
16:15:59.019: [AMF] 2019-11-18 16:15:59.018     3360 [AMFDeviceComputeImpl]   Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImpl.cpp(1962):AMF_ERROR 19 : AMF_OPENCL_FAILED: AMFProgramsCompute::Get().GetProgram(kernelID, (void**)&clProgramTmp, &buildID, this)
16:15:59.019: 
16:15:59.019: [AMF] 2019-11-18 16:15:59.018     3360 [AMFDeviceComputeImpl]   Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImpl.cpp(1873):AMF_ERROR 19 : AMF_OPENCL_FAILED: GetKernel(zeroBufferKernelID, &m_pKernelZeroBufferUChar)
16:15:59.019: 
16:15:59.019: [AMF] 2019-11-18 16:15:59.018     3360 [AMFDeviceComputeImpl]   Error: ..\..\..\..\..\runtime\src\core\DeviceComputeImpl.cpp(1819):AMF_ERROR 19 : AMF_OPENCL_FAILED: PostInit()
16:15:59.019: 
16:15:59.019: [AMF] 2019-11-18 16:15:59.018     3360 [AMFContextImpl]   Error: ..\..\..\..\..\runtime\src\core\ContextImpl.cpp(340):AMF_ERROR 19 : AMF_OPENCL_FAILED: pDeviceOpenCL->Init(pCommandQueue)
16:15:59.022: [AMF] <Id: 3> Unable to initialize converter, error AMF_OPENCL_FAILED (code 19)
```

Disable OpenCL if you have it enabled.

**Comment by SpeederFlash** [comment]
Which specific settings? I went through every setting in output with Master view and disabled everything saying OpenCL, error still persists.

New Log File, all OpenCL settings I found disabled: [2019-11-19 14-09-35.txt](https://github.com/obsproject/obs-amd-encoder/files/3865624/2019-11-19.14-09-35.txt)

**Comment by Xaymar** [comment]
Unfortunately this doesn't seem to be a bug in the plugin, more of a problem with the driver. Have you tried reinstalling the driver using Display Driver Uninstaller? If that doesn't work, then unfortunately there isn't much I can do.

**Comment by Xaymar** [comment]
It has been more than a month since I suggested a solution, with no answer. I will close this on 7th January 2020 if there is no further reply from the creator.
