### ISSUE TITLE
Windows 1909 update breaks obs desktop capture while useing nvidia control panel

### ISSUE THREAD

**Issue by some1else1999** [Xaymar/OBS-AMD-Advanced-Media-Framework#388]
I know filling out this form completely helps you but this is simple to recreate and most likely not simple to fix

1.obs works fine using the nvida control panel to force obs to use integrated graphics.

2.install win 1909 update
obs will not allow screen capture (shows black screen). obs log file shows that obs is being run by nvidia.   go to nvida control panel and it tells me i am using my integrated  graphics card.  bang head on desk

3. uninstall win 1909 update

4 return to step 1

here is a forum post about this issue with some log files (i think 1)  
https://obsproject.com/forum/threads/black-screen-on-display.112587/

To the person that is reading this you are under appreciated and i hope that the fleas of a million camels infest the crotch of your enemy (yes i realize this may be me) 
(insert witty nonsense about having a great day here)

I do not expect a reply or even a acknowledgement of my issue as that i have not filled out your form correctly

**Comment by jp9000** [comment]
Are you in the correct repository?  You're making this in the AMD encoder repository.  It has nothing to do with NVIDIA and display capture.  I think you meant to file this in the obs-studio repository:  https://github.com/obsproject/obs-studio

We're also aware of the nvidia control panel issue, although you're still free to file the report there if you'd like if it's not already there.

Also although we appreciate the sentiment, preferably might want to exclude the fleas comment, hah.  Thank you however.
