### ISSUE TITLE
Recording broken with new Radeon Driver 19.12.2

### ISSUE THREAD

**Issue by DifferentialityDevelopment** [Xaymar/OBS-AMD-Advanced-Media-Framework#391]
## Expected Behavior
Using AMD Hardware Encoder, I should be able to record videos using my Radeon GPU,
In my case I'm using a Vega 64, upon selecting stop recording, it should stop the recording.

## Current Behavior
With the latest Radeon Driver, OBS is no longer able to record, the file is never created, but OBS says it is recording. Upon selecting Stop Recording it changes to "Stopping Recording" but does not do anything, and you have to force close the process.

## Steps to Reproduce

1. Install latest OBS, Latest Radeon Drivers, Latest AMD Encoder OBS Extension.
2. Select AMD Hardware Encoder as the encoder as try recording.
3. Try stopping the recording.
4. No recording will be created, and the OBS process is also needs to be force closed.

## Additional information
While I'm not sure if this is a problem with the encoder or with the drivers itself. 
I just felt someone should report this issue as it was working perfectly fine before the new drivers were installed.
Backtracking to the older drivers is highly discouraged as well, as the new drivers bring a host of very important features.

**Comment by Xaymar** [comment]
If it happens only with the new drivers, the problem is likely with AMD. This would be another issue on top of the new drivers causing massively lower performance at random.

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
