### ISSUE TITLE
5120x2160 resolution support?

### ISSUE THREAD

**Issue by importnil** [Xaymar/OBS-AMD-Advanced-Media-Framework#394]
### Description

Hello. I'm running a 5120x2160 (LG 34WK95U) display on AMD Radeon 5700 XT and trying to record or stream with this resolution results in an AMT_FAIL error, like no drivers are presented. Tried a 4096x2160 resolution and recording worked perfectly smooth.

Will there be support in a near future for such a resolution? Thanks!

**Comment by Xaymar** [comment]
Support for resolutions is given by the Hardware, and the Driver. The plugin has no say over this. Please contact AMD for this.
