### ISSUE TITLE
Need HD6850 Support

### ISSUE THREAD

**Issue by KenyMylankca** [Xaymar/OBS-AMD-Advanced-Media-Framework#398]
Can i get help for Amd HD6850 encoder support in OBS? We very very need it! Please help. Thanks.

**Comment by jp9000** [comment]
If you mean you need general support, please use either our forums or support channels on discord.  If you mean you want encoder support that doesn't already exist, then you're likely out of luck.  Especially if it was released like 10 years ago like the HD6850 was.

**Comment by KenyMylankca** [comment]
This is just so rude you behave. I still have an HD6850 and don't have money to buy a newer one and need this encoder support to use it in OBS, and that's all. But you don't care. I hope you face with such a similar bad thing in your life, just like how this now.

**Comment by dodgepong** [comment]
This has nothing to do with OBS supporting it. Your card literally doesn't have the hardware encoder on it. It is _impossible_ for _anybody_ to add AMF support for your card.
