### ISSUE TITLE
Nothing happens when I click Record

### ISSUE THREAD

**Issue by TUTCMO** [Xaymar/OBS-AMD-Advanced-Media-Framework#40]
As is stated in the title, nothing happens when I click Record. It doesn't start recording. I only have this problem this encoder. x264, QSV, etc., all work fine. 
[2016-08-21 14-35-29.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/429013/2016-08-21.14-35-29.txt)

**Comment by Xaymar** [comment]
Are you sure you want to record at 9kbit/s? Make sure to set the values in the Advanced interface in **bits**, not kbits. If you don't want that much control, use the simple interface. Also upgrade to 1.2.0rc1, it contains some fixes for issues.

```
14:35:41.377: [AMF Encoder 1.2.0pre2] <AMFEncoder::VCE_H264_Encoder::VCE_H264_Encoder> Initializing...
14:35:41.377: [AMF Encoder 1.2.0pre2] <AMFEncoder::VCE::H264> Attempting to create AVC Encoder...
14:35:41.399: [AMF Encoder 1.2.0pre2] <AMFEncoder::VCE::SetMemoryType> Set to Host.
14:35:41.399: [AMF Encoder 1.2.0pre2] <AMFEncoder::VCE::SetSurfaceFormat> Set to NV12.
14:35:41.399: [AMF Encoder 1.2.0pre2] <AMFEncoder::VCE::SetUsage> Set to Transcoding.
14:35:41.399: [AMF Encoder 1.2.0pre2] <AMFEncoder::VCE::SetFrameSize> Set to 2560x1440.
14:35:41.400: [AMF Encoder 1.2.0pre2] <AMFEncoder::VCE::SetFrameRate> Set to 60/1.
14:35:41.400: [AMF Encoder 1.2.0pre2] <AMFEncoder::VCE::SetRateControlMethod> Set to Constant Bitrate.
14:35:41.400: [AMF Encoder 1.2.0pre2] <AMFEncoder::VCE::EnableFillerData> Set to Enabled.
14:35:41.400: [AMF Encoder 1.2.0pre2] <AMFEncoder::VCE::SetInitialVBVBufferFullness> Set to 1.000000.
14:35:41.400: [AMF Encoder 1.2.0pre2] <AMFEncoder::VCE::SetTargetBitrate> Failed to set to 9000, error AMF_OUT_OF_RANGE (code 5).
```

**Comment by TUTCMO** [comment]
So it works now. 

I just followed the settings here: https://github.com/Xaymar/OBS-AMD-Media-Framework/wiki/Tested-Configurations

What settings should I use to get a higher quality recording? Would it be possible to get a lossless recording? 

And IDK what you mean by bits. Is that megabits?

**Comment by Xaymar** [comment]
If you want a higher quality recording, just increase the bitrate - eventually you'll get near-lossless quality. You could also try CQP (Constant QP) with QP values of 0 or 1, if you have the 1.3.0 preview build.

What I meant by bits is that the Bitrate is in bits. As in, 1 kbit = 1000 bits, so your value should be 9000000 instead of 9000. This is a common mistake many people make due to other encoder plugins using the wrong terminology.

**Comment by TUTCMO** [comment]
I see.

Thank you.
