### ISSUE TITLE
AMD FX9800P Graphics - Radeon R8 M445DX Test Results

### ISSUE THREAD

**Issue by cmogul** [Xaymar/OBS-AMD-Advanced-Media-Framework#402]
Per Your Instructions I ran a test on my video card.  I have attached the zip file for H264 and H265.  Thank you for your help!
Here is the link to the file on my GDrive as it is too big for the site: https://drive.google.com/file/d/1S1ATmXjyTIbAgcfTxjxeQxlgHsXoAko5/view?usp=sharing

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
