### ISSUE TITLE
Add AMD 5600XT Support?

### ISSUE THREAD

**Issue by SarahSzabo** [Xaymar/OBS-AMD-Advanced-Media-Framework#403]
I'm currently using a 5600XT and it would be pretty cool to be able to use it for OBS.

I couldn't say what percentage of AMD cards are the 56000XT though. I would think that adding 5600XT support might be relatively straightforward since I think 5600XT shares a lot in common with the 5700 and is often described as a stripped down version of the 5700.

```
Graphics:  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] driver: amdgpu v: kernel 
           Display: x11 server: X.Org 1.20.8 driver: amdgpu FAILED: ati unloaded: modesetting,radeon 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz, 1920x1080~75Hz 
           OpenGL: renderer: AMD Radeon RX 5600 XT (NAVI10 DRM 3.37.0 5.7.9-1-MANJARO LLVM 10.0.0) 
           v: 4.6 Mesa 20.1.3
```

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
