### ISSUE TITLE
Encoder failure with Radeon 530 video card

### ISSUE THREAD

**Issue by mmateusmedeiros** [Xaymar/OBS-AMD-Advanced-Media-Framework#404]
Dear has a configuration on my computer with AMD Ryzen 5 2500 processor with a Radeon 530 video card, but whenever I try to use the amd encoder for recording or transmission I get the message "impossible to output the video - NVENC or AMD". I analyzed the log and found that the obs does not run the encoder, I believe there is a problem with the plugin. I'm using the latest video card driver update, version 20.4.2.

Attached is the log of the aforementioned operation!

[2020-07-28 08-37-39.txt](https://github.com/obsproject/obs-amd-encoder/files/4988049/2020-07-28.08-37-39.txt)

**Comment by Xaymar** [comment]
[The Radeon 530 does not have decode or encode support](https://www.amd.com/en/products/graphics/radeon-530)

**Comment by codinjutsu** [comment]
I installed the encoder but its not working on my obs studio. I'm using Radeon5 M330 and I updated it to the latest version 2020.12.1. But still not yet showing up on my obs

**Comment by Xaymar** [comment]
[The Radeon 5 M330 also does not appear to have decode or encode support](https://www.amd.com/en/support/graphics/amd-radeon-r5-series/amd-radeon-r5-300-series/amd-radeon-r5-m330)

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
