### ISSUE TITLE
I can't Change Target Bitrate in OBS Output Steaming Setting

### ISSUE THREAD

**Issue by supperpee2** [Xaymar/OBS-AMD-Advanced-Media-Framework#406]
I can't Change Target Bitrate in OBS Output Steaming Setting
win 10
VGA : RX5700XT

[https://imageupload.io/kkc7PJ8MPi.i](url)
![2020-11-20_10-41-42](https://user-images.githubusercontent.com/74752066/99755406-4c5ad800-2b1d-11eb-8c1c-6478fe807b38.png)

**Comment by Gol-D-Ace** [comment]
First up when reporting bugs please do not delete the template in the text box and fill it out entirely.

This is a known issue with new AMD drivers. Please downgrade your driver (try 20.11.1) or wait until AMD fixes the issue.

Therefore this is not an issue caused by OBS.
