### ISSUE TITLE
Display capture not working with AMD Ryzen 5 4600H processor

### ISSUE THREAD

**Issue by prateekkrjain** [Xaymar/OBS-AMD-Advanced-Media-Framework#408]
### Description
I am trying to use OBS Studio's Display Capture feature on the AMD Ryzen 5 4600H processor, but it is not working and showing a black screen. While, when I try to use the Window capture feature it works perfectly.

### Expected Behavior
The display capture feature should capture the entire screen and now show the black screen.

### Reproduction Steps
1. Install OBS Studio x64 from the website
2. Also, install the AMD encoder
3. Open the OBS Studio with or without Administrator privileges, and add the Display Capture in the Sources section.
4. Ideally after adding the Display Capture in the Sources section, it should start capturing the screen.

### System Information
- Software Version: 26.0.2
- Operating System: Windows 10
- Kernel Version: Windows
- CPU: AMD Ryzen 5 4600H
- GPU: NVIDIA 1650 Ti
- RAM: 8 GB

### Checklist:
- [x ] I have read the contribution guidelines.
- [x ] I can reproduce the issue with the exact reproduction steps I have provided.
- [x ] The issue appears on all of my systems that can run this software.

**Comment by RytoEX** [comment]
The AMD Encoder Plugin has nothing to do with the Display Capture source in OBS.

Please use the Discord or forums for assistance getting display capture working on your system.
