### ISSUE TITLE
Bitrate problem - RX 5700 XT

### ISSUE THREAD

**Issue by Gabri404** [Xaymar/OBS-AMD-Advanced-Media-Framework#409]
Hello
I have a RX 5700 XT, I am attaching the link if it can help
(https://amzn.to/3haB4D4)

My problem is with all versions of this "Plugin". Once installed it is not possible for me to change the bitrate, I can only enter "1 or 0". I attach link (https://i.imgur.com/duKbSy5.png)

Obviously once I encountered this error, my only way to fix it was to reinstall OBS studio from scratch.

But using an RX 5700 XT, I have serious problems when streaming in 1600x900 30 fps at 6000 bitrate, with a lot of image grain. I believed your "Plugin" could help me, if so, how can I fix this Bitrate error?

**Comment by stasko48** [comment]
One fix I found is to downgrade your drivers. I tried 20.4.2 and it works there. Or use Streamlabs.

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
