### ISSUE TITLE
RX 5700 support b-frames?

### ISSUE THREAD

**Issue by stasko48** [Xaymar/OBS-AMD-Advanced-Media-Framework#410]
Using driver version 20.12.1. On the H264 encoder, although I cannot set any bitrate other than 0 or 1. There is an option for setting b frames in master view, which wasn't present on previous drivers other than 20.11.2. I tried recording a file, using CQP setting the B-Frame Period to 1. However, using avidemux, it does not show any b frames. Is it a bug?

**Comment by lextra2** [comment]
amf does not support b-frames. not for avc, not for hevc and doesn't matter what gpu you use.

**Comment by Benman2785** [comment]
i always thought R9 380 and 380X and 385 support b-frames for AMD AMF VCE

**Comment by macchky** [comment]
5700 **NOT** support B-frames.

**Comment by Poilaucul** [comment]
B-Frame support has been added a couple months ago, now OBS needs to support it.
Source: https://www.tomshardware.com/news/amd-amf-encoder-quality-boost

**Comment by lextra2** [comment]
> B-Frame support has been added a couple months ago, now OBS needs to support it. Source: https://www.tomshardware.com/news/amd-amf-encoder-quality-boost

https://github.com/obsproject/obs-studio/pull/6508
As you can see, a new amf plugin for obs is being worked on. But B-frames is only for Rdna2 gpus (6000series)

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
