### ISSUE TITLE
Sudden OBS Studio Crashes while streaming

### ISSUE THREAD

**Issue by TeeKaybeebop** [Xaymar/OBS-AMD-Advanced-Media-Framework#413]
Full System Specifications
Processor: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz 2.90 GHz
RAM: 16.0 GB
x64-based Windows
Windows build: Windows 10 Pro
Windows version: 20H2
OS Build: 19042.685
Motherboard: ASRock, H310CM-DVS
BIOS Mode: UEFI
BIOS Version/Date: American Megatrends Inc. P4.20, 2019-05-14

Installed Open Broadcaster Software Studio Version
26.1.1

Installed Plugin Version
64bit version

Installed AMD Driver Version 
I don't run AMD Driver. My computer runs on: NVIDIA GeForce GTX 1660 SUPER
DAC Type: Integrated RAMDAC

The latest/current log file from Open Broadcaster Software Studio showing the Issue (start OBS with --verbose --log_unfiltered --
unfiltered_log as parameter and tick the Debug option in the encoder!)
From C:\Users\ytg06\AppData\Roaming\obs-studio\logs:
21:05:04.798: 	Game DVR: On
21:05:04.798: 	Game DVR Background Recording: Off
21:05:04.805: Sec. Software Status:
21:05:04.806: Current Date/Time: 2021-01-16, 21:05:04
21:05:04.806: Browser Hardware Acceleration: true
21:05:04.806: Portable mode: false
21:05:05.192: OBS 26.1.1 (64-bit, windows)
21:05:05.192: ---------------------------------
21:05:05.193: ---------------------------------
21:05:05.193: audio settings reset:
21:05:05.193: 	samples per sec: 48000
21:05:05.193: 	speakers:        2
21:05:05.196: ---------------------------------
21:05:05.196: Initializing D3D11...
21:05:05.196: Available Video Adapters: 
21:05:05.198: 	Adapter 0: NVIDIA GeForce GTX 1660 SUPER
21:05:05.198: 	  Dedicated VRAM: 1987051520
21:05:05.198: 	  Shared VRAM:    4260335616
21:05:05.198: 	  PCI ID:         10de:21c4
21:05:05.199: 	  Driver Version: 26.21.14.4108
21:05:05.199: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=60, name=S24F350
21:05:05.202: Loading up D3D11 on adapter NVIDIA GeForce GTX 1660 SUPER (0)
21:05:05.313: D3D11 loaded successfully, feature level used: b000
21:05:05.313: DXGI increase maximum frame latency success
21:05:05.313: D3D11 GPU priority setup success
21:05:05.717: ---------------------------------
21:05:05.717: video settings reset:
21:05:05.717: 	base resolution:   1920x1080
21:05:05.717: 	output resolution: 1280x720
21:05:05.717: 	downscale filter:  Bicubic
21:05:05.717: 	fps:               30/1
21:05:05.717: 	format:            NV12
21:05:05.717: 	YUV mode:          709/Partial
21:05:05.717: NV12 texture support enabled
21:05:05.718: Audio monitoring device:
21:05:05.718: 	name: default
21:05:05.718: 	id: default
21:05:05.721: ---------------------------------
21:05:05.728: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
21:05:05.730: Failed to load 'en-US' text for module: 'decklink-captions.dll'
21:05:05.731: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
21:05:05.771: [AMF] Unable to load 'amfrt64.dll', error code 126.
21:05:05.774: [AMF] AMF Test failed due to one or more errors.
21:05:05.774: Failed to initialize module 'enc-amf.dll'
21:05:05.818: [obs-browser]: Version 2.9.1
21:05:05.818: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
21:05:05.829: NVENC supported
21:05:05.980: Couldn't find VLC installation, VLC video source disabled
21:05:06.004: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
21:05:06.005: No blackmagic support
21:05:06.040: ---------------------------------
21:05:06.040:   Loaded Modules:
21:05:06.040:     win-wasapi.dll
21:05:06.040:     win-mf.dll
21:05:06.040:     win-dshow.dll
21:05:06.040:     win-decklink.dll
21:05:06.040:     win-capture.dll
21:05:06.040:     vlc-video.dll
21:05:06.040:     text-freetype2.dll
21:05:06.040:     rtmp-services.dll
21:05:06.040:     obs-x264.dll
21:05:06.040:     obs-vst.dll
21:05:06.040:     obs-transitions.dll
21:05:06.040:     obs-text.dll
21:05:06.040:     obs-qsv11.dll
21:05:06.040:     obs-outputs.dll
21:05:06.040:     obs-filters.dll
21:05:06.040:     obs-ffmpeg.dll
21:05:06.040:     obs-browser.dll
21:05:06.040:     image-source.dll
21:05:06.040:     frontend-tools.dll
21:05:06.040:     enc-amf.dll
21:05:06.040:     decklink-ouput-ui.dll
21:05:06.040:     decklink-captions.dll
21:05:06.040:     coreaudio-encoder.dll
21:05:06.040: ---------------------------------
21:05:06.040: ==== Startup complete ===============================================
21:05:06.051: All scene data cleared
21:05:06.052: ------------------------------------------------
21:05:06.497: WASAPI: Device 'Headphones(High Definition Audio Device)' [48000 Hz] initialized
21:05:06.497: [Loaded global audio device]: 'Desktop Audio'
21:05:06.543: WASAPI: Device 'Mic(USB2.0 MIC)' [48000 Hz] initialized
21:05:06.544: [Loaded global audio device]: 'Mic/Support'
21:05:06.544: Switched to scene 'Scene'
21:05:06.544: ------------------------------------------------
21:05:06.544: Loaded scenes:
21:05:06.544: - scene 'Scene':
21:05:06.544: ------------------------------------------------
21:05:06.583: adding 64 milliseconds of audio buffering, total audio buffering is now 64 milliseconds (source: 마이크/보조)
21:05:06.583: 
21:06:26.099: [duplicator-monitor-capture: 'Display Capture'] update settings:
21:06:26.099: 	display: 1 (1920x1080)
21:06:26.099: 	cursor: true
21:06:26.103: User added source 'Display Capture' (monitor_capture) to scene
21:06:27.686: [duplicator-monitor-capture: 'Display Capture'] update settings:
21:06:27.686: 	display: 1 (1920x1080)
21:06:27.686: 	cursor: false
21:06:35.044: User added source 'Video Capture Device' (dshow_input) to scene 'Scene'
21:06:35.049: Video Capture Device: DecodeDeviceId failed
21:06:35.049: Video Capture Device: Video configuration failed
21:06:35.172: ---------------------------------
21:06:35.173: [DShow Device: 'Video Capture Device'] settings updated: 
21:06:35.173: 	video device: USB2.0 PC CAMERA
21:06:35.173: 	video path: \\?\usb#vid_1908&pid_2310&mi_00#6&3180fc4b&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
21:06:35.173: 	resolution: 640x480
21:06:35.173: 	flip: 0
21:06:35.173: 	fps: 30.00 (interval: 333333)
21:06:35.173: 	format: YUY2
21:06:37.986: ---------------------------------
21:06:37.986: [DShow Device: 'Video Capture Device'] settings updated: 
21:06:37.986: 	video device: USB2.0 PC CAMERA
21:06:37.986: 	video path: \\?\usb#vid_1908&pid_2310&mi_00#6&3180fc4b&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
21:06:37.986: 	resolution: 640x480
21:06:37.986: 	flip: 0
21:06:37.986: 	fps: 30.00 (interval: 333333)
21:06:37.986: 	format: YUY2
21:07:21.257: User added source 'Browser' (browser_source) to scene 'Scene'
21:09:37.524: User added filter 'Color Filter' (color_filter) to source 'Browser'
21:10:56.031: Settings changed (stream 1)
21:10:56.031: ------------------------------------------------
21:11:28.562: [jim-nvenc: 'simple_h264_stream'] settings:
21:11:28.562: 	rate_control: CBR
21:11:28.562: 	bitrate:      2500
21:11:28.562: 	cqp:          20
21:11:28.562: 	keyint:       60
21:11:28.562: 	preset:       hq
21:11:28.562: 	profile:      high
21:11:28.562: 	width:        1280
21:11:28.562: 	height:       720
21:11:28.562: 	2-pass:       false
21:11:28.562: 	b-frames:     2
21:11:28.562: 	lookahead:    false
21:11:28.562: 	psycho_aq:    true
21:11:28.562: 
21:11:28.569: ---------------------------------
21:11:28.569: [FFmpeg aac encoder: 'simple_aac'] bitrate: 160, channels: 2, channel_layout: 3
21:11:28.569: 
21:11:28.574: [rtmp stream: 'simple_stream'] Connecting to RTMP URL rtmp://sel01.contribute.live-video.net/app...
21:11:28.582: [rtmp stream: 'simple_stream'] Interface: Realtek PCIe GbE Family Controller (ethernet, 1000 mbps)
21:11:30.192: [rtmp stream: 'simple_stream'] Connection to rtmp://sel01.contribute.live-video.net/app successful
21:11:30.196: ==== Streaming Start ===============================================
21:16:03.853: [duplicator-monitor-capture: 'Display Capture'] update settings:
21:16:03.853: 	display: 1 (1920x1080)
21:16:03.853: 	cursor: true

Full Description of the Issue
Whenever I run my OBS Studio, whether it be few seconds or few minutes,
it just suddenly crashes and closes the application immediately without any warning.
I tried to check for any crash logs, since the crash happens when I am live streaming very often,
but I cannot find any traces of a crash under my "crashes" folder.

All I can find are the logs under "C:\Users\ytg06\AppData\Roaming\obs-studio\logs".

Please let me know if there are specific steps I can do to avoid this from happening ever again.

Sincerely,
An OBS User.

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
