### ISSUE TITLE
My stream's quality is bad and idk how to improve

### ISSUE THREAD

**Issue by filuu** [Xaymar/OBS-AMD-Advanced-Media-Framework#416]
### Description
I have problems with quality. 
I tried everything but it didn't improve.
Here's what I see: 
![me](https://user-images.githubusercontent.com/78280087/106369115-145ae700-634f-11eb-9ab9-546352bb3b8a.png)
Here's what stream sees: 
![stream](https://user-images.githubusercontent.com/78280087/106369118-1ae95e80-634f-11eb-95df-f646b1ce884c.png)
I changed bitrate, encoder, rate control method and it didnt work.
The quality, color is different.

I stream on youtube.
Here are my settings:
![image](https://user-images.githubusercontent.com/78280087/106369186-803d4f80-634f-11eb-88da-a8a8b2be2d6a.png)
![image](https://user-images.githubusercontent.com/78280087/106369194-96e3a680-634f-11eb-9df0-6384d52325b0.png)

### System Information
I use 1920x1080 60hz monitor (and stream 1920x1080 30 fps)
- Software Version: 26.1.0 (64bit, Windows)
- Operating System: Windows 10, 64bit
- Kernel Version: idk what's that i use windows 10
- CPU: AMD FX 8350, 8-core, 4,00GHz
- GPU: radeon r9 270x
- RAM: 8gb

### Checklist:
- [x ] I have read the contribution guidelines.
- [x ] This is not a bug, crash or generic issue.

**Comment by Benman2785** [comment]
...

1080p30 with only 3500kbps...
try 6000kbps // you need 10MBit/s upload for that
also use this settings:
![image](https://user-images.githubusercontent.com/21282980/107131359-d07b5b00-68d5-11eb-9332-79f4facfe362.png)
