### ISSUE TITLE
AMD Radeon HD 5750

### ISSUE THREAD

**Issue by RadoslavL** [Xaymar/OBS-AMD-Advanced-Media-Framework#419]
I tested my gpu using the performance test. Here are the results -
[Results.zip](https://github.com/obsproject/obs-amd-encoder/files/6565976/Results.zip)

**Comment by flaeri** [comment]
Hello @rlelchev 
This isnt really the right place to post something like this. This is for bug/reports issues, and you seem to have wiped the template, and just posted some performance results.

**Comment by RadoslavL** [comment]
I am really sorry. I think i saw a text on the github page telling me to post my results here. Sorry for wasting your time on this!
