### ISSUE TITLE
Missing AMF Library crashes Plugin at startup

### ISSUE THREAD

**Issue by NAICOLAS** [Xaymar/OBS-AMD-Advanced-Media-Framework#42]
Installed the lastest build, with of course removing the previous one. OBS crashes straight away. Please help. https://app.box.com/s/ozo3ga4fz1yu15ufsuyxvplkvk2siy7g

**Comment by max20091** [comment]
also post log file, not just crash file

**Comment by NAICOLAS** [comment]
https://gist.github.com/6001085fb5113ec331acac4809053e07

I'm guessing the lack of the AMF files is the case. Where should everything be installed since I can't really find the Exact folder to paste them in... obs-studio root folder?

**Comment by Xaymar** [comment]
If that DLL is missing, make sure that you have driver version 16.7.2 or newer. I personally only recommend using versions older than that for cards that pre-date anything that uses GCN/VCE.

**Comment by hymccord** [comment]
You have a GTX 750 Ti. This is for AMD...

**Comment by NAICOLAS** [comment]
I was under the impression that this would work with the APU on my CPU..? It has computing cores and should be eligable for use.

Guessing I was wrong then!

**Comment by hymccord** [comment]
It'll work for your APU. It's GCN 2.0. You still need the drivers for it.

**Comment by NAICOLAS** [comment]
Yeah, I noticed that it started working once I connected my monitor to the built-in APU(IGFX). 
Wasn't too obvious since it should be registered either way logically, but no.

**Comment by lonjil** [comment]
I am also having this problem, same dll same error code. I have a 390x with the 16.7.3 driver. Monitor is connected to the card.
Startup log: https://gist.github.com/lonjil/f86f65f5dd08498f3d7ac917c1e2a24b
Crash log: https://gist.github.com/lonjil/6234a574d2206268e23e74a3f7781ec4

**Comment by Xaymar** [comment]
@lonjil Same LoadLibraryW error as everyone else:
`17:34:15.384: [AMF Encoder] <Plugin::AMD::AMF::AMF> Loading of 'L"amfrt64.dll"' failed with error code 126.`

For whatever reason, it can't find amfrt64.dll in system32. You can try searching for it and manually appending the path where you found it to the PATH system variable so that LoadLibrary can see it.

**Comment by Xaymar** [comment]
In theory, 1.3.0pre3 should have fixed it.

**Comment by Xaymar** [comment]
Can't reproduce this anymore, if it happens again please open a new issue.
