### ISSUE TITLE
AMF HEVC doesn't stop recording

### ISSUE THREAD

**Issue by reDBo0n** [Xaymar/OBS-AMD-Advanced-Media-Framework#421]
### Description
I've tried to record with the HEVC Encoder, but everytime I use it OBS can't stop the Recording (or the replay buffer). Only option is to kill the process. Recording with AVC or x264 works just fine.

### System Information
- OBS Studio 27.0.1
- Windows 10 21H1
- AMD Ryzen 7 1700 OC@3.8GHz
- AMD Radeon RX 5700 (with 5700XT BIOS)
- Radeon Software 21.6.2
- 16GB Ram @ 3GHz

Log file
[2021-07-01 15-32-37.txt](https://github.com/obsproject/obs-amd-encoder/files/6748639/2021-07-01.15-32-37.txt)

**Comment by PxCommoner** [comment]
I am having the same issue as well.

Log file
[2021-07-15 04-16-14.txt](https://github.com/obsproject/obs-amd-encoder/files/6825665/2021-07-15.04-16-14.txt)

It might have to do with the Radeon drivers

**Comment by reDBo0n** [comment]
Issue got fixed on Radeon™ Software Adrenalin 21.8.2
