### ISSUE TITLE
Unable to initialize converter, error AMF_OPENCL_FAILED (code 19)

### ISSUE THREAD

**Issue by Shahed0631j** [Xaymar/OBS-AMD-Advanced-Media-Framework#424]
I am using Intel pentium g4400 with 8gb ddr4 ram amd asus h110mk motherboard, 120 GB transcend ssd
recently I've added asus r7 360 oc 2gb ddr5 v2 graphics card ,
I had installed amd driver adrenalin-2020-21.5.2 , in obs it shows h254/AVF,,, but when I select and try to record or stream it says
'starting the output failed. please check the log for more details '
and in the log it says
"Unable to initialize converter, error AMF_OPENCL_FAILED (code 19)"
please help me
Detailed log:
11:24:21.478: CPU Name: Intel(R) Pentium(R) CPU G4400 @ 3.30GHz
11:24:21.479: CPU Speed: 3312MHz
11:24:21.479: Physical Cores: 2, Logical Cores: 2
11:24:21.479: Physical Memory: 8130MB Total, 4963MB Free (NOTE: 32bit programs cannot use more than 3gb)
11:24:21.479: Windows Version: 10.0 Build 19043 (release: 2009; revision: 1083; 64-bit)
11:24:21.479: Running as administrator: false
11:24:21.479: Aero is Enabled (Aero is always on for windows 8 and above)
11:24:21.479: Windows 10 Gaming Features:
11:24:21.479: 	Game Bar: On
11:24:21.479: 	Game DVR: On
11:24:21.479: 	Game DVR Background Recording: Off
11:24:21.481: Sec. Software Status:
11:24:21.483: 	Microsoft Defender Antivirus: enabled (AV)
11:24:21.483: 	Windows Firewall: enabled (FW)
11:24:21.484: Current Date/Time: 2021-09-29, 11:24:21
11:24:21.484: Browser Hardware Acceleration: true
11:24:21.484: Portable mode: false
11:24:21.797: OBS 27.0.1 (32-bit, windows)
11:24:21.797: ---------------------------------
11:24:21.798: ---------------------------------
11:24:21.798: audio settings reset:
11:24:21.798: 	samples per sec: 48000
11:24:21.798: 	speakers:        2
11:24:21.800: ---------------------------------
11:24:21.800: Initializing D3D11...
11:24:21.800: Available Video Adapters: 
11:24:21.803: 	Adapter 0: AMD Radeon (TM) R7 360 Series
11:24:21.803: 	  Dedicated VRAM: 2121830400
11:24:21.803: 	  Shared VRAM:    2173071360
11:24:21.803: 	  PCI ID:         1002:665f
11:24:21.803: 	  Driver Version: 27.20.20903.8001
11:24:21.803: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=59, name=HP V214b
11:24:21.806: Loading up D3D11 on adapter AMD Radeon (TM) R7 360 Series (0)
11:24:21.843: D3D11 loaded successfully, feature level used: b000
11:24:21.843: DXGI increase maximum frame latency success
11:24:21.843: D3D11 GPU priority setup failed (not admin?)
11:24:22.386: ---------------------------------
11:24:22.386: video settings reset:
11:24:22.386: 	base resolution:   960x540
11:24:22.386: 	output resolution: 960x540
11:24:22.386: 	downscale filter:  Bicubic
11:24:22.386: 	fps:               60000/1001
11:24:22.386: 	format:            NV12
11:24:22.386: 	YUV mode:          709/Partial
11:24:22.386: NV12 texture support enabled
11:24:22.387: Audio monitoring device:
11:24:22.387: 	name: Default
11:24:22.387: 	id: default
11:24:22.389: ---------------------------------
11:24:22.389: Skipping module '../../obs-plugins/32bit/chrome_elf.dll', not an OBS plugin
11:24:22.394: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
11:24:22.395: Failed to load 'en-US' text for module: 'decklink-captions.dll'
11:24:22.396: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
11:24:37.682: [AMF] Version 2.6.0 loaded (Compiled: 1.4.14.0, Runtime: 1.4.20.0, Library: 1;4;20;0;21.09.03.08;202105111331;CL#2303889).
11:24:37.808: [AMF] [Capability Manager] Testing Direct3D 11 Adapter 'AMD Radeon (TM) R7 360 Series (VEN_1002/DEV_665f/SUB_4961043/REV_0081)':
11:24:37.808:   H264/AVC: Supported
11:24:37.808:   H265/HEVC: Not Supported
11:24:37.808: 
11:24:37.808: [AMF] [H265/HEVC] Not supported by any GPU, disabling...
11:24:37.816: Skipping module '../../obs-plugins/32bit/libcef.dll', not an OBS plugin
11:24:37.826: Skipping module '../../obs-plugins/32bit/libEGL.dll', not an OBS plugin
11:24:37.827: Skipping module '../../obs-plugins/32bit/libGLESv2.dll', not an OBS plugin
11:24:37.831: [obs-browser]: Version 2.14.3
11:24:37.831: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
11:24:37.836: [noise suppress: Nvidia RTX denoiser disabled, redistributable not found]
11:24:38.167: Couldn't find VLC installation, VLC video source disabled
11:24:38.178: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
11:24:38.179: No blackmagic support
11:24:38.185: ---------------------------------
11:24:38.185:   Loaded Modules:
11:24:38.185:     win-wasapi.dll
11:24:38.185:     win-mf.dll
11:24:38.185:     win-dshow.dll
11:24:38.185:     win-decklink.dll
11:24:38.185:     win-capture.dll
11:24:38.185:     vlc-video.dll
11:24:38.185:     text-freetype2.dll
11:24:38.185:     rtmp-services.dll
11:24:38.185:     obs-x264.dll
11:24:38.185:     obs-vst.dll
11:24:38.185:     obs-transitions.dll
11:24:38.185:     obs-text.dll
11:24:38.185:     obs-qsv11.dll
11:24:38.185:     obs-outputs.dll
11:24:38.185:     obs-filters.dll
11:24:38.185:     obs-ffmpeg.dll
11:24:38.185:     obs-browser.dll
11:24:38.185:     image-source.dll
11:24:38.185:     frontend-tools.dll
11:24:38.185:     enc-amf.dll
11:24:38.185:     decklink-ouput-ui.dll
11:24:38.185:     decklink-captions.dll
11:24:38.185:     coreaudio-encoder.dll
11:24:38.185: ---------------------------------
11:24:38.185: ==== Startup complete ===============================================
11:24:38.194: All scene data cleared
11:24:38.194: ------------------------------------------------
11:24:38.352: WASAPI: Device 'Speakers (Realtek High Definition Audio)' [44100 Hz] initialized
11:24:38.352: [Loaded global audio device]: 'Desktop Audio'
11:24:38.457: WASAPI: Device 'Mic in at rear panel (Pink) (Realtek High Definition Audio)' [48000 Hz] initialized
11:24:38.457: [Loaded global audio device]: 'Mic/Aux'
11:24:38.458: [window-capture: 'Window Capture'] update settings:
11:24:38.458: 	executable: HD-Player.exe
11:24:38.458: 	method selected: WGC
11:24:38.458: 	method chosen: WGC
11:24:38.458: 
11:24:38.459: Switched to scene 'Scene'
11:24:38.459: ------------------------------------------------
11:24:38.459: Loaded scenes:
11:24:38.459: - scene 'Scene':
11:24:38.459:     - source: 'Window Capture' (window_capture)
11:24:38.459: - scene 'Scene 2':
11:24:38.459: ------------------------------------------------
11:24:38.480: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux)
11:24:38.480: 
11:24:41.472: [AMF] <Id: 3> Unable to initialize converter, error AMF_OPENCL_FAILED (code 19)
11:24:41.472: Stream output type 'rtmp_output' failed to start!

**Comment by flaeri** [comment]
@Shahed0631j Hello!

Could you please try updating to this driver, and see if that dosent fix HEVC for you? It does for me :)
https://www.amd.com/en/support/kb/release-notes/rn-rad-win-21-10-2

**Comment by Shahed0631j** [comment]
Yeah! Don't worry I've fixed it. By using older driver.

**Comment by flaeri** [comment]
@Shahed0631j yeah, that works too :) Just a heads up that the newer driver is probably also going to do the trick for you. Does that mean you would like to close this issue?

**Comment by Shahed0631j** [comment]
I have no problem with that, but someone other guy who had the same problem
as mine, he will get help with my issue. Isn’t it?

**Comment by flaeri** [comment]
none in this thread. I've reached the people in the issues that I believe related to this, as well. Ok, close away :)

**Comment by g-k-m** [comment]
Just want to say on the newest driver 22.2.1 this happens again. I rolled back to 22.1.1 and it works again. Not sure about 22.1.2

Is this in someway related to this project? Like, if a driver breaks the obs amd encoder functionality (cannot use h264 and h265), am i supposed to report it here so someone can fix it, or am i supposed to report it to amd? Cuz I did a bug report from Radeon Software but i am not sure if they read each one, neither i am sure if they will do anything about it. Technically the 22.2.1 driver is not a WHQL one but it's a decent indication of how it will go, so if the next WHQL driver doesn't solve it, what am i supposed to do, report it here, report it to amd, or do nothing? And where do i report it to amd besides the bug report?

**Comment by flaeri** [comment]
@g-k-m I think doing both is probably a good idea :)
I know the team has started on a rework of the AMD encoder, which will hopefully play a bit nicer with drivers, as well as hopefully simplifying and bringing more frequent updates if needed.

Fingers crossed for now :)

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
