### ISSUE TITLE
Any solution for Ubuntu 20.04 using OBS Studio?

### ISSUE THREAD

**Issue by rajhlinux** [Xaymar/OBS-AMD-Advanced-Media-Framework#425]
Hello, I am trying to get HEVC hardware encoding from my AMD Radeon Pro WX 2100 using Ubuntu 20.04 on OBS Studio.

VAAPI does not work.

I installed the driver and AMD packages from the AMD driver folder from AMDs website on Ubuntu, still nothing works when recording on OBS with VAAPI.

How can I get OBS Studio with the AMF AMD encoder option working on Ubuntu 20.04 how it works perfectly on windows 10?

Thanks.

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
