### ISSUE TITLE
My rewrite of the plugin

### ISSUE THREAD

**Issue by e00E** [Xaymar/OBS-AMD-Advanced-Media-Framework#426]
I want to note this here in case it is useful for other people or OBS wants to take over the code. I have rewritten this plugin form scratch: https://github.com/e00E/obs-amf .
My initial motivation was to fix full color range but I have since implemented much more like support for texture encoding. The biggest missing part is easier configuration for non technical users.

**Comment by e00E** [comment]
More context: There is another PR directly to the obs repo with a separate rewrite. Both of the rewrites have the goal of updating to the current AMF version and supporting texture encoding. I suggest looking at my rewrite too when reviewing the other PR. I'm not sure I should make a "PR" to this repo as the PR would completely change all files.

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
