### ISSUE TITLE
OBS Unable to initalize converter, error AMF_OPENCL_FAILED (code 19) DRİVER UPDATE 

### ISSUE THREAD

**Issue by haaypo** [Xaymar/OBS-AMD-Advanced-Media-Framework#428]
### Reproduction Steps

1. Open a portal to the Infinite Void
2. Summon an ancient God
3. Realize your mistake

### System Information

- Software Version: [e. g. 1.0.0, 1.2.1, ... - NEVER LATEST]
- Operating System: [e. g. Windows, Debian, Ubuntu, RedHat, FreeBSD, ...]
- Kernel Version: [e. g. 1903/1809 (Windows), 4.12 (Linux), ...]
- CPU: [e. g. Intel i7, AMD Zen2, Qualcomm, ...]
- GPU: [e. g. Nvidia RTX 2xxx Series, AMD Radeone 5xxx Series, ...]
- RAM: [e. g. 16GB, 32GB, 64GB, ...]

### Checklist:

- [ ] I have read the contribution guidelines.
- [ ] I can reproduce the issue with the exact reproduction steps I have provided.
- [ ] The issue appears on all of my systems that can run this software.

**Comment by haaypo** [comment]
my video drivers and windows everything is up to date but no matter what i do i keep getting this error i can't stream from video card please help me

**Comment by haaypo** [comment]
19:14:08.818: CPU Name: AMD Ryzen 3 2200G with Radeon Vega Graphics    
19:14:08.818: CPU Speed: 3493MHz
19:14:08.818: Physical Cores: 4, Logical Cores: 4
19:14:08.818: Physical Memory: 16317MB Total, 13231MB Free
19:14:08.818: Windows Version: 10.0 Build 19044 (release: 2009; revision: 1682; 64-bit)
19:14:08.818: Running as administrator: false
19:14:08.818: Aero is Enabled (Aero is always on for windows 8 and above)
19:14:08.818: Windows 10 Gaming Features:
19:14:08.818: 	Game DVR: On
19:14:08.825: Sec. Software Status:
19:14:08.827: Current Date/Time: 2022-05-07, 19:14:08
19:14:08.827: Browser Hardware Acceleration: true
19:14:08.827: Hide OBS windows from screen capture: false
19:14:08.827: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
19:14:08.827: Portable mode: false
19:14:09.284: OBS 27.2.4 (64-bit, windows)
19:14:09.284: ---------------------------------
19:14:09.331: ---------------------------------
19:14:09.331: audio settings reset:
19:14:09.331: 	samples per sec: 44100
19:14:09.331: 	speakers:        2
19:14:09.349: ---------------------------------
19:14:09.349: Initializing D3D11...
19:14:09.349: Available Video Adapters: 
19:14:09.352: 	Adapter 0: Radeon RX 570 Series
19:14:09.352: 	  Dedicated VRAM: 4272939008
19:14:09.352: 	  Shared VRAM:    4260317184
19:14:09.352: 	  PCI ID:         1002:67df
19:14:09.352: 	  Driver Version: 30.0.15021.7000
19:14:09.352: 	  output 0:
19:14:09.352: 	    name=DP
19:14:09.352: 	    pos={0, 0}
19:14:09.352: 	    size={1920, 1080}
19:14:09.352: 	    attached=true
19:14:09.352: 	    refresh=144
19:14:09.352: 	    space=RGB_FULL_G22_NONE_P709
19:14:09.352: 	    sdr_white_nits=80
19:14:09.352: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
19:14:09.353: 	  output 1:
19:14:09.353: 	    name=MACROSILICON
19:14:09.353: 	    pos={-1280, 0}
19:14:09.353: 	    size={1280, 1024}
19:14:09.353: 	    attached=true
19:14:09.353: 	    refresh=60
19:14:09.353: 	    space=RGB_FULL_G22_NONE_P709
19:14:09.353: 	    sdr_white_nits=80
19:14:09.353: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
19:14:09.355: Loading up D3D11 on adapter Radeon RX 570 Series (0)
19:14:09.398: D3D11 loaded successfully, feature level used: b000
19:14:09.398: DXGI increase maximum frame latency success
19:14:09.398: D3D11 GPU priority setup failed (not admin?)
19:14:09.944: ---------------------------------
19:14:09.944: video settings reset:
19:14:09.944: 	base resolution:   1920x1080
19:14:09.944: 	output resolution: 1280x720
19:14:09.944: 	downscale filter:  Bicubic
19:14:09.944: 	fps:               60/1
19:14:09.944: 	format:            NV12
19:14:09.944: 	YUV mode:          709/Partial
19:14:09.944: NV12 texture support enabled
19:14:09.945: Audio monitoring device:
19:14:09.945: 	name: Varsayılan
19:14:09.945: 	id: default
19:14:09.946: ---------------------------------
19:14:09.970: No AJA devices found, skipping loading AJA UI plugin
19:14:09.970: Failed to initialize module 'aja-output-ui.dll'
19:14:09.988: No AJA devices found, skipping loading AJA plugin
19:14:09.988: Failed to initialize module 'aja.dll'
19:14:10.019: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
19:14:10.041: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
19:14:10.058: Failed to load 'en-US' text for module: 'decklink-captions.dll'
19:14:10.076: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
19:14:10.094: Failed to load 'en-US' text for module: 'enc-amf.dll'
19:14:10.098: [AMF] Version 2.1.6 loaded (Compiled: 1.4.2.0, Runtime: 1.4.24.0, Library: 1;4;24;0;21.50.19.01;202203221705;AMD-Radeon-Driver/drivers:6ae99a18d6400f2580e76259e796a6f74096ec9f).
19:14:10.359: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
19:14:10.395: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
19:14:10.445: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
19:14:10.510: [obs-browser]: Version 2.17.13
19:14:10.510: [obs-browser]: CEF Version 95.0.0-MediaHandler.2467+g8092a57+chromium-95.0.4638.69
19:14:10.619: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found
19:14:15.006: [vlc-video]: Couldn't find VLC installation, VLC video source disabled
19:14:15.243: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
19:14:15.243: No blackmagic support
19:14:15.303: ---------------------------------
19:14:15.303:   Loaded Modules:
19:14:15.303:     win-wasapi.dll
19:14:15.303:     win-mf.dll
19:14:15.303:     win-dshow.dll
19:14:15.303:     win-decklink.dll
19:14:15.303:     win-capture.dll
19:14:15.304:     vlc-video.dll
19:14:15.304:     text-freetype2.dll
19:14:15.304:     rtmp-services.dll
19:14:15.304:     obs-x264.dll
19:14:15.304:     obs-vst.dll
19:14:15.304:     obs-transitions.dll
19:14:15.304:     obs-text.dll
19:14:15.304:     obs-qsv11.dll
19:14:15.304:     obs-outputs.dll
19:14:15.304:     obs-filters.dll
19:14:15.304:     obs-ffmpeg.dll
19:14:15.304:     obs-browser.dll
19:14:15.304:     image-source.dll
19:14:15.304:     frontend-tools.dll
19:14:15.304:     enc-amf.dll
19:14:15.304:     decklink-ouput-ui.dll
19:14:15.304:     decklink-captions.dll
19:14:15.304:     coreaudio-encoder.dll
19:14:15.304: ---------------------------------
19:14:15.304: ==== Startup complete ===============================================
19:14:15.468: All scene data cleared
19:14:15.468: ------------------------------------------------
19:14:15.486: [win-wasapi: 'Masaüstü Ses'] update settings:
19:14:15.486: 	device id: default
19:14:15.486: 	use device timing: 1
19:14:15.496: [Loaded global audio device]: 'Masaüstü Ses'
19:14:15.497: [win-wasapi: 'Mic/Aux'] update settings:
19:14:15.497: 	device id: {0.0.1.00000000}.{6f8a792d-97fa-4017-b48c-1c409cb132da}
19:14:15.497: 	use device timing: 0
19:14:15.502: [noise suppress: 'Gürültü Bastırma'] NVAFX redist is not installed.
19:14:15.511: [Loaded global audio device]: 'Mic/Aux'
19:14:15.511:     - filter: 'Gürültü Filtresi' (noise_gate_filter)
19:14:15.511:     - filter: 'Gürültü Bastırma' (noise_suppress_filter)
19:14:15.511:     - filter: 'Kazanç' (gain_filter)
19:14:15.566: [duplicator-monitor-capture: 'Ekran Yakalama'] update settings:
19:14:15.566: 	display: 1 (1920x1080)
19:14:15.566: 	cursor: true
19:14:15.566: 	method: DXGI
19:14:15.584: [Media Source 'Ortam Kaynağı']: settings:
19:14:15.584: 	input:                   C:/Users/BURHAN/Videos/2021-12-29 21-57-07.mkv
19:14:15.584: 	input_format:            (null)
19:14:15.584: 	speed:                   100
19:14:15.584: 	is_looping:              yes
19:14:15.584: 	is_linear_alpha:         no
19:14:15.584: 	is_hw_decoding:          no
19:14:15.584: 	is_clear_on_media_end:   yes
19:14:15.584: 	restart_on_activate:     yes
19:14:15.584: 	close_when_inactive:     no
19:14:15.586: [Media Source 'Ortam Kaynağı 2']: settings:
19:14:15.586: 	input:                   C:/Users/BURHAN/Videos/y2mate.com - ＦＯＲＥＳＴ　ＣＨＩＬＬ_1080p_Trim.mp4
19:14:15.586: 	input_format:            (null)
19:14:15.586: 	speed:                   59
19:14:15.586: 	is_looping:              yes
19:14:15.586: 	is_linear_alpha:         no
19:14:15.586: 	is_hw_decoding:          no
19:14:15.586: 	is_clear_on_media_end:   yes
19:14:15.586: 	restart_on_activate:     yes
19:14:15.586: 	close_when_inactive:     no
19:14:15.639: WASAPI: Device 'Hoparlör (2- USBFC1-A)' [48000 Hz] initialized
19:14:15.643: WASAPI: Device 'Mikrofon (3- USB PnP Sound Device)' [48000 Hz] initialized
19:14:15.698: adding 69 milliseconds of audio buffering, total audio buffering is now 69 milliseconds (source: Mic/Aux)
19:14:15.698: 
19:14:15.758: Switched to scene 'Sahne'
19:14:15.758: ------------------------------------------------
19:14:15.758: Loaded scenes:
19:14:15.758: - scene 'başla':
19:14:15.758:     - source: 'Ortam Kaynağı' (ffmpeg_source)
19:14:15.758: - scene 'Sahne':
19:14:15.758:     - source: 'Ekran Yakalama' (monitor_capture)
19:14:15.758:     - source: 'Tarayıcı' (browser_source)
19:14:15.758:     - source: 'Video Yakalama Aygıtı' (dshow_input)
19:14:15.758:     - source: 'Görüntü' (image_source)
19:14:15.758: - scene 'Sahne 2':
19:14:15.758:     - source: 'Ortam Kaynağı 2' (ffmpeg_source)
19:14:15.758:     - source: 'Metin (GDI+)' (text_gdiplus)
19:14:15.758: - scene 'Sahne 3':
19:14:15.758:     - source: 'Video Yakalama Aygıtı' (dshow_input)
19:14:15.758:     - source: 'BrowserSource' (browser_source)
19:14:15.758: ------------------------------------------------
19:14:15.792: ---------------------------------
19:14:15.792: [DShow Device: 'Video Yakalama Aygıtı'] settings updated: 
19:14:15.792: 	video device: Logitech HD Webcam C525
19:14:15.792: 	video path: \\?\usb#vid_046d&pid_0826&mi_02#7&25b811c1&0&0002#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\{bbefb6c7-2fc4-4139-bb8b-a58bba724083}
19:14:15.792: 	resolution: 1280x720
19:14:15.792: 	flip: 0
19:14:15.792: 	fps: 30.00 (interval: 333333)
19:14:15.792: 	format: I420
19:14:15.792: 	buffering: disabled
19:14:22.975: [AMF] <Id: 7> Unable to initalize converter, error AMF_OPENCL_FAILED (code 19)
19:14:22.975: Stream output type 'rtmp_output' failed to start!

**Comment by haaypo** [comment]
PLEASEEEEEEEEEEEEE HELPPPPPP

**Comment by sebastian-s-beckmann** [comment]
This issue appears to be a support request, for which we don't use GitHub Issues.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

Thank you!
