### ISSUE TITLE
Hardware-Support is missing supported cards

### ISSUE THREAD

**Issue by marktheminer** [Xaymar/OBS-AMD-Advanced-Media-Framework#437]
https://github.com/obsproject/obs-amd-encoder/wiki/Hardware-Support

I bought a RX 6600 based card and it works great.  The list needs to be updated.

**Comment by Artoria2e5** [comment]
RX 6600 is VCN 3.0. The wiki is wayyyy behind (bro, we are at 4.0, you still not having any info on 1.0?) and editing is locked, so there's nothing I can do :(

Do you mind running the test and pasting whatever it says here? Might help the devs figure out what to write when they come around.

It's also totally possible that they will never come back, considering obs has a better way to do AMD built-in now (https://github.com/obsproject/obs-studio/pull/6508). The support list remains useful and should probably be copied to the OBS page.

**Comment by Artoria2e5** [comment]
I happen to have a 6800 XT which should have identical capabilities, just different speeds. The result of the test is uploaded below, according to what the readme.txt in that zip file says I should do.

Ho boy, no wonder nobody is uploading the results! The video files are too large for that! Somebody, fix the README! Well, I will just delete all the h264 and h265 files and just give you the txts.

[H264/Caps.txt](https://github.com/obsproject/obs-amd-encoder/files/13407956/Caps.txt)
[ResultsH264.zip](https://github.com/obsproject/obs-amd-encoder/files/13407966/ResultsH264.zip)
[H265/Caps.txt](https://github.com/obsproject/obs-amd-encoder/files/13407978/Caps.txt)
[ResultsH265.zip](https://github.com/obsproject/obs-amd-encoder/files/13407972/ResultsH265.zip)

A draft text for VCN 3.0 based on Caps.txt is:
### AVC/SVC (H264)
- Type: Hardware Accelerated
- Resolution 128x128 - 4096x4096
- Interlacing: No
- Max. Profile: (what's a 100? is it: High)
- Max. Level: 5.2
- B-Frames: Yes, according to https://codecalamity.com/amd-re-introduces-the-b-frame/
- Max. Simultaneous Streams: 16
- Formats: NV12 (Native/Output), YUV420P, YV12, BGRA, RGBA, ARGB
- Backends: Vulkan, DirectX 11, OpenGL, OpenCL
### HEVC (H265)
- Type: Hardware Accelerated
- Resolution 128x128 - 8192x4352
- Interlacing: No
- Max. Profile: 1, which is Main in ["HM"](http://hevc.info/HM-doc/namespace_profile.html)
- Max. Tier: 0, which is Main in ["HEVC test model (HM)"](http://hevc.info/HM-doc/namespace_level.html)
- Max. Level: 186, which is 6.2 in "HM"
- Max. Simultaneous Streams: 16
- Formats: NV12 (Native/Output), P010 (native/output), YUV420P, YV12, BGRA, RGBA, ARGB
- Backends: Vulkan, DirectX 11, OpenGL, OpenCL

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
