### ISSUE TITLE
AMD Radeon Pro 5300M AMF Speed Test Results

### ISSUE THREAD

**Issue by DarthGigi** [Xaymar/OBS-AMD-Advanced-Media-Framework#442]
### Description
> "If you have a GPU or APU with VCE support and it is not yet listed here or there are no limits for it known, you can [run the test yourself](https://github.com/Xaymar/obs-studio_amf-encoder-plugin/releases/download/1.9.9.6/AMFSpeedTest.zip)! Once you have run the test, create an issue and it will be added to the wiki."

Here are the results: [AMFSpeedTest Results.zip](https://github.com/obsproject/obs-amd-encoder/files/13774122/AMFSpeedTest.Results.zip).

<details>
<summary>Note</summary>
I have removed the `.h264` and `.h265` files from the zip, as they increase the file size to about 77MB and GitHub has a 25MB file limit. If these files are needed, please let me know and I'll re-run the test and upload these.
</details>

### System Information
- Software Version:
  - AMD Software: **Adrenalin Edition: 23.9.3**
  - Driver Version: **23.20.11.04-230921a-396203C-AMD-Software-Adrenalin-Edition**
  - AMD Windows Driver Version: **31.0.22011.4008**
- Operating System: **Windows 11 Pro**
- Kernel Version: **23H2 (22631.2715)**
- CPU: **Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz**
- GPU: **AMD Radeon Pro 5300M**
- RAM: **16GB DDR4**

### Checklist:
- [x] I have read the contribution guidelines.
- [X] This is not a bug, crash or generic issue.

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
