### ISSUE TITLE
RX 6600 works well

### ISSUE THREAD

**Issue by ivico94** [Xaymar/OBS-AMD-Advanced-Media-Framework#443]
### Description

Here are the results for AMD RX660

### System Information

Windows 10.0.19045 Build 19045
(RAM) 32,0 Go
Processeur	Intel(R) Core(TM) i7-4770K CPU @ 4.1GHz,

### Checklist:

- [x ] I have read the contribution guidelines.
- [x ] This is not a bug, crash or generic issue.

[Caps.txt](https://github.com/obsproject/obs-amd-encoder/files/14211570/Caps.txt)
[H265_1920x1080.txt](https://github.com/obsproject/obs-amd-encoder/files/14211573/H265_1920x1080.txt)

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
