### ISSUE TITLE
AMD Encoder not being recognised by OBS

### ISSUE THREAD

**Issue by ffuentesm** [Xaymar/OBS-AMD-Advanced-Media-Framework#444]
### Description
OBS is behaving as if AMD encoder is not installed. 
![image](https://github.com/obsproject/obs-amd-encoder/assets/44974827/76b3c95d-e098-442e-9b37-4ac1e5b0b329)

![image](https://github.com/obsproject/obs-amd-encoder/assets/44974827/5ec110fb-39c7-42e7-9631-c849b1dbf058)

> 10:09:31.389: [texture-amf-h264: 'simple_video_recording'] B-Frames set to 3 but b-frames are not supported by this device
10:09:31.389: [texture-amf-h264: 'simple_video_recording'] Failed to set property 'QvbrQualityLevel': AMF_INVALID_ARG
10:09:31.389: [texture-amf-h264: 'simple_video_recording'] Failed to set property 'HighMotionQualityBoostEnable': AMF_INVALID_ARG
10:09:31.389: [texture-amf-h264: 'simple_video_recording'] settings:
10:09:31.389: 	rate_control: CQP
10:09:31.389: 	bitrate:      2500
10:09:31.389: 	cqp:          20
10:09:31.389: 	keyint:       250
10:09:31.389: 	preset:       quality
10:09:31.389: 	profile:      high
10:09:31.389: 	b-frames:     0
10:09:31.389: 	width:        1152
10:09:31.389: 	height:       720
10:09:31.389: 	params:       (none)
10:09:40.424: [texture-amf-h264] amf_avc_create_texencode: AMFComponent::Init failed: AMF_FAIL
10:09:40.450: [fallback-amf-h264: 'simple_video_recording'] B-Frames set to 3 but b-frames are not supported by this device
10:09:40.450: [fallback-amf-h264: 'simple_video_recording'] Failed to set property 'QvbrQualityLevel': AMF_INVALID_ARG
10:09:40.450: [fallback-amf-h264: 'simple_video_recording'] Failed to set property 'HighMotionQualityBoostEnable': AMF_INVALID_ARG
10:09:40.450: [fallback-amf-h264: 'simple_video_recording'] settings:
10:09:40.450: 	rate_control: CQP
10:09:40.450: 	bitrate:      2500
10:09:40.450: 	cqp:          20
10:09:40.450: 	keyint:       250
10:09:40.450: 	preset:       quality
10:09:40.450: 	profile:      high
10:09:40.450: 	b-frames:     0
10:09:40.450: 	width:        1152
10:09:40.450: 	height:       720
10:09:40.450: 	params:       (none)
10:09:49.498: [fallback-amf-h264] amf_avc_create_fallback: AMFComponent::Init failed: AMF_FAIL

### Expected Behavior
It should record the screen using the AMD encoder

### Reproduction Steps

1. Open OBS
2. install obs-amd-encoder-2.6.0.0
3. download required software (AMD drives, Visual C++)
4. Press record

### System Information
- Software Version: obs-amd-encoder-2.6.0.0, OBS 30.1.2
- Operating System: Windows 11
- Kernel Version: Version 23H2 (OS Build 22631.3527)
- CPU: AMD ryzen 5 3600x
- GPU: RX 580
- RAM: 32 GB

### Checklist:
- [x] I have read the contribution guidelines.
- [x] I can reproduce the issue with the exact reproduction steps I have provided.
- [x] The issue appears on all of my systems that can run this software.

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
