### ISSUE TITLE
bitrate problem

### ISSUE THREAD

**Issue by Lump1n404** [Xaymar/OBS-AMD-Advanced-Media-Framework#445]
only 2 bitrate values are entered. this is 1 or 0. the value does not increase either through + or on the numeric block
![Снимок экрана 2024-06-07 115235](https://github.com/obsproject/obs-amd-encoder/assets/172023610/df38d7e2-0f7d-4b64-9e3b-5b1d6b7c2332)

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
