### ISSUE TITLE
RX 6600 test results

### ISSUE THREAD

**Issue by giannism13** [Xaymar/OBS-AMD-Advanced-Media-Framework#446]
### Description
Hello,

I've run the tests found [here](https://github.com/obsproject/obs-amd-encoder/wiki/Hardware-Support). I've uploaded the [results ](https://drive.google.com/file/d/1e0_u_NqH5QFJzUDCwC3cicBhYtcM_aTM/view?usp=sharing)so you can add my gpu RX6600 on the list

**Comment by RytoEX** [comment]
This repository is being archived. All Issues are being closed. Thank you for understanding.
