### ISSUE TITLE
Did a test record, wanted to change b-pictures to 0 from -1 and obs stalled/no respond.

### ISSUE THREAD

**Issue by wazerstar** [Xaymar/OBS-AMD-Advanced-Media-Framework#45]
Notice text in Danish left top corner (Svare ikke = Not responding)

http://prnt.sc/c9gbjr

Did a test record, stopped it after around 30 seconds, went to options to change setting since I'm getting flickers again with new update, started with b-pictures setting it to 0 and obs stalled/not responding

[2016-08-23 19-15-49.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/433135/2016-08-23.19-15-49.txt)

**Comment by wazerstar** [comment]
Just did another test and changed min and max qp after a test record, hitting apply and it stalled again.

**Comment by Xaymar** [comment]
Encoder was waiting for more frames, I think that is fixed it the last version.
