### ISSUE TITLE
Updated Danish translation file

### ISSUE THREAD

**Issue by wazerstar** [Xaymar/OBS-AMD-Advanced-Media-Framework#47]
[da-DK.zip](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/433317/da-DK.zip)

**Comment by nwgat** [comment]
i think you can change these lines to english, as danish or norwegian dont really fit these
AMF.H264Simple.Profile.Baseline="Baseline"
AMF.H264Simple.Profile.Main="Main"
AMF.H264Simple.Profile.High="High"

am doing a norwegian one using your nice translation as base :)
its literally remove 1-2 letters in a word, i like to joke about danish being norwegian without the writing errors

**Comment by Xaymar** [comment]
Closed, see #52
