### ISSUE TITLE
Edit wiki page

### ISSUE THREAD

**Issue by max20091** [Xaymar/OBS-AMD-Advanced-Media-Framework#53]
Can you open the wiki page so I can edit and add something to it?

**Comment by Xaymar** [comment]
What do you wish to add? The wiki is purposefully locked down to collaborators only, so that it won't even contain bad content.

**Comment by max20091** [comment]
just my Tested Configuration.

**Comment by Xaymar** [comment]
Oh, you can just upload your log file, i'll add it then.

**Comment by max20091** [comment]
[2016-08-22 17-08-32.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/434510/2016-08-22.17-08-32.txt)

**Comment by nwgat** [comment]
"The third Generation of the Video Coding Engine. Added High-Quality Scaling and h265/HEVC (waiting for SDK update) support."

does Fiji/tonga have a hevc encoder?, robert said polaris was the first one with that on reddit

**Comment by Xaymar** [comment]
Back when Tonga/Fiji XT were released, AMD said they'd get H265 support. But it seems that they lack the power to do so or have some bugs in the VCE chip that made it impossible - or AMD is just toying with us again. But from what I have seen, H265 support isn't so widespread and the encoder will take quite a while to reach anything usable.
And yes, i did test it already - there are quite a few debug strings left around that led me to the discovery of the HEVC component.

**Comment by nwgat** [comment]
ooh, much like tonga xt right? :P

**Comment by nwgat** [comment]
here is a matrix table based on robert's [reddit ](https://www.reddit.com/r/Amd/comments/4y10gr/today_we_released_a_new_version_of_the_amd_media/d6kkje0)
[gpumatrix.md.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/435028/gpumatrix.md.txt)

**Comment by Xaymar** [comment]
@max20091 Can you add your settings to #61? I'm closing this as it's easier to just keep track of all of them in one issue.
