### ISSUE TITLE
Recorded video does not have the desired frame rate

### ISSUE THREAD

**Issue by Wolverine80** [Xaymar/OBS-AMD-Advanced-Media-Framework#56]
Hi,

I tested your plugin today and like it very much. But I have one issue that makes it for me impossible to use.
All videos don't have the frame rate that I set up in OBS. It does not matter if I record 30 or 60fps. So I can't import them in the editing software. 
I tried lots of settings and found out that the quality setting has influence. 
I recorded just the desktop at 1080p at 60fps. The result was a video with 59fps and Speed setting. 
If I set it to Quality i got 50fps. The same with 30fps records. 

I use an AMD R9-290´card with the 16.8.2 drivers under Win 10 x64. 
Add-on version is 1.2.0 (RC1) and OBS 0.15.4 (64bit)

@Xaymar I added the logfiles and spec informations. 

[PC.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/439196/PC.txt)
[2016-08-26 13-53-19.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/439197/2016-08-26.13-53-19.txt)
[2016-08-26 13-46-56.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/439198/2016-08-26.13-46-56.txt)
[2016-08-26 13-40-12.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/439199/2016-08-26.13-40-12.txt)

**Comment by max20091** [comment]
Did you set Transcoding when you are recording your game?

**Comment by Xaymar** [comment]
Please [read this](https://github.com/Xaymar/OBS-AMD-Media-Framework/wiki/Reporting-Issues) and update your issue accordingly.

**Comment by Wolverine80** [comment]
@max20091  I did not even record a game in the tests. Just the desktop. But, yes, it was on transcoding

**Comment by Xaymar** [comment]
1.2.0rc1 is no longer in development, please use either 1.1 or 1.3.0
