### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Cruyelo** [Xaymar/OBS-AMD-Advanced-Media-Framework#6]
I attached two crash logs, and two logs from OBS Studio (I'm not sure which one goes with which crash, that's why I'm adding two).
I tried recording with Game Capture and Display Capture. Every crash was at 19sec, 20sec, 21 sec. The result is a low quality video, I can upload an example if it could help.

[2016-07-31 14-28-41.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/392583/2016-07-31.14-28-41.txt)
[Crash 2016-07-31 14-29-53.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/392584/Crash.2016-07-31.14-29-53.txt)
[2016-07-31 14-30-13.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/392585/2016-07-31.14-30-13.txt)
[Crash 2016-07-31 14-27-48.txt](https://github.com/Xaymar/OBS-AMD-Media-Framework/files/392586/Crash.2016-07-31.14-27-48.txt)

**Comment by Xaymar** [comment]
Same issue as in #5, closing this one.
