### ISSUE TITLE
fixed i-Frames (Issue that is actually for @Jackun's OBS Classic fork)

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#60]
Hi,

first i want to thank you for your good work and hope you continue ;)

i noticed your 1.3.0pre5 - The AMF SDK Path (and 1.3.0pre3) dont have "GOP size" or fixed i-Frames (I Pic Period) // please could you also add "MV Search Range" & "IME Search Range" & "Force 16x16 skip" & "Force IME search window center to [0,0]"

maybe would be also nice to choose between DX9, DX11, DX12
oh and with newer dirvers "Disable D3D/OpenCL interoperability" is forced

ty again

ps: if you need a tester with some time i can assist you ;)

**Comment by Xaymar** [comment]
What?
Edit: Someone explain to me how this is at all relevant to the plugin.

**Comment by Ryzym** [comment]
Those were all settings in Jackun's OBS Classic VCE Fork.

**Comment by Xaymar** [comment]
Yeah, but still not relevant to the plugin. I can't add features for something that doesn't even exist anymore - or rather that never existed in the old or new SDK.

**Comment by Benman2785** [comment]
well i think "GOP size" and fixed i-Frames are still possible - because the plugin clearly lacks correct i-frame settings - even after 10s it stays blurry...

**Comment by Benman2785** [comment]
oh and do you need german localisation?

**Comment by Xaymar** [comment]
I am german, so no, I don't need german localization right now. Also neither GOPSize or "Fixed I-Frames" are actually a feature of the SDK. I think what you want is controlling headers, in which case you should take a look at Header Insertion Spacing. As for GOPSize, that is also being controlled by that combined with IDR Period (Keyframe Interval).

**Comment by Xaymar** [comment]
Concerning the footage being blurry, increase the bitrate you use. Or take a look at #61 for working settings.

**Comment by Benman2785** [comment]
Xaymar GOP size and IDR shouldnt be the same (in h264) - so better have an option each
i will check out Header Insertion Spacing

i want it to be useable for streaming - so i need the bitrate at that level

do you have some time to talk on ts3? maybe i can help with some stuff ;)

**Comment by Xaymar** [comment]
I feel like I'm talking to a wall at the moment. Here, I'll say it again: **The SDK does not support GOPSize!** If you really want these ~~hallucinated~~ features, implement them yourself.

Also if you drop the bitrate too low, you're on your own - this is a hardware encoder, you've got to expect that. I'm closing this before I go insane.
