### ISSUE TITLE
Gathering New Tested Settings (1.3.0)

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/OBS-AMD-Advanced-Media-Framework#61]
This Issue is dedicated to gather new tested settings. Only Settings with the latest Driver, 64-Bit OBS and latest Plugin Version are accepted. You can find the exact plugin version in the log output of obs:

`15:05:59.207: [AMF Encoder] Version 1.3.0pre8-1.3.0.5`

Please format your reply like this:

```
### System Specs
* CPU: ...
* GPU: ...
* RAM: ...GB DDR... ....Mhz
* Disk: HDD/SSD/...
* WIDTHxHEIGHT, FPSfps
* Driver Version: xx.x.x
* OBS Studio Version: x.xx.x 32/64-Bit
* Plugin Version: x.x.x-x.x.x.x

### Interface: Simple/Advanced
* Individual Settings listed here

### Examples:
* Preview: [YouTube/Twitch/Beam/...](LINKHERE)
* Raw File: [Download](mega.co.nz, google drive, ...)
* [MediaInfo](link to txt output here)
```

Edit: Comments that aren't on the newest version have been nuked from orbit.

**Comment by Xaymar** [comment]
Example:

### System Specs
* CPU: AMD FX-6100
* GPU: AMD Radeon R9 285 (ASUS Radeon R9 285 Strix OC DirectCU II)
* RAM: 16GB DDR3 1333Mhz
* Disk: Striped RAID (2xHDD)

### Interface: Simple
* Keyframe Interval: 1
* Quality Preset: Quality
* Profile: High
* Profile Level: 5.2 (Maximum Available)
* Rate Control Method: Constant QP
* Minimum QP: 1
* Maximum QP: 51
* I-/P-/B-Frame QP: 31/36/41
* Use Custom Buffer Size: No
* Enable Frame Skipping: No
* Turn on Debug Tracing: No

### Examples
* Preview: [YouTube](https://www.youtube.com/watch?v=fMDkv12ZLT8)
* Raw File: [Download](http://cdn.xaymar.com/private/2016/08/2016-08-27%2023-08-48.mkv)
* [MediaInfo](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/440860/Example.txt)

**Comment by Xaymar** [comment]
Proper B-Frames by changing delta QP, may need more experimenting.

### System Specs
* CPU: AMD FX-6100
* GPU: AMD Radeon R9 285 (ASUS Radeon R9 285 Strix OC DirectCU II)
* RAM: 16GB DDR3 1333Mhz
* Disk: Striped RAID (2xHDD)

### Interface: Advanced
* Usage Type: Transcoding
* Profile: High
* Profile Level: 5.2
* Maximum LTR Frames: 0
* Rate Control Method: Constant QP
* Frame Skipping: Disabled
* Minimum QP: 11
* Maximum QP: 41
* Target/Peak Bitrate: -1
* I-/P-/B-Frame QP: 21/26/31
* VBV Buffer Size: 25000000
* Initial VBV Buffer Fullness: 100%
* Enforce HRD Compatibility: No
* Filler Data: Enabled
* Maximum AU Size (bits): 0
* B-Picture Delta QP: -2
* Reference B-Picture Delta QP: -4
* Header Insertion Spacing: -1
* Keyframe IDR-Perod: 60 (1x Framerate)
* De-Blocking Filter: Enabled
* Intra-Refresh Memory...: -1
* Slices Per Frame: -1
* Number of B-Pictures: 3
* B-Picture Reference: Enabled
* Scan Type: Progressive
* Quality Preset: Quality
* Motion Estimation: Both
* Turn on Debug Tracing: No

### Examples:
* Preview: [YouTube]()
* Raw File: [Download]() (675 MB)
* [MediaInfo](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/440871/2016-08-27.23-47-16.txt)

**Comment by Xaymar** [comment]
Quick flashes (dark to bright) cause short blockyness in dark areas, otherwise useable. Not useable for streaming to anything as better quality can be attained.

### System Specs
* CPU: AMD FX-6100
* GPU: AMD Radeon R9 285 (ASUS Radeon R9 285 Strix OC DirectCU II)
* RAM: 16GB DDR3 1333Mhz
* Disk: Striped RAID (2xHDD)

### Interface: Advanced
* Usage Type: Transcoding
* Profile: High
* Profile Level: 5.2
* Maximum LTR Frames: 0
* Rate Control Method: Constant QP
* Frame Skipping: Disabled
* Minimum QP: 0
* Maximum QP: 51
* Target/Peak Bitrate: 3500000
* I-/P-/B-Frame QP: 33/36/39
* VBV Buffer Size: 3500000
* Initial VBV Buffer Fullness: 100%
* Enforce HRD Compatibility: No
* Filler Data: Enabled
* Maximum AU Size (bits): 0
* B-Picture Delta QP: 0
* Reference B-Picture Delta QP: 0
* Header Insertion Spacing: -1
* Keyframe IDR-Perod: 60 (1x Framerate)
* De-Blocking Filter: Enabled
* Intra-Refresh Memory...: -1
* Slices Per Frame: -1
* Number of B-Pictures: 3
* B-Picture Reference: Enabled
* Scan Type: Progressive
* Quality Preset: Quality
* Motion Estimation: Both
* Turn on Debug Tracing: No

### Examples:
* No Preview or Download
* [MediaInfo](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/440885/2016-08-28.00-52-20.txt)

**Comment by Xaymar** [comment]
Averages around 5.5mbit/s, so can be used for YouTube, Beam and Hitbox streaming. Quality is okay, could be better - not recommended for recording.

### System Specs
* CPU: AMD FX-6100
* GPU: AMD Radeon R9 285 (ASUS Radeon R9 285 Strix OC DirectCU II)
* RAM: 16GB DDR3 1333Mhz
* Disk: Striped RAID (2xHDD)

### Interface: Advanced
* Usage Type: Transcoding
* Profile: High
* Profile Level: 5.2
* Maximum LTR Frames: 0
* Rate Control Method: Constant QP
* Frame Skipping: Disabled
* Minimum QP: 0
* Maximum QP: 51
* Target/Peak Bitrate: 3500000
* I-/P-/B-Frame QP: 38/41/43
* VBV Buffer Size: 3500000
* Initial VBV Buffer Fullness: 100%
* Enforce HRD Compatibility: No
* Filler Data: Enabled
* Maximum AU Size (bits): 0
* B-Picture Delta QP: 0
* Reference B-Picture Delta QP: 1
* Header Insertion Spacing: -1
* Keyframe IDR-Perod: 60 (1x Framerate)
* De-Blocking Filter: Enabled
* Intra-Refresh Memory...: -1
* Slices Per Frame: -1
* Number of B-Pictures: 3
* B-Picture Reference: Enabled
* Scan Type: Progressive
* Quality Preset: Quality
* Motion Estimation: Both
* Turn on Debug Tracing: No

### Examples:
* No Preview or Download
* [MediaInfo](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/440886/2016-08-28.00-57-02.txt)

**Comment by Xaymar** [comment]
Average around 4mbit/s, could be used for Twitch, YouTube, Beam and HitBox streaming. Dark-to-Bright areas are not properly represented (still better than CBR at this bitrate). Possible recommendation for Twitch partners?

### System Specs
* CPU: AMD FX-6100
* GPU: AMD Radeon R9 285 (ASUS Radeon R9 285 Strix OC DirectCU II)
* RAM: 16GB DDR3 1333Mhz
* Disk: Striped RAID (2xHDD)

### Interface: Advanced
* Usage Type: Transcoding
* Profile: High
* Profile Level: 5.2
* Maximum LTR Frames: 0
* Rate Control Method: Constant QP
* Frame Skipping: Disabled
* Minimum QP: 0
* Maximum QP: 51
* Target/Peak Bitrate: 3500000
* I-/P-/B-Frame QP: 41/43/45
* VBV Buffer Size: 3500000
* Initial VBV Buffer Fullness: 100%
* Enforce HRD Compatibility: No
* Filler Data: Enabled
* Maximum AU Size (bits): 0
* B-Picture Delta QP: 2
* Reference B-Picture Delta QP: 1
* Header Insertion Spacing: -1
* Keyframe IDR-Perod: 60 (1x Framerate)
* De-Blocking Filter: Enabled
* Intra-Refresh Memory...: -1
* Slices Per Frame: -1
* Number of B-Pictures: 3
* B-Picture Reference: Enabled
* Scan Type: Progressive
* Quality Preset: Quality
* Motion Estimation: Both
* Turn on Debug Tracing: No

### Examples:
* No Preview or Download
* [MediaInfo](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/440888/2016-08-28.01-03-09.txt)

**Comment by Xaymar** [comment]
Average 3.5 to 3.7mbit, possibly for non-Twitch Partners looking to 1920x1080 at 60fps. Large details seem to act blocky (B-Frame QP too high?), and movement of darker areas is not properly displayed. More tests needed, most likely will have to lower B-Frame QP and increase I-Frame or P-Frame QP or toy with Delta QP more.

### System Specs
* CPU: AMD FX-6100
* GPU: AMD Radeon R9 285 (ASUS Radeon R9 285 Strix OC DirectCU II)
* RAM: 16GB DDR3 1333Mhz
* Disk: Striped RAID (2xHDD)

### Interface: Advanced
* Usage Type: Transcoding
* Profile: High
* Profile Level: 5.2
* Maximum LTR Frames: 0
* Rate Control Method: Constant QP
* Frame Skipping: Disabled
* Minimum QP: 0
* Maximum QP: 51
* Target/Peak Bitrate: -1
* I-/P-/B-Frame QP: 35/40/45
* VBV Buffer Size: -1
* Initial VBV Buffer Fullness: 100%
* Enforce HRD Compatibility: No
* Filler Data: Enabled
* Maximum AU Size (bits): 0
* B-Picture Delta QP: 4
* Reference B-Picture Delta QP: 2
* Header Insertion Spacing: -1
* Keyframe IDR-Perod: 60 (1x Framerate)
* De-Blocking Filter: Enabled
* Intra-Refresh Memory...: -1
* Slices Per Frame: -1
* Number of B-Pictures: 3
* B-Picture Reference: Enabled
* Scan Type: Progressive
* Quality Preset: Quality
* Motion Estimation: Both
* Turn on Debug Tracing: No

### Examples:
* Preview: [YouTube](https://www.youtube.com/watch?v=p6tLXKyrhE8)
* Raw File: [Download](http://cdn.xaymar.com/private/2016/08/2016-08-28%2001-43-36.mkv) (80 MB, 3.5mbit/s)
* [MediaInfo](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/440899/2016-08-28.01-43-36.txt)

**Comment by Xaymar** [comment]
Average 3.5 to 3.8mbit, possibly for non-Twitch Partners looking to 1920x1080 at 60fps. Better details on moving and dark parts, text is completely readable, small details are kept if there is a brightness difference. Best result so far at this bitrate.

### System Specs
* CPU: AMD FX-6100
* GPU: AMD Radeon R9 285 (ASUS Radeon R9 285 Strix OC DirectCU II)
* RAM: 16GB DDR3 1333Mhz
* Disk: Striped RAID (2xHDD)

### Interface: Advanced
* Usage Type: Transcoding
* Profile: High
* Profile Level: 5.2
* Maximum LTR Frames: 0
* Rate Control Method: Constant QP
* Frame Skipping: Disabled
* Minimum QP: 0
* Maximum QP: 51
* Target/Peak Bitrate: -1
* I-/P-/B-Frame QP: 39/43/44
* VBV Buffer Size: -1
* Initial VBV Buffer Fullness: 100%
* Enforce HRD Compatibility: No
* Filler Data: Enabled
* Maximum AU Size (bits): 0
* B-Picture Delta QP: 2
* Reference B-Picture Delta QP: 1
* Header Insertion Spacing: -1
* Keyframe IDR-Perod: 60 (1x Framerate)
* De-Blocking Filter: Enabled
* Intra-Refresh Memory...: -1
* Slices Per Frame: -1
* Number of B-Pictures: 3
* B-Picture Reference: Enabled
* Scan Type: Progressive
* Quality Preset: Quality
* Motion Estimation: Both
* Turn on Debug Tracing: No

### Examples:
* Preview: [YouTube](https://youtu.be/FESldLxpTbM)
* Raw File: [Download](http://cdn.xaymar.com/private/2016/08/2016-08-28%2001-59-53.mkv) (81 MB, ~3.55mbit/s)
* [MediaInfo](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/440911/2016-08-28.01-59-53.txt)

**Comment by max20091** [comment]
High quality recording for first gen GCN GPU
### System Specs
* CPU: Intel Pentium G630
* GPU: AMD Radeon HD 7730 1GB GDDR5
* GPU driver version: 16.8.2
* RAM: 6GB DDR3 1066Mhz
* Disk: HDD R/W 80MB/s
* 1280x720, 60fps

### Interface: Simple
* Keyframe Interval: 5
* Quality Preset: Quality
* Profile: High
* Profile Level: 4.2
* Rate Control Method: Constant QP
* Minimum QP: 18
* Maximum QP: 25
* Use Custom Buffer Size: No
* Enable Frame Skipping: No
* Turn on Debug Tracing: No

### Examples:
* Preview: [Youtube](https://youtu.be/A92kDZ3rVwc)
* Raw File: [Download](https://drive.google.com/open?id=0B3fo2a5_bBE6RVZiWWVJM0l4TjA)

**Comment by seanman** [comment]
# System Specs

    CPU: AMD FX 6300
    GPU: AMD Radeon HD 7770 1GB GDDR5
    GPU driver version: 16.8.2 / OBS AMF plugin version: 1.3.0pre5
    RAM: 8GB DDR3 1066Mhz
    Resolution : 1280x1024 rescale to 1280x720

# Interface

Preset : Twitch
-     Keyframe Interval: 2 secs
-     Quality Preset: Speed
-     Profile: Main
-     Profile Level: 4.1
-     Rate Control Method: CBR
-     Minimum QP: 18
-     Maximum QP: 51
-     Use Custom Buffer Size: No
-     Enable Frame Skipping: No
-     Turn on Debug Tracing: No

# Game
BF1 Beta with DX11 all low and off effect, resolution scale 42%
Preview : Uploading

**Comment by max20091** [comment]
@seanman maybe the CPU is parking? I dunno if this can help you http://coderbag.com/Programming-C/CPU-core-parking-manager
Also you can assign OBS to last 2 cores and assign your game to first 4 cores http://www.howtogeek.com/121775/how-to-force-windows-applications-to-use-a-specific-cpu/

**Comment by seanman** [comment]
I thought my proccie run all the process, 100% for the six cores :D, and thx @max20091  for the tips.

**Comment by Xaymar** [comment]
@max20091 @seanman I'd actually recommend locking it to only two cores - the encoder may be multithreaded, but AMF seems to have trouble with multi-threading.

**Comment by seanman** [comment]
@Xaymar thx for information, i will try again with 16.8.3 crimson.

**Comment by Xaymar** [comment]
Perfect for a Camera + Gameplay setup so that one can apply proper effects later in editing. Or a multi-camera/multi-stream recording. Whatever really.

### System Specs
* CPU: AMD FX-6100 4.0 Ghz
* GPU: AMD Radeon R9 285 (ASUS Radeon R9 285 Strix OC DirectCU II)
* RAM: 16GB DDR3 1333Mhz
* Disk: Striped RAID (2xHDD)
* 3840x1080, 60fps
* Driver Version: 16.8.2
* OBS Studio Version: 0.15.4 64-Bit
* Plugin Version: 1.3.0pre6-1.3.0.4

### Interface: Simple
* Keyframe Interval: 1
* Quality Preset: Speed
* Profile: High
* Profile Level: 5.2
* Rate Control Method: CQP
* Minimum QP: 0
* Maximum QP: 51
* I-/P-/B-Frame QP: 22/22/22
* Use Custom Buffer Size: Enabled
* Buffer Size: 65535 kbit/s
* Filler Data: Disabled
* Frame Skipping: Disabled
* B-Picture Pattern: 3
* B-Picture Reference: Enabled
* B-Picture Delta QP: 2
* Reference B-Picture Delta QP: 1
* De-Blocking Filter: Enabled
* Enforce HRD Compatibility: Disabled

### Examples:
* Too large for upload, MediaInfo not necessary.

**Comment by Xaymar** [comment]
High Quality 1280x720 60fps stream for Twitch at average 2126kbit/s

### System Specs
* CPU: AMD FX-6100 4.0 Ghz
* GPU: AMD Radeon R9 285 (ASUS Radeon R9 285 Strix OC DirectCU II)
* RAM: 16GB DDR3 1333Mhz
* Disk: Striped RAID (2xHDD)
* 1280x720, 60fps
* Driver Version: 16.8.2
* OBS Studio Version: 0.15.4 64-Bit
* Plugin Version: 1.3.0pre8-1.3.0.4

### Interface: Simple
* Keyframe Interval: 2
* Quality Preset: Balanced
* Profile: Main
* Profile Level: 4.1
* Rate Control Method:
* Min/Max QP: 36/51
* I-/P-/B-Frame QP: 31/38/43
* Use Custom Buffer Size: No
* Filler Data: Disabled
* Frame Skipping: Disabled
* B-Picture Pattern: 3
* B-Picture Reference: Enabled
* B-Picture Delta QP: 2
* Reference B-Picture Delta QP: 1
* Deblocking Filter: Enabled
* Enforce HRD Compatibility: Enabled

### Examples:
* Preview: [Twitch](https://www.twitch.tv/xaymar/v/87426113)
* Raw File: [Download](http://cdn.xaymar.com/private/2016/09/2016-09-04%2000-55-42.mkv)
* [MediaInfo](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/453821/2016-09-04.00-55-42.txt)

**Comment by CKannas** [comment]
This is the most recent stable simple settings for streaming on Twitch, so far.

# System Specs:
CPU: AMD Athlon X4 860K
GPU: AMD Radeon R7 370 (MSI Radeon R7 370 2GB Gaming OC)
RAM: 8GB DDR3 1866Mhz
Disk: 1TB (1xHDD)
1280 x 720, 30fps
Driver Version: 16.8.3
OBS Studio Version: 0.15.4 64-Bit
Plugin Version: 1.3.0pre7-1.3.0.5

# Interface: Simple
Keyframe Interval: 2
Quality Preset: Speed
Profile: Main
Profile Level: 4.1
Rate Control Method: Constant Bit Rate (CBR)
Minimum QP: 18
Maximum QP: 51
Target Bitrate (kb/s): 1600
Maximum Bitrate (kb/s): 1700
De-Blocking Filter: Yes
Use Custom Buffer Size: Yes
Custom Buffer Size (kb/s): 1650
Filler Data: Yes
Enable Frame Skipping: Yes
Turn on Debug Tracing: Yes

# Examples
Preview: [Twitch](https://www.twitch.tv/nobodyhells/v/87515521)

**Comment by razorlikes** [comment]
Stable for Twitch streaming. Gets a little blocky on very fast motion (e.g. fast turning in FPS games) but looks great overall! Mostly hovering around 1950-2000 kbit/s but spikes up to 2200 kbit/s.

### System Specs
* CPU: AMD FX-8350 @ 4.66GHz
* GPU: AMD Radeon R9 390 (Sapphire R9 390 Nitro)
* RAM: 12GB DDR3 1566Mhz
* Disk: 1TB HDD(Recording), 256GB SSD(OS), 2x500GB HDD RAID0(Games)
* 960x540, 40fps
* Driver Version: 16.8.1
* OBS Studio Version: 0.15.4 64-Bit
* Plugin Version: 1.3.0pre7-1.3.0.5

### Interface: Advanced
* Usage Type: Transcoding
* Profile: High
* Profile Level: 4.1
* Maximum LTR Frames: -1
* Rate Control Method: VBR Peak Constrained
* Frame Skipping: Enabled
* Minimum QP: 18
* Maximum QP: 51
* Target Bitrate: 1900000
* Peak Bitrate: 2000000
* I-/P-/B-Frame QP: 22/22/22
* VBV Buffer Size: 1950000
* Initial VBV Buffer Fullness: 100%
* Enforce HRD Compatibility: Disabled
* Filler Data: Disabled
* Maximum AU Size (bits): 0
* B-Picture Delta QP: 4
* Reference B-Picture Delta QP: 2
* Header Insertion Spacing: 0
* Keyframe IDR-Perod: 80 (2x Framerate)
* De-Blocking Filter: Enabled
* Intra-Refresh Memory...: 0
* Slices Per Frame: 1
* B-Picture Pattern: 0
* B-Picture Reference: Enabled
* Scan Type: Progressive
* Quality Preset: Balanced
* Motion Estimation: Both
* Turn on Debug Tracing: No

### Examples:
Preview: [Twitch](https://www.twitch.tv/razorlikes/v/87545566)

**Comment by Xaymar** [comment]
# 1.3.0pre8 Delimiter

**Comment by Xaymar** [comment]
This is the current "Recording" Preset.

### System Specs
- CPU: AMD-FX6100
- GPU: AMD Radeon R9 285
- RAM: 16GB DDR3 1333Mhz
- Disk: Striped RAID (2xHDD)
- 1920x1080, 60fps
- Driver Version: 16.8.3
- OBS Studio Version: 0.15.4 64-Bit
- Plugin Version: 1.3.0pre8-1.3.0.5

### Interface: Simple
- Keyframe Interval: 1
- Quality Preset: Speed
- Profile: High
- Profile Level: 5.2 (Maximum Available)
- Rate Control Method: VBR_LAT
- Target Bitrate: 20000
- Peak Bitrate: 100000
- Minimum QP: 0
- Maximum QP: 51
- Use Custom Buffer Size: Disabled
- Filler Data: Disabled
- Frame Skipping: Disabled
- B-Picture Pattern: 3 (Maximum Available)
- B-Picture Reference: Enabled
- B-Picture Delta QP: 0
- Reference B-Picture Delta QP: 0
- Deblocking Filter: Enabled
- Enforce HRD Compatibility: Disabled

### Examples:
- Raw File: [Download](http://cdn.xaymar.com/private/2016/09/2016-09-07%2005-24-31.mkv)
- [MediaInfo](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/458212/2016-09-07.05-24-31.txt)

**Comment by Xaymar** [comment]
This is the 1.3.0rc1 "Twitch" Preset.

### System Specs
- CPU: AMD-FX6100
- GPU: AMD Radeon R9 285
- RAM: 16GB DDR3 1333Mhz
- Disk: Striped RAID (2xHDD)
- 1920x1080, 60fps
- Driver Version: 16.8.3
- OBS Studio Version: 0.15.4 64-Bit
- Plugin Version: 1.3.0pre8-1.3.0.5

### Interface: Simple
- Keyframe Interval: 2
- Quality Preset: Speed
- Profile: Main
- Profile Level: 4.1
- Rate Control Method: CBR
- Target Bitrate: 2500
- Minimum QP: 0
- Maximum QP: 51
- Use Custom Buffer Size: Enabled
- Buffer Size: 2500
- Filler Data: Enabled
- Frame Skipping: Disabled
- B-Picture Pattern: 3 (Maximum Available)
- B-Picture Reference: Enabled
- B-Picture Delta QP: 0
- Reference B-Picture Delta QP: 0
- Deblocking Filter: Enabled
- Enforce HRD Compatibility: Disabled

### Examples:
- Raw File: [Download](http://cdn.xaymar.com/private/2016/09/2016-09-07%2005-30-50.mkv)
- [MediaInfo](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/458225/2016-09-07.05-30-50.txt)

**Comment by Xaymar** [comment]
This is a possible 1.3.0rc1 "YouTube" Preset. Might toy around with the bitrate.

### System Specs
- CPU: AMD-FX6100
- GPU: AMD Radeon R9 285
- RAM: 16GB DDR3 1333Mhz
- Disk: Striped RAID (2xHDD)
- 1920x1080, 60fps
- Driver Version: 16.8.3
- OBS Studio Version: 0.15.4 64-Bit
- Plugin Version: 1.3.0pre8-1.3.0.5

### Interface: Simple
- Keyframe Interval: 2
- Quality Preset: Speed
- Profile: Main
- Profile Level: 4.1
- Rate Control Method: VBR
- Target Bitrate: 3500
- Peak Bitrate: 6000
- Minimum QP: 0
- Maximum QP: 51
- Use Custom Buffer Size: Enabled
- Buffer Size: 6000
- Filler Data: Enabled
- Frame Skipping: Disabled
- B-Picture Pattern: 3 (Maximum Available)
- B-Picture Reference: Enabled
- B-Picture Delta QP: 0
- Reference B-Picture Delta QP: 0
- Deblocking Filter: Enabled
- Enforce HRD Compatibility: Disabled

### Examples:
- Raw File: [Download](http://cdn.xaymar.com/private/2016/09/2016-09-07%2005-34-50.mkv)
- [MediaInfo](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/458229/2016-09-07.05-34-50.txt)

**Comment by CKannas** [comment]
1.3.0pre8 is more stable and has lower CPU usage than 1.3.0pre7

### System Specs
* CPU: AMD Athlon X4 860k @4.3GHz
* GPU: MSI R7 370 2GB Gaming OC
* RAM: 8GB DDR3 1866Mhz
* Disk: 1TB HDD
* 1920x1080 -> 1280x720, 30fps
* Driver Version: 16.8.3
* OBS Studio Version: 0.15.4 64-Bit
* Plugin Version: 1.3.0pre8-1.3.0.5

### Interface: Simple
* Keyframe Interval: 2
* Quality Preset: Speed
* Profile: Main
* Profile Level: 4.1
* Rate Control Method: CBR
* Target Bitrate: 1700
* Peak Bitrate: 1800
* Minimum QP: 18
* Maximum QP: 51
* Use Custom Buffer Size: Enabled
* Buffer Size: 1800
* Filler Data: Enabled
* Frame Skipping: Enable
* Deblocking Filter: Enabled
* Enforce HRD Compatibility: Disabled

### Examples:
* Preview: [Twitch](https://www.twitch.tv/nobodyhells/v/88117466)
* Bitrate: [Twitch Inspector](http://prntscr.com/cfed5m)

**Comment by JLNNN** [comment]
@CKannas this is what I get when I'm trying to watch your recorded past broadcast: (stuttery video, no sound)

https://dl.dropboxusercontent.com/u/27535805/Video%2008.09.16%2C%2000%2023%2034.mov

**Comment by CKannas** [comment]
@JLNNN when watching it via Twitch the image in some places is blocky but in general is ok. I do not now what happened with the audio... :(

**Comment by Xaymar** [comment]
@JLNNN Make sure to disable flash player in your browsers plugins. Flash Player uses a broken Decoder and has not received any significant updates related to that for a while.

**Comment by JLNNN** [comment]
@Xaymar I tested this on three different computers. One PC, one iMac and one MacBook Pro - on PC I get this stuttery video and on Macs everything is just black. Maybe it's a Chrome problem? On Safari it's working fine. Haven't tested Firefox/Internet Explorer.

**Comment by Xaymar** [comment]
@JLNNN chrome://plugins and disable Flash. Chrome's built-in flash player is terrible. It should work fine in any browser that natively prefers HTML5 over Flash.

**Comment by JLNNN** [comment]
@Xaymar I disabled it and the videos starts to play. But when I'm trying to jump to a specific time, the video seems stuck. If I'm trying the same with my recorded past broadcast videos, everything is working as expected so I don't think it has something to do with the installed version of flash. (But that's just a guess.)

**Comment by Xaymar** [comment]
Seeking is always a weird issue, I have not figured out how to make it work properly yet with all formats. Too many corner cases with ffmpeg and rtmp.

**Comment by Alcorsa** [comment]
### System Specs
- CPU: Intel Core i5-2500K CPU 3.30GHz
- GPU: AMD Radeon R9 285 2 GB
- RAM: 16 GB DDR3 1333 Mhz
- Disk: 1 TB HDD
- 1080p->720p, Lanczos, 30 fps
- Driver Version: 16.8.3
- OBS Studio Version: 0.15.4 64-Bit
- Plugin Version: 1.3.0pre8-1.3.0.5

### Interface: Simple
- Keyframe Interval: 2
- Quality Preset: Quality
- Profile: Main
- Profile Level: 4.1
- Rate Control Method: CBR
- Target Bitrate: 3000
- Peak Bitrate: 3500
- Minimum QP: 0
- Maximum QP: 51
- Use Custom Buffer Size: Enabled
- Buffer Size: 3000
- Filler Data: Enabled
- Frame Skipping: Disabled
- B-Picture Pattern: 3 (Maximum Available)
- B-Picture Reference: Enabled
- B-Picture Delta QP: 4
- Reference B-Picture Delta QP: 3
- Deblocking Filter: Enabled
- Enforce HRD Compatibility: Disabled

### Examples:
- https://www.twitch.tv/coresgc/v/88219516
- [Twitch Inspector](http://imagehost.spark-media.ru/i4/2785958A-A65C-19E8-3CCC-1FA6D7082FCC.png)

**Comment by Xaymar** [comment]
Please do not use this Issue for discussing unrelated things. If your tested settings show issues, also do not submit them here, but open up a separate issue so they can be fixed. In the name of my bug tracking tool, thanks.
@CKannas, I deleted your configuration since it wasn't seekable (output corrupt). Try again with the modified version.

**Comment by seanman** [comment]
Not good video, pixel and pixel. In game fps didnt affected, and no randomly drop fps
### System Specs
* CPU: FX6300
* GPU: HD 7770
* RAM: 8GB DDR3 667Mhz
* Disk: 1TB HDD
* 1280x1024 60fps
* Driver Version: 16.9.1
* OBS Studio Version: 0.15.4 /64-Bit
* Plugin Version: 1.3.0pre8

### Interface: Simple/Advanced
* Recording presets

### Examples:
* Game : BF4, All low mesh ultra
* Preview:  https://youtu.be/G1-T5z7FwM0

**Comment by locodicegr** [comment]
@seanman i bet you are using mp4, use MKV to fix this.

**Comment by seanman** [comment]
@locodicegr thx mate MKV and got clear view.
no randomly fps drop, all cpu works 100% and vga 100%. 

### System Specs
- CPU: FX6300
-  GPU: HD 7770
-  RAM: 8GB DDR3 667Mhz
- Disk: 1TB HDD
-  1280x1024 60fps
-  Driver Version: 16.9.1
-  OBS Studio Version: 0.15.4 /64-Bit
-  Plugin Version: 1.3.0rc1

### Interface: Simple/Advanced
- Recording presets

### Examples:
- Game : BF4, All low mesh ultra
- Preview: https://youtu.be/KSpgvEVf5F0

**Comment by CKannas** [comment]
### System Specs
- CPU: AMD Athlon X4 860K (@4.3GHz)
- GPU: MSI R7 370 2GB Gaming OC
- RAM: 8GB DDR3 1866Mhz
- Disk: 1TB HDD
- 1920x1080 ->1280x720, Lanczos, 30fps
- Driver Version: 16.8.3
- OBS Studio Version: 0.15.4 64-Bit (Affinity set to 2 cores)
- Plugin Version: 1.3.0rc1-1.3.0.5

### Interface: Simple
- Keyframe Interval: 2
- Quality Preset: Speed
- Profile: Main
- Profile Level: 4.1
- Rate Control Method: CBR
- Target Bitrate: 1800
- Minimum QP: 18
- Maximum QP: 51
- Use Custom Buffer Size: Enabled
- Buffer Size: 1800
- Filler Data: Enabled
- Frame Skipping: Disabled
- Deblocking Filter: Enabled
- Enforce HRD Compatibility: Disabled
- CABAC: Enabled
- Debug Tracing: Enabled

### Examples:
- Preview: [Twitch.](https://www.twitch.tv/nobodyhells/v/88480100)
- Log File: [2016-09-10 01-08-20.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/465562/2016-09-10.01-08-20.txt)

**Comment by Roph** [comment]
Here's mine with polaris:

### System Specs
- CPU: AMD FX-8320
- GPU: AMD Radeon RX470
- RAM: 16GB DDR3, 1600Mhz
- Disk: OBS on SSD, writing video to HDD
- Games at 1080p60, bicubic downsampling to 1280x720
- Driver Version: 16.9.1
- OBS Studio Version:0.15.4 64-bit
- Plugin Version: 1.3.0rc2

### 720p60

### Interface: Simple
- Keyframe Interval: 2
- Quality Preset: Quality
- Profile: High
- Level: 5.2
- Rate Control Method: Variable Bitrate (Peak Constrained) (VBR)
- Target Bitrate: 4900
- Peak Bitrare: 6000
- Minimum QP: 18
- Maximum QP: 51
- Custom Buffer Size: 5000
- Filler Data: Enabled
- Frame Skipping: Enabled
- Deblocking Filter: Enabled
- Enforce HRD Compatibility: Disabled
- CABAC: Enabled

### Examples:
- Raw File: [Download](http://dump.roph.eu/vce/OBS/samples/720p60.mp4)
- [MediaInfo](http://pastebin.com/nBXQiRMZ)

### 720p30

### Interface: Simple
- Keyframe Interval: 2
- Quality Preset: Quality
- Profile: High
- Level: 5.2
- Rate Control Method: Variable Bitrate (Peak Constrained) (VBR)
- Target Bitrate: 3300
- Peak Bitrare: 4000
- Minimum QP: 18
- Maximum QP: 51
- Custom Buffer Size: 3300
- Filler Data: Enabled
- Frame Skipping: Enabled
- Deblocking Filter: Enabled
- Enforce HRD Compatibility: Disabled
- CABAC: Enabled

### Examples:
- Raw File: [Download](http://dump.roph.eu/vce/OBS/samples/720p30.mp4)
- [MediaInfo](http://pastebin.com/SbSDuQpp)

**Comment by Roph** [comment]
Done a bunch of testing and tweaking and I've arrived at the following bitrates, at least encoded by a polaris GPU. Every other setting is the same as above, only the bitrates are different:

Bitrates in Target/Peak:

### 960x540

30fps: 2000/3500 ([Sample](http://dump.roph.eu/vce/OBS/samples/540p30.mp4))
60fps: 3000/4400 ([Sample](http://dump.roph.eu/vce/OBS/samples/540p60.mp4))

### 1920x1080

30fps: 5300/7000 ([Sample](http://dump.roph.eu/vce/OBS/samples/1080p30.mp4))
60fps: 7600/9000 ([Sample](http://dump.roph.eu/vce/OBS/samples/1080p60.mp4))

Rocket League is I think a great test due to the very detailed grass, often taking up half of the screen and in constant movement.

**Comment by seanman** [comment]
No Frame Drop Issue, the quality good also

### System Specs
- CPU: FX6300
- GPU: HD 7770
- RAM: 8GB DDR3 667Mhz
- Disk: 1TB HDD
- 1280x1024 30fps
- Driver Version: 16.9.1
- OBS Studio Version: 0.15.4 /64-Bit
- Plugin Version: 1.3.0rc3

### Interface: Simple
- presets : Recording (i dont change anythings)

### Examples:
- Game : BF4, All low mesh ultra, resolution 1280*1024
- Preview: https://youtu.be/t_ANF2Aw0xg

**Comment by locodicegr** [comment]
I think you have to close this, and make new one, for the final release!
Just a suggestion!
