### ISSUE TITLE
Memory leak, using over 13GB before crash

### ISSUE THREAD

**Issue by Wolverine80** [Xaymar/OBS-AMD-Advanced-Media-Framework#66]
Hi,

I just encountered a memory leak using Version 1.1.2.
Memory detail out of Windows event-log:
`Windows hat diagnostiziert, dass der virtuelle Speicher unzureichend ist. Die folgenden Programme belegten den meisten virtuellen Speicher: obs64.exe (3280) belegt 13665398784 Bytes, Overwatch.exe (1292) belegt 3823415296 Bytes und RadeonSettings.exe (2516) belegt 195080192 Bytes.`

OBS Version 0.15.4 (64bit)
[2016-08-31 20-41-07.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/448026/2016-08-31.20-41-07.txt)
[Crash 2016-08-31 19-34-44.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/448028/Crash.2016-08-31.19-34-44.txt)
[PC.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/448029/PC.txt)

**Comment by Xaymar** [comment]
1.1.2 is not supported, please use version 1.3.0 or newer.
