### ISSUE TITLE
21:9 Support

### ISSUE THREAD

**Issue by OverwatchPlays** [Xaymar/OBS-AMD-Advanced-Media-Framework#67]
For some reason I am able to record at 1920x810 but no higher. This was an issue with the default AMD 264 encoder on Studio even though it should be supported by the encoder?

**Comment by Xaymar** [comment]
Please [read this first](https://github.com/Xaymar/OBS-AMD-Media-Framework/wiki/Reporting-Issues) and update your issue accordingly.

**Comment by max20091** [comment]
It's seems like you are using first gen GCN GPU. What is your current GPU?

**Comment by Xaymar** [comment]
#61 shows that the encoder is not the issue here. Your card most likely does not support resolutions this high - you'll have to figure out another solution for this. The plugin outputs what is supported into the log file at launch so make sure to read it.

**Comment by OverwatchPlays** [comment]
Sorry for any confusion, this is my first time using Github. I am using an r9 390x. I chacked the log files and it seems that max res supported is 1920x1920 (if I am reading them correctly that is)
[2016-09-02 08-53-01.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/450693/2016-09-02.08-53-01.txt)

**Comment by Xaymar** [comment]
Yep, maximum resolution your GPU supports in 1920x1920. So if you want to actually have the 21:9 footage you either have to scale down or figure out how to fit your footage into a 1920x1920 video and later in editing convert it to the proper 21:9 resolution by cutting and transforming the pieces back into the correct places.

Edit: Alternatively, get a R9 285 or 380 for cheap. They support 4K at 60 fps.

**Comment by Xaymar** [comment]
I'm closing this now, as it's not an encoder issue.
