### ISSUE TITLE
Import/Export Settings

### ISSUE THREAD

**Issue by nwgat** [Xaymar/OBS-AMD-Advanced-Media-Framework#69]
would have been great to have this ability
- export as json
- copy as markdown (for forums/github/etc)

**Comment by Xaymar** [comment]
I don't really see how this is a plugin feature request, it would have to be something that obs provides for us, like a callback or something similar.
As for exporting to json, you can use the files that OBS gives you in %APPDATA%\obs-studio\basic\profiles.

**Comment by Xaymar** [comment]
I have decided against implementing this but instead made it easier to read the individual properties when they are written to the log files.
