### ISSUE TITLE
Shared Encoder for Simple and Advanced User Interfaces

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/OBS-AMD-Advanced-Media-Framework#7]
Instead of calling VCE functions directly wrap them through this interface - ideally nothing should have to be done by the user interface that works with this.

**Comment by nwgat** [comment]
+1

**Comment by Xaymar** [comment]
Initial class is now complete, missing are the dynamic parameters.

**Comment by Xaymar** [comment]
Done in 1.2.0
