### ISSUE TITLE
Crashing with v1.3.0pre6

### ISSUE THREAD

**Issue by JLNNN** [Xaymar/OBS-AMD-Advanced-Media-Framework#70]
My OBS keeps crashing when I'm trying to start a new stream with the simple interface. I haven't tried the advanced one. Reinstalling plugin does not help. Here's the log:

http://pastebin.com/QKe8ueBP

Greetings,
  JLNNN

**Comment by Xaymar** [comment]
https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/wiki/Reporting-Issues

**Comment by Xaymar** [comment]
Also try Version 1.3.0pre7, I "fixed" some of the crashes related to applying properties that can't work on some cards.

**Comment by JLNNN** [comment]
1.3.0pre7 fixed this for me.
