### ISSUE TITLE
Audio async and stopping completely on 1.3.0pre8

### ISSUE THREAD

**Issue by JLNNN** [Xaymar/OBS-AMD-Advanced-Media-Framework#75]
https://www.twitch.tv/derawesumdude/v/88108600

At first my stream starts as usual but later on it's getting async with sound/video and then it stops completely. Guess it's the same kind of issue that @Ckannas stated [here](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/issues/61#issuecomment-245435652).

Switched back to 1.3.0pre7 and it's working fine for a stream longer than 3 hours.

**Comment by Xaymar** [comment]
Hmm, not sure what is happening here. It works fine in container formats so it might be another corner case of how obs muxes packets.

**Comment by Xaymar** [comment]
After how many minutes does the desync appear? I have a 15 minute stream recording now and can't see any desync happening

**Comment by Xaymar** [comment]
@JLNNN Can you try with this build and report back?

http://cdn.xaymar.com/private/2016/09/35A2D79429BB8B7FF7577D26506CA6B8CE481939DFEAD1131B625E939768BB13_OBS-AMD-AMF-Plugin-Installer.exe

**Comment by CKannas** [comment]
I'm doing further tests.

From [Twitch Analyser](https://r-1.ch/analyzer) I got this [analysis](http://prntscr.com/cffg85), while [Twitch Inspector](https://inspector.twitch.tv/) shows this [analysis](http://prntscr.com/cffh5h).

Twitch Video is [here](https://www.twitch.tv/nobodyhells/v/88154527), [Twitch Stream Configuration Quality](http://prntscr.com/cffhfc).

Audio is Ok until 10:20, after that there is no audio..
Video is blocky in some places but is expected to be like this.

**Comment by Xaymar** [comment]
Is that with pre8 or the just uploaded version? I did tests of up to 15 minutes and can't reproduce this issue. :/

**Comment by CKannas** [comment]
@Xaymar, sorry with pre8.
Can't get the new version.

**Comment by Xaymar** [comment]
The link for it is one comment above yours.

**Comment by CKannas** [comment]
@Xaymar I can't download it... :/

**Comment by Xaymar** [comment]
That is strange, i have never had someone who couldn't download a file - it works even on my shitty mobile connection.

**Comment by CKannas** [comment]
@Xaymar [Network error](http://prntscr.com/cfg0mn)

**Comment by CKannas** [comment]
@Xaymar I figured out why I couldn't download it.... My antivirus was reporting it as a false positive...
Will check it at the afternoon when I'll be home.

Thanks and sorry for any inconvenience.

**Comment by CKannas** [comment]
@Xaymar I'm testing it now. It seems better, the 1st attempt I got very high bitrates between 3000-8000 kbps, during the second streaming all is normal so far. Will post final outcome at the end.

## Update:

The stream was ok, the sound was fine for all the duration, vido was blocky as it should be expected in 720p 1800kbps. 
[Twitch](https://www.twitch.tv/nobodyhells/v/88235772)
[Bitrate](http://prntscr.com/cfq7t5)
[Stream analysis](http://prntscr.com/cfq8o8)

**Comment by Xaymar** [comment]
Audio Desync is solved in 1.3.0rc1, to be released sometime in the future. Not entirely sure when, just soon(TM) will be enough for now.
