### ISSUE TITLE
Black screen for some users on Twitch

### ISSUE THREAD

**Issue by JLNNN** [Xaymar/OBS-AMD-Advanced-Media-Framework#76]
When I'm streaming on Twitch, some users tell me they can't view my stream but they hear all of the sounds. Even if they try to view my past recorded broadcasts, there's only black.

I think it has something to do with NVIDIA cards, is that possible? Because when they switch on the iOS/Android app of Twitch, everything is working fine. All users that were unable to view my screen told me they got NVIDIA cards.

It doesn't matter which version of the plugin I'm using. My specs:

Intel Core i5-3750K @ 4,10GHz
AMD RX 480 8 GB RAM
16 GB DDR3 RAM
Windows 10 (64 Bit)

When I'm switching to x264 encoding via CPU, everything is working fine. That's the reason I think it has something to do with the plugin, not my hardware. View my current stream settings here: (And I think there's a problem with the encoding of the charset, too :D UTF-8 ftw? xD)

![settings](https://cloud.githubusercontent.com/assets/1099235/18330983/17571d38-755c-11e6-9631-d68263e58e17.jpg)

Thx in advance :)

**Comment by Xaymar** [comment]
Yes, it could be possible that it is linked to Nvidia cards, but the likelier cause is Flash Player. Flash Player has an outdated decoder which kind of messes up with how the rtmp and nal are structured.

As for the file, i think it was saved with the wrong encoding. Gotta fix that.

**Comment by nwgat** [comment]
try a lower level, some hardware only does 4.1 max

**Comment by Xaymar** [comment]
@JLNNN 
If possible, use the Presets without modifying them - they are designed to work together with a specific use case. Since your use case is most likely streaming to Twitch, you should be using the Twitch preset. Also what @nwgat said is true too.

**Comment by Xaymar** [comment]
Haven't heard back from you for a while, so I'm closing this for tracking purposes.

**Comment by JLNNN** [comment]
Just for the record: Setting profile level to 4.1 helped. THX!
