### ISSUE TITLE
Black/Corrupted stream output on Chrome

### ISSUE THREAD

**Issue by Sam202s** [Xaymar/OBS-AMD-Advanced-Media-Framework#80]
I've been having issues with streaming to twitch, when the stream is viewed on Chrome with hardware acceleration on, the output is black/corrupted. 
System Specs
http://imgur.com/a/GBhAH
Log file
[2016-09-10 14-08-40.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/465572/2016-09-10.14-08-40.txt)
[2016-09-10 14-20-33.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/465571/2016-09-10.14-20-33.txt)
 OBS version: OBS Studio 0.15.4
Plugin Version:  1.3.0rc1
The black/corrupted stream output only occurs when Chrome is using hardware acceleration, without it on it is normal, and it is normal on other browsers.

**Comment by Xaymar** [comment]
1. Upgrade to 1.3.0rc2, it fixes some things.
2. You have an ASUS card, you might have to underclock the GPU back to a stock/reference card.
3. After doing both of the above, try enabling "Enforce HRD Compatibility" and set Quality Preset to Speed.

**Comment by Xaymar** [comment]
This issue has previously been brought up here: #76. Possible vendor-specific issue.

**Comment by Sam202s** [comment]
Didn't seem to fix the issue.

**Comment by CKannas** [comment]
Maybe just disable hardware acceleration in Chrome, is known to cause
issues in general...

**Comment by nwgat** [comment]
set level to 4.1, chrome has hardware decoding but not all devices can decode higher levels than 4.1

**Comment by Xaymar** [comment]
Not a plugin issue.
