### ISSUE TITLE
AMD SDK

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#83]
hey,

nur so nebenbei, ich bin einer der gründe warum AMD die SDK erneuert hat, hab da den Kontakt von Erin (AMD CM USA) und Jim (OBS) zustande gebracht - was dann weitergeleitet wurde; ebenso hab ich mit Robert geschrieben dass da was an der SDK gemacht werden muss und es ne Erläuterung geben soll

also falls du auch kontakt zu den AMD Devs suchst dann kann ich vl helfen - kenne auch Leute von AMD Deutschland in München

hatte ja schon mal hilfe angeboten - musst du wissen ;)

**Comment by kytos22** [comment]
Can you write in english, please?

**Comment by wazerstar** [comment]
He says he only reason to why the SDK has been updated lol, and he would like to tell that he can help him and he knows AMD in Germany or something.

**Comment by locodicegr** [comment]
Well thats good.

**Comment by Benman2785** [comment]
wazerstar - i said im one of the reasons -> if u want i can show u some links at community.amd.com or screenshots from chats with AMD employees so that u belive me :p

**Comment by locodicegr** [comment]
@Benman2785 no reason to do that, just help @Xaymar improve & chat with amd to fix some bugs or i dont know!

**Comment by Xaymar** [comment]
If you can get me in contact with more people at AMD, then do. I currently only have MikhailAMD over on the GPUOpen repository as a contact person.

**Comment by Benman2785** [comment]
Robert Hallock wrote me today that he is already in contact with you (and also with Jim) - and he the guy that handles AMF SDK marketing.

but i will give him your email again, so he takes care of you //

ps https://twitter.com/nvictvs is AMD Germany CM

**Comment by Benman2785** [comment]
Robert told me you are in frequent contact with AMD

**Comment by kytos22** [comment]
@Benman2785 He is in contact with Mikhail (AMD Dev) on github helping with some issues. He talked with Robert on reddit afaik. If there is someone more that can help him, I think is welcome.

**Comment by locodicegr** [comment]
@Benman2785 i dont believe everything amd is saying. , lol.

**Comment by Benman2785** [comment]
i will check if Erin can manage to contact the the AMD Devs he is needing ;)

edit: can take some time, she married yesterday -> now honeymoon -> in ~2-3weeks then i can ask her to work again

**Comment by Xaymar** [comment]
I will be closing this issue now, if there's anything else you want to tell me please contact me via E-Mail: info@xaymar.com .
