### ISSUE TITLE
Enforce Streaming Service Settings

### ISSUE THREAD

**Issue by JLNNN** [Xaymar/OBS-AMD-Advanced-Media-Framework#87]
Just a quick question that you can add to the wiki maybe:

What is the property "Enforce Streaming Service Settings" used for? How does it affect streaming?

Thx in advance,
  JLNNN

**Comment by Xaymar** [comment]
The exact effect depends on the target service i think. This question is more for the OBS forums, since all I did was add support for the checkbox that OBS provides.

**Comment by JLNNN** [comment]
Alright, thx :)
