### ISSUE TITLE
OpenCL error

### ISSUE THREAD

**Issue by kurdtkobain** [Xaymar/OBS-AMD-Advanced-Media-Framework#88]
1.3.0rc3 fails and crashes obs

A8-7600 APU with a XFX Double Dissipation R7 360
log
[2016-09-18 15-10-17.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/478930/2016-09-18.15-10-17.txt)
crashlog
[Crash 2016-09-18 15-10-42.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/478931/Crash.2016-09-18.15-10-42.txt)

EDIT:
those are unedited logs both get cut off towards end

**Comment by Ryzym** [comment]
Now I have no idea what any of this code means, but for anyone who does, I think this stuff from the bottom was the cause?

`15:10:41.478: [AMFTrace::CLWrapper]    Trace: Load function clSetPrintfCallback failed

15:10:41.526: [AMF Encoder] Plugin::AMD::VCEEncoder::VCEEncoder InitOpenCL failed with error AMF_OPENCL_FAILED (code 19)

15:10:41.579: [AMFTrace::CLWrapper]    Trace: Load function clSetImageFormatAMD failed

15:10:41.579: [AMFTrace::CLWrapper]    Trace: Load function clCreateImageTiledAMD failed

15:10:41.579: [AMFTrace::CLWrapper]    Trace: Load function clSetThreadTraceBuffersAMD failed

15:10:41.579: [AMFTrace::AMFDeviceComputeImpl]    Error: ..........\runtime\src\core\DeviceComputeImpl.cpp(1599):OpenCL failed, error = -1:Init::clGetDeviceIDs failed

15:10:41.579: [AMFTrace::AMFContextImpl]    Error: ..........\runtime\src\core\ContextImpl.cpp(317):AMF_ERROR 19 : AMF_OPENCL_FAILED: pDeviceOpenCL->Init(pCommandQueue)`

**Comment by max20091** [comment]
It seems it failed to load OpenCL, can you try to reinstall driver to latest version or use lower OBS AMF version like 1.3.0rc2?
Currently there is no way to change memory type.

**Comment by Xaymar** [comment]
You need to have a cleanly installed 16.9.1 driver. Uninstall your old one, restart, install the new one, restart, use plugin.

**Comment by max20091** [comment]
@Xaymar is there anyway to manually change memory type if I don't want to use OpenCL?

**Comment by Xaymar** [comment]
No. There's no reason to not use it anyway, since it helps solve some of the issues encountered before. 
OpenCL is merely used to move the frame from RAM to VRAM without having to use per line memcpy. In general, the OpenCL solution should be faster for all systems.

**Comment by kurdtkobain** [comment]
Reinstalling drivers and using rc4 worked
now if only it did not cause my gpu to heat up

**Comment by nwgat** [comment]
if you use you gpu it will heat up, there is a reason there is a cooler!

**Comment by kurdtkobain** [comment]
yes that's obvious but my gpu idles at 40c, rc2 rose temp to 41-43c, rc4 raises it to 54-58c

**Comment by max20091** [comment]
@kurdtkobain Using GPU OpenCL will reduce CPU usage further more but it also increase GPU usage
