### ISSUE TITLE
Gathering New Tested Settings

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/OBS-AMD-Advanced-Media-Framework#90]
This Issue is dedicated to gather new tested settings. Only Settings with the latest Driver, 64-Bit OBS and latest Plugin Version are accepted. You can find the exact plugin version in the log output of obs:

`15:05:59.207: [AMF Encoder] Version 1.3.0-1.3.0.5`

Please format your reply like this:

```
### System Specs
* CPU: ...
* GPU: ...
* RAM: ...GB DDR... ....Mhz
* Disk: HDD/SSD/...
* WIDTHxHEIGHT, FPSfps
* Driver Version: xx.x.x
* OBS Studio Version: x.xx.x 32/64-Bit
* Plugin Version: x.x.x-x.x.x.x

### Interface: Simple/Advanced
* Individual Settings listed here

### Examples:
* Preview: [YouTube/Twitch/Beam/...](LINKHERE)
* Raw File: [Download](mega.co.nz, google drive, ...)
* [MediaInfo](link to txt output here)
```

**Comment by MajorWales** [comment]
## High-quality Recording

### System Specs
- **CPU:** Intel 4690K OC 4.4GHz
- **GPU:** ASUS R9 290 Ref.
- **RAM:** 16GBGB DDR3 2666Mhz
- **Disk:** HDD (Record to separate HDD)
- **Resolution:** 1920x1080, 60fps
- **Driver Version:** 16.9.1
- **OBS Studio Version:** 0.15.4 64-Bit
- **Plugin Version:** 1.3.0rc4hf1-1.3.0.5

## Interface: Simple
- **Keyframe Interval:** 1
- **Quality Preset:** Quality
- **Profile:** High
- **Profile Level:** 4.2
- **Rate Control Method:** VBR (Peak Constrained)
- **Target Bitrate:** 25000
- **Peak Bitrate:** 50000
- **QP (Min/Max):** 18/51
- **Filler Data:** Enabled
- **Frame Skipping:** Enabled

### Advanced
- **B-Picture Pattern:** 3
- **B-Picture Reference:** Enabled
- **B-Picture Delta QP:** 0
- **Reference B-Picture Delta:** 0
- **Deblocking Filter:** Enabled
- **Enforce HRD Compatibility:** Disabled
- **CABAC:** Enabled

### Examples:
- **Preview:** [YouTube](https://youtu.be/YVPe0cVvcEg)
- **Raw File:** [Download](https://mega.nz/#!z4wHkTLa!M2LMul1EZcCmH68g7UX7I7o65BNzYhDvMBGuaflm33U)
- [MediaInfo](http://pastebin.com/mCxW5U0C)

**Comment by CKannas** [comment]
### System Specs
- CPU: AMD Athlon X4 860K @4.3GHz
- GPU: MSi R7 370 2GB Gaming 
- RAM: 8GB DDR3 1866Mhz
- Disk: 1TB HDD, 240GB SSD
- 1920x1080 -> 1280x720, 30fps
- Driver Version: 16.9.1
- OBS Studio Version: 0.15.4 64-Bit
- Plugin Version: 1.3.0rc4-1.3.0.5

### Interface: Simple
- Keyframe Interval: 2
- Quality Preset: Quality
- Profile: Main
- Profile Level: 4.1
- Rate Control Method: CBR (Constant Bitrate)
- Target Bitrate: 1800
- QP (Min/Max): 31/51
- Filler Data: Enabled
- Frame Skipping: Disabled

#### Advanced
- Deblocking Filter: Enabled
- Enforce HRD Compatibility: Disabled
- CABAC: Disabled (according to the log, I have it enabled in settings)

### Examples:
- Preview: [Twitch](https://www.twitch.tv/nobodyhells/v/90427229)

**Comment by locodicegr** [comment]
Time for a new thread for this, when OBS comes out with the bundled plugin! 💃

**Comment by CKannas** [comment]
This was from my SWTOR stream last night (27th Sept 2016).

### System Specs
- CPU: AMD Athlon X4 860K @4.3GHz
- GPU: MSi R7 370 2GB Gaming 
- RAM: 8GB DDR3 1866Mhz
- Disk: 1TB HDD, 240GB SSD
- 1920x1080 -> 1280x720, 30fps
- Driver Version: 16.9.1
- OBS Studio Version: 0.15.4 64-Bit
- Plugin Version: 1.3.0rc7-1.3.0.5

### Interface: Simple
- Keyframe Interval: 2
- Quality Preset: Quality
- Profile: Main
- Profile Level: 4.1
- Rate Control Method: CBR (Constant Bitrate)
- Target Bitrate: 1600
- QP (Min/Max): 18/51
- Filler Data: Enabled
- Frame Skipping: Disabled

#### Advanced
- Custom Buffer: 1600
- Deblocking Filter: Enabled
- Enforce HRD Compatibility: Disabled
- Memory Type: Automatic
- Compute Type: OpenCL
- Surface format: Automatic
- CABAC: Enabled (according to the log is Disabled)

### Examples:
- Preview: [Twitch](https://www.twitch.tv/nobodyhells/v/91690639)

**Comment by Benman2785** [comment]
STREAMING SETTINGS 4 TWITCH.TV

### System Specs
- CPU: FX-8150 @4.2GHz
- GPU: RX 480 8G OC (Nitro+ OC)
- RAM: 8GB DDR3 1866Mhz
- Disk: 3TB WD HDD (here write Video) /120GB SSD (here OBS)
- input 1920x1080, 30fps -> output: 720p30 @3400kbps
- Driver Version: 16.10.1
- OBS Studio Version: 0.16.2 32/64-Bit
- Plugin Version: 1.3.3.1

### Interface: Advanced

MemoryType: DX11
Profile: High
Profile Level: 5.2
Max LTR Frames: 1
CBR
FrameSkip: enabled (long video 3:25min) / disabled (short video 1min)
Bitrate 3400kbps
PeakBitrate: 1400kbps
minQP: 1 (FIXED - without u wont have CBR)
maxQP: 42 (enough for most games - better quality)
VBV: 1132kbps - kinda strict buffer
FillerData: enabled -> HAS to be active for twitch.tv
KeyframeIntervall: 60 Frames (2x FPS)
GoP: 15 (1/2 FPS recommended by YT and h264)
CABAC: enabled

### Examples:
- Raw File: [Download]
- http://benmanshafen.de/pics/OBS/Xaymar/Xaymar_OBS_AMD_AMF_1.3.3.1-RX480.mp4 ~100mb (3:25min)
- http://benmanshafen.de/pics/OBS/Xaymar/Xaymar_OBS_AMD_AMF_1.3.3.1-noFrameSkip-RX480.mp4 ~28mb (1min no FrameSkip)

Testfile for SceneChange (usually result in high peak):
- http://benmanshafen.de/pics/OBS/Xaymar/Xaymar_OBS_AMD_AMF_1.3.3.1-noFrameSkip-BitrateWhenScenceChange-RX480.mp4 ~5mb (10s no FrameSkip)

BitrateCheck:
- http://benmanshafen.de/pics/OBS/Xaymar/Xaymar_OBS_AMD_AMF_1.3.3.1-RX480.jpg
  ![xaymar_obs_amd_amf_1 3 3 1-rx480](https://cloud.githubusercontent.com/assets/21282980/19188068/96893ae2-8c8f-11e6-9182-364bbb1d656a.jpg)
- http://benmanshafen.de/pics/OBS/Xaymar/Xaymar_OBS_AMD_AMF_1.3.3.1-noFrameSkip-BitrateWhenScenceChange-RX480.jpg
  ![xaymar_obs_amd_amf_1 3 3 1-noframeskip-bitratewhenscencechange-rx480](https://cloud.githubusercontent.com/assets/21282980/19188056/8321e01c-8c8f-11e6-9218-1bc192d9dd4d.jpg)

last Pic is important for streaming - twitch.tv allows peaks up to ~5000kbps before it drops

HERE a game Scene
- http://benmanshafen.de/pics/OBS/Xaymar/Xaymar_OBS_AMD_AMF_1.3.3.1-CBR_3400kbps.mp4 ~800mb (29:32min)
  ![xaymar_obs_amd_amf_1 3 3 1-cbr_3400kbps](https://cloud.githubusercontent.com/assets/21282980/19197379/d697da2e-8cb9-11e6-81e5-9fa634560584.jpg)

u still see some problems with FillerData and higher Peaks as wished

EDIT:
i also set PeakBitrate "0" now - prevents peaks (but have to be tested)
