### ISSUE TITLE
AMF load error when attempting to record in OBS

### ISSUE THREAD

**Issue by ryanjjjj** [Xaymar/OBS-AMD-Advanced-Media-Framework#91]
# First i will start with some background.

I had an issue with AMD AMF that was similar to an earlier thread [here](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/issues/42) with the same error. (Plugin::AMD::AMF::AMF Loading of 'amfrt64.dll' failed with error code 126.)

I determined that i did not have my display driver updated to the newest version required, so i went and downloaded the installer to update them and ultimately fix the issue.
However, Upon restarting and checking the display driver i saw it had only updated it to 15.3.

I'm mentioning this on the off chance that someone has the same issue i do, AMD's Installer will not install the newest graphics drivers available if you are using an older graphics card. (In my case a Radeon HD 6520G). This means amfrt64.dll is never installed into sys32.

That being said, you can fix this spesific error by going to the location AMD Extracts the installer files C:/AMD/\* and manually copying amfrt64 and or amfrt32 to C:/Windows/System32. (This wont be the same path for everyone depending on the installer version but my exact path was "C:\AMD\Radeon-Crimson-16.7.3-With-DOTNet45-Win7-64Bit\Packages\Drivers\Display\W76A_INF\B304863")
## 

My issue now is an AMF error "AMF_ENCODER_NOT_PRESENT".
Its very possible that my attempted workaround is not enough to use AMF but for pure curiosity I'm wondering if there is something i would be able to do to fix the loading failure.
Below is the full log file.

[2016-09-23 15-30-41.txt](https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/files/490560/2016-09-23.15-30-41.txt)

**Comment by Xaymar** [comment]
You are aware that your GPU does not actually have any Hardware Encoding capabilities? Please read the wiki: https://github.com/Xaymar/OBS-AMD-Advanced-Media-Framework/wiki/Hardware,-GCN-and-VCE-Limits

**Comment by ryanjjjj** [comment]
Well that would explain it, damn was hoping it was something i could play with to get working.
Thanks anyways.

**Comment by nwgat** [comment]
you can use the x264 encoing with veryfast on the cpu but yeah terrascale 2 is not supported
