### ISSUE TITLE
R9 Fury hardware limits for wiki

### ISSUE THREAD

**Issue by Brisse89** [Xaymar/OBS-AMD-Advanced-Media-Framework#97]
I don't see hardware limits for the R9 Fury listed in the wiki, so here's a copy paste from my OBS log using a Sapphire Nitro R9 Fury.

> Type | Acc.Type | Max Bitrate | Stream # | Max Profile | Max Level | BFrames | Ref. Frames | Layer # | FSM | Instance # 
> AVC | Hardware |   100000000 |       16 |         100 |        52 |     Yes |    1 -   16 |       1 |  No |          1 
> SVC | Hardware |   100000000 |       16 |         100 |        51 |      No |    1 -   16 |       3 |  No |          1 
> HEVC |     None |           0 |        0 |           0 |         0 |      No |    0 -    0 |       0 |  No |          0 
> Type |   Flow | Min. Res. | Max. Res. | S.I | Align | Formats | Memory Types
> AVC |  Input |   64x  64 | 4096x2160 |  No |    32 | NV12 (Native), YUV420P, YV12, BGRA, RGBA, ARGB | DX11 (Native), OPENCL, OPENGL, HOST
> AVC | Output |   64x  64 | 4096x2160 |  No |    32 | NV12 (Native) | DX11 (Native), OPENCL, OPENGL, HOST
> SVC |  Input |   64x  64 | 1920x1920 |  No |    32 | NV12 (Native), YUV420P, YV12, BGRA, RGBA, ARGB | DX11 (Native), OPENCL, OPENGL, HOST
> SVC | Output |   64x  64 | 1920x1920 |  No |    32 | NV12 (Native) | DX11 (Native), OPENCL, OPENGL, HOST

**Comment by Xaymar** [comment]
Added

**Comment by CKannas** [comment]
Reuse the thread to post hardware limits for R7 370 if you need them for the wiki.

[Pastebin](http://pastebin.com/0qBW1zAd)

**Comment by Xaymar** [comment]
Added that one too.
