### ISSUE TITLE
Bitrate Problem CBR

### ISSUE THREAD

**Issue by Benman2785** [Xaymar/OBS-AMD-Advanced-Media-Framework#98]
hi
### System Specs
- CPU: FX-8150 @4.2GHz
- GPU: RX 480 (Sapphire Nitro+ 8G OC)
- RAM: 8GB DDR3 1866Mhz
- Disk: WD HDD (here i save)/ A-Data SSD (here OBS)/
- 1280x720, 30fps
- Driver Version: 16.9.1 (i try 16.9.2 Hotfix in 2min)
- OBS Studio Version: 0.15.4 32-Bit
- Plugin Version: 1.3.0.3
### Interface: Advanced

![xaymar_obs-amd-amf_v1 3 0 3_bitrate-problem-cbr](https://cloud.githubusercontent.com/assets/21282980/18942593/6a51747e-861a-11e6-8034-1d31bc89b06b.jpg)
![xaymar_obs-amd-amf_v1 3 0 3_bitrate-problem-cbr-settings](https://cloud.githubusercontent.com/assets/21282980/18942594/6a59591e-861a-11e6-9e35-6d07ef3ebe12.jpg)

as you can see - the bitrate is pretty low (even i set it to max in CBR) - FillerData has no effekt
the quality is also a little shitty (due to "lack of bitrate")

when i set "normal" 720p30 bitrates (3400kbps; 4500kbps peak) it looks horrible - and only uses around 400kbps bitrate (800kbps and 200kbps in constant change)

looks like it didnt set CBR

**Comment by JLNNN** [comment]
Did you stream or record your video? Because there's a "Recording" tab on the right.

**Comment by Xaymar** [comment]
You have a VCE3 card, those currently have a Driver issue that doesn't allow CBR to perform properly. @MikhailAMD promised a fix in the next driver package. https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/18

**Comment by Benman2785** [comment]
thank you ;)

**Comment by Xaymar** [comment]
16.9.2 has this fixed.

**Comment by Benman2785** [comment]
not fixed with 16.9.2

**Comment by Xaymar** [comment]
Then you'll have to wait until 16.9.3: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/18

**Comment by MikhailAMD** [comment]
The driver with the fix was not released yet.

Mikhail
On Tue, Oct 04, 2016 at 11:14am, Benman2785 <notifications@github.com<mailto:notifications@github.com>> wrote:

not fixed with 16.9.2

##

**Comment by Benman2785** [comment]
its fixed now with 16.10.1 - but have to find out if still "minQP 1" has to be set to use it

EDIT: you STILL have to use "minQP 1" to avoid bitrate-up'n'down // but FillerNALs work right now (when minQP 1 is set)

**Comment by Xaymar** [comment]
@Benman2785 Is that a RX 4xx exclusive bug?

**Comment by Benman2785** [comment]
@Xaymar sry, i only have a RX 480 to test right now (my 7970GHz died and my APU-Laptop only allows catalyst 15.10 - so i cant use your plugin there) - but before my 7970 died i had same problem with older version of your plugin and crimson 16.7.3

i will try to get my hands on a R7 380 and an R7 250 to test some GCN-Generations

**Comment by Xaymar** [comment]
Could you test this build in the simpler interface for me (H264 Encoder without the [Advanced] stuff)?

http://cdn.xaymar.com/private/2016/10/1-3-3-2pre1_OBS-AMD-AMF-Plugin-Installer.exe

**Comment by Benman2785** [comment]
i do ;)

**Comment by Benman2785** [comment]
![xaymar_obs_amd_amf_1 3 3 2pre1-cbr_3400kbps_test](https://cloud.githubusercontent.com/assets/21282980/19204445/3317767e-8cdd-11e6-8b2e-0b73fc786b16.jpg)
http://benmanshafen.de/pics/OBS/Xaymar/Xaymar_OBS_AMD_AMF_1.3.3.2pre1-CBR_3400kbps_test.mp4 ~36mb (1:30min)

looks good, BUT still has FillerData-Bug on RX 480 - when u check video u see that it appears when from high movement to "no movement" -> an when then switched back you normally get a peak (but not this time - i think u fixed that)
yet it still doesnt set bitrate properly

**Comment by Benman2785** [comment]
and it doesnt save "CBR" option (or doesnt load it when i go again into settings)

**Comment by Xaymar** [comment]
Make sure you have no preset selected, I've changed nothing that would affect saving options.

**Comment by Benman2785** [comment]
k i check now

**Comment by Benman2785** [comment]
![xaymar_obs_amd_amf_1 3 3 2pre1-cbr_3400kbps_test_2](https://cloud.githubusercontent.com/assets/21282980/19205189/2433b600-8ce1-11e6-9c3f-784451e15d5f.jpg)

much better CBR - but still when switched from high movement to no movent you get "no filler-data"

used 3400kbps & 1132kb buffer
![xaymar_obs_amd_amf_1 3 3 2pre1-cbr_3400kbps_test_2_settings](https://cloud.githubusercontent.com/assets/21282980/19205241/7cfbed3e-8ce1-11e6-8e80-f15d264ee54e.jpg)

yeah - now it saves CBR -> so was my fault

**Comment by Benman2785** [comment]
i check now with quality preset and high profile

**Comment by Benman2785** [comment]
![xaymar_obs_amd_amf_1 3 3 2pre1-cbr_3400kbps_test_3_settings](https://cloud.githubusercontent.com/assets/21282980/19206006/3136e9ee-8ce6-11e6-9685-80df082b25c9.jpg)
![xaymar_obs_amd_amf_1 3 3 2pre1-cbr_3400kbps_test_3](https://cloud.githubusercontent.com/assets/21282980/19205453/dbefc60c-8ce2-11e6-9814-3eb7af2c41b4.jpg)
http://benmanshafen.de/pics/OBS/Xaymar/Xaymar_OBS_AMD_AMF_1.3.3.2pre1-CBR_3400kbps_test_3.mp4 ~24mb (1min)

still drops bitrate when no movement
